/**
 * Binomial Expansion.
 *
 * Level 1 builds Pascal's triangle and expands with it: rows and their
 * patterns, (1 + x)^n, brackets with numbers in them, the signs a negative part
 * brings when both parts carry a number, and one term picked out on its own.
 * Level 2 names the triangle's entries: factorials and nCr, nCr as the
 * coefficient of a term and the general term that follows, estimating a power
 * from the first three terms, and a bracket multiplied by an expansion.
 * Level 3 works backwards to the unknowns: n and k from two coefficients,
 * neighbouring coefficients equal or in a ratio, the sum of the coefficients,
 * and the number in front of x. Level 4 multiplies two expansions: the pairs
 * that make one coefficient, the first three terms of a product, brackets that
 * pair off into (1 - x^2)^n, three terms in a bracket as (1 + u)^n, and
 * equating coefficients across a product. Level 5 goes back to estimates and
 * on to surds: how big the error of a three-term estimate is, a number in
 * front of x, (1 + √2)^n as a + b√2, conjugate pairs, and a number and a surd
 * together. Level 6 lets n be negative or a fraction: an expansion that never
 * ends, negative whole n and the geometric series, fractional n, the range
 * |x| < 1 the series holds for, and (a + bx)^n with the a taken out.
 * Level 7 turns the series into numbers: roots such as √1.02, reciprocals
 * such as 1/0.98², a number taken out first, how many places an estimate is
 * good to and which x to choose, and the series of a partial-fraction split.
 *
 * Each level closes with a level check: twelve to fifteen questions, no
 * teaching slides, one attempt each.
 */
import type { Block, Course, SlideRef } from '../types';

const teach = (...blocks: Block[]): SlideRef => ({
  type: 'literal',
  slide: { kind: 'teach', body: blocks },
});

const ask = (generatorId: string, difficulty = 1): SlideRef => ({
  type: 'generated',
  generatorId,
  difficulty,
});

const prose = (text: string): Block => ({ kind: 'prose', text });
const maths = (tex: string): Block => ({ kind: 'display', tex });

/** A question with a short worked example just above it, on the same slide. */
const askWith = (generatorId: string, difficulty: number, ...leadIn: Block[]): SlideRef => ({
  type: 'generated',
  generatorId,
  difficulty,
  leadIn,
});

export const binomialExpansion: Course = {
  id: 'binomial-expansion',
  category: 'advanced-algebra',
  position: 40,
  title: 'Binomial Expansion',
  blurb: "Pascal's triangle and nCr: expanding a bracket to a power, picking out one term, and estimating powers.",
  levels: [
    {
      id: 'be-l1',
      title: "Pascal's Triangle and (a + b)ⁿ",
      lessons: [
        {
          id: 'be-l1-triangle',
          title: "Building Pascal's Triangle",
          slides: [
            teach(
              prose(
                "Pascal's triangle starts with a single $1$, called row $0$. Every row starts and ends with $1$, and every other number is the sum of the two above it.",
              ),
              maths(
                '\\begin{array}{c} 1 \\\\ 1 \\quad 1 \\\\ 1 \\quad 2 \\quad 1 \\\\ 1 \\quad 3 \\quad 3 \\quad 1 \\\\ 1 \\quad 4 \\quad 6 \\quad 4 \\quad 1 \\end{array}',
              ),
              prose(
                'Row $n$ holds the numbers in the expansion of $(a + b)^n$. Row $2$ is $1 \\; 2 \\; 1$, and $(a + b)^2 = a^2 + 2ab + b^2$.',
              ),
            ),
            ask('bin-pascal-row'),
            ask('bin-pascal-tree'),
            teach(
              prose('Two patterns check a row. It reads the same from either end, and it adds up to a power of $2$.'),
              maths('1 + 4 + 6 + 4 + 1 = 16 = 2^{4}'),
              prose(
                'Every number is added into two below it, so each row adds to twice the one above. Row $n$ adds to $2^n$. Row $4$ is also the coefficients of $(1 + x)^4$, so they add to $16$ too.',
              ),
              prose(
                '$(a + b)^4 = a^4 + 4a^3b + 6a^2b^2 + 4ab^3 + b^4$ has $5$ terms, one for each number in row $4$. So $(a + b)^n$ has $n + 1$ terms.',
              ),
            ),
            ask('bin-pascal-error'),
            ask('bin-pascal-tree'),
            teach(
              prose('The second number in row $n$ is always $n$, and the numbers rise to the middle and fall again. Row $7$, built from row $6$:'),
              maths(
                '\\begin{gathered} 1 \\enspace 6 \\enspace 15 \\enspace 20 \\enspace 15 \\enspace 6 \\enspace 1 \\\\ 1 \\enspace 7 \\enspace 21 \\enspace 35 \\enspace 35 \\enspace 21 \\enspace 7 \\enspace 1 \\end{gathered}',
              ),
              prose('The largest number is in the middle: $20$ on its own in row $6$, and the pair $35, 35$ in row $7$.'),
            ),
            ask('bin-row-facts'),
            ask('bin-pascal-row'),
            ask('bin-row-facts+choice'),
            ask('bin-pascal-error'),
          ],
          skillCheck: [ask('bin-pascal-row', 2), ask('bin-pascal-tree', 2), ask('bin-pascal-error', 2)],
        },
        {
          id: 'be-l1-one-x',
          title: 'Expanding (1 + x)ⁿ',
          slides: [
            teach(
              prose('$(1 + x)^n$ expands with row $n$ as its coefficients, and the power of $x$ rising by one each term.'),
              maths('(1 + x)^{3} = 1 + 3x + 3x^{2} + x^{3}'),
              maths('\\begin{aligned} (1 + x)^{4} &= 1 + 4x + 6x^{2} \\\\ &\\quad + 4x^{3} + x^{4} \\end{aligned}'),
              prose(
                'Multiplying out gives the same. Each term picks $1$ or $x$ from each bracket, and the triangle counts the ways to pick.',
              ),
            ),
            ask('bin-one-x-tiles'),
            ask('bin-one-x-coeff'),
            teach(
              prose('In $(1 - x)^n$ the second part is $-x$. An even power of it is positive and an odd power negative, so the signs alternate.'),
              maths('\\begin{aligned} (1 - x)^{4} &= 1 - 4x + 6x^{2} \\\\ &\\quad - 4x^{3} + x^{4} \\end{aligned}'),
              prose('The same goes for any negative part: its power decides the sign.'),
            ),
            ask('bin-sign-flow'),
            ask('bin-one-x-tiles'),
            ask('bin-one-x-coeff+choice'),
            teach(
              prose(
                'The coefficient of $x^k$ is the number in place $k$ of the row, counting from $0$. In $(1 + x)^6$ the $x^2$ term takes place $2$ of $1 \\; 6 \\; 15 \\; 20 \\; 15 \\; 6 \\; 1$: $15x^2$.',
              ),
              prose('Put $x = 1$ and every term becomes its coefficient, so they add to $2^n$:'),
              maths('(1 + 1)^{4} = 1 + 4 + 6 + 4 + 1 = 16'),
              prose('Count the terms too: $1, 4x, 6x^2, 4x^3, x^4$ is $5$ terms, so $(1 + x)^n$ has $n + 1$.'),
            ),
            askWith(
              'bin-row-facts',
              1,
              prose(
                'The row rises to the middle and falls again. Row $7$ from row $6$ is $1 \\; 7 \\; 21 \\; 35 \\; 35 \\; 21 \\; 7 \\; 1$: its largest number is the middle pair, $35$.',
              ),
            ),
            ask('bin-sign-flow'),
            ask('bin-row-facts+choice'),
          ],
          skillCheck: [ask('bin-one-x-tiles', 2), ask('bin-one-x-coeff', 2), ask('bin-sign-flow', 2)],
        },
        {
          id: 'be-l1-numbers',
          title: 'Brackets with Numbers',
          slides: [
            teach(
              prose(
                'The triangle works for any two-part bracket. In $(a + b)^n$ each term is a number from row $n$, times $a$ to one power and $b$ to another, the powers adding to $n$.',
              ),
              maths('\\begin{aligned} (a + b)^{3} &= a^{3} + 3a^{2}b \\\\ &\\quad + 3ab^{2} + b^{3} \\end{aligned}'),
              prose('Put $x$ for $a$ and $2$ for $b$, and raise the $2$ to its power:'),
              maths('\\begin{aligned} (x + 2)^{3} &= x^{3} + 3x^{2}(2) \\\\ &\\quad + 3x(2)^{2} + 2^{3} \\\\ &=x^{3} + 6x^{2} + 12x + 8 \\end{aligned}'),
              prose('A number stuck to $x$ is raised with it. The $x^2$ term of $(1 + 2x)^3$:'),
              maths('3 \\times 1^{1} \\times (2x)^{2} = 3 \\times 4x^{2} = 12x^{2}'),
            ),
            ask('bin-term-tiles'),
            ask('bin-coeff'),
            teach(
              prose('The powers of the number are where the size comes from. The $x^2$ term of $(x + 3)^4$:'),
              maths('6 \\times x^{2} \\times 3^{2} = 54x^{2}'),
              prose('The $6$ is place $2$ of row $4$, and the $3$ is squared because $x$ has taken the other two of the four.'),
              prose('A negative number keeps its sign inside the power, so odd powers of it are negative:'),
              maths('\\begin{aligned} (x - 2)^{3} &= x^{3} + 3x^{2}(-2) \\\\ &\\quad + 3x(-2)^{2} + (-2)^{3} \\\\ &=x^{3} - 6x^{2} + 12x - 8 \\end{aligned}'),
            ),
            ask('bin-expand-tiles'),
            ask('bin-term-reduce'),
            ask('bin-term-tiles'),
            teach(
              prose('When both parts carry a number, raise each one to its own power. The $x$ term of $(2x + 3)^3$:'),
              maths('\\begin{aligned} 3 \\times (2x)^{1} \\times 3^{2} &= 3 \\times 2x \\times 9 \\\\ &= 54x \\end{aligned}'),
              prose('A minus goes into the power with its number. The $x$ term of $(2 - 3x)^2$:'),
              maths('2 \\times 2^{1} \\times (-3x)^{1} = -12x'),
            ),
            ask('bin-term-reduce+choice'),
            ask('bin-coeff+choice'),
            ask('bin-expand-tiles'),
          ],
          skillCheck: [ask('bin-term-tiles', 2), ask('bin-coeff', 2), ask('bin-term-reduce', 2)],
        },
        {
          id: 'be-l1-signs',
          title: 'Signs and Powers',
          slides: [
            teach(
              prose('When both parts carry a number, both numbers are raised to their powers. The $x^2$ term of $(2x - 3)^4$:'),
              maths('\\begin{aligned} & 6 \\times (2x)^{2} \\times (-3)^{2} \\\\ &= 6 \\times 4x^{2} \\times 9 \\\\ &= 216x^{2} \\end{aligned}'),
              prose('Two slips to avoid: $(2x)^2$ is $4x^2$, not $2x^2$, and the $-3$ takes its sign into the power.'),
            ),
            ask('bin-split-tree'),
            ask('bin-sign-flow', 2),
            ask('bin-expand-tiles', 2),
            teach(
              prose(
                'The sign of a term depends only on the power of the negative part: even gives positive, odd gives negative. So the signs of $(2x - 3)^n$ alternate, starting with $+$.',
              ),
              maths('\\begin{aligned} (2x - 3)^{3} &= 8x^{3} - 36x^{2} \\\\ &\\quad + 54x - 27 \\end{aligned}'),
            ),
            ask('bin-pick-term+choice', 2),
            ask('bin-term-reduce', 2),
            ask('bin-split-tree', 2),
            teach(
              prose('Check a whole expansion by putting $x = 1$. The terms must add to the bracket at $x = 1$:'),
              maths('(2 - 3)^{4} = 1'),
              maths('16 - 96 + 216 - 216 + 81 = 1'),
            ),
            ask('bin-expand-tiles', 2),
            ask('bin-sign-flow', 2),
          ],
          skillCheck: [ask('bin-split-tree', 2), ask('bin-expand-tiles', 2), ask('bin-sign-flow', 2)],
        },
        {
          id: 'be-l1-one-term',
          title: 'Picking Out One Term',
          slides: [
            teach(
              prose(
                'One term does not need the rest. Decide the powers first: in $(x + 2)^6$ the $x^4$ term has $x$ to the power $4$, so $2$ to the power $2$.',
              ),
              prose('Then take the number from row $6$ in place $2$, the power of the second part, counting from $0$:'),
              maths('15 \\times x^{4} \\times 2^{2} = 60x^{4}'),
            ),
            ask('bin-pick-term'),
            ask('bin-term-tiles', 2),
            ask('bin-coeff', 2),
            teach(
              prose(
                'Which part carries $x$ changes the count. In $(2 + x)^6$ the $x^4$ term has $x$ to the power $4$ as the second part, so it takes place $4$ of the row, and $2^2$:',
              ),
              maths('15 \\times 2^{2} \\times x^{4} = 60x^{4}'),
              prose('The row is symmetrical, so places $2$ and $4$ hold the same number anyway.'),
            ),
            ask('bin-split-tree'),
            ask('bin-pick-term+choice'),
            ask('bin-coeff+choice', 2),
            teach(
              prose('Working backwards: when a coefficient is given, write it in terms of the unknown and solve.'),
              prose('In $(1 + kx)^5$ the $x^2$ term is'),
              maths('10(kx)^{2} = 10k^{2}x^{2}'),
              prose('If that coefficient is $90$, then $k^2 = 9$ and $k = 3$, taking $k > 0$.'),
              prose('An odd power keeps the sign. If the $x^3$ coefficient of $(1 + kx)^4$ is $-32$, then $4k^3 = -32$, $k^3 = -8$ and $k = -2$.'),
            ),
            ask('bin-find-k'),
            ask('bin-find-k+choice'),
          ],
          skillCheck: [ask('bin-pick-term', 2), ask('bin-find-k', 2), ask('bin-coeff', 2)],
        },
      ],
      levelCheck: [
        ask('bin-pascal-row', 2),
        ask('bin-pascal-tree', 2),
        ask('bin-pascal-error', 2),
        ask('bin-row-facts+choice', 2),
        ask('bin-one-x-tiles', 2),
        ask('bin-one-x-coeff', 2),
        ask('bin-sign-flow', 2),
        ask('bin-term-tiles', 2),
        ask('bin-term-reduce+choice', 2),
        ask('bin-expand-tiles', 2),
        ask('bin-split-tree', 2),
        ask('bin-coeff', 2),
        ask('bin-pick-term', 2),
        ask('bin-find-k', 2),
      ],
    },
    {
      id: 'be-l2',
      title: 'nCr and the General Term',
      lessons: [
        {
          id: 'be-l2-ncr',
          title: 'Factorials and nCr',
          slides: [
            teach(
              prose('$n!$, read "$n$ factorial", multiplies every whole number from $n$ down to $1$:'),
              maths('5! = 5 \\times 4 \\times 3 \\times 2 \\times 1 = 120'),
              prose('$0!$ is defined to be $1$. A quotient of factorials cancels down:'),
              maths('\\frac{7!}{5!} = 7 \\times 6 = 42'),
            ),
            ask('bin-factorial'),
            ask('bin-factorial+choice'),
            teach(
              prose(
                'The number in place $r$ of row $n$ is called ${}^{n}C_{r}$, counting places from $0$. Row $6$ is $1 \\; 6 \\; 15 \\; 20 \\; 15 \\; 6 \\; 1$, so ${}^{6}C_{0} = 1$, ${}^{6}C_{1} = 6$ and ${}^{6}C_{2} = 15$.',
              ),
              prose('It counts the ways to choose $r$ things from $n$, and it has a formula:'),
              maths('{}^{n}C_{r} = \\frac{n!}{r! \\, (n - r)!}'),
              maths('{}^{6}C_{2} = \\frac{6!}{2! \\times 4!} = \\frac{6 \\times 5}{2} = 15'),
              prose('Choosing $2$ to take is choosing $4$ to leave, so ${}^{6}C_{4} = 15$ too: the row is symmetrical.'),
            ),
            ask('bin-ncr-row'),
            ask('bin-ncr-reduce'),
            ask('bin-ncr-facts'),
            teach(
              prose('The ends of every row: ${}^{n}C_{0} = {}^{n}C_{n} = 1$, and ${}^{n}C_{1} = n$.'),
              prose('And the triangle\'s own rule, two neighbours adding to the number below them:'),
              maths('{}^{n}C_{r} + {}^{n}C_{r + 1} = {}^{n + 1}C_{r + 1}'),
            ),
            ask('bin-ncr-reduce'),
            ask('bin-ncr-facts+choice'),
          ],
          skillCheck: [ask('bin-factorial', 2), ask('bin-ncr-reduce', 2), ask('bin-ncr-facts', 2)],
        },
        {
          id: 'be-l2-coefficient',
          title: 'nCr as the Coefficient',
          slides: [
            teach(
              prose('With nCr the expansion can be written for any $n$, without the row:'),
              maths(
                '\\begin{aligned} (a + b)^{n} &= a^{n} + {}^{n}C_{1}a^{n - 1}b \\\\ &\\quad + {}^{n}C_{2}a^{n - 2}b^{2} \\\\ &\\quad + \\dots + b^{n} \\end{aligned}',
              ),
              prose('The term with $b^r$ is the **general term**:'),
              maths('{}^{n}C_{r} \\, a^{n - r} \\, b^{r}'),
            ),
            ask('bin-which-r-flow'),
            ask('bin-general-tiles'),
            ask('bin-coeff-ncr'),
            teach(
              prose(
                '$r$ is the power of the second part. If $x$ sits in the first part, as in $(x + 2)^7$, then $x^6$ needs $7 - r = 6$, so $r = 1$.',
              ),
              prose('If it sits in the second, as in $(2 + x)^7$, then $x^6$ needs $r = 6$.'),
            ),
            ask('bin-general-reduce'),
            ask('bin-which-r-flow'),
            ask('bin-coeff-ncr+choice'),
            teach(
              prose('nCr does not have to come from a row you know: cancel the factorials, then multiply by the powers.'),
              maths('{}^{8}C_{3} = \\frac{8 \\times 7 \\times 6}{6} = 56'),
              prose('So the $x^5$ term of $(x + 2)^8$ is'),
              maths('56 \\times x^{5} \\times 2^{3} = 448x^{5}'),
              prose('With a number on $x$ and a minus, each part keeps its number and sign. The $x^3$ term of $(2x - 3)^4$ has $r = 1$:'),
              maths('\\begin{aligned} & {}^{4}C_{1} \\, (2x)^{3} \\, (-3)^{1} \\\\ &= 4 \\times 8x^{3} \\times (-3) \\\\ &= -96x^{3} \\end{aligned}'),
            ),
            ask('bin-general-tiles'),
            ask('bin-general-reduce+choice'),
          ],
          skillCheck: [ask('bin-which-r-flow', 2), ask('bin-general-tiles', 2), ask('bin-coeff-ncr', 2)],
        },
        {
          id: 'be-l2-general',
          title: 'The General Term',
          slides: [
            teach(
              prose('The general term finds a term by its power of $x$, even when $x$ is in both parts:'),
              prose('In $\\left(x + \\frac{2}{x}\\right)^6$ the general term is'),
              maths('\\begin{aligned} & {}^{6}C_{r} \\, x^{6 - r} \\left(\\frac{2}{x}\\right)^{r} \\\\ &= {}^{6}C_{r} \\, 2^{r} \\, x^{6 - 2r} \\end{aligned}'),
              prose('The term **independent** of $x$ has power $0$: $6 - 2r = 0$, so $r = 3$, and the term is $20 \\times 2^3 = 160$.'),
            ),
            askWith(
              'bin-free-term',
              1,
              prose('With $x^2$ in the first part its power doubles. In $\\left(x^{2} - \\frac{2}{x}\\right)^6$ the general term is'),
              maths('\\begin{aligned} & {}^{6}C_{r} \\, (x^{2})^{6 - r} \\left(-\\frac{2}{x}\\right)^{r} \\\\ &= {}^{6}C_{r} \\, (-2)^{r} \\, x^{12 - 3r} \\end{aligned}'),
              prose('The power of $x$ is $2(6 - r) - r = 12 - 3r$. Setting $12 - 3r = 0$ gives $r = 4$, so the term is ${}^{6}C_{4} \\times (-2)^4 = 15 \\times 16 = 240$.'),
            ),
            ask('bin-general-tiles', 2),
            ask('bin-coeff-ncr', 2),
            teach(
              prose('Any power works the same way. For $x^2$ in the same expansion, $6 - 2r = 2$, so $r = 2$:'),
              maths('{}^{6}C_{2} \\times 2^{2} = 15 \\times 4 = 60'),
              prose('If the equation for $r$ has no whole-number answer, there is no such term.'),
            ),
            ask('bin-free-term+choice'),
            ask('bin-which-r-flow', 2),
            ask('bin-coeff-ncr+choice', 2),
            teach(
              prose('Working back to $n$ uses ${}^{n}C_{1} = n$ and ${}^{n}C_{2} = \\frac{n(n - 1)}{2}$.'),
              prose('If $(1 + x)^n$ has $x^2$ coefficient $28$, then $n(n - 1) = 56 = 8 \\times 7$, so $n = 8$.'),
            ),
            ask('bin-find-n'),
            ask('bin-find-n+choice'),
          ],
          skillCheck: [ask('bin-free-term', 2), ask('bin-coeff-ncr', 2), ask('bin-find-n', 2)],
        },
        {
          id: 'be-l2-approx',
          title: 'Estimating with Three Terms',
          slides: [
            teach(
              prose('When $x$ is small its higher powers are tiny, so the first few terms of $(1 + x)^n$ give a good estimate.'),
              maths('(1 + x)^{5} \\approx 1 + 5x + 10x^{2}'),
              prose('For $1.02^5$ put $x = 0.02$: $1 + 0.1 + 0.004 = 1.104$. The true value is $1.10408\\dots$'),
            ),
            ask('bin-three-terms-steps'),
            ask('bin-approx'),
            teach(
              prose('A number in front of $x$ is raised to the power with it, so it is squared in the third term:'),
              maths('(1 - 3x)^{7} \\approx 1 - 21x + 189x^{2}'),
              prose('$7 \\times (-3x) = -21x$, and $21 \\times (-3x)^2 = 21 \\times 9x^2 = 189x^2$.'),
              prose('A first part other than $1$ is raised too, its power falling term by term:'),
              maths('\\begin{aligned} & (2 + x)^{5} \\\\ &\\approx 2^{5} + 5 \\times 2^{4}x \\\\ &\\quad + 10 \\times 2^{3}x^{2} \\\\ &= 32 + 80x + 80x^{2} \\end{aligned}'),
            ),
            ask('bin-approx-tiles'),
            ask('bin-approx+choice'),
            ask('bin-approx-tiles', 2),
            teach(
              prose('To estimate a power from a given bracket, choose $x$ to make the bracket equal the number:'),
              prose('For $(0.98)^6$ from $(1 - 2x)^6$:'),
              maths('1 - 2x = 0.98, \\quad x = 0.01'),
              prose('A number below $1$ needs a negative change: $0.98 = 1 + (-0.02)$.'),
            ),
            ask('bin-approx-x'),
            ask('bin-three-terms-steps', 2),
            ask('bin-approx-x+choice'),
          ],
          skillCheck: [ask('bin-approx', 2), ask('bin-approx-tiles', 2), ask('bin-approx-x', 2)],
        },
        {
          id: 'be-l2-product',
          title: 'A Bracket Times an Expansion',
          slides: [
            teach(
              prose(
                'A term of $(1 + 2x)(1 + x)^5$ does not need the whole product. The $x^3$ term comes two ways: $1$ times the expansion\'s $x^3$ term, and $2x$ times its $x^2$ term.',
              ),
              maths('1 \\times 10x^{3} + 2x \\times 10x^{2} = 30x^{3}'),
            ),
            ask('bin-pair-flow'),
            ask('bin-product-coeff'),
            ask('bin-two-bracket-tree'),
            teach(
              prose('Signs come along. In $(1 - 2x)(1 + x)^7$ the $x^4$ coefficient is'),
              maths('1 \\times 35 + (-2) \\times 35 = -35'),
              prose('For the first few terms of the product, multiply the first bracket into the start of the expansion and collect. With $(1 + x)^5 = 1 + 5x + 10x^2 + \\dots$:'),
              maths('\\begin{aligned} & (1 + 2x)(1 + 5x + 10x^{2}) \\\\ &= 1 + 5x + 10x^{2} \\\\ &\\quad + 2x + 10x^{2} + \\dots \\\\ &= 1 + 7x + 20x^{2} + \\dots \\end{aligned}'),
            ),
            ask('bin-product-expand'),
            ask('bin-pair-flow'),
            ask('bin-product-coeff+choice'),
            teach(
              prose(
                'When the expansion has a number of its own, find its two coefficients first. For the $x^3$ term of $(1 + 3x)(1 + 2x)^4$ they are $32$ and $24$:',
              ),
              maths('1 \\times 32 + 3 \\times 24 = 104'),
            ),
            ask('bin-two-bracket-tree', 2),
            ask('bin-product-expand', 2),
          ],
          skillCheck: [ask('bin-product-coeff', 2), ask('bin-two-bracket-tree', 2), ask('bin-product-expand', 2)],
        },
      ],
      levelCheck: [
        ask('bin-factorial', 2),
        ask('bin-ncr-reduce', 2),
        ask('bin-ncr-facts+choice', 2),
        ask('bin-ncr-row', 2),
        ask('bin-which-r-flow', 2),
        ask('bin-general-tiles', 2),
        ask('bin-general-reduce+choice', 2),
        ask('bin-coeff-ncr', 2),
        ask('bin-free-term', 2),
        ask('bin-find-n', 2),
        ask('bin-approx', 2),
        ask('bin-approx-tiles', 2),
        ask('bin-approx-x+choice', 2),
        ask('bin-product-coeff', 2),
        ask('bin-two-bracket-tree', 2),
      ],
    },
    {
      id: 'be-l3',
      title: 'Unknowns and Conditions',
      lessons: [
        {
          id: 'be-l3-two',
          title: 'Two Unknowns, Two Coefficients',
          slides: [
            teach(
              prose('In $(1 + kx)^n$ the first two terms after the $1$ are'),
              maths('nkx + \\frac{n(n - 1)}{2}k^{2}x^{2}'),
              prose('So when both coefficients are given, there are two equations for $n$ and $k$. If they are $12$ and $60$:'),
              maths('\\begin{aligned} nk &= 12 \\\\ \\frac{n(n - 1)}{2}k^{2} &= 60 \\end{aligned}'),
            ),
            teach(
              prose('The first gives $k = \\frac{12}{n}$, so $k^2 = \\frac{144}{n^2}$. Put that into the second and one $n$ cancels:'),
              maths('\\begin{aligned} \\frac{144(n - 1)}{2n} &= 60 \\\\ 144(n - 1) &= 120n \\\\ 24n &= 144 \\end{aligned}'),
              prose('So $n = 6$, and then $k = \\frac{12}{6} = 2$.'),
            ),
            ask('bin-two-unknowns-flow'),
            ask('bin-n-then-k-tree'),
            ask('bin-two-unknowns'),
            teach(
              prose('With $n$ and $k$ found, every other term follows. The $x^3$ coefficient of $(1 + 2x)^6$ is'),
              maths('{}^{6}C_{3} \\times 2^{3} = 20 \\times 8 = 160'),
              prose('A negative $x$ coefficient means a negative $k$: the sign comes through $nk$, since $n$ is positive. With $k = -2$ the $x^3$ coefficient would be $20 \\times (-8) = -160$.'),
            ),
            ask('bin-n-then-k-tree', 2),
            ask('bin-next-coeff-steps'),
            ask('bin-two-unknowns+choice'),
            ask('bin-two-unknowns-flow', 2),
            ask('bin-next-coeff-steps', 2),
          ],
          skillCheck: [ask('bin-two-unknowns', 2), ask('bin-n-then-k-tree', 2), ask('bin-next-coeff-steps', 2)],
        },
        {
          id: 'be-l3-equal',
          title: 'Equal Coefficients',
          slides: [
            teach(
              prose('Two neighbouring numbers in a row of Pascal\'s triangle are equal only in the middle of an odd row: $35, 35$ in row $7$.'),
              prose('Setting ${}^{n}C_{r} = {}^{n}C_{r + 1}$ and cancelling the factorials says the same thing:'),
              maths('r + 1 = n - r, \\quad n = 2r + 1'),
              prose('So if $x^3$ and $x^4$ have equal coefficients in $(1 + x)^n$, then $n = 7$.'),
            ),
            teach(
              prose('With $k$ in the bracket, the power of $k$ matches the power of $x$. In $(1 + kx)^7$, equal $x^2$ and $x^3$ coefficients say'),
              maths('21k^{2} = 35k^{3}'),
              prose('Divide by $k^2$, which is allowed because $k \\neq 0$:'),
              maths('k = \\frac{21}{35} = \\frac{3}{5}'),
            ),
            ask('bin-equal-tiles'),
            ask('bin-equal-coeff'),
            teach(
              prose('A first part other than $1$ brings its own powers into each coefficient. In $(2 + kx)^4$, equal $x$ and $x^2$ coefficients say'),
              maths('\\begin{aligned} 4 \\times 2^{3}k &= 6 \\times 2^{2}k^{2} \\\\ 32k &= 24k^{2} \\end{aligned}'),
              prose('Divide by $k$: $k = \\frac{32}{24} = \\frac{4}{3}$.'),
            ),
            ask('bin-equal-tiles', 2),
            ask('bin-equal-coeff+choice'),
            ask('bin-equal-flow', 2),
            teach(
              prose(
                'To find which pair is equal, compare neighbours. In $(a + bx)^n$ the $x^{r + 1}$ coefficient is the $x^r$ one multiplied by',
              ),
              maths('\\frac{b(n - r)}{a(r + 1)}'),
              prose('They are equal when that is $1$. In $(1 + 2x)^5$: $2(5 - r) = r + 1$, so $r = 3$, and the $x^3$ and $x^4$ coefficients are both $80$.'),
              prose('In $(3 + x)^7$: $7 - r = 3(r + 1)$, so $r = 1$, and the $x$ and $x^2$ coefficients are both $5103$.'),
            ),
            ask('bin-equal-which'),
            ask('bin-equal-which', 2),
          ],
          skillCheck: [ask('bin-equal-tiles', 2), ask('bin-equal-coeff', 2), ask('bin-equal-which', 2)],
        },
        {
          id: 'be-l3-ratio',
          title: 'Coefficients in a Ratio',
          slides: [
            teach(
              prose('Divide the $x^2$ coefficient of $(1 + kx)^n$ by the $x$ coefficient:'),
              maths('\\frac{n(n - 1)k^{2}}{2} \\div nk = \\frac{(n - 1)k}{2}'),
              prose('If the $x^2$ coefficient of $(1 + kx)^5$ is $6$ times the $x$ coefficient, then $\\frac{4k}{2} = 6$, so $k = 3$.'),
            ),
            ask('bin-ratio-tiles'),
            ask('bin-ratio-reduce'),
            ask('bin-ratio-coeff'),
            teach(
              prose('The same works for any neighbouring pair: the $x^{r + 1}$ coefficient over the $x^r$ one is'),
              maths('\\frac{(n - r)k}{r + 1}'),
              prose('The multiple can be a fraction. If the $x^2$ coefficient of $(1 + kx)^4$ is $\\frac{9}{2}$ times the $x$ one:'),
              maths('\\frac{3k}{2} = \\frac{9}{2}, \\quad k = 3'),
            ),
            ask('bin-ratio-n-steps'),
            ask('bin-ratio-reduce', 2),
            ask('bin-ratio-tiles', 2),
            teach(
              prose('When $k$ is given and $n$ is not, the same equation is solved for $n$.'),
              prose('In $(1 + 2x)^n$, if the $x^2$ coefficient is $5$ times the $x$ coefficient:'),
              maths('\\frac{2(n - 1)}{2} = 5, \\quad n = 6'),
              prose('Check: $12$ and $15 \\times 4 = 60$.'),
            ),
            ask('bin-ratio-coeff+choice'),
            ask('bin-ratio-n-steps', 2),
          ],
          skillCheck: [ask('bin-ratio-coeff', 2), ask('bin-ratio-reduce', 2), ask('bin-ratio-tiles', 2)],
        },
        {
          id: 'be-l3-sum',
          title: 'The Sum of the Coefficients',
          slides: [
            teach(
              prose('Put $x = 1$ and every term of an expansion becomes its coefficient, so the coefficients of $(a + kx)^n$ add up to $(a + k)^n$.'),
              maths('(2 + 3x)^{4}: \\quad 5^{4} = 625'),
              prose('Row sums of $2^n$ are the case $a = k = 1$. Worked backwards: if $(1 + kx)^5$ has coefficients adding to $243 = 3^5$, then $1 + k = 3$ and $k = 2$.'),
            ),
            ask('bin-sum-slider'),
            teach(
              prose('Put $x = -1$ and the odd powers turn negative: that gives the coefficients of $(2 + 3x)^4$ with alternating signs.'),
              maths('(2 - 3)^{4} = 1'),
              prose('and indeed $16 - 96 + 216 - 216 + 81 = 1$.'),
              prose('Add the two and the odd-power coefficients cancel, leaving the even ones twice. Subtract and the even ones cancel, leaving the odd ones twice:'),
              maths('\\begin{aligned} \\text{even}&: \\enspace \\tfrac{625 + 1}{2} = 313 \\\\ \\text{odd}&: \\enspace \\tfrac{625 - 1}{2} = 312 \\end{aligned}'),
              prose('Check: $16 + 216 + 81 = 313$ and $96 + 216 = 312$.'),
            ),
            ask('bin-sum-coeff'),
            ask('bin-sum-which'),
            ask('bin-sum-tree'),
            teach(
              prose('An even power hides a sign. If the coefficients of $(1 + kx)^4$ add up to $81$, then $1 + k = 3$ or $1 + k = -3$:'),
              maths('k = 2 \\quad \\text{or} \\quad k = -4'),
              prose('So a question says $k > 0$, or asks for both.'),
            ),
            ask('bin-sum-coeff', 2),
            ask('bin-sum-which', 2),
            ask('bin-sum-slider', 2),
            ask('bin-sum-tree', 2),
          ],
          skillCheck: [ask('bin-sum-coeff', 2), ask('bin-sum-tree', 2), ask('bin-sum-which', 2)],
        },
        {
          id: 'be-l3-front',
          title: 'The Unknown in Front',
          slides: [
            teach(
              prose('In $(a + x)^n$ the constant term is $a^n$, and the $x^{n - 1}$ term is $na\\,x^{n - 1}$.'),
              prose('If the $x^4$ coefficient of $(a + x)^5$ is $15$, then $5a = 15$ and $a = 3$.'),
              prose('If the constant term of $(a + x)^3$ is $-8$, then $a^3 = -8$ and $a = -2$: an odd power keeps the sign.'),
            ),
            ask('bin-front-a'),
            ask('bin-front-a+choice'),
            teach(
              prose('A middle term brings nCr and the number on $x$ along. The $x^2$ coefficient of $(a + 2x)^4$ is $216$:'),
              maths('\\begin{aligned} 6 \\times a^{2} \\times 4 &= 216 \\\\ a^{2} &= 9 \\end{aligned}'),
              prose('An even power loses the sign: $a = 3$ and $a = -3$ both work, unless the question says $a > 0$.'),
              prose('A minus on $x$ rides along with its number: the $x$ coefficient of $(a - 3x)^3$ is $3a^2 \\times (-3) = -9a^2$.'),
            ),
            ask('bin-front-sign'),
            ask('bin-front-tiles'),
            ask('bin-front-tiles', 2),
            ask('bin-front-sign', 2),
            teach(
              prose('With $a$ and $n$ both unknown, two coefficients are needed. In $(a + x)^n$ the constant is $81$ and the $x$ coefficient is $108$:'),
              maths('\\frac{na^{n - 1}}{a^{n}} = \\frac{n}{a} = \\frac{108}{81} = \\frac{4}{3}'),
              prose('And $a^n = 81$: $a = 3$, $n = 4$ fits both.'),
            ),
            ask('bin-front-flow'),
            ask('bin-front-flow', 2),
          ],
          skillCheck: [ask('bin-front-a', 2), ask('bin-front-sign', 2), ask('bin-front-flow', 2)],
        },
      ],
      levelCheck: [
        ask('bin-two-unknowns', 2),
        ask('bin-n-then-k-tree', 2),
        ask('bin-next-coeff-steps', 2),
        ask('bin-equal-coeff', 2),
        ask('bin-equal-tiles', 2),
        ask('bin-equal-which', 2),
        ask('bin-ratio-reduce', 2),
        ask('bin-ratio-coeff+choice', 2),
        ask('bin-ratio-tiles', 2),
        ask('bin-sum-coeff', 2),
        ask('bin-sum-tree', 2),
        ask('bin-sum-which', 2),
        ask('bin-front-a', 2),
        ask('bin-front-sign', 2),
        ask('bin-front-flow', 2),
      ],
    },
    {
      id: 'be-l4',
      title: 'Products of Expansions',
      lessons: [
        {
          id: 'be-l4-pairs',
          title: 'Two Expansions, One Coefficient',
          slides: [
            teach(
              prose('Multiply two expansions and every term of the product is a term of the first times a term of the second. A multiple of $x^2$ comes three ways: $1 \\times x^2$, $x \\times x$ and $x^2 \\times 1$.'),
              prose('Take $(1 + 2x)^3(1 + x)^4$. Each bracket starts, as far as $x^2$:'),
              maths('\\begin{aligned} (1 + 2x)^{3}&: \\enspace 1 + 6x + 12x^{2} \\\\ (1 + x)^{4}&: \\enspace 1 + 4x + 6x^{2} \\end{aligned}'),
            ),
            ask('bin-two-exp-flow'),
            teach(
              prose('Pair them up, the powers adding to $2$:'),
              maths('\\begin{aligned} & 1 \\times 6 + 6 \\times 4 + 12 \\times 1 \\\\ &= 42 \\end{aligned}'),
              prose('So the $x^2$ coefficient is $42$. The pair most often dropped is $1 \\times 6x^2$: the $1$ has no $x$, but it still makes an $x^2$ term.'),
              prose('A minus rides along in its pair: $(1 - 2x)^3$ starts $1 - 6x + 12x^2$, and its middle pair would be $(-6x) \\times 4x = -24x^2$.'),
            ),
            ask('bin-two-exp-tiles'),
            ask('bin-two-exp-coeff'),
            ask('bin-two-exp-tree'),
            ask('bin-two-exp-coeff+choice'),
            teach(
              prose('$x^k$ comes $k + 1$ ways, as long as both brackets reach $x^k$. In $(1 + x)^2(1 + 3x)^5$ the first bracket stops at $x^2$, so $x^3$ comes only three ways:'),
              maths('\\begin{aligned} & 1 \\times 270 + 2 \\times 90 + 1 \\times 15 \\\\ &= 465 \\end{aligned}'),
              prose('With negative numbers in the brackets, bracket each coefficient before multiplying.'),
            ),
            ask('bin-two-exp-tiles', 2),
            ask('bin-two-exp-flow', 2),
            ask('bin-two-exp-tree', 2),
          ],
          skillCheck: [ask('bin-two-exp-coeff', 2), ask('bin-two-exp-tree', 2), ask('bin-two-exp-flow', 2)],
        },
        {
          id: 'be-l4-three',
          title: 'The First Three Terms',
          slides: [
            teach(
              prose('To expand a product as far as $x^2$, expand each bracket only as far as $x^2$: every later term makes $x^3$ or higher, whatever it is multiplied by. Here the brackets start:'),
              maths('\\begin{aligned} (1 + x)^{5}&: \\enspace 1 + 5x + 10x^{2} \\\\ (1 - 2x)^{3}&: \\enspace 1 - 6x + 12x^{2} \\end{aligned}'),
            ),
            teach(
              prose('The $x$ term is $x$ from one bracket and $1$ from the other, so the $x$ coefficients add: $5 - 6 = -1$.'),
              prose('The $x^2$ term takes both $x^2$ terms and the two $x$ terms multiplied, $5x \\times (-6x) = -30x^2$:'),
              maths('10 - 30 + 12 = -8'),
              maths('\\begin{aligned} & (1 + x)^{5}(1 - 2x)^{3} \\\\ &= 1 - x - 8x^{2} + \\dots \\end{aligned}'),
            ),
            ask('bin-first-three-tiles'),
            ask('bin-first-three-steps'),
            ask('bin-first-three-which'),
            teach(
              prose('In general the $x$ coefficient of $(1 + ax)^m(1 + bx)^n$ is $ma + nb$, and the $x^2$ coefficient has three parts:'),
              maths('{}^{m}C_{2}a^{2} + ma \\times nb + {}^{n}C_{2}b^{2}'),
              prose('The middle one, the two $x$ coefficients multiplied, is the one that goes missing.'),
            ),
            ask('bin-first-three-reduce'),
            ask('bin-first-three-tiles', 2),
            ask('bin-first-three-steps', 2),
            ask('bin-first-three-which', 2),
            ask('bin-first-three-reduce', 2),
          ],
          skillCheck: [ask('bin-first-three-tiles', 2), ask('bin-first-three-steps', 2), ask('bin-first-three-which', 2)],
        },
        {
          id: 'be-l4-pairing',
          title: 'Pairing Brackets',
          slides: [
            teach(
              prose('$(1 + x)(1 - x) = 1 - x^2$. When both brackets have the same power, they pair off one at a time:'),
              maths('(1 + x)^{n}(1 - x)^{n} = (1 - x^{2})^{n}'),
              prose('So $(1 + 3x)^4(1 - 3x)^4 = (1 - 9x^2)^4$: one expansion to do instead of two. Its second part is $-9x^2$, so its $x^2$ term is'),
              maths('{}^{4}C_{1} \\times (-9x^{2}) = -36x^{2}'),
            ),
            ask('bin-collapse-which'),
            ask('bin-collapse-tiles'),
            teach(
              prose('Every term of $(1 - x^2)^n$ is a power of $x^2$, so the odd powers of $x$ all vanish: the $x^3$ coefficient of $(1 + x)^5(1 - x)^5$ is $0$.'),
              prose('The $x^{2k}$ term is ${}^{n}C_{k}(-x^2)^k$: the number is ${}^{n}C_{k}$ and the sign is $(-1)^k$. In $(1 - x^2)^5$ the $x^4$ term is'),
              maths('{}^{5}C_{2}(-x^{2})^{2} = 10x^{4}'),
              prose('A number is squared with it: the $x^4$ term of $(1 - 9x^2)^4$ is ${}^{4}C_{2}(-9x^2)^2 = 6 \\times 81x^4 = 486x^4$.'),
            ),
            ask('bin-collapse-coeff'),
            ask('bin-collapse-flow'),
            ask('bin-collapse-which', 2),
            ask('bin-collapse-tiles', 2),
            teach(
              prose('It only works with equal powers: $(1 + x)^3(1 - x)^5$ is $(1 - x^2)^3(1 - x)^2$, and the odd powers come back.'),
              prose('Check the pairing first, then use the sign rule: in $(1 - 4x^2)^3$ the $x^2$ term is ${}^{3}C_{1}(-4x^2) = -12x^2$, negative because the power of $-4x^2$ is odd.'),
            ),
            ask('bin-collapse-coeff+choice', 2),
            ask('bin-collapse-flow', 2),
          ],
          skillCheck: [ask('bin-collapse-coeff', 2), ask('bin-collapse-flow', 2), ask('bin-collapse-tiles', 2)],
        },
        {
          id: 'be-l4-trinomial',
          title: 'Three Terms in a Bracket',
          slides: [
            teach(
              prose('$(1 + x + x^2)^n$ has three terms in its bracket. Call the last two $u = x + x^2$ and it is a binomial again:'),
              maths('\\begin{aligned} (1 + u)^{n} &= 1 + nu \\\\ &\\quad + {}^{n}C_{2}u^{2} + \\dots \\end{aligned}'),
              prose('Only $u$ and $u^2$ can reach $x^2$: $u^3$ starts at $x^3$.'),
            ),
            ask('bin-trinomial-tree'),
            teach(
              prose('So $x^2$ comes from two places: the $x^2$ inside $nu$, and the $x^2$ at the start of $u^2 = x^2 + 2x^3 + x^4$. In $(1 + x + x^2)^4$:'),
              maths('4 \\times 1 + 6 \\times 1 = 10'),
              prose('The $x$ coefficient is just $4$, from $nu$. With numbers, $u = px + qx^2$ and $u^2$ starts $p^2x^2$. In $(1 + 2x - x^2)^3$ the $x^2$ coefficient is'),
              maths('3 \\times (-1) + 3 \\times 2^{2} = 9'),
            ),
            ask('bin-trinomial-work-steps'),
            ask('bin-trinomial-coeff'),
            ask('bin-trinomial-which'),
            ask('bin-trinomial-tree', 2),
            teach(
              prose('$x^3$ needs $u^2$ and $u^3$: $u^2 = p^2x^2 + 2pq\\,x^3 + \\dots$ and $u^3 = p^3x^3 + \\dots$. In $(1 + x + 2x^2)^4$, with $p = 1$ and $q = 2$:'),
              maths('\\begin{aligned} & {}^{4}C_{2} \\times 2 \\times 1 \\times 2 + {}^{4}C_{3} \\times 1^{3} \\\\ &= 24 + 4 = 28 \\end{aligned}'),
              prose('$nu$ has nothing above $x^2$, so it adds no $x^3$.'),
            ),
            ask('bin-trinomial-coeff', 2),
            ask('bin-trinomial-which', 2),
            ask('bin-trinomial-work-steps', 2),
          ],
          skillCheck: [ask('bin-trinomial-coeff', 2), ask('bin-trinomial-tree', 2), ask('bin-trinomial-work-steps', 2)],
        },
        {
          id: 'be-l4-equating',
          title: 'Equating Across a Product',
          slides: [
            teach(
              prose('$(1 + x)^3(1 + x)^4 = (1 + x)^7$, so the $x^2$ coefficient worked either way must agree. From the pairs on the left:'),
              maths('1 \\times 6 + 3 \\times 4 + 3 \\times 1 = 21'),
              prose('and on the right it is ${}^{7}C_{2} = 21$. A sum of nCr products like this is one nCr.'),
            ),
            ask('bin-identity-tiles'),
            ask('bin-identity-sum'),
            teach(
              prose('Equating works on unknowns too. The $x$ coefficient of $(1 + ax)^2(1 + x)^5$ is $2a + 5$: $x$ from one bracket, $1$ from the other.'),
              prose('If it is $11$:'),
              maths('2a + 5 = 11, \\quad a = 3'),
            ),
            ask('bin-find-a-flow'),
            ask('bin-find-a-coeff'),
            teach(
              prose('Once $a$ is known, every other coefficient follows. With $a = 3$, the $x^2$ coefficient of $(1 + 3x)^2(1 + x)^5$ is'),
              maths('9 + 6 \\times 5 + 10 = 49'),
              prose('the first bracket\'s $x^2$ term, the two $x$ terms multiplied, and the second bracket\'s $x^2$ term.'),
            ),
            ask('bin-find-a-tree'),
            ask('bin-identity-tiles', 2),
            ask('bin-find-a-coeff+choice', 2),
            ask('bin-find-a-tree', 2),
          ],
          skillCheck: [ask('bin-identity-tiles', 2), ask('bin-find-a-coeff', 2), ask('bin-find-a-tree', 2)],
        },
      ],
      levelCheck: [
        ask('bin-two-exp-coeff', 2),
        ask('bin-two-exp-tree', 2),
        ask('bin-two-exp-flow', 2),
        ask('bin-first-three-tiles', 2),
        ask('bin-first-three-steps', 2),
        ask('bin-first-three-which', 2),
        ask('bin-collapse-coeff', 2),
        ask('bin-collapse-flow', 2),
        ask('bin-collapse-tiles', 2),
        ask('bin-trinomial-coeff', 2),
        ask('bin-trinomial-tree', 2),
        ask('bin-trinomial-work-steps', 2),
        ask('bin-find-a-coeff', 2),
        ask('bin-identity-tiles', 2),
        ask('bin-find-a-tree', 2),
      ],
    },
    {
      id: 'be-l5',
      title: 'Estimates and Surds',
      lessons: [
        {
          id: 'be-l5-error',
          title: 'How Big the Error Is',
          slides: [
            teach(
              prose('nCr and the General Term estimated $(1.02)^5$ from the first three terms of $(1 + x)^5$ with $x = 0.02$: $1 + 0.1 + 0.004 = 1.104$. The first term it leaves out is ${}^{5}C_{3}x^3$:'),
              maths('10 \\times 0.02^{3} = 0.00008'),
              prose('Every later term carries a higher power of $0.02$ and is smaller still, so the estimate is out by about $0.00008$. With $x = -0.02$ it would be $10 \\times (-0.02)^3 = -0.00008$: an odd power keeps the minus.'),
            ),
            ask('bin-dropped-term'),
            ask('bin-kept-sum-tree'),
            ask('bin-dropped-term+choice', 2),
            teach(
              prose('An estimate is accurate to $k$ decimal places when its error is under half a unit in place $k$:'),
              maths('\\begin{aligned} 3 \\text{ places}&: \\enspace 0.0005 \\\\ 4 \\text{ places}&: \\enspace 0.00005 \\end{aligned}'),
              prose('$0.00008$ is under $0.0005$ but not under $0.00005$, so $1.104$ is accurate to $3$ decimal places.'),
            ),
            ask('bin-safe-places'),
            ask('bin-enough-terms-flow'),
            teach(
              prose('When the term left out is too big for the places asked, three terms are not enough: keep the $x^3$ term as well.'),
              prose('With $x$ negative the $x$ term is negative and the $x^2$ term positive. For $(0.98)^6$, $x = -0.02$:'),
              maths('\\begin{aligned} & 1 + 6(-0.02) + 15(-0.02)^{2} \\\\ &= 1 - 0.12 + 0.006 = 0.886 \\end{aligned}'),
              prose('The first term left out is ${}^{6}C_{3} \\times (-0.02)^{3} = -0.00016$. The terms alternate in sign, so the error is smaller than that, and under $0.0005$: $0.886$ is good to $3$ decimal places.'),
            ),
            ask('bin-kept-sum-tree', 2),
            ask('bin-safe-places', 2),
            ask('bin-enough-terms-flow', 2),
          ],
          skillCheck: [ask('bin-dropped-term', 2), ask('bin-safe-places', 2), ask('bin-enough-terms-flow', 2)],
        },
        {
          id: 'be-l5-near',
          title: 'A Number in Front',
          slides: [
            teach(
              prose('A power of a number near $2$ or $3$ is estimated the same way, with the whole number kept in the bracket. $2.01 = 2 + 0.01$, so $(2.01)^5$ comes from $(2 + x)^5$ with $x = 0.01$.'),
              prose('A number just below takes a minus: $1.98 = 2 - 0.02$, so $(1.98)^4$ comes from $(2 - x)^4$ with $x = 0.02$.'),
            ),
            ask('bin-near-setup'),
            teach(
              prose('The $2$ is raised to a power in every term, falling as the power of $x$ rises. With $(2 - x)$ the $x$ term turns negative.'),
              maths('\\begin{aligned} & (2 + x)^{5} \\\\ &= 2^{5} + 5 \\times 2^{4}x \\\\ &\\quad + 10 \\times 2^{3}x^{2} + \\dots \\\\ &= 32 + 80x + 80x^{2} + \\dots \\end{aligned}'),
              prose('Put $x = 0.01$:'),
              maths('32 + 0.8 + 0.008 = 32.808'),
            ),
            ask('bin-near-tiles'),
            ask('bin-near-substitute-steps'),
            ask('bin-near-estimate'),
            ask('bin-near-setup', 2),
            teach(
              prose('With the minus, the $x$ term is negative and the $x^2$ term positive:'),
              maths('\\begin{aligned} & (2 - x)^{4} \\\\ &= 16 - 32x + 24x^{2} - \\dots \\end{aligned}'),
              prose('Put $x = 0.02$:'),
              maths('16 - 0.64 + 0.0096 = 15.3696'),
            ),
            ask('bin-near-tiles', 2),
            ask('bin-near-substitute-steps', 2),
            ask('bin-near-estimate+choice', 2),
          ],
          skillCheck: [ask('bin-near-tiles', 2), ask('bin-near-substitute-steps', 2), ask('bin-near-estimate', 2)],
        },
        {
          id: 'be-l5-surd',
          title: 'Surd Expansions',
          slides: [
            teach(
              prose('Powers of $\\sqrt{2}$ alternate: $(\\sqrt{2})^2 = 2$ is whole, and $(\\sqrt{2})^3 = 2\\sqrt{2}$ keeps one root. So an expansion of $(1 + \\sqrt{2})^n$ gathers into $a + b\\sqrt{2}$, with $a$ and $b$ whole.'),
              maths('\\begin{aligned} & (1 + \\sqrt{2})^{3} \\\\ &= 1 + 3\\sqrt{2} + 6 + 2\\sqrt{2} \\\\ &= 7 + 5\\sqrt{2} \\end{aligned}'),
              prose('A number on the root is raised with it: $(2\\sqrt{3})^2 = 4 \\times 3 = 12$, so $(1 + 2\\sqrt{3})^2 = 1 + 4\\sqrt{3} + 12 = 13 + 4\\sqrt{3}$. The surd arithmetic is the same as in Exponents & Radicals.'),
            ),
            ask('bin-surd-powers-tree'),
            ask('bin-surd-tiles'),
            ask('bin-surd-part'),
            teach(
              prose('The even powers of $\\sqrt{2}$ make $a$ and the odd powers make $b$. For $(1 + \\sqrt{2})^4$, row $4$ is $1, 4, 6, 4, 1$:'),
              maths('\\begin{aligned} a &= 1 + 6 \\times 2 + 4 = 17 \\\\ b &= 4 + 4 \\times 2 = 12 \\end{aligned}'),
            ),
            ask('bin-surd-gather-steps'),
            ask('bin-surd-part+choice', 2),
            ask('bin-surd-powers-tree', 2),
            teach(
              prose('In $(1 - \\sqrt{2})^n$ only the odd powers of $-\\sqrt{2}$ are negative, so $a$ stays the same and $b$ changes sign:'),
              maths('(1 - \\sqrt{2})^{4} = 17 - 12\\sqrt{2}'),
            ),
            ask('bin-surd-tiles', 2),
            ask('bin-surd-gather-steps', 2),
          ],
          skillCheck: [ask('bin-surd-tiles', 2), ask('bin-surd-part', 2), ask('bin-surd-gather-steps', 2)],
        },
        {
          id: 'be-l5-conjugate',
          title: 'Conjugate Pairs',
          slides: [
            teach(
              prose('$(1 + \\sqrt{2})^4 = 17 + 12\\sqrt{2}$ and $(1 - \\sqrt{2})^4 = 17 - 12\\sqrt{2}$. Added, the roots cancel; subtracted, the whole parts cancel:'),
              maths('\\begin{aligned} \\text{sum} &= 34 \\\\ \\text{difference} &= 24\\sqrt{2} \\end{aligned}'),
            ),
            ask('bin-conjugate-tiles'),
            ask('bin-conjugate-value'),
            teach(
              prose('It works for every $n$. Only the odd powers of $\\sqrt{2}$ change sign between the two expansions, so adding cancels them and subtracting doubles them:'),
              maths('\\begin{aligned} & (1 + \\sqrt{2})^{n} + (1 - \\sqrt{2})^{n} \\\\ &= 2a \\end{aligned}'),
              maths('\\begin{aligned} & (1 + \\sqrt{2})^{n} - (1 - \\sqrt{2})^{n} \\\\ &= 2b\\sqrt{2} \\end{aligned}'),
              prose('With $n = 3$: $(1 + \\sqrt{2})^3 = 7 + 5\\sqrt{2}$ and $(1 - \\sqrt{2})^3 = 7 - 5\\sqrt{2}$, so the sum is $14$ and the difference $10\\sqrt{2}$.'),
            ),
            ask('bin-conjugate-which'),
            ask('bin-conjugate-flow'),
            ask('bin-conjugate-value+choice', 2),
            ask('bin-conjugate-tiles', 2),
            teach(
              prose('Watch the order inside the bracket. $\\sqrt{2} - 1 = -(1 - \\sqrt{2})$, so $(\\sqrt{2} - 1)^n$ is $(1 - \\sqrt{2})^n$ when $n$ is even, and its negative when $n$ is odd.'),
              maths('(\\sqrt{2} - 1)^{3} = -(1 - \\sqrt{2})^{3}'),
            ),
            ask('bin-conjugate-which', 2),
            ask('bin-conjugate-flow', 2),
          ],
          skillCheck: [ask('bin-conjugate-value', 2), ask('bin-conjugate-which', 2), ask('bin-conjugate-flow', 2)],
        },
        {
          id: 'be-l5-mixed',
          title: 'A Number and a Surd',
          slides: [
            teach(
              prose('A number in front of the root works the same way, its powers kept. In $(2 + \\sqrt{3})^2$ the $2$ is squared too:'),
              maths('\\begin{aligned} (2 + \\sqrt{3})^{2} &= 4 + 4\\sqrt{3} + 3 \\\\ &= 7 + 4\\sqrt{3} \\end{aligned}'),
              prose('A number on the root as well is raised with the root, $(2\\sqrt{3})^2 = 12$:'),
              maths('\\begin{aligned} (2 + 2\\sqrt{3})^{2} &= 4 + 8\\sqrt{3} + 12 \\\\ &= 16 + 8\\sqrt{3} \\end{aligned}'),
            ),
            ask('bin-mixed-terms-tree'),
            ask('bin-mixed-tiles'),
            ask('bin-mixed-part'),
            teach(
              prose('A bracket times its conjugate is a difference of two squares:'),
              maths('\\begin{aligned} & (2 + \\sqrt{3})(2 - \\sqrt{3}) \\\\ &= 4 - 3 = 1 \\end{aligned}'),
              prose('With the same power on both they pair off, so $(2 + \\sqrt{3})^n(2 - \\sqrt{3})^n = 1^n = 1$. In general the product is $(p^2 - k)^n$.'),
            ),
            ask('bin-unit-steps'),
            ask('bin-mixed-part+choice', 2),
            ask('bin-mixed-terms-tree', 2),
            teach(
              prose('So $(2 - \\sqrt{3})^n$ is $1$ divided by $(2 + \\sqrt{3})^n$: small where the other is large. It has the same $a$ and $b$, with a minus:'),
              maths('(2 - \\sqrt{3})^{3} = 26 - 15\\sqrt{3}'),
              prose('Check: $26^2 - 3 \\times 15^2 = 676 - 675 = 1$.'),
            ),
            ask('bin-mixed-tiles', 2),
            ask('bin-unit-steps', 2),
          ],
          skillCheck: [ask('bin-mixed-tiles', 2), ask('bin-mixed-part', 2), ask('bin-unit-steps', 2)],
        },
      ],
      levelCheck: [
        ask('bin-dropped-term', 2),
        ask('bin-safe-places', 2),
        ask('bin-enough-terms-flow', 2),
        ask('bin-near-tiles', 2),
        ask('bin-near-substitute-steps', 2),
        ask('bin-near-estimate', 2),
        ask('bin-surd-tiles', 2),
        ask('bin-surd-powers-tree', 2),
        ask('bin-surd-part', 2),
        ask('bin-conjugate-which', 2),
        ask('bin-conjugate-value', 2),
        ask('bin-conjugate-flow', 2),
        ask('bin-mixed-tiles', 2),
        ask('bin-mixed-part', 2),
        ask('bin-unit-steps', 2),
      ],
    },
    {
      id: 'be-l6',
      title: 'The Binomial Series for Rational n',
      lessons: [
        {
          id: 'be-l6-never',
          title: 'The Series That Never Ends',
          slides: [
            teach(
              prose('The coefficient of $x^r$ in $(1 + x)^n$ is $\\frac{n(n - 1)\\dots(n - r + 1)}{r!}$. For a whole $n$ a factor on top reaches $0$, and every coefficient after it is $0$. In $(1 + x)^2$ the $x^3$ coefficient is'),
              maths('(2)(1)(0) \\div 3! = 0'),
              prose('so the expansion stops. The same formula works for any $n$, and for $n = -\\frac{1}{2}$ the factors $-\\frac{1}{2}, -\\frac{3}{2}, -\\frac{5}{2}, \\dots$ never reach $0$: the expansion never ends.'),
            ),
            ask('bin-series-factors-tiles'),
            ask('bin-series-stops-choice'),
            ask('bin-series-coef-steps'),
            teach(
              prose('Work each coefficient from $n$ exactly as before. For $n = -\\frac{1}{2}$:'),
              maths('\\begin{aligned} x^{2}&: \\enspace (-\\tfrac{1}{2})(-\\tfrac{3}{2}) \\div 2! = \\tfrac{3}{8} \\\\ x^{3}&: \\enspace \\tfrac{3}{8} \\times (-\\tfrac{5}{2}) \\div 3 = -\\tfrac{5}{16} \\end{aligned}'),
              prose('Each coefficient is the one before times the next factor, over the next whole number.'),
            ),
            ask('bin-series-build-tree'),
            ask('bin-series-factors-tiles', 2),
            ask('bin-series-coef-steps', 2),
            teach(
              prose('Four terms of the series are usually enough:'),
              maths('\\begin{aligned} & (1 + x)^{-1/2} \\\\ &= 1 - \\tfrac{1}{2}x + \\tfrac{3}{8}x^{2} - \\tfrac{5}{16}x^{3} + \\dots \\end{aligned}'),
              prose('Check the value of $n$, not its look: $(1 + x)^{6/2}$ is $(1 + x)^3$ and stops, while $(1 + x)^{-4/2}$ is $(1 + x)^{-2}$ and never ends.'),
            ),
            ask('bin-series-stops-choice', 2),
            ask('bin-series-build-tree', 2),
          ],
          skillCheck: [ask('bin-series-coef-steps', 2), ask('bin-series-stops-choice', 2), ask('bin-series-build-tree', 2)],
        },
        {
          id: 'be-l6-negative',
          title: 'Negative Whole n',
          slides: [
            teach(
              prose('With $n = -1$ the numbers from $n$ are $-1, 1, -1, \\dots$, so'),
              maths('\\begin{aligned} & (1 + x)^{-1} \\\\ &= 1 - x + x^{2} - x^{3} + \\dots \\end{aligned}'),
              prose('That is the geometric series of Sequences & Series, first term $1$ and ratio $-x$. A number on $x$ is raised with it: in $(1 + 2x)^{-1}$ the $x^2$ term is $1 \\times 2^2 x^2 = 4x^2$.'),
            ),
            teach(
              prose('For $n = -2$ the numbers from $n$ are $-2$, then $(-2)(-3) \\div 2 = 3$, then $(-2)(-3)(-4) \\div 6 = -4$:'),
              maths('\\begin{aligned} & (1 + x)^{-2} \\\\ &= 1 - 2x + 3x^{2} - 4x^{3} + \\dots \\end{aligned}'),
              prose('For $n = -3$ they are $-3$, then $(-3)(-4) \\div 2 = 6$, then $(-3)(-4)(-5) \\div 6 = -10$.'),
              prose('A number on $x$ goes into each power with its sign. In $(1 - 3x)^{-2}$:'),
              maths('\\begin{aligned} x&: \\enspace (-2) \\times (-3) = 6 \\\\ x^{2}&: \\enspace 3 \\times (-3)^{2} = 27 \\end{aligned}'),
            ),
            ask('bin-negative-tiles'),
            ask('bin-negative-coef'),
            ask('bin-negative-tree'),
            teach(
              prose('With $n$ negative every factor on top is negative, so the numbers from $n$ alternate in sign. A minus in the bracket turns the odd terms back, and every term of $(1 - x)^{-2}$ is positive:'),
              maths('\\begin{aligned} & (1 - x)^{-2} \\\\ &= 1 + 2x + 3x^{2} + 4x^{3} + \\dots \\end{aligned}'),
              prose('So the sign of a term is two signs multiplied: the number from $n$, and the power of the number on $x$.'),
            ),
            ask('bin-negative-signs-flow'),
            ask('bin-negative-coef+choice', 2),
            ask('bin-negative-tiles', 2),
            ask('bin-negative-signs-flow', 2),
            ask('bin-negative-tree', 2),
          ],
          skillCheck: [ask('bin-negative-tiles', 2), ask('bin-negative-coef', 2), ask('bin-negative-signs-flow', 2)],
        },
        {
          id: 'be-l6-fraction',
          title: 'Fractional n',
          slides: [
            teach(
              prose('$(1 + x)^{1/2}$ is $\\sqrt{1 + x}$, as in Exponents & Radicals. The numbers from $n = \\frac{1}{2}$ are $\\frac{1}{2}$, then'),
              maths('\\begin{aligned} & (\\tfrac{1}{2})(-\\tfrac{1}{2}) \\div 2! = -\\tfrac{1}{8} \\\\ & (\\tfrac{1}{2})(-\\tfrac{1}{2})(-\\tfrac{3}{2}) \\div 3! = \\tfrac{1}{16} \\end{aligned}'),
              maths('\\begin{aligned} & (1 + x)^{1/2} \\\\ &= 1 + \\tfrac{1}{2}x - \\tfrac{1}{8}x^{2} + \\tfrac{1}{16}x^{3} - \\dots \\end{aligned}'),
            ),
            ask('bin-fraction-term-steps'),
            teach(
              prose('A number on $x$ is raised with it, as before. In $(1 + 4x)^{1/2}$:'),
              maths('\\begin{aligned} x&: \\enspace \\tfrac{1}{2} \\times 4 = 2 \\\\ x^{2}&: \\enspace -\\tfrac{1}{8} \\times 4^{2} = -2 \\end{aligned}'),
              prose('$n$ can be negative too. For $n = -\\frac{1}{2}$ the numbers are $-\\frac{1}{2}$, then $(-\\frac{1}{2})(-\\frac{3}{2}) \\div 2! = \\frac{3}{8}$. In $(1 + 2x)^{-1/2}$:'),
              maths('\\begin{aligned} x&: \\enspace -\\tfrac{1}{2} \\times 2 = -1 \\\\ x^{2}&: \\enspace \\tfrac{3}{8} \\times 2^{2} = \\tfrac{3}{2} \\end{aligned}'),
            ),
            ask('bin-fraction-tiles'),
            ask('bin-fraction-which'),
            teach(
              prose('Three slips to watch: divide by $r!$, raise the number on $x$ to the power $r$, and keep the sign each factor brings. For $n = \\frac{1}{3}$ the second factor is $\\frac{1}{3} - 1 = -\\frac{2}{3}$, so the $x^2$ number is $(\\frac{1}{3})(-\\frac{2}{3}) \\div 2! = -\\frac{1}{9}$:'),
              maths('\\begin{aligned} & (1 + 3x)^{1/3} \\\\ &= 1 + \\tfrac{1}{3}(3x) - \\tfrac{1}{9}(3x)^{2} + \\dots \\\\ &= 1 + x - x^{2} + \\dots \\end{aligned}'),
            ),
            ask('bin-fraction-tiles', 2),
            ask('bin-fraction-coef'),
            ask('bin-fraction-coef+choice', 2),
            ask('bin-fraction-term-steps', 2),
            ask('bin-fraction-which', 2),
          ],
          skillCheck: [ask('bin-fraction-tiles', 2), ask('bin-fraction-coef', 2), ask('bin-fraction-which', 2)],
        },
        {
          id: 'be-l6-valid',
          title: 'Valid for |x| < 1',
          slides: [
            teach(
              prose('$(1 + x)^{-1} = 1 - x + x^2 - \\dots$ is a geometric series, and a geometric series only has a sum when its ratio is under $1$ in size. At $x = 2$ its terms $1, -2, 4, -8, \\dots$ just grow.'),
              prose('Every series here is the same: for $n$ negative or a fraction, the expansion of $(1 + x)^n$ holds only for $|x| < 1$. In $(1 + bx)^n$ it is the whole part added to the $1$ that must be under $1$ in size:'),
              maths('|bx| < 1 \\iff |x| < \\frac{1}{|b|}'),
              prose('So $(1 - 3x)^{1/2}$ holds for $|3x| < 1$, which is $|x| < \\frac{1}{3}$.'),
            ),
            ask('bin-valid-bound'),
            teach(
              prose('A fraction on $x$ works the same way. $(1 + \\frac{x}{4})^{-2}$ holds for $|\\frac{x}{4}| < 1$, so $|x| < 4$, and $(1 - \\frac{2x}{3})^{1/2}$ for $|\\frac{2x}{3}| < 1$, so $|x| < \\frac{3}{2}$.'),
              prose('To test one $x$, find the size of $bx$ there. For $(1 + 2x)^{-1}$ at $x = \\frac{1}{4}$, $|2x| = \\frac{1}{2}$, under $1$, so the series holds; at $x = 1$, $|2x| = 2$, so it does not.'),
            ),
            ask('bin-valid-which-x'),
            ask('bin-valid-slider'),
            ask('bin-valid-flow'),
            ask('bin-valid-bound+choice', 2),
            ask('bin-valid-which-x', 2),
            teach(
              prose('Outside the range the series still gives numbers, just not the right ones: $(1 + 2x)^{-1}$ at $x = 1$ is $\\frac{1}{3}$, but its series $1 - 2 + 4 - 8 + \\dots$ never settles.'),
              prose('Right at the edge it depends on $n$, so the questions here keep clear of it.'),
            ),
            ask('bin-valid-slider', 2),
            ask('bin-valid-flow', 2),
          ],
          skillCheck: [ask('bin-valid-bound', 2), ask('bin-valid-which-x', 2), ask('bin-valid-flow', 2)],
        },
        {
          id: 'be-l6-taken-out',
          title: 'Taking the Number Out',
          slides: [
            teach(
              prose('The series needs a $1$ in the bracket, so take the number out first, powered like the rest:'),
              maths('\\begin{aligned} & (4 + x)^{1/2} \\\\ &= 4^{1/2}(1 + \\tfrac{x}{4})^{1/2} \\\\ &= 2(1 + \\tfrac{x}{4})^{1/2} \\end{aligned}'),
              prose('$4^{1/2} = 2$ and $8^{-1/3} = \\frac{1}{2}$, as in Exponents & Radicals.'),
            ),
            ask('bin-taken-out-coef-steps'),
            ask('bin-taken-out-parts-tree'),
            teach(
              prose('Expand the bracket with $\\frac{x}{4}$ in place of $x$, then multiply every term by the $2$:'),
              maths('\\begin{aligned} & (1 + \\tfrac{x}{4})^{1/2} \\\\ &= 1 + \\tfrac{1}{8}x - \\tfrac{1}{128}x^{2} + \\dots \\end{aligned}'),
              maths('\\begin{aligned} & (4 + x)^{1/2} \\\\ &= 2 + \\tfrac{1}{4}x - \\tfrac{1}{64}x^{2} + \\dots \\end{aligned}'),
            ),
            ask('bin-taken-out-tiles'),
            ask('bin-taken-out-coef-steps', 2),
            ask('bin-taken-out-tiles', 2),
            teach(
              prose('The range comes from the bracket left behind: $(1 + \\frac{x}{4})^{1/2}$ holds for $|\\frac{x}{4}| < 1$, so $(4 + x)^{1/2}$ holds for $|x| < 4$. In general:'),
              maths('(a + bx)^{n}: \\enspace |x| < \\frac{a}{|b|}'),
              prose('So $(2 - 3x)^{-1} = \\frac{1}{2}(1 - \\frac{3x}{2})^{-1}$ holds for $|\\frac{3x}{2}| < 1$, which is $|x| < \\frac{2}{3}$.'),
            ),
            ask('bin-taken-out-range'),
            ask('bin-taken-out-range+choice', 2),
            ask('bin-taken-out-parts-tree', 2),
          ],
          skillCheck: [ask('bin-taken-out-tiles', 2), ask('bin-taken-out-coef-steps', 2), ask('bin-taken-out-range', 2)],
        },
      ],
      levelCheck: [
        ask('bin-series-coef-steps', 2),
        ask('bin-series-stops-choice', 2),
        ask('bin-series-build-tree', 2),
        ask('bin-negative-tiles', 2),
        ask('bin-negative-coef', 2),
        ask('bin-negative-signs-flow', 2),
        ask('bin-fraction-tiles', 2),
        ask('bin-fraction-coef', 2),
        ask('bin-fraction-which', 2),
        ask('bin-valid-bound', 2),
        ask('bin-valid-which-x', 2),
        ask('bin-valid-flow', 2),
        ask('bin-taken-out-tiles', 2),
        ask('bin-taken-out-coef-steps', 2),
        ask('bin-taken-out-range', 2),
      ],
    },
    {
      id: 'be-l7',
      title: 'Approximating with the Series',
      lessons: [
        {
          id: 'be-l7-root',
          title: 'A Root from the Series',
          slides: [
            teach(
              prose('A root is a fractional power, so the series from The Binomial Series for Rational n gives its value. $\\sqrt{1.02} = (1.02)^{1/2}$, which is $(1 + x)^{1/2}$ with $x = 0.02$:'),
              maths('\\begin{aligned} & (1 + x)^{1/2} \\\\ &= 1 + \\tfrac{1}{2}x - \\tfrac{1}{8}x^{2} + \\dots \\end{aligned}'),
              prose('$x = 0.02$ is well inside $|x| < 1$, so the series holds, and its terms shrink fast. A cube root is the power $\\frac{1}{3}$, and one over a root is a negative power: $\\frac{1}{\\sqrt{1.02}} = (1.02)^{-1/2}$.'),
            ),
            ask('bin-root-setup'),
            ask('bin-root-terms-tree'),
            ask('bin-root-estimate'),
            teach(
              prose('Put $x = 0.02$ into each term:'),
              maths('\\begin{aligned} \\tfrac{1}{2} \\times 0.02 &= 0.01 \\\\ \\tfrac{1}{8} \\times 0.02^{2} &= 0.00005 \\end{aligned}'),
              prose('So $\\sqrt{1.02} \\approx 1 + 0.01 - 0.00005 = 1.00995$. The true value is $1.0099504\\dots$: each later term carries a higher power of a small number, so three terms are already very close.'),
            ),
            ask('bin-root-substitute-steps'),
            teach(
              prose('Below $1$, $x$ is negative: $\\sqrt{0.98}$ is $(1 + x)^{1/2}$ with $x = -0.02$, and $x^2$ is still positive: $1 - 0.01 - 0.00005 = 0.98995$.'),
              prose('One over a cube root below $1$: $\\frac{1}{\\sqrt[3]{0.91}} = (1 + x)^{-1/3}$ with $x = -0.09$, and $(1 + x)^{-1/3} \\approx 1 - \\frac{1}{3}x + \\frac{2}{9}x^2$:'),
              maths('1 + 0.03 + \\tfrac{2}{9} \\times 0.0081 = 1.0318'),
              prose('A root of a power multiplies the powers: $\\sqrt{1.01^{3}} = (1.01)^{3/2}$, so $n = \\frac{3}{2}$ and $x = 0.01$.'),
            ),
            ask('bin-root-estimate+choice', 2),
            ask('bin-root-setup', 2),
            ask('bin-root-terms-tree', 2),
            ask('bin-root-substitute-steps', 2),
          ],
          skillCheck: [ask('bin-root-estimate', 2), ask('bin-root-terms-tree', 2), ask('bin-root-substitute-steps', 2)],
        },
        {
          id: 'be-l7-reciprocal',
          title: 'Reciprocals',
          slides: [
            teach(
              prose('One over a power is a negative power, as in Exponents & Radicals:'),
              maths('\\frac{1}{(1 - x)^{2}} = (1 - x)^{-2}'),
              prose('Its series, from The Binomial Series for Rational n, is $1 + 2x + 3x^2 + \\dots$, so $\\frac{1}{0.98^2}$ comes from $x = 0.02$:'),
              maths('1 + 0.04 + 0.0012 = 1.0412'),
            ),
            ask('bin-reciprocal-rewrite'),
            ask('bin-reciprocal-flow'),
            ask('bin-reciprocal-estimate'),
            teach(
              prose('With a number on $x$, find $x$ from the whole bracket. $\\frac{1}{1.04} = (1 + 2x)^{-1}$ needs $1 + 2x = 1.04$, so $x = 0.02$:'),
              maths('\\begin{aligned} & (1 + 2x)^{-1} \\\\ &= 1 - 2x + 4x^{2} - \\dots \\end{aligned}'),
              maths('1 - 0.04 + 0.0016 = 0.9616'),
            ),
            ask('bin-reciprocal-terms-tree'),
            teach(
              prose('Watch the signs. With $n$ negative the terms alternate, and a minus in the bracket turns the odd ones back: every term of $(1 - x)^{-2}$ is positive, so $\\frac{1}{0.98^2}$ comes out above $1$, as it should.'),
              prose('A root underneath is a fractional negative power: $\\frac{1}{\\sqrt{(1 - x)^3}} = (1 - x)^{-3/2}$, and a number on top stays in front, $\\frac{2}{\\sqrt[3]{1 + x}} = 2(1 + x)^{-1/3}$. For $\\frac{1}{\\sqrt{0.98}} = (1 - x)^{-1/2}$ with $x = 0.02$:'),
              maths('\\begin{aligned} & (1 - x)^{-1/2} \\approx 1 + \\tfrac{1}{2}x + \\tfrac{3}{8}x^{2} \\\\ &= 1 + 0.01 + 0.00015 \\\\ &= 1.01015 \\end{aligned}'),
            ),
            ask('bin-reciprocal-estimate+choice', 2),
            ask('bin-reciprocal-rewrite', 2),
            ask('bin-reciprocal-flow', 2),
            ask('bin-reciprocal-terms-tree', 2),
          ],
          skillCheck: [ask('bin-reciprocal-estimate', 2), ask('bin-reciprocal-flow', 2), ask('bin-reciprocal-terms-tree', 2)],
        },
        {
          id: 'be-l7-out-first',
          title: 'Taking the Number Out First',
          slides: [
            teach(
              prose('The series needs a bracket that starts with $1$. $4.08$ is not near $1$, so take the $4$ out first, as in The Binomial Series for Rational n:'),
              maths('\\begin{aligned} \\sqrt{4.08} &= \\sqrt{4} \\times \\sqrt{1.02} \\\\ &= 2(1 + 0.02)^{1/2} \\end{aligned}'),
            ),
            ask('bin-out-first-tiles'),
            ask('bin-out-first-which'),
            teach(
              prose('Estimate the bracket, then multiply by the number taken out:'),
              maths('\\begin{aligned} \\sqrt{4.08} &\\approx 2 \\times 1.00995 \\\\ &= 2.0199 \\end{aligned}'),
              prose('A cube root takes out a cube: $\\sqrt[3]{8.24} = 2(1 + 0.03)^{1/3}$.'),
              prose('One over a root takes out one over the root, and a number just below makes $x$ negative:'),
              maths('\\begin{aligned} \\frac{1}{\\sqrt{3.92}} &= 4^{-1/2}(1 - 0.02)^{-1/2} \\\\ &= \\tfrac{1}{2}(1 + x)^{-1/2} \\end{aligned}'),
              prose('with $x = -0.02$.'),
            ),
            ask('bin-out-first-estimate'),
            ask('bin-out-first-tree'),
            ask('bin-out-first-estimate+choice', 2),
            ask('bin-out-first-tiles', 2),
            teach(
              prose('This is the range from The Binomial Series for Rational n at work: $(a + bx)^n$ holds for $|x| < \\frac{a}{|b|}$. Writing $\\sqrt{4.08}$ as $(1 + 3.08)^{1/2}$ is equal, but $3.08$ is far outside $|x| < 1$ and that series does not hold.'),
              prose('Taking the $4$ out leaves $x = 0.02$, deep inside the range, where three terms are plenty.'),
            ),
            ask('bin-out-first-which', 2),
            ask('bin-out-first-tree', 2),
          ],
          skillCheck: [ask('bin-out-first-tiles', 2), ask('bin-out-first-estimate', 2), ask('bin-out-first-tree', 2)],
        },
        {
          id: 'be-l7-error',
          title: 'How Good, and Which x',
          slides: [
            teach(
              prose('$\\frac{1}{1.02} = (1 + x)^{-1}$ at $x = 0.02$, and three terms give $1 - 0.02 + 0.0004 = 0.9804$. As in Estimates and Surds, the first term left out is about the size of the error:'),
              maths('-x^{3} = -0.000008'),
              prose('An estimate is good to $k$ places when its error is under half a unit in place $k$. $0.000008$ is under $0.00005$ but not under $0.000005$, so $0.9804$ is good to $4$ places.'),
            ),
            ask('bin-error-term'),
            ask('bin-error-places-flow'),
            ask('bin-error-term+choice', 2),
            teach(
              prose('To estimate a surd, choose $x$ so the bracket holds a number you know. $0.98 = \\frac{49 \\times 2}{100}$, so'),
              maths('\\begin{aligned} \\sqrt{0.98} &= \\tfrac{7}{10}\\sqrt{2} \\\\ \\sqrt{2} &= \\tfrac{10}{7}(1 - 0.02)^{1/2} \\end{aligned}'),
              prose('$x = 1$ gives $\\sqrt{2}$ too, but at the edge of the range the terms barely shrink. The smaller $|x|$, the better.'),
            ),
            ask('bin-known-root-which'),
            ask('bin-error-places-flow', 2),
            teach(
              prose('Three terms of $(1 - 0.02)^{1/2}$ give $0.98995$, so'),
              maths('\\begin{aligned} \\sqrt{2} &\\approx \\tfrac{10}{7} \\times 0.98995 \\\\ &= 1.4142142\\dots \\end{aligned}'),
              prose('The term left out is about $\\frac{10}{7} \\times 0.0000005$, under $0.000005$, so this is good to $5$ places: $\\sqrt{2} \\approx 1.41421$.'),
            ),
            ask('bin-known-root-estimate'),
            ask('bin-known-root-which', 2),
            ask('bin-known-root-estimate+choice', 2),
          ],
          skillCheck: [ask('bin-error-term', 2), ask('bin-error-places-flow', 2), ask('bin-known-root-estimate', 2)],
        },
        {
          id: 'be-l7-split',
          title: 'A Partial-Fraction Split',
          slides: [
            teach(
              prose('A proper fraction with two brackets underneath splits into two simpler ones, as in Algebraic & Partial Fractions:'),
              maths('\\begin{aligned} & \\frac{4 + 5x}{(1 - x)(1 + 2x)} \\\\ &= \\frac{3}{1 - x} + \\frac{1}{1 + 2x} \\end{aligned}'),
              prose('Each part is a number times $(1 + wx)^{-1}$, whose series is geometric: $1 - wx + w^2x^2 - \\dots$'),
            ),
            ask('bin-pf-parts-tree'),
            ask('bin-pf-coef'),
            ask('bin-pf-tiles'),
            teach(
              prose('Expand each part, then add like terms:'),
              maths('\\begin{aligned} \\frac{3}{1 - x} &= 3 + 3x + 3x^{2} + \\dots \\\\ \\frac{1}{1 + 2x} &= 1 - 2x + 4x^{2} - \\dots \\end{aligned}'),
              prose('So the series of the whole fraction starts $4 + x + 7x^2 + \\dots$'),
            ),
            ask('bin-pf-coef+choice', 2),
            ask('bin-pf-parts-tree', 2),
            ask('bin-pf-tiles', 2),
            teach(
              prose('Each part holds on its own range: $|x| < 1$ for $\\frac{3}{1 - x}$, and $|x| < \\frac{1}{2}$ for $\\frac{1}{1 + 2x}$.'),
              prose('The series of the whole needs both, so it holds for the smaller: $|x| < \\frac{1}{2}$.'),
            ),
            ask('bin-pf-range'),
            ask('bin-pf-range', 2),
          ],
          skillCheck: [ask('bin-pf-tiles', 2), ask('bin-pf-coef', 2), ask('bin-pf-range', 2)],
        },
      ],
      levelCheck: [
        ask('bin-root-estimate', 2),
        ask('bin-root-terms-tree', 2),
        ask('bin-root-substitute-steps', 2),
        ask('bin-reciprocal-flow', 2),
        ask('bin-reciprocal-estimate', 2),
        ask('bin-reciprocal-terms-tree', 2),
        ask('bin-out-first-tiles', 2),
        ask('bin-out-first-which', 2),
        ask('bin-out-first-estimate', 2),
        ask('bin-error-term', 2),
        ask('bin-error-places-flow', 2),
        ask('bin-known-root-estimate', 2),
        ask('bin-pf-tiles', 2),
        ask('bin-pf-parts-tree', 2),
        ask('bin-pf-range', 2),
      ],
    },
  ],
};
