/**
 * Geometry, level 6: Pythagoras' Geometry.
 *
 * Pythagoras' theorem stated and used, never proved (the owner's rule for this
 * Fundamentals course): the hypotenuse, whole-number triples, a shorter side
 * and answers left as roots, the two special right triangles, and ladders,
 * diagonals and distances. Generators and figures are in
 * `generators/geometryPythagoras.ts`.
 */
import type { Level } from '../../types';
import { ladderSvg, pointsSvg, rectDiagSvg, rightTriSvg } from '../../generators/geometryPythagoras';
import { ask, diagram, display, prose, teach } from './blocks';

export const pythagoras: Level = {
  id: 'geo-l6',
  title: "Pythagoras' Geometry",
  lessons: [
    {
      id: 'geo-l6-theorem',
      title: 'The Pythagorean Theorem',
      slides: [
        teach(
          prose('In a right-angled triangle, the side opposite the right angle is the **hypotenuse**. It is always the longest side.'),
          diagram(rightTriSvg(4, 3, 0, { a: 'a', b: 'b', c: 'c' })),
          prose("**Pythagoras' theorem**: the square of the hypotenuse is the sum of the squares of the other two sides."),
          display('a^2 + b^2 = c^2'),
          prose('With shorter sides of $3\\text{ cm}$ and $4\\text{ cm}$:'),
          display('c^2 = 3^2 + 4^2 = 9 + 16 = 25'),
          display('c = \\sqrt{25} = 5'),
        ),
        ask('geo-pyth-which'),
        ask('geo-pyth-hyp'),
        teach(
          prose('Always square first, then add, then take the square root. With shorter sides of $6\\text{ cm}$ and $8\\text{ cm}$:'),
          diagram(rightTriSvg(8, 6, 1, { a: '8 cm', b: '6 cm', c: 'c' })),
          display('c^2 = 36 + 64 = 100'),
          display('c = \\sqrt{100} = 10'),
          prose('Adding first gives $6 + 8 = 14$, which is wrong: the hypotenuse is always shorter than the other two sides added together.'),
        ),
        ask('geo-pyth-tiles'),
        ask('geo-pyth-hyp+choice', 2),
        ask('geo-pyth-which', 2),
        teach(
          prose('The right angle can sit in any corner, and the letters can be anything. Find the side opposite the right angle first: that is the one on its own.'),
          diagram(rightTriSvg(5, 4, 3, { a: 'p', b: 'q', c: 'r' })),
          display('p^2 + q^2 = r^2'),
          prose('Sides of $5\\text{ cm}$ and $12\\text{ cm}$:'),
          display('c^2 = 25 + 144 = 169'),
          display('c = \\sqrt{169} = 13'),
        ),
        ask('geo-pyth-tiles', 2),
      ],
      skillCheck: [ask('geo-pyth-hyp', 2), ask('geo-pyth-tiles', 2), ask('geo-pyth-which', 2)],
    },
    {
      id: 'geo-l6-triples',
      title: 'Pythagorean Triples',
      slides: [
        teach(
          prose("A **Pythagorean triple** is three whole numbers that fit Pythagoras' theorem. The ones to know:"),
          display('3,\\ 4,\\ 5 \\qquad 5,\\ 12,\\ 13 \\qquad 8,\\ 15,\\ 17'),
          prose('To test three lengths, square the two shorter ones and add, then compare with the square of the longest. For $5,\\ 12,\\ 13$:'),
          display('25 + 144 = 169 = 13^2'),
          prose('So they make a right-angled triangle. For $6,\\ 7,\\ 9$:'),
          display('36 + 49 = 85'),
          prose('That is not $9^2 = 81$, so they do not.'),
        ),
        ask('geo-triple-check'),
        ask('geo-triple-check', 2),
        teach(
          prose('Any multiple of a triple is a triple too. Times $3,\\ 4,\\ 5$ by $10$ and you get $30,\\ 40,\\ 50$.'),
          diagram(rightTriSvg(20, 15, 0, { a: '20 cm', b: '15 cm', c: 'x' })),
          prose('Spot the multiple and skip the squaring. These sides are $5$ times $4$ and $3$:'),
          display('20 = 5 \\times 4 \\qquad 15 = 5 \\times 3'),
          display('x = 5 \\times 5 = 25'),
          prose('It works for a shorter side too. A hypotenuse of $26$ and a side of $10$ are $2$ times $13$ and $5$, so the other side is $2 \\times 12 = 24$.'),
        ),
        ask('geo-triple-scale'),
        ask('geo-triple-table'),
        ask('geo-triple-scale+choice', 2),
        teach(
          prose('In a table of multiples, divide a side you know by the triple to get the multiple, then times the missing one by it. A row of $3,\\ 4,\\ 5$ reading $?,\\ 28,\\ 35$:'),
          display('35 \\div 5 = 7'),
          display('3 \\times 7 = 21'),
          prose('Rows of $5,\\ 12,\\ 13$ or $8,\\ 15,\\ 17$ work the same way.'),
        ),
        ask('geo-triple-table', 2),
      ],
      skillCheck: [ask('geo-triple-check', 2), ask('geo-triple-scale', 2), ask('geo-triple-table', 2)],
    },
    {
      id: 'geo-l6-roots',
      title: 'Squares and Roots',
      slides: [
        teach(
          prose('To find a **shorter side**, start from the hypotenuse: its square minus the square of the side you know.'),
          diagram(rightTriSvg(5, 12, 0, { a: '5 cm', b: 'x', c: '13 cm' })),
          display('x^2 = 13^2 - 5^2 = 169 - 25 = 144'),
          display('x = \\sqrt{144} = 12'),
          prose('Take away for a shorter side, add for the hypotenuse. The answer must come out shorter than the hypotenuse.'),
        ),
        ask('geo-pyth-leg'),
        ask('geo-pyth-leg+choice', 2),
        teach(
          prose('The working can be laid out as a tree: the two squares on top, then the sum (or the difference), then the square root.'),
          display('\\sqrt{9^2 + 12^2}'),
          display('9^2 = 81 \\qquad 12^2 = 144'),
          display('81 + 144 = 225'),
          display('\\sqrt{225} = 15'),
          prose('For a shorter side, $\\sqrt{15^2 - 9^2}$ gives $225 - 81 = 144$, and $\\sqrt{144} = 12$.'),
        ),
        ask('geo-pyth-tree'),
        ask('geo-pyth-tree', 2),
        teach(
          prose('When the square is not a square number, leave the answer as a **square root**, typed with the $\\sqrt{\\ }$ key. Shorter sides of $2\\text{ cm}$ and $3\\text{ cm}$:'),
          diagram(rightTriSvg(3, 2, 1, { a: '3 cm', b: '2 cm', c: 'x' })),
          display('x^2 = 4 + 9 = 13'),
          display('x = \\sqrt{13}'),
          prose('A hypotenuse of $6\\text{ cm}$ and a side of $4\\text{ cm}$:'),
          display('x^2 = 36 - 16 = 20'),
          display('x = \\sqrt{20}'),
        ),
        ask('geo-pyth-surd'),
        ask('geo-pyth-surd+choice', 2),
      ],
      skillCheck: [ask('geo-pyth-leg', 2), ask('geo-pyth-tree', 2), ask('geo-pyth-surd', 2)],
    },
    {
      id: 'geo-l6-special',
      title: 'Special Right Triangles',
      slides: [
        teach(
          prose('Cut a square along its diagonal and you get **half a square**: two equal sides and two $45^\\circ$ angles.'),
          diagram(rightTriSvg(1, 1, 0, { a: '5 cm', c: 'x', angles: ['45°', '45°'], equal: true })),
          display('x^2 = 5^2 + 5^2 = 50'),
          display('x = \\sqrt{50} = 5\\sqrt{2}'),
          prose('So the hypotenuse is always a side times $\\sqrt{2}$. Backwards, a hypotenuse of $7\\sqrt{2}$ means a side of $7$.'),
          prose('A whole-number hypotenuse, such as $10$: the two equal squares share its square.'),
          display('x^2 + x^2 = 100 \\qquad x^2 = 50'),
          display('x = \\sqrt{50}'),
        ),
        ask('geo-special-45'),
        ask('geo-special-45+choice', 2),
        teach(
          prose('Cut an equilateral triangle in half and you get angles of $30^\\circ$, $60^\\circ$ and $90^\\circ$. The side opposite $30^\\circ$ is the shortest, and the hypotenuse is **twice** it.'),
          diagram(rightTriSvg(1, Math.sqrt(3), 0, { a: '4 cm', b: 'b', c: 'c', angles: ['60°', '30°'] })),
          display('c = 2 \\times 4 = 8'),
          display('b^2 = 8^2 - 4^2 = 48 \\qquad b = 4\\sqrt{3}'),
          prose('So the longer side is always the shortest side times $\\sqrt{3}$. Backwards, a hypotenuse of $10$ halves to a shortest side of $5$, and the longer side is $5\\sqrt{3}$.'),
        ),
        ask('geo-special-30'),
        ask('geo-special-tiles'),
        ask('geo-special-30+choice', 2),
        teach(
          prose('Given the longer side, the shortest side is the number in front of $\\sqrt{3}$. A longer side of $6\\sqrt{3}$:'),
          display('a = 6 \\qquad c = 2 \\times 6 = 12'),
        ),
        ask('geo-special-tiles', 2),
      ],
      skillCheck: [ask('geo-special-45', 2), ask('geo-special-30', 2), ask('geo-special-tiles', 2)],
    },
    {
      id: 'geo-l6-applications',
      title: 'Applications',
      slides: [
        teach(
          prose('A ladder against a wall makes a right-angled triangle with the ground, and the **ladder is the hypotenuse**.'),
          diagram(ladderSvg(5, 12, { foot: '5 m', height: 'x', ladder: '13 m' })),
          prose('How far up the wall does it reach? Take away, since $x$ is a shorter side:'),
          display('x^2 = 13^2 - 5^2 = 169 - 25 = 144'),
          display('x = \\sqrt{144} = 12'),
          prose('Given the foot and the height, add instead to find the ladder.'),
        ),
        ask('geo-ladder'),
        ask('geo-ladder+choice', 2),
        teach(
          prose('A **diagonal** cuts a rectangle into two right-angled triangles, and the diagonal is the hypotenuse of each.'),
          diagram(rectDiagSvg(8, 6, { bottom: '8 cm', right: '6 cm', diag: 'x' })),
          display('x^2 = 64 + 36 = 100'),
          display('x = \\sqrt{100} = 10'),
          prose('Given the diagonal and one side, take away for the other side.'),
        ),
        ask('geo-diagonal'),
        ask('geo-diagonal+choice', 2),
        teach(
          prose('The **distance between two points** is the hypotenuse of the triangle made by the steps across and up.'),
          diagram(pointsSvg([1, 2], [7, 10])),
          prose('From $A(1, 2)$ to $B(7, 10)$, subtract the coordinates:'),
          display('7 - 1 = 6 \\qquad 10 - 2 = 8'),
          display('AB^2 = 36 + 64 = 100'),
          display('AB = \\sqrt{100} = 10'),
          prose('With a negative coordinate, bracket it: $3 - (-2) = 5$. A negative step squares to a positive number, since $(-6)^2 = 36$.'),
        ),
        ask('geo-distance'),
        ask('geo-dist-tree'),
        ask('geo-distance+choice', 2),
      ],
      skillCheck: [ask('geo-ladder', 2), ask('geo-diagonal', 2), ask('geo-distance', 2)],
    },
  ],
  levelCheck: [
    ask('geo-pyth-which', 2),
    ask('geo-pyth-hyp', 2),
    ask('geo-pyth-tiles', 2),
    ask('geo-triple-check', 2),
    ask('geo-triple-scale', 2),
    ask('geo-pyth-leg', 2),
    ask('geo-pyth-surd', 2),
    ask('geo-special-45', 2),
    ask('geo-special-30', 2),
    ask('geo-ladder', 2),
    ask('geo-diagonal', 2),
    ask('geo-distance', 2),
  ],
};
