/**
 * Geometry, level 5: Areas.
 *
 * Area as squares counted, rectangles and shapes made of them, triangles,
 * parallelograms and trapezia from a perpendicular height, circles and their
 * parts in terms of $\pi$, and how area scales by the square of the length
 * factor. Generators and figures are in `generators/geometryAreas.ts`.
 */
import type { Level } from '../../types';
import { compoundSvg, gridSvg, quadHeightSvg, triHeightSvg } from '../../generators/geometryAreas';
import { circleSvg, partCircleSvg, rectSvg, sectorSvg } from '../../generators/geometryLengths';
import { ask, diagram, display, prose, teach } from './blocks';

export const areas: Level = {
  id: 'geo-l5',
  title: 'Areas',
  lessons: [
    {
      id: 'geo-l5-reasoning',
      title: 'Reasoning About Area',
      slides: [
        teach(
          prose('The **area** of a shape is how much flat space it covers, counted in squares. A square with $1\\text{ cm}$ sides has an area of $1\\text{ cm}^2$, one **square centimetre**.'),
          diagram(
            gridSvg({
              cells: [[2, 1], [3, 1], [4, 1], [2, 2], [3, 2], [4, 2], [5, 2]],
              halves: [{ x: 5, y: 1, edge: 'b', flip: false }, { x: 3, y: 3, edge: 't', flip: false }],
            }),
          ),
          prose('This shape has 7 whole squares and 2 half squares. Two halves make one whole:'),
          display('A = 7 + 1 = 8'),
          prose('So its area is $8\\text{ cm}^2$.'),
        ),
        ask('geo-area-count'),
        ask('geo-area-count+choice', 2),
        teach(
          prose('A rectangle is rows of squares: its **length** times its **width**.'),
          display('A = lw'),
          diagram(rectSvg(6, 4, '6 cm', '4 cm')),
          display('A = 6 \\times 4 = 24'),
          prose('Backwards: a rectangle with an area of $35\\text{ cm}^2$ and a length of $7\\text{ cm}$. Divide the area by the side you know:'),
          display('w = 35 \\div 7 = 5'),
        ),
        ask('geo-rect-area'),
        ask('geo-rect-area+choice', 2),
        teach(
          prose('An L-shape splits into two rectangles, $A$ and $B$. Find each area, then add them.'),
          diagram(compoundSvg(10, 8, 4, 5, { W: '10 cm', H: '8 cm', t: '6 cm', r: '3 cm' })),
          prose('The step across is the full width less the top:'),
          display('10 - 6 = 4'),
          prose('Rectangle $A$ is the full height and $B$ is the lower step:'),
          display('A: \\quad 6 \\times 8 = 48'),
          display('B: \\quad 4 \\times 3 = 12'),
          display('\\text{Total} = 48 + 12 = 60'),
        ),
        ask('geo-area-compound'),
        ask('geo-area-compound', 2),
      ],
      skillCheck: [ask('geo-area-count', 2), ask('geo-rect-area', 2), ask('geo-area-compound', 2)],
    },
    {
      id: 'geo-l5-polygons',
      title: 'Polygon Areas',
      slides: [
        teach(
          prose('A triangle is half of a rectangle, so its area is half the base times the **perpendicular height**: the dashed line meeting the base at a right angle.'),
          display('A = \\tfrac{1}{2}bh'),
          diagram(triHeightSvg({ b: 10, h: 6, p: 3 }, '10 cm', '6 cm')),
          display('A = \\tfrac{1}{2} \\times 10 \\times 6 = 30'),
          prose('When the top corner leans past the end of the base, the height falls outside the triangle. The base is still just the side it stands on.'),
          diagram(triHeightSvg({ b: 6, h: 8, p: 9 }, '6 cm', '8 cm')),
          display('A = \\tfrac{1}{2} \\times 6 \\times 8 = 24'),
        ),
        ask('geo-tri-area'),
        ask('geo-tri-area+choice', 2),
        teach(
          prose('A **parallelogram** is a rectangle with a slice moved from one end to the other, so its area is base times perpendicular height. The sloping side is not the height and is not used.'),
          display('A = bh'),
          diagram(quadHeightSvg({ b: 9, a: 9, h: 4, off: 3 }, { bottom: '9 cm', height: '4 cm', slant: '5 cm' })),
          display('A = 9 \\times 4 = 36'),
          prose('A **trapezium** has two parallel sides, $a$ and $b$. Add them, halve, and times by the height:'),
          display('A = \\tfrac{1}{2}(a + b)h'),
          diagram(quadHeightSvg({ b: 10, a: 6, h: 5, off: 2 }, { bottom: '10 cm', top: '6 cm', height: '5 cm' })),
          display('a + b = 6 + 10 = 16'),
          display('A = \\tfrac{1}{2} \\times 16 \\times 5 = 40'),
        ),
        ask('geo-para-area'),
        ask('geo-trap-area'),
        ask('geo-para-area+choice', 2),
        teach(
          prose('Backwards: a triangle with a base of $8\\text{ cm}$ and an area of $28\\text{ cm}^2$. Half the base times the height is the area, so the base times the height is twice the area:'),
          diagram(triHeightSvg({ b: 8, h: 7, p: 3 }, '8 cm', 'h')),
          display('8 \\times h = 2 \\times 28 = 56'),
          display('h = 56 \\div 8 = 7'),
        ),
        ask('geo-tri-height'),
        ask('geo-trap-area', 2),
        ask('geo-tri-height+choice', 2),
      ],
      skillCheck: [ask('geo-tri-area', 2), ask('geo-para-area', 2), ask('geo-trap-area', 2)],
    },
    {
      id: 'geo-l5-circles',
      title: 'Circle Areas',
      slides: [
        teach(
          prose('The area of a circle is $\\pi$ times the radius squared:'),
          display('A = \\pi r^2'),
          diagram(circleSvg('r', '5 cm')),
          display('A = \\pi \\times 5^2 = 25\\pi'),
          prose('Leave the answer in terms of $\\pi$. Given a diameter, halve it first. A diameter of $7\\text{ cm}$:'),
          display('r = 7 \\div 2 = 3.5'),
          display('A = \\pi \\times 3.5^2 = 12.25\\pi'),
        ),
        ask('geo-circle-area'),
        ask('geo-circle-area+choice', 2),
        teach(
          prose('Backwards: a circle with an area of $49\\pi\\text{ cm}^2$. The number in front of $\\pi$ is $r^2$, so take its square root:'),
          display('r^2 = 49'),
          display('r = \\sqrt{49} = 7'),
          prose('The diameter is then $2 \\times 7 = 14$.'),
          prose('A **semicircle** is half a circle, and a **quarter circle** a quarter. A quarter circle with a radius of $6\\text{ cm}$:'),
          diagram(partCircleSvg('quarter', '6 cm')),
          display('r^2 = 36'),
          display('A = 36\\pi \\div 4 = 9\\pi'),
        ),
        ask('geo-circle-back'),
        ask('geo-semi-area'),
        ask('geo-circle-back+choice', 2),
        teach(
          prose('A **sector** is the fraction $\\frac{\\theta}{360}$ of the circle, so its area is that fraction of $\\pi r^2$:'),
          display('A = \\frac{\\theta}{360} \\times \\pi r^2'),
          diagram(sectorSvg(120, { angle: '120°', radius: '6 cm' })),
          display('\\pi \\times 6^2 = 36\\pi'),
          display('A = \\frac{120}{360} \\times 36\\pi = 12\\pi'),
          prose('Every area formula so far:'),
          display('\\text{rectangle } A = lw \\qquad \\text{triangle } A = \\tfrac{1}{2}bh'),
          display('\\text{parallelogram } A = bh \\qquad \\text{trapezium } A = \\tfrac{1}{2}(a + b)h'),
          display('\\text{circle } A = \\pi r^2 \\qquad \\text{semicircle } A = \\tfrac{1}{2}\\pi r^2'),
        ),
        ask('geo-sector-area'),
        ask('geo-area-formula'),
        ask('geo-sector-area+choice', 2),
      ],
      skillCheck: [ask('geo-circle-area', 2), ask('geo-circle-back', 2), ask('geo-sector-area', 2)],
    },
    {
      id: 'geo-l5-scaling',
      title: 'Scaling Areas',
      slides: [
        teach(
          prose('Enlarge a $3\\text{ cm}$ by $2\\text{ cm}$ rectangle by a scale factor of $2$. Both sides double:'),
          diagram(rectSvg(6, 4, '6 cm', '4 cm')),
          display('3 \\times 2 = 6 \\qquad 2 \\times 2 = 4'),
          display('\\text{new area} = 6 \\times 4 = 24'),
          display('\\text{old area} = 3 \\times 2 = 6'),
          prose('The area went from $6$ to $24$, which is $4$ times as much. Area is length times length, so it grows by the **length factor squared**:'),
          display('\\text{area factor} = k^2 = 2^2 = 4'),
          prose('Backwards, the length factor is the square root of the area factor. An area factor of $9$:'),
          display('k = \\sqrt{9} = 3'),
        ),
        ask('geo-rect-enlarge'),
        ask('geo-area-factor'),
        ask('geo-rect-enlarge', 2),
        teach(
          prose('This works for any pair of similar shapes. A triangle of $5\\text{ cm}^2$ with sides $3$ times as long:'),
          display('3^2 = 9 \\qquad 5 \\times 9 = 45'),
          prose('Backwards, divide by the area factor. Sides $1.5$ times as long and a new area of $18\\text{ cm}^2$:'),
          display('1.5^2 = 2.25 \\qquad 18 \\div 2.25 = 8'),
          prose('A factor below $1$ shrinks the shape: $k = 0.5$ gives an area factor of $0.25$.'),
        ),
        ask('geo-area-scale'),
        ask('geo-area-factor+choice', 2),
        ask('geo-area-table'),
        teach(
          prose('From two areas, divide to get the area factor, then take the square root for the length factor. Areas of $12\\text{ cm}^2$ and $75\\text{ cm}^2$:'),
          display('75 \\div 12 = 6.25'),
          display('k = \\sqrt{6.25} = 2.5'),
          prose('So every side of the larger shape is $2.5$ times as long.'),
        ),
        ask('geo-area-scale+choice', 2),
        ask('geo-area-table', 2),
      ],
      skillCheck: [ask('geo-area-factor', 2), ask('geo-area-scale', 2), ask('geo-rect-enlarge', 2)],
    },
  ],
  levelCheck: [
    ask('geo-area-count', 2),
    ask('geo-rect-area', 2),
    ask('geo-area-compound', 2),
    ask('geo-tri-area', 2),
    ask('geo-para-area', 2),
    ask('geo-trap-area', 2),
    ask('geo-tri-height', 2),
    ask('geo-circle-area', 2),
    ask('geo-circle-back', 2),
    ask('geo-semi-area', 2),
    ask('geo-sector-area', 2),
    ask('geo-area-factor', 2),
    ask('geo-area-scale', 2),
  ],
};
