/**
 * Teaching figures that move.
 *
 * A `traversal` is a curve with a dot that travels along it, and it is a
 * *block*, not a slide. That distinction is the whole design: it can sit inside
 * a teaching slide beside prose, it asks nothing, it grades nothing, and the
 * reducer never hears about it. A moving figure that could also be wrong would
 * have to answer to the three invariants; one that only illustrates does not.
 *
 * The dot is moved by writing attributes on the live SVG rather than by React
 * state, for the same reason the tree slide measures its connectors from the
 * laid-out DOM: the geometry lives in the path, and `getPointAtLength` is the
 * only honest way to ask where a curve actually is. Re-rendering sixty times a
 * second to move one circle would also be a poor trade on a phone.
 */
import { useEffect, useRef, useState } from 'react';

export function Traversal({
  svg,
  pathId,
  durationMs,
}: {
  svg: string;
  pathId: string;
  durationMs: number;
}) {
  const wrapRef = useRef<HTMLDivElement>(null);
  const [runs, setRuns] = useState(0);

  useEffect(() => {
    const wrap = wrapRef.current;
    if (!wrap) return;

    const path = wrap.querySelector<SVGPathElement>(`#${CSS.escape(pathId)}`);
    const dot = wrap.querySelector<SVGCircleElement>('#traversal-dot');
    // A figure whose ids do not match degrades to the static frame the SVG
    // already draws. A teaching aid is not worth throwing for.
    if (!path || !dot) return;

    const drop = wrap.querySelector<SVGLineElement>('#traversal-drop');
    const total = path.getTotalLength();

    const place = (at: number) => {
      const point = path.getPointAtLength(at);
      dot.setAttribute('cx', String(point.x));
      dot.setAttribute('cy', String(point.y));
      if (drop) {
        drop.setAttribute('x1', String(point.x));
        drop.setAttribute('x2', String(point.x));
        drop.setAttribute('y1', String(point.y));
      }
    };

    // Reduced motion gets the end state, not a frozen start: the point of the
    // figure is where the curve ends up, and holding the dot at x = 0 would
    // show the one frame that carries no information.
    if (window.matchMedia('(prefers-reduced-motion: reduce)').matches) {
      place(total);
      return;
    }

    let frame = 0;
    const started = performance.now();
    const step = (now: number) => {
      const progress = Math.min((now - started) / durationMs, 1);
      place(total * progress);
      if (progress < 1) frame = requestAnimationFrame(step);
    };
    frame = requestAnimationFrame(step);
    return () => cancelAnimationFrame(frame);
  }, [pathId, durationMs, runs]);

  return (
    <div className="traversal" ref={wrapRef}>
      {/* Generated by our own content code, never user input. */}
      <div className="traversal-figure" dangerouslySetInnerHTML={{ __html: svg }} />
      <button type="button" className="text-button" onClick={() => setRuns((n) => n + 1)}>
        &#8635; Replay
      </button>
    </div>
  );
}
