/**
 * KaTeX rendering.
 *
 * KaTeX is bundled rather than loaded from a CDN, fonts included, because the
 * app has to render maths with no network at all.
 */
import { useMemo } from 'react';
import katex from 'katex';
import 'katex/dist/katex.min.css';
import type { Block } from '../content/types';
import { Traversal } from './figures';

function render(tex: string, displayMode: boolean, trust: boolean): string {
  try {
    return katex.renderToString(tex, {
      displayMode,
      throwOnError: false,
      strict: false,
      trust,
    });
  } catch {
    // Never let a malformed expression blank the screen mid-lesson.
    return tex;
  }
}

/**
 * `trust` enables the commands KaTeX withholds by default, of which this app
 * uses exactly one: \htmlClass, so the answer editor can hand a class to the
 * caret it draws inside the formula. It is opt-in per call rather than on
 * globally, and the only caller is the answer slot, whose content is built from
 * keypad presses — there is no free-text input anywhere in the app, so the set
 * of commands that can reach it is the set this code puts there.
 */
export function Tex({
  tex,
  display = false,
  trust = false,
}: {
  tex: string;
  display?: boolean;
  trust?: boolean;
}) {
  const html = useMemo(() => render(tex, display, trust), [tex, display, trust]);
  return <span dangerouslySetInnerHTML={{ __html: html }} />;
}

/**
 * Prose with inline maths delimited by $...$.
 *
 * Splitting on a capturing group keeps the delimiters in the array, so odd
 * indices are always the maths segments.
 */
export function Prose({ text }: { text: string }) {
  const parts = useMemo(() => text.split(/\$([^$]+)\$/g), [text]);
  return (
    <p className="prose">
      {parts.map((part, idx) =>
        idx % 2 === 1 ? <Tex key={idx} tex={part} /> : <span key={idx}>{part}</span>,
      )}
    </p>
  );
}

export function Blocks({ blocks }: { blocks: Block[] }) {
  return (
    <>
      {blocks.map((block, idx) => {
        if (block.kind === 'prose') return <Prose key={idx} text={block.text} />;
        if (block.kind === 'diagram') {
          // SVG is generated by our own plane.ts, never user input.
          return (
            <div
              key={idx}
              className="diagram"
              dangerouslySetInnerHTML={{ __html: block.svg }}
            />
          );
        }
        if (block.kind === 'traversal') {
          return (
            <Traversal
              key={idx}
              svg={block.svg}
              pathId={block.pathId}
              durationMs={block.durationMs}
            />
          );
        }
        return (
          <div key={idx} className="display-math">
            <Tex tex={block.tex} display />
          </div>
        );
      })}
    </>
  );
}
