/**
 * KaTeX rendering.
 *
 * KaTeX is bundled rather than loaded from a CDN, fonts included, because the
 * app has to render maths with no network at all.
 */
import { useMemo } from 'react';
import katex from 'katex';
import 'katex/dist/katex.min.css';
import type { Block } from '../content/types';
import { Traversal } from './figures';

function render(tex: string, displayMode: boolean, trust: boolean): string {
  try {
    return katex.renderToString(tex, {
      displayMode,
      throwOnError: false,
      strict: false,
      trust,
    });
  } catch {
    // Never let a malformed expression blank the screen mid-lesson.
    return tex;
  }
}

/**
 * `trust` enables the commands KaTeX withholds by default, of which this app
 * uses exactly one: \htmlClass, so the answer editor can hand a class to the
 * caret it draws inside the formula. It is opt-in per call rather than on
 * globally, and the only caller is the answer slot, whose content is built from
 * keypad presses — there is no free-text input anywhere in the app, so the set
 * of commands that can reach it is the set this code puts there.
 */
export function Tex({
  tex,
  display = false,
  trust = false,
}: {
  tex: string;
  display?: boolean;
  trust?: boolean;
}) {
  const html = useMemo(() => render(tex, display, trust), [tex, display, trust]);
  return <span dangerouslySetInnerHTML={{ __html: html }} />;
}

/**
 * Prose with inline maths delimited by $...$.
 *
 * Splitting on a capturing group keeps the delimiters in the array, so odd
 * indices are always the maths segments.
 */
/**
 * One paragraph of teaching text.
 *
 * Three inline markups are understood: `$maths$`, `**bold**` and `*italic*`.
 * All three were written into the content from the start; only the maths was
 * ever rendered, because this split on the dollar signs alone. A slide
 * introducing a term showed the learner `**parabola**`, and one stressing a
 * word showed `*periodic*` — 34 bold spans and dozens of italic ones reading
 * as stray punctuation.
 *
 * One alternation, bold before italic so `**` is claimed by the bold branch
 * rather than being read as an empty italic followed by a stray asterisk.
 */
/**
 * The markup, without a paragraph around it.
 *
 * Split out because a decision tree's branch labels carry maths too, and they
 * live inside buttons — where a `<p>` is not valid content. Anything that needs
 * the inline markup in a non-paragraph context uses this.
 */
export function Inline({ text }: { text: string }) {
  const parts = useMemo(() => text.split(/(\$[^$]+\$|\*\*[^*]+\*\*|\*[^*]+\*)/g), [text]);
  return (
    <>
      {parts.map((part, idx) => {
        if (part.startsWith('$') && part.endsWith('$')) {
          return <Tex key={idx} tex={part.slice(1, -1)} />;
        }
        if (part.startsWith('**') && part.endsWith('**')) {
          return <strong key={idx}>{part.slice(2, -2)}</strong>;
        }
        if (part.startsWith('*') && part.endsWith('*')) {
          return <em key={idx}>{part.slice(1, -1)}</em>;
        }
        return <span key={idx}>{part}</span>;
      })}
    </>
  );
}

export function Prose({ text }: { text: string }) {
  return (
    <p className="prose">
      <Inline text={text} />
    </p>
  );
}

export function Blocks({ blocks }: { blocks: Block[] }) {
  return (
    <>
      {blocks.map((block, idx) => {
        if (block.kind === 'prose') return <Prose key={idx} text={block.text} />;
        if (block.kind === 'diagram') {
          // SVG is generated by our own plane.ts, never user input.
          return (
            <div
              key={idx}
              className="diagram"
              dangerouslySetInnerHTML={{ __html: block.svg }}
            />
          );
        }
        if (block.kind === 'traversal') {
          return (
            <Traversal
              key={idx}
              svg={block.svg}
              pathId={block.pathId}
              durationMs={block.durationMs}
            />
          );
        }
        return (
          <div key={idx} className="display-math">
            <Tex tex={block.tex} display />
          </div>
        );
      })}
    </>
  );
}
