/**
 * Sequences & Series, level 8: Harder Sums of Powers.
 *
 * Shown in Series & Induction straight after Sums of Powers, before the
 * method of differences and before induction, so it uses nothing but the
 * three standard results, restated where each lesson first needs them.
 */
import type { Level } from '../../types';
import { ask, maths, prose, teach } from './blocks';

export const harderSums: Level = {
  id: 'sq-l8',
  title: 'Harder Sums of Powers',
  lessons: [
    {
      id: 'sq-l8-products',
      title: 'Products of Consecutive Numbers',
      slides: [
        teach(
          prose('The three standard results from Sums of Powers:'),
          maths(
            '\\begin{aligned} \\sum_{r=1}^{n} r &= \\frac{1}{2}n(n + 1) \\\\ \\sum_{r=1}^{n} r^2 &= \\frac{1}{6}n(n + 1)(2n + 1) \\\\ \\sum_{r=1}^{n} r^3 &= \\frac{1}{4}n^2(n + 1)^2 \\end{aligned}',
          ),
          prose('For a product such as $(r + 1)(r + 2)$, multiply out first and then split the sum. The constant is added once for each of the $n$ terms:'),
          maths('\\begin{gathered} \\sum_{r=1}^{n} (r + 1)(r + 2) \\\\ = \\sum r^2 + 3\\sum r + 2n \\end{gathered}'),
          prose('At $n = 6$:'),
          maths('91 + 3 \\times 21 + 2 \\times 6 = 166'),
          prose('Check: $6 + 12 + 20 + 30 + 42 + 56 = 166$.'),
        ),
        ask('seq-l8-expand-tree'),
        ask('seq-l8-product-sum'),
        ask('seq-l8-product-table'),
        teach(
          prose('Three brackets work the same way. Multiply two of them, then the third:'),
          maths('\\begin{aligned} &r(r + 1)(r + 2) \\\\ &= r(r^2 + 3r + 2) \\\\ &= r^3 + 3r^2 + 2r \\end{aligned}'),
          prose('Now $\\sum r^3$ comes in. Up to $5$, $\\sum r^3 = 225$, $\\sum r^2 = 55$ and $\\sum r = 15$:'),
          maths('225 + 3 \\times 55 + 2 \\times 15 = 420'),
          prose('Check: $6 + 24 + 60 + 120 + 210 = 420$.'),
        ),
        ask('seq-l8-expand-tiles'),
        ask('seq-l8-product-sum+choice', 2),
        teach(
          prose('With no plain $r$ among the brackets, a constant appears again:'),
          maths('\\begin{aligned} &(r + 1)(r + 2)(r + 3) \\\\ &= r^3 + 6r^2 + 11r + 6 \\end{aligned}'),
          prose('so the sum up to $n$ is'),
          maths('\\sum r^3 + 6\\sum r^2 + 11\\sum r + 6n'),
        ),
        ask('seq-l8-expand-tiles', 2),
        ask('seq-l8-expand-tree', 2),
      ],
      skillCheck: [ask('seq-l8-product-sum', 2), ask('seq-l8-expand-tree', 2), ask('seq-l8-expand-tiles', 2)],
    },
    {
      id: 'sq-l8-factorised',
      title: 'Answers in Factorised Form',
      slides: [
        teach(
          prose('A sum written as one expression in $n$ is usually wanted factorised. The results for $\\sum r^2$ and $\\sum r$ both carry $n(n + 1)$, so write both over $6$:'),
          maths('\\begin{aligned} \\sum r^2 &= \\frac{1}{6}n(n + 1)(2n + 1) \\\\ \\sum r &= \\frac{1}{6}n(n + 1) \\times 3 \\end{aligned}'),
          prose('Then take $\\frac{1}{6}n(n + 1)$ out of $\\sum r(r + 1) = \\sum r^2 + \\sum r$:'),
          maths('\\begin{aligned} &\\frac{1}{6}n(n + 1)\\big((2n + 1) + 3\\big) \\\\ &= \\frac{1}{6}n(n + 1)(2n + 4) \\\\ &= \\frac{1}{3}n(n + 1)(n + 2) \\end{aligned}'),
          prose('The last line takes $2$ out of the bracket, which turns sixths into thirds.'),
        ),
        ask('seq-l8-factor-const'),
        ask('seq-l8-factor-tiles'),
        ask('seq-l8-factor-order'),
        teach(
          prose('With $\\sum r^3$ in the sum, write everything over $4$:'),
          maths('\\begin{aligned} \\sum r^3 &= \\frac{1}{4}n(n + 1) \\\\ &\\quad \\times n(n + 1) \\\\ \\sum r &= \\frac{1}{4}n(n + 1) \\times 2 \\end{aligned}'),
          prose('Taking out $\\frac{1}{4}n(n + 1)$:'),
          maths('\\begin{aligned} &\\sum_{r=1}^{n} (r^3 + 3r) \\\\ &= \\frac{1}{4}n(n + 1)\\big(n(n + 1) + 6\\big) \\\\ &= \\frac{1}{4}n(n + 1)(n^2 + n + 6) \\end{aligned}'),
          prose('Once it is factorised, a value is quick. At $n = 10$ the last bracket is $116$, so the sum is'),
          maths('\\frac{1}{4} \\times 10 \\times 11 \\times 116 = 3190'),
        ),
        teach(
          prose('With $2r^3$ in place of $r^3$, write everything over $2$ instead:'),
          maths('\\begin{aligned} 2\\sum r^3 &= \\frac{1}{2}n(n + 1) \\\\ &\\quad \\times n(n + 1) \\\\ \\sum r &= \\frac{1}{2}n(n + 1) \\times 1 \\end{aligned}'),
          prose('Taking out $\\frac{1}{2}n(n + 1)$, a $3$ goes into the bracket as it is, where beside $r^3$ it doubled to $6$:'),
          maths('\\begin{aligned} &\\sum_{r=1}^{n} (2r^3 + 3r) \\\\ &= \\frac{1}{2}n(n + 1)\\big(n(n + 1) + 3\\big) \\\\ &= \\frac{1}{2}n(n + 1)(n^2 + n + 3) \\end{aligned}'),
          prose('Check at $n = 2$: the terms $5$ and $22$ make $27$, and so does $\\frac{1}{2} \\times 2 \\times 3 \\times 9$.'),
        ),
        ask('seq-l8-factor-const', 2),
        ask('seq-l8-factor-eval-tree'),
        teach(
          prose('When $\\sum r^3$ and $\\sum r^2$ are both in the sum, write everything over $12$, so that each result carries $\\frac{1}{12}n(n + 1)$:'),
          maths('\\begin{aligned} \\sum r^3 &= \\frac{1}{12}n(n + 1) \\\\ &\\quad \\times 3n(n + 1) \\\\ \\sum r^2 &= \\frac{1}{12}n(n + 1) \\\\ &\\quad \\times 2(2n + 1) \\\\ \\sum r &= \\frac{1}{12}n(n + 1) \\times 6 \\end{aligned}'),
          prose('For $\\sum (r^3 + r^2)$ the bracket is'),
          maths('\\begin{aligned} &3n(n + 1) + 2(2n + 1) \\\\ &= 3n^2 + 7n + 2 \\end{aligned}'),
          prose('so'),
          maths('\\sum_{r=1}^{n} (r^3 + r^2) = \\frac{1}{12}n(n + 1)(3n^2 + 7n + 2)'),
          prose('If every number in the bracket shares a factor, take it out, as sixths became thirds above.'),
        ),
        ask('seq-l8-factor-tiles', 2),
        ask('seq-l8-factor-order', 2),
      ],
      skillCheck: [ask('seq-l8-factor-tiles', 2), ask('seq-l8-factor-const', 2), ask('seq-l8-factor-eval-tree', 2)],
    },
    {
      id: 'sq-l8-odd-even',
      title: 'Odd and Even Terms',
      slides: [
        teach(
          prose('The even squares are $2^2 + 4^2 + \\dots + (2n)^2$. Each term is $(2r)^2 = 4r^2$, so the sum is $4$ times the standard result, $\\sum r^2 = \\frac{1}{6}n(n + 1)(2n + 1)$:'),
          maths('\\sum_{r=1}^{n} (2r)^2 = 4\\sum_{r=1}^{n} r^2'),
          prose('The odd squares are what is left of all the squares up to $(2n)^2$ once the even ones are taken away:'),
          maths('\\sum_{r=1}^{n} (2r - 1)^2 = \\sum_{r=1}^{2n} r^2 - 4\\sum_{r=1}^{n} r^2'),
          prose('For $1^2 + 3^2 + \\dots + 9^2$ there are $5$ terms, so $n = 5$ and all the squares run up to $10^2$:'),
          maths('385 - 4 \\times 55 = 165'),
        ),
        ask('seq-l8-odd-tiles'),
        ask('seq-l8-split-odd-tree'),
        ask('seq-l8-parity-sum'),
        teach(
          prose('Cubes work the same way with $(2r)^3 = 8r^3$, using $\\sum r^3 = \\frac{1}{4}n^2(n + 1)^2$:'),
          maths('\\sum_{r=1}^{n} (2r - 1)^3 = \\sum_{r=1}^{2n} r^3 - 8\\sum_{r=1}^{n} r^3'),
          prose('For $1^3 + 3^3 + 5^3$, $n = 3$:'),
          maths('441 - 8 \\times 36 = 153'),
          prose('Check: $1 + 27 + 125 = 153$.'),
        ),
        ask('seq-l8-split-odd-tree', 2),
        ask('seq-l8-parity-sum+choice', 2),
        teach(
          prose('A running total of the odd squares grows by the next odd square each time:'),
          maths('\\begin{aligned} T_5 &= 165 \\\\ T_6 &= 165 + 11^2 = 286 \\end{aligned}'),
          prose('To start a table part way along, work the first total out as all the squares less the even ones.'),
        ),
        ask('seq-l8-odd-table', 2),
        ask('seq-l8-odd-tiles', 2),
      ],
      skillCheck: [ask('seq-l8-parity-sum', 2), ask('seq-l8-split-odd-tree', 2), ask('seq-l8-odd-tiles', 2)],
    },
    {
      id: 'sq-l8-solve-n',
      title: 'Solving for n',
      slides: [
        teach(
          prose('Given a total, work back to $n$. If $\\sum_{r=1}^{n} r = 210$, then with $\\sum r = \\frac{1}{2}n(n + 1)$:'),
          maths('\\begin{aligned} \\tfrac{1}{2}n(n + 1) &= 210 \\\\ n(n + 1) &= 420 \\end{aligned}'),
          prose('Look for two numbers in a row that multiply to $420$. $\\sqrt{420} \\approx 20.5$, so try $20$ and $21$:'),
          maths('20 \\times 21 = 420'),
          prose('So $n = 20$.'),
        ),
        teach(
          prose('Two totals have a shortcut. The first $n$ odd numbers add up to $n^2$, so if they add up to $144$, then $n = \\sqrt{144} = 12$.'),
          prose('And $\\sum r^3$ is the square of $\\sum r$:'),
          maths('\\frac{1}{4}n^2(n + 1)^2 = \\left(\\frac{1}{2}n(n + 1)\\right)^2'),
          prose('So if the cubes up to $n^3$ add up to $3025$, take the square root first:'),
          maths('\\begin{aligned} \\tfrac{1}{2}n(n + 1) &= \\sqrt{3025} = 55 \\\\ n(n + 1) &= 110 \\end{aligned}'),
          prose('Two numbers in a row: $10$ and $11$, so $n = 10$.'),
        ),
        ask('seq-l8-solve-n'),
        ask('seq-l8-solve-flow'),
        ask('seq-l8-solve-n+choice', 2),
        teach(
          prose('An equation between two sums: solve $\\sum r^2 = 7\\sum r$. Put in the standard results:'),
          maths('\\frac{1}{6}n(n + 1)(2n + 1) = 7 \\times \\frac{1}{2}n(n + 1)'),
          prose('Divide both sides by $\\frac{1}{2}n(n + 1)$, which is not zero for $n \\ge 1$. Since $\\frac{1}{6} \\div \\frac{1}{2} = \\frac{1}{3}$:'),
          maths('\\begin{aligned} \\tfrac{1}{3}(2n + 1) &= 7 \\\\ 2n + 1 &= 21 \\\\ n &= 10 \\end{aligned}'),
        ),
        ask('seq-l8-ratio-n'),
        ask('seq-l8-ratio-order'),
        teach(
          prose('The same division works for other pairs. For $\\sum r^3 = 36\\sum r$, dividing $\\frac{1}{4}n^2(n + 1)^2$ by $\\frac{1}{2}n(n + 1)$ leaves $\\frac{1}{2}n(n + 1)$:'),
          maths('\\begin{aligned} \\tfrac{1}{2}n(n + 1) &= 36 \\\\ n(n + 1) &= 72 \\end{aligned}'),
          prose('so $n = 8$. From Answers in Factorised Form, $\\sum r(r + 1)$ is $\\frac{1}{3}n(n + 1)(n + 2)$, and the same division leaves $\\frac{2}{3}(n + 2)$.'),
        ),
        ask('seq-l8-ratio-n', 2),
        ask('seq-l8-solve-flow', 2),
      ],
      skillCheck: [ask('seq-l8-solve-n', 2), ask('seq-l8-ratio-n', 2), ask('seq-l8-solve-flow', 2)],
    },
    {
      id: 'sq-l8-alternating',
      title: 'Alternating Sums',
      slides: [
        teach(
          prose('In $1^2 - 2^2 + 3^2 - 4^2 + \\dots - (2n)^2$ the signs take turns. Pair the terms from the start: pair $k$ is'),
          maths('\\begin{aligned} &(2k - 1)^2 - (2k)^2 \\\\ &= -(4k - 1) \\end{aligned}'),
          prose('There are $n$ pairs. Adding them uses $\\sum k = \\frac{1}{2}n(n + 1)$:'),
          maths('\\begin{aligned} &-\\left(4\\sum_{k=1}^{n} k - n\\right) \\\\ &= -\\big(2n(n + 1) - n\\big) \\\\ &= -n(2n + 1) \\end{aligned}'),
          prose('For $n = 3$ that gives $-3 \\times 7$, which is $-21$, and adding term by term agrees:'),
          maths('1 - 4 + 9 - 16 + 25 - 36 = -21'),
        ),
        ask('seq-l8-alt-pair-table'),
        ask('seq-l8-alt-tree'),
        ask('seq-l8-alt-sum'),
        teach(
          prose('With an odd number of terms, the last one has no partner. Pair the rest, then add it back. For $1^2 - 2^2 + \\dots + 9^2$ there are $9$ terms, so $4$ pairs and $9^2$ left over:'),
          maths('-4 \\times 9 + 81 = 45'),
          prose('Check: $1 - 4 + 9 - 16 + 25 - 36 + 49 - 64 + 81 = 45$.'),
        ),
        ask('seq-l8-alt-flow'),
        ask('seq-l8-alt-tree', 2),
        teach(
          prose('In sigma form the sign is a power of $-1$: $(-1)^r$ is $-1$ when $r$ is odd, so the first term is taken away, and every sign is the other way round:'),
          maths('\\sum_{r=1}^{2n} (-1)^r r^2 = n(2n + 1)'),
          prose('With plain numbers each pair is $-1 + 2$, which is $1$, so'),
          maths('\\sum_{r=1}^{10} (-1)^r r = 5'),
          prose('With $(-1)^{r + 1}$ the first term is added, as in the sums above.'),
        ),
        ask('seq-l8-alt-sum', 2),
        ask('seq-l8-alt-flow', 2),
      ],
      skillCheck: [ask('seq-l8-alt-sum', 2), ask('seq-l8-alt-tree', 2), ask('seq-l8-alt-flow', 2)],
    },
  ],
  levelCheck: [
    ask('seq-l8-product-sum', 2),
    ask('seq-l8-expand-tiles', 2),
    ask('seq-l8-expand-tree', 2),
    ask('seq-l8-product-table', 2),
    ask('seq-l8-factor-tiles', 2),
    ask('seq-l8-factor-const', 2),
    ask('seq-l8-factor-eval-tree', 2),
    ask('seq-l8-parity-sum', 2),
    ask('seq-l8-split-odd-tree', 2),
    ask('seq-l8-odd-tiles', 2),
    ask('seq-l8-solve-n', 2),
    ask('seq-l8-ratio-n', 2),
    ask('seq-l8-alt-sum', 2),
    ask('seq-l8-alt-tree', 2),
  ],
};
