/**
 * Sequences & Series, level 9: Strong Induction and Recurrences.
 *
 * Shown last in Series & Induction, after Proof by Induction for Series,
 * which proved sums and the closed form of u_{n+1} = pu_n + q by ordinary
 * induction. This level takes rules that look two terms back: running them,
 * solving them through the characteristic equation, proving the closed form
 * by strong induction, Fibonacci facts, and strong induction on amounts made
 * from two stamps. The generators are in `generators/sequencesStrongInduction.ts`.
 */
import type { Level } from '../../types';
import { ask, askAfter, maths, prose, teach } from './blocks';

export const strongInduction: Level = {
  id: 'sq-l9',
  title: 'Strong Induction and Recurrences',
  lessons: [
    {
      id: 'sq-l9-two-back',
      title: 'Rules that Look Two Back',
      slides: [
        teach(
          prose('A rule can look two terms back. The Fibonacci numbers add the two before, $F_{n+2} = F_{n+1} + F_n$, from $F_1 = F_2 = 1$: that gives $1, 1, 2, 3, 5, 8, 13, \\dots$'),
          prose('Another: $u_{n+2} = 2u_{n+1} + 3u_n$ with $u_1 = 1$ and $u_2 = 2$. Each term is twice the one before plus three times the one before that:'),
          maths('\\begin{aligned} u_3 &= 2 \\times 2 + 3 \\times 1 = 7 \\\\ u_4 &= 2 \\times 7 + 3 \\times 2 = 20 \\\\ u_5 &= 2 \\times 20 + 3 \\times 7 = 61 \\end{aligned}'),
          prose('One starting term is not enough: $u_3$ needs both $u_2$ and $u_1$. A rule needs as many starting terms as it reaches back: the highest index in it less the lowest.'),
        ),
        ask('seq-l9-run-table'),
        ask('seq-l9-next-term'),
        ask('seq-l9-starts'),
        teach(
          prose('Four terms are enough to find the rule. The terms $2, 3, 8, 19$ follow $u_{n+2} = au_{n+1} + bu_n$. Put $n = 1$ and $n = 2$ in:'),
          maths('\\begin{aligned} 8 &= 3a + 2b \\\\ 19 &= 8a + 3b \\end{aligned}'),
          prose('Multiply the first by $3$ and the second by $2$, so both have $6b$, and take the first from the second:'),
          maths('\\begin{aligned} 24 &= 9a + 6b \\\\ 38 &= 16a + 6b \\\\ 14 &= 7a \\end{aligned}'),
          prose('So $a = 2$. Put it in the first equation for $b$, then run the rule once more:'),
          maths('\\begin{aligned} 8 &= 6 + 2b \\\\ b &= 1 \\\\ u_5 &= 2 \\times 19 + 8 = 46 \\end{aligned}'),
        ),
        ask('seq-l9-find-ab'),
        ask('seq-l9-run-table', 2),
        askAfter(
          'seq-l9-next-term',
          2,
          prose('A rule runs backwards too. With $u_{n+2} = 2u_{n+1} + 3u_n$, $u_4 = 20$ and $u_5 = 61$, the rule at $n = 3$ gives $u_3$:'),
          maths('\\begin{aligned} 61 &= 2 \\times 20 + 3u_3 \\\\ 21 &= 3u_3 \\\\ u_3 &= 7 \\end{aligned}'),
        ),
        teach(
          prose('Count how far back a rule reaches even when a term is missing from it. $u_{n+2} = 3u_n + 1$ has no $u_{n+1}$, yet it still jumps two: $u_1$ fixes $u_3, u_5, \\dots$ and $u_2$ fixes $u_4, u_6, \\dots$ So it needs two starting terms.'),
          prose('And a rule that reaches three back needs three starting terms, $u_1$, $u_2$ and $u_3$:'),
          maths('u_{n+3} = u_{n+1} + 2u_n'),
        ),
        ask('seq-l9-starts', 2),
        ask('seq-l9-find-ab', 2),
      ],
      skillCheck: [ask('seq-l9-run-table', 2), ask('seq-l9-find-ab', 2), ask('seq-l9-next-term+choice', 2)],
    },
    {
      id: 'sq-l9-closed',
      title: 'Closed Forms from the Characteristic Equation',
      slides: [
        teach(
          prose('To find a formula for $u_{n+2} = 5u_{n+1} - 6u_n$, try $u_n = x^n$ and divide through by $x^n$:'),
          maths('\\begin{aligned} x^{n+2} &= 5x^{n+1} - 6x^n \\\\ x^2 &= 5x - 6 \\end{aligned}'),
          prose('This is the **characteristic equation**. It factorises as $(x - 2)(x - 3) = 0$, so both $2^n$ and $3^n$ fit the rule, and so does $u_n = A \\times 2^n + B \\times 3^n$ for any $A$ and $B$.'),
          prose('In general, a rule and its characteristic equation are'),
          maths('u_{n+2} = au_{n+1} + bu_n \\qquad x^2 = ax + b'),
          prose('and with roots $p$ and $q$ the terms are'),
          maths('u_n = Ap^n + Bq^n'),
        ),
        ask('seq-l9-char-tiles'),
        askAfter(
          'seq-l9-closed-check',
          1,
          prose('Test a formula against the rule. $u_n = 2^n + 3^n$ gives $u_1 = 5$ and $u_2 = 13$, and then the rule gives'),
          maths('u_3 = 5 \\times 13 - 6 \\times 5 = 35'),
          prose('while the formula gives $2^3 + 3^3 = 35$ as well.'),
        ),
        askAfter(
          'seq-l9-closed-term',
          1,
          prose('The formula goes straight to a far term, with no need to run the rule four more times:'),
          maths('u_6 = 2^6 + 3^6 = 64 + 729 = 793'),
        ),
        teach(
          prose('$A$ and $B$ come from the starting terms. For $u_n = A \\times 2^n + B \\times 3^n$ with $u_0 = 3$ and $u_1 = 7$, put $n = 0$ and $n = 1$ in:'),
          maths('\\begin{aligned} A + B &= 3 \\\\ 2A + 3B &= 7 \\end{aligned}'),
          prose('Multiply the first by $3$ and take it from the second, so $B$ goes:'),
          maths('\\begin{aligned} 3A + 3B &= 9 \\\\ -A &= -2 \\\\ A &= 2 \\end{aligned}'),
          prose('Then $B = 3 - 2 = 1$, and $u_n = 2 \\times 2^n + 3^n$.'),
        ),
        ask('seq-l9-coeffs'),
        teach(
          prose('A root can be negative. The rule $u_{n+2} = u_{n+1} + 2u_n$ has characteristic equation'),
          maths('\\begin{aligned} x^2 &= x + 2 \\\\ (x - 2)(x + 1) &= 0 \\end{aligned}'),
          prose('So the roots are $2$ and $-1$, and'),
          maths('u_n = A \\times 2^n + B \\times (-1)^n'),
          prose('The $(-1)^n$ part flips sign every term.'),
          prose('Test every row you can: $u_n = 2^n + (-1)^n$ gives $1, 5, 7, 17$, and the rule agrees:'),
          maths('\\begin{aligned} u_3 &= 5 + 2 \\times 1 = 7 \\\\ u_4 &= 7 + 2 \\times 5 = 17 \\end{aligned}'),
          prose('A formula that fits $u_1$ alone can still be wrong at $u_2$.'),
        ),
        ask('seq-l9-char-tiles+choice', 2),
        askAfter(
          'seq-l9-coeffs',
          2,
          prose('From $u_1$ and $u_2$ it works the same way. With $u_n = A \\times 2^n + B \\times 3^n$, $u_1 = 7$ and $u_2 = 17$:'),
          maths('\\begin{aligned} 2A + 3B &= 7 \\\\ 4A + 9B &= 17 \\end{aligned}'),
          prose('Multiply the first by $3$ and take it from the second, so $B$ goes:'),
          maths('\\begin{aligned} 6A + 9B &= 21 \\\\ -2A &= -4 \\\\ A &= 2 \\end{aligned}'),
          prose('Then $B = 1$.'),
        ),
        ask('seq-l9-closed-check', 2),
        ask('seq-l9-closed-term', 2),
      ],
      skillCheck: [ask('seq-l9-char-tiles', 2), ask('seq-l9-coeffs', 2), ask('seq-l9-closed-term', 2)],
    },
    {
      id: 'sq-l9-strong',
      title: 'Strong Induction',
      slides: [
        teach(
          prose('A proof by induction has four parts: base case, assumption at $n = k$, step to $n = k + 1$, conclusion. A two-back rule changes two of them.'),
          prose('The step builds $u_{k+1}$ from $u_k$ and $u_{k-1}$, so it assumes the claim at both $n = k - 1$ and $n = k$. This is **strong induction**: the assumption may cover every case up to $k$.'),
          prose('And the step reaches back two, so it needs **two base cases**: $n = 1$ and $n = 2$, or $n = 0$ and $n = 1$ if the sequence starts at $u_0$. Then $3$ follows from $1$ and $2$, $4$ from $2$ and $3$, and so on. A rule one back, as in Proof by Induction for Series, needs one.'),
        ),
        ask('seq-l9-base-flow'),
        askAfter(
          'seq-l9-step-check',
          1,
          prose('The step in numbers at $k = 3$, for this claim and rule:'),
          maths('u_n = 2^n + 3^n \\qquad u_{n+1} = 5u_n - 6u_{n-1}'),
          prose('The formula gives $u_2 = 13$ and $u_3 = 35$, and then the rule gives'),
          maths('u_4 = 5 \\times 35 - 6 \\times 13 = 97'),
          prose('which is $2^4 + 3^4$, the formula at $n = 4$.'),
        ),
        ask('seq-l9-missing-base'),
        teach(
          prose('At the step, write the rule one place down, so it makes $u_{k+1}$:'),
          maths('u_{k+1} = 5u_k - 6u_{k-1}'),
          prose('Put in the claim at $n = k$ and $n = k - 1$, and collect each power:'),
          maths('\\begin{aligned} u_{k+1} &= 5(2^k + 3^k) \\\\ &\\quad - 6(2^{k-1} + 3^{k-1}) \\\\ &= 2^{k-1}(5 \\times 2 - 6) \\\\ &\\quad + 3^{k-1}(5 \\times 3 - 6) \\\\ &= 4 \\times 2^{k-1} + 9 \\times 3^{k-1} \\\\ &= 2^{k+1} + 3^{k+1} \\end{aligned}'),
          prose('$4 = 2^2$ and $9 = 3^2$ because $2$ and $3$ solve $x^2 = 5x - 6$. That is why the step always comes back to the formula.'),
        ),
        ask('seq-l9-order-strong'),
        ask('seq-l9-step-check', 2),
        teach(
          prose('Why both base cases? Take the same rule and claim,'),
          maths('u_{n+1} = 5u_n - 6u_{n-1} \\qquad u_n = 2^n + 3^n'),
          prose('but start from $u_1 = 5$ and $u_2 = 14$. The claim holds at $n = 1$, and the step above still works. But $u_2 = 14$, not $13$: the claim is false, and checking $n = 1$ alone would have "proved" it.'),
          prose('A rule reaching three back needs three base cases, and its step assumes the claim at $n = k - 2$, $k - 1$ and $k$.'),
        ),
        ask('seq-l9-missing-base', 2),
        ask('seq-l9-base-flow', 2),
        ask('seq-l9-order-strong', 2),
      ],
      skillCheck: [ask('seq-l9-order-strong', 2), ask('seq-l9-missing-base', 2), ask('seq-l9-step-check', 2)],
    },
    {
      id: 'sq-l9-fibonacci',
      title: 'Fibonacci Facts',
      slides: [
        teach(
          prose('The Fibonacci numbers: $F_1 = F_2 = 1$ and $F_{n+2} = F_{n+1} + F_n$, giving $1, 1, 2, 3, 5, 8, 13, 21, 34, 55, \\dots$'),
          prose('Add them up as you go: $1, 2, 4, 7, 12, 20, 33, 54$. Each total is one less than the Fibonacci number two places on:'),
          maths('F_1 + F_2 + \\dots + F_n = F_{n+2} - 1'),
          prose('Ordinary induction proves it, since the step only uses the sum up to $k$. Adding the next term to $F_{k+2} - 1$:'),
          maths('(F_{k+2} - 1) + F_{k+1} = F_{k+3} - 1'),
        ),
        ask('seq-l9-fib-table'),
        ask('seq-l9-fib-sum'),
        askAfter(
          'seq-l9-fib-sum+choice',
          2,
          prose('A sum that starts later is the first $n$ terms less the first $m - 1$:'),
          maths('\\begin{aligned} F_m + \\dots + F_n &= (F_{n+2} - 1) \\\\ &\\quad - (F_{m+1} - 1) \\\\ &= F_{n+2} - F_{m+1} \\end{aligned}'),
          prose('So $F_4 + \\dots + F_8 = F_{10} - F_5 = 55 - 5 = 50$.'),
        ),
        teach(
          prose('Look at odd and even: $1, 1, 2, 3, 5, 8, 13, 21, 34$ runs odd, odd, even, odd, odd, even.'),
          prose('Odd plus odd is even, odd plus even is odd, even plus odd is odd, and then two odds come round again, so the pattern repeats for ever. $F_n$ is even exactly when $n$ is a multiple of $3$: $F_{30}$ is even, $F_{31}$ is odd.'),
        ),
        ask('seq-l9-fib-even'),
        ask('seq-l9-fib-table', 2),
        teach(
          prose('Strong induction proves $F_n < 2^n$. Base cases: $F_1 = 1 < 2$ and $F_2 = 1 < 4$. Assume it at $n = k - 1$ and $n = k$:'),
          maths('\\begin{aligned} F_{k+1} &= F_k + F_{k-1} \\\\ &< 2^k + 2^{k-1} \\\\ &= 2^{k-1}(2 + 1) \\\\ &= 3 \\times 2^{k-1} \\\\ &< 4 \\times 2^{k-1} = 2^{k+1} \\end{aligned}'),
          prose('The same works for any $u_{n+2} = au_{n+1} + bu_n$ with $a$ and $b$ positive and a bound $c^n$, as long as $ac + b \\le c^2$ and both base cases are under the bound.'),
        ),
        ask('seq-l9-order-bound'),
        ask('seq-l9-fib-even', 2),
        ask('seq-l9-order-bound', 2),
      ],
      skillCheck: [ask('seq-l9-fib-sum', 2), ask('seq-l9-fib-even', 2), ask('seq-l9-order-bound', 2)],
    },
    {
      id: 'sq-l9-stamps',
      title: 'Building Every Amount',
      slides: [
        teach(
          prose('With 3p and 5p stamps, which amounts can be made? $1$, $2$, $4$ and $7$ cannot; $3$, $5$ and $6$ can, and from $8$ on every amount can:'),
          maths('\\begin{aligned} 8 &= 3 + 5 \\\\ 9 &= 3 \\times 3 \\\\ 10 &= 2 \\times 5 \\end{aligned}'),
          prose('Three in a row, and a 3p stamp more on each makes the next three, $11$, $12$ and $13$, and so on for ever. So $7$ is the largest amount that cannot be made.'),
          prose('For two sizes $a$ and $b$ with no common factor, the largest is always $ab - a - b$: here $15 - 3 - 5 = 7$.'),
        ),
        ask('seq-l9-stamp-table'),
        ask('seq-l9-frobenius'),
        ask('seq-l9-frobenius+choice', 2),
        teach(
          prose('Strong induction proves the claim that every amount of at least 8p can be made. The step makes $k + 1$ by adding a 3p stamp to $k - 2$, so it assumes every amount from $8$ up to $k$ can be made.'),
          prose('The step reaches back $3$, so the first three amounts, $8$, $9$ and $10$, have nothing to step back to: they are the base cases, one for each penny of the stamp the step adds. Once $k \\ge 10$, $k - 2$ is at least $8$ and the assumption covers it.'),
          prose('Stepping back by the 5p stamp instead would need five base cases, $8$ to $12$.'),
        ),
        ask('seq-l9-base-count'),
        ask('seq-l9-order-stamps'),
        ask('seq-l9-stamp-table', 2),
        teach(
          prose('With 4p and 5p stamps the largest that cannot be made is $20 - 4 - 5 = 11$. Stepping back by 4p needs four base cases:'),
          maths('\\begin{aligned} 12 &= 3 \\times 4 \\\\ 13 &= 2 \\times 4 + 5 \\\\ 14 &= 4 + 2 \\times 5 \\\\ 15 &= 3 \\times 5 \\end{aligned}'),
          prose('Then every amount from $16$ on is one 4p stamp more than an amount already made.'),
        ),
        ask('seq-l9-base-count', 2),
        ask('seq-l9-order-stamps', 2),
      ],
      skillCheck: [ask('seq-l9-frobenius', 2), ask('seq-l9-base-count', 2), ask('seq-l9-order-stamps', 2)],
    },
  ],
  levelCheck: [
    ask('seq-l9-run-table', 2),
    ask('seq-l9-find-ab', 2),
    ask('seq-l9-char-tiles', 2),
    ask('seq-l9-coeffs', 2),
    ask('seq-l9-closed-term', 2),
    ask('seq-l9-step-check', 2),
    ask('seq-l9-missing-base', 2),
    ask('seq-l9-order-strong', 2),
    ask('seq-l9-fib-sum', 2),
    ask('seq-l9-fib-even', 2),
    ask('seq-l9-order-bound', 2),
    ask('seq-l9-frobenius', 2),
    ask('seq-l9-base-count', 2),
    ask('seq-l9-order-stamps', 2),
  ],
};
