/**
 * Content model.
 *
 * A course is levels of lessons; a lesson is roughly ten guided slides followed
 * by three skill-check questions. Guided slides alternate between teaching a
 * technique and practising it; the skill check is sealed, with no route back to
 * the worked examples.
 */
import type { Rng } from '../engine/rng';

/** A unit of rendered content. Prose may embed inline maths between $ signs. */
export type Block =
  | { kind: 'prose'; text: string }
  | { kind: 'display'; tex: string }
  /** Inline SVG, generated by our own code — never user input. */
  | { kind: 'diagram'; svg: string }
  /**
   * A curve with a dot that travels along it, replayable.
   *
   * Like `diagram`, the SVG is generated by our own code and never user input.
   * It must contain a `<path id="{pathId}">` for the dot to follow and a
   * `<circle id="traversal-dot">` sitting at the path's start, so that a
   * browser refusing to animate still shows a sensible still. An optional
   * `<line id="traversal-drop">` is tracked to the dot as a drop line.
   */
  | { kind: 'traversal'; svg: string; pathId: string; durationMs: number };

/** One line of a worked solution, shown only when the learner asks for it. */
export interface SolutionStep {
  /** Explanatory line; may contain $inline maths$. */
  text?: string;
  /** A centred equation for this step. */
  tex?: string;
}

/** A key on the contextual maths keypad. `i` appears only for complex topics. */
export interface KeypadKey {
  /** Text inserted into the answer. */
  insert: string;
  /** Label rendered on the key; defaults to `insert`. */
  label?: string;
  /** Rendered as TeX rather than plain text (used for `i`). */
  tex?: boolean;
}

interface Prompted {
  /** The question, shown above the answer area. */
  prompt: Block[];
}

export type Slide =
  /** Explains an idea. No answer required — the only control is Continue. */
  | ({ kind: 'teach'; body: Block[] })
  /** Tap one option from a small set. */
  | ({ kind: 'choice' } & Prompted & {
      options: { id: string; label: string; tex?: boolean }[];
      correctId: string;
    })
  /** Type an expression on the contextual keypad. Checked by equivalence. */
  | ({ kind: 'expression' } & Prompted & {
      /** Shown to the left of the input, e.g. "3i + 7i =". TeX. */
      lead?: string;
      keypad: KeypadKey[];
      /** The canonical answer; anything equivalent to it is accepted. */
      answer: string;
      /**
       * The function the question is about, in mathjs syntax, where the answer
       * is its derivative. Never displayed: it exists so a test can
       * differentiate it independently and confirm the generator's own answer
       * is genuinely correct, rather than merely self-consistent.
       */
      source?: string;
      /**
       * The dual of `source`, for integration: the function being integrated,
       * where the answer is one of its antiderivatives.
       *
       * Declaring the integrand rather than reusing `source` keeps the oracle
       * pointing the same way it always has — mathjs differentiates, we check —
       * which is the only direction a test can be independent in, since
       * symbolic integration is the thing we would be marking its own homework
       * with. With `limits` the answer is a number instead, and the oracle
       * becomes quadrature over that interval.
       */
      integrand?: string;
      /** Limits of a definite integral, as [lower, upper]. */
      limits?: [number, number];
      domain: 'real' | 'complex' | 'positive';
      mode: 'exact' | 'upToConstant';
    })
  /** Tap a lattice point on the complex plane. */
  | ({ kind: 'plot' } & Prompted & {
      /** Axes run from -range to +range in both directions. */
      range: number;
      /** The point that must be tapped. */
      answer: { re: number; im: number };
    })
  /**
   * Drag to a value, with the value read back live above the track.
   *
   * The answer is the number under the handle, so this asks "where is it?"
   * rather than "what is it?" — a question about a quantity the learner can
   * see moving, which is the one shape none of the other widgets offer.
   */
  | ({ kind: 'slider' } & Prompted & {
      min: number;
      max: number;
      /** The drag granularity. Also the default tolerance, halved. */
      step: number;
      answer: number;
      /** How far off the answer still counts. Defaults to half a step. */
      tolerance?: number;
      /**
       * TeX read above the track, with the literal `{v}` standing for the
       * current value — the same marker convention the tiles template uses
       * for its blanks.
       */
      readout: string;
      /**
       * A picture the handle moves a marker across.
       *
       * Without one a slider is only a different way to type a number. The
       * marker is drawn by the widget rather than baked into the SVG, so the
       * figure stays a static string: `xMin`/`xMax` say what horizontal span
       * the drawing covers, and the widget maps the current value onto it.
       * They need not match `min`/`max` — a graph usually shows more than the
       * answer can range over.
       */
      figure?: { svg: string; xMin: number; xMax: number };
    })
  /** Drop tokens from a bank into blanks in an equation. */
  | ({ kind: 'tiles' } & Prompted & {
      /**
       * TeX with {0}, {1}, … marking the blanks.
       *
       * The widget splits on those markers and renders each literal piece
       * between them as TeX on its own, which forbids two things. Braces round
       * a digit anywhere — `x^{2}` has its `{2}` taken for a blank marker, and
       * `\log_{10}` likewise — so write `x^2`, or keep the subscript to a
       * single character. And no `\left` or `\right` spanning a blank, since
       * each half is then unmatched; plain parentheses render the same and are
       * valid on their own. A test renders every fragment, so a mistake here
       * fails rather than reaching the learner as red error text.
       */
      template: string;
      /** Tokens offered, including distractors. */
      bank: string[];
      /** Expected token per blank. */
      answer: string[];
      /** When true the blanks may be filled in any order (e.g. "x = a or x = b"). */
      unordered?: boolean;
    })
  /**
   * Reduce an expression one operation at a time.
   *
   * The line is held as TeX fragments rather than one string because each
   * fragment is an independent tap target; KaTeX gives no handle on a
   * sub-expression once it has rendered a whole formula.
   *
   * Only the next reduction's span is offered, so the slide grades *evaluation*
   * rather than choice of order. Which operation comes first is a different
   * skill, and a `choice` slide asks it directly.
   */
  | ({ kind: 'steps' } & Prompted & {
      /** Tokens of the opening line, each rendered as its own TeX fragment. */
      start: string[];
      /** Reductions in the order they must be performed. */
      reductions: {
        /** Half-open range of the current line that this step collapses. */
        span: [number, number];
        /** What that span becomes. */
        value: string;
        /** Values offered for this step, including distractors. */
        bank: string[];
      }[];
    })
  /**
   * Fill the intermediate values of an evaluation tree.
   *
   * Nodes are listed in evaluation order and each names the nodes feeding it,
   * which is enough to lay out rows and draw the connectors without the content
   * author positioning anything by hand.
   */
  | ({ kind: 'tree' } & Prompted & {
      /** The expression the tree evaluates. TeX. */
      expression: string;
      /** In evaluation order. `from` holds ids of nodes feeding this one. */
      nodes: { id: string; from: string[] }[];
      /** Values offered, including distractors. */
      bank: string[];
      /** Expected value per node, in `nodes` order. */
      answer: string[];
    });

/**
 * Produces a slide from randomised parameters.
 *
 * `render` and `solution` both receive the same parameters, which is what lets
 * the opt-in worked solution use the learner's actual numbers rather than a
 * generic template.
 */
export interface Generator<P = unknown> {
  id: string;
  sample(rng: Rng, difficulty: number): P;
  render(params: P): Slide;
  solution(params: P): SolutionStep[];
  /**
   * The same question, asked as multiple choice.
   *
   * Optional, and where it exists the registry derives a second generator from
   * it automatically under the id `<id>+choice`, which a lesson references like
   * any other. That is what keeps a lesson from asking seven questions through
   * one widget: the same skill, a different shape, with no second generator to
   * write and keep in step.
   *
   * Return the correct option flagged and the rest as distractors. Order does
   * not matter — the wrapper rotates them by the question's own numbers, so the
   * answer is not always first yet one question still renders one way.
   *
   * Every label is TeX the learner reads, so it follows the same rule as the
   * rest of the displayed strings: written by hand, not derived from `answer`.
   * A test renders each one and checks every distractor is genuinely wrong.
   */
  choices?(params: P): ChoiceOption[];
}

/** One option of a generator's multiple-choice form. */
export interface ChoiceOption {
  /** What the learner reads. TeX. */
  tex: string;
  /** Exactly one option per question sets this. */
  correct?: boolean;
  /**
   * The same value in mathjs syntax, where the option is an expression.
   *
   * Only used by the test that proves a distractor is really wrong; it is never
   * displayed. Leave it off for an option that is not an expression at all — a
   * count, a yes/no, a coordinate pair — and the check is skipped.
   */
  answer?: string;
}

export type GeneratorRegistry = Record<string, Generator<never>>;

export type SlideRef =
  | { type: 'literal'; slide: Slide; solution?: SolutionStep[] }
  | {
      type: 'generated';
      generatorId: string;
      difficulty?: number;
      /**
       * Teaching prose shown above the generated question, on the same slide.
       *
       * A lesson reads as one thread rather than a teaching block followed by a
       * quiz block: "Let's think about what we just did in reverse" belongs with
       * the question it sets up, not on a slide of its own the learner has to
       * remember across a tap.
       *
       * It is a property of the *reference* rather than the generator because
       * the continuity belongs to the lesson: the same generator is set up
       * differently depending on what came before it.
       */
      leadIn?: Block[];
    };

export interface Lesson {
  id: string;
  title: string;
  /**
   * Assessment flow: one attempt per question, no worked solutions, scored as
   * a percentage.
   *
   * Set by `levelCheckLesson`. It is a property of the lesson rather than of
   * the phase because the seal has to hold from the very first question, and
   * the reducer is the only thing that reads it.
   */
  assessment?: boolean;
  /** Roughly ten slides: teach, practise x3, teach, practise x2-3. */
  slides: SlideRef[];
  /** Three sealed questions. Guided slides cannot be reviewed from here. */
  skillCheck: SlideRef[];
}

export interface Level {
  id: string;
  title: string;
  lessons: Lesson[];
  /**
   * The assessment closing the level: questions only, no teaching slides.
   *
   * It reuses `Lesson` rather than inventing a second shape — a level check is
   * a lesson whose guided deck is empty, which the session reducer already
   * treats as sealed from the first question.
   */
  levelCheck?: SlideRef[];
}

export interface Course {
  id: string;
  title: string;
  blurb: string;
  levels: Level[];
}

/**
 * A group of related courses, shown as one tab on the home screen.
 *
 * Categories carry the difficulty banding — Foundations through Advanced — so a
 * course does not have to name its own level, and a topic studied at both A
 * level and undergraduate simply has more levels rather than two entries.
 */
export interface Category {
  id: string;
  title: string;
  blurb: string;
  courses: Course[];
}

/**
 * The level check as a playable lesson.
 *
 * Returns undefined when the level has no check, so the caller can leave the
 * row out rather than offering an empty assessment.
 */
export function levelCheckLesson(level: Level): Lesson | undefined {
  if (!level.levelCheck || level.levelCheck.length === 0) return undefined;
  return {
    id: `${level.id}:check`,
    title: `${level.title} — Level Check`,
    assessment: true,
    slides: [],
    skillCheck: level.levelCheck,
  };
}
