/**
 * Content model.
 *
 * A course is levels of lessons; a lesson is roughly ten guided slides followed
 * by three skill-check questions. Guided slides alternate between teaching a
 * technique and practising it; the skill check is sealed, with no route back to
 * the worked examples.
 */
import type { Rng } from '../engine/rng';
import type { Precision } from '../engine/equivalence';
import type { Expr } from './expr';
import type { BaseCurve, Window } from './transform';
import type { ForceArrow, ForceScene } from './forces';

/** A unit of rendered content. Prose may embed inline maths between $ signs. */
export type Block =
  | { kind: 'prose'; text: string }
  | { kind: 'display'; tex: string }
  /** Inline SVG, generated by our own code — never user input. */
  | { kind: 'diagram'; svg: string }
  /**
   * A curve with a dot that travels along it, replayable.
   *
   * Like `diagram`, the SVG is generated by our own code and never user input.
   * It must contain a `<path id="{pathId}">` for the dot to follow and a
   * `<circle id="traversal-dot">` sitting at the path's start, so that a
   * browser refusing to animate still shows a sensible still. An optional
   * `<line id="traversal-drop">` is tracked to the dot as a drop line.
   */
  | { kind: 'traversal'; svg: string; pathId: string; durationMs: number };

/** One line of a worked solution, shown only when the learner asks for it. */
export interface SolutionStep {
  /** Explanatory line; may contain $inline maths$. */
  text?: string;
  /** A centred equation for this step. */
  tex?: string;
}

/** A key on the contextual maths keypad. `i` appears only for complex topics. */
export interface KeypadKey {
  /** Text inserted into the answer. */
  insert: string;
  /** Label rendered on the key; defaults to `insert`. */
  label?: string;
  /** Rendered as TeX rather than plain text (used for `i`). */
  tex?: boolean;
  /**
   * Makes this a function key: `insert` names the function (`sin`, `cos`,
   * `tan`, `asin`, `acos` or `atan`) and pressing it opens a template, so
   * what the learner types next lands inside the brackets. The value says
   * which unit the angle is in, which only the question knows.
   */
  fn?: 'degrees' | 'radians';
}

interface Prompted {
  /** The question, shown above the answer area. */
  prompt: Block[];
}

export type Slide =
  /** Explains an idea. No answer required — the only control is Continue. */
  | ({ kind: 'teach'; body: Block[] })
  /** Tap one option from a small set. */
  | ({ kind: 'choice' } & Prompted & {
      options: { id: string; label: string; tex?: boolean }[];
      correctId: string;
    })
  /** Type an expression on the contextual keypad. Checked by equivalence. */
  | ({ kind: 'expression' } & Prompted & {
      /** Shown to the left of the input, e.g. "3i + 7i =". TeX. */
      lead?: string;
      keypad: KeypadKey[];
      /**
       * Keys already pressed when the slide opens, such as `4 sin(` with the
       * caret inside the brackets, so the learner supplies only the angle or
       * the ratio. *Start over* returns to this rather than to an empty box.
       * Graded like anything else typed: by value, against `answer`.
       */
      prefill?: KeypadKey[];
      /** The canonical answer; anything equivalent to it is accepted. */
      answer: string;
      /**
       * The function the question is about, in mathjs syntax, where the answer
       * is its derivative. Never displayed: it exists so a test can
       * differentiate it independently and confirm the generator's own answer
       * is genuinely correct, rather than merely self-consistent.
       */
      source?: string;
      /**
       * The dual of `source`, for integration: the function being integrated,
       * where the answer is one of its antiderivatives.
       *
       * Declaring the integrand rather than reusing `source` keeps the oracle
       * pointing the same way it always has — mathjs differentiates, we check —
       * which is the only direction a test can be independent in, since
       * symbolic integration is the thing we would be marking its own homework
       * with. With `limits` the answer is a number instead, and the oracle
       * becomes quadrature over that interval.
       */
      integrand?: string;
      /** Limits of a definite integral, as [lower, upper]. */
      limits?: [number, number];
      /**
       * Other ways the learner is told they may write this answer, in mathjs
       * syntax — never displayed. A teach slide or solution step that says
       * "either form is accepted" is a promise about the checker that the
       * checker only keeps through fields like `domain`: `-a/(2*sqrt(x^3))`
       * agrees with `x^(-3/2)` for positive x and disagrees on the wider real
       * line, so the prose is only true because of a field sitting elsewhere
       * in the generator. A test grades each declared writing against
       * `answer` under this slide's own `domain` and `mode`, exactly as the
       * reducer grades a learner's typed answer — which is what makes
       * changing that field fail a test instead of a learner.
       */
      alsoAccepts?: string[];
      domain: 'real' | 'complex' | 'positive';
      mode: 'exact' | 'upToConstant';
      /**
       * The precision the prompt asks for ("to 2 decimal places"), when the
       * answer is a rounded number. `answer` is then that rounded value, and
       * anything rounding to it is accepted, the unrounded working included.
       */
      precision?: Precision;
    })
  /** Tap a lattice point on the complex plane. */
  | ({ kind: 'plot' } & Prompted & {
      /** Axes run from -range to +range in both directions. */
      range: number;
      /** The point that must be tapped. */
      answer: { re: number; im: number };
    })
  /**
   * Drag to a value, with the value read back live above the track.
   *
   * The answer is the number under the handle, so this asks "where is it?"
   * rather than "what is it?" — a question about a quantity the learner can
   * see moving, which is the one shape none of the other widgets offer.
   */
  | ({ kind: 'slider' } & Prompted & {
      min: number;
      max: number;
      /** The drag granularity. Also the default tolerance, halved. */
      step: number;
      answer: number;
      /** How far off the answer still counts. Defaults to half a step. */
      tolerance?: number;
      /**
       * TeX read above the track, with the literal `{v}` standing for the
       * current value — the same marker convention the tiles template uses
       * for its blanks.
       */
      readout: string;
      /**
       * A picture the handle moves a marker across.
       *
       * Without one a slider is only a different way to type a number. The
       * marker is drawn by the widget rather than baked into the SVG, so the
       * figure stays a static string: `xMin`/`xMax` say what horizontal span
       * the drawing covers, and the widget maps the current value onto it.
       * They need not match `min`/`max` — a graph usually shows more than the
       * answer can range over.
       */
      figure?: {
        svg: string;
        /** The span the drawing covers along the marker's axis. */
        xMin: number;
        xMax: number;
        /**
         * Which way the marker lies. `x` is a vertical line at a position along
         * the bottom; `y` is a horizontal line at a height.
         *
         * Both are needed because a slider's answer is not always a position. A
         * midline is a height, so a vertical marker would be the wrong axis
         * entirely; a period is a duration, so a marker at the value alone
         * points at nothing — it has to start from a peak.
         */
        axis?: 'x' | 'y';
        /**
         * Where the value is measured from, in the figure's own units.
         *
         * A period slid to 6 puts the marker 6 *after the first peak*, so the
         * learner drags until it lands on the next one. Without this the line
         * sits at 6 on the axis and means nothing.
         */
        origin?: number;
      };
    })
  /**
   * Draw a solution set on a number line.
   *
   * The learner builds the set from taps rather than typing it: a number
   * places or removes a dot, a dot toggles between filled (included) and
   * hollow (excluded), and a tap on the line shades or clears the stretch it
   * falls in, running off the edge as a ray beyond the outermost dot. So an
   * inequality's answer is shown the way it is drawn on paper, and open
   * against closed ends is a thing the learner has to decide, not read off.
   *
   * The model and the grade live in `src/content/numberLine.ts`.
   */
  | ({ kind: 'numberLine' } & Prompted & {
      /** The first and last tick. Both on the `step` lattice. */
      min: number;
      max: number;
      /** Tick spacing, 1 or 0.5. At most twelve steps fit a phone. */
      step: number;
      /**
       * The set, written the canonical way: pieces sorted and merged, joined
       * by `|`, as in `(-inf,2]|[5,inf)` or `[-1,3)`. Never displayed.
       */
      answer: string;
    })
  /** Drop tokens from a bank into blanks in an equation. */
  | ({ kind: 'tiles' } & Prompted & {
      /**
       * TeX with {0}, {1}, … marking the blanks.
       *
       * The widget splits on those markers and renders each literal piece
       * between them as TeX on its own, which forbids two things. Braces round
       * a digit anywhere — `x^{2}` has its `{2}` taken for a blank marker, and
       * `\log_{10}` likewise — so write `x^2`, or keep the subscript to a
       * single character. And no `\left` or `\right` spanning a blank, since
       * each half is then unmatched; plain parentheses render the same and are
       * valid on their own. A test renders every fragment, so a mistake here
       * fails rather than reaching the learner as red error text.
       */
      template: string;
      /** Tokens offered, including distractors. */
      bank: string[];
      /** Expected token per blank. */
      answer: string[];
      /** When true the blanks may be filled in any order (e.g. "x = a or x = b"). */
      unordered?: boolean;
    })
  /**
   * Reduce an expression one operation at a time.
   *
   * The line is held as TeX fragments rather than one string because each
   * fragment is an independent tap target; KaTeX gives no handle on a
   * sub-expression once it has rendered a whole formula.
   *
   * Only the next reduction's span is offered, so the slide grades *evaluation*
   * rather than choice of order. Which operation comes first is a different
   * skill, and a `choice` slide asks it directly.
   */
  | ({ kind: 'steps' } & Prompted & {
      /** Tokens of the opening line, each rendered as its own TeX fragment. */
      start: string[];
      /** Reductions in the order they must be performed. */
      reductions: {
        /** Half-open range of the current line that this step collapses. */
        span: [number, number];
        /** What that span becomes. */
        value: string;
        /** Values offered for this step, including distractors. */
        bank: string[];
        /**
         * Index of the operator token the learner taps to choose this
         * reduction. Defaults to the start of the span.
         *
         * The operator rather than the whole sub-expression, because in
         * `8 + 4 x 3` the two candidate operations *share the 4* — their spans
         * overlap, and no two overlapping regions can both be tap targets.
         * Pointing at the sign is also what a person does when asked which
         * operation comes first.
         */
        operator?: number;
        /**
         * Other operations offered at this stage, none of them the one
         * precedence says to do next.
         *
         * No content uses this now: the `reduce` slide asks the same question
         * from an expression tree, which can offer every piece rather than an
         * authored pair. Kept because the widget and its guards are tested and
         * a linear reduction with one wrong turn is still a reasonable thing to
         * author; delete it with `steps` if that stops being true.
         *
         * Without these the slide hands the learner the correct operation and
         * only asks what it evaluates to — it grades arithmetic and takes the
         * ordering for granted. With them the learner has to say *which*
         * operation comes next as well as what it makes, and reaching for
         * `8 + 4` before `4 x 3` is an error in its own right even when the
         * addition is carried out perfectly.
         *
         * A decoy is collapsed for real when chosen: the learner's own wrong
         * line is what they then look at, rather than being stopped at the
         * moment of the mistake, which would give the answer away. It must
         * therefore cover as many tokens as the correct span, or every later
         * span is off by the difference — there is a test for that.
         */
        decoys?: { operator: number; span: [number, number] }[];
      }[];
    })
  /**
   * Evaluate a whole expression in the head, from four options.
   *
   * The same subject as `reduce` with every support taken away: no pieces to
   * tap, no line of working, no bank narrowed to one stage. The learner has to
   * hold the order in their head and arrive at a number, which is what doing
   * this on paper actually asks of them.
   *
   * It is a pick-one rather than a typed answer because the point is the
   * reasoning, not the typing — and because a wrong order lands on one of the
   * offered numbers, so choosing it feels like success until it is marked.
   */
  | ({ kind: 'evaluate' } & Prompted & {
      expr: Expr;
      /** Exactly one of these equals the expression's value. */
      options: string[];
    })
  /**
   * Evaluate an expression by reducing one piece at a time, choosing both
   * *which* piece comes next and what it comes to.
   *
   * The difference from `steps` is the first of those. `steps` offers the one
   * correct sub-expression and asks only for its value, so it grades arithmetic
   * and takes the ordering for granted — and its flat token spans cannot do
   * otherwise, because which pieces may go next is a fact about the
   * expression's shape rather than about where its characters sit.
   *
   * So the question is carried as a tree (`src/content/expr.ts`), and what may
   * be tapped is computed from it. Operators are always offered, whether or not
   * their operands are settled, which is what makes taking `8 + 4` before
   * `4 x 3` possible — a mistake that cannot be made cannot be taught. Powers
   * and roots are offered only once reducible.
   *
   * There is no expected sequence. A walk is right when every value given is
   * what its piece comes to and nothing is left; the value is the only test.
   * A piece taken before its operands were settled is not refused for that:
   * `8 + 4 x 3` taken left to right comes to 36, not 20, so the order mistake
   * is already in the answer.
   */
  | ({ kind: 'reduce' } & Prompted & {
      expr: Expr;
      /**
       * Values offered when a given node is tapped, keyed by its path.
       *
       * Paths are stable as the tree collapses — reducing one node leaves every
       * other node's address alone — so one map authored up front serves every
       * stage, including the stages reached by a wrong turn.
       */
      banks: Record<string, string[]>;
    })
  /**
   * A decision tree: which method does this problem call for?
   *
   * The opposite direction of travel from `tree`, and the two are easy to
   * confuse. `tree` is about *computing* — its nodes hold numbers, it is built
   * bottom-up from the inputs, and the route through it is fixed by the
   * expression. This is about *choosing* — its nodes hold questions, it runs
   * top-down, and the learner's answers decide which branch is taken. What gets
   * graded is the path, not a value.
   *
   * It exists because picking the right method is a skill the other widgets
   * cannot ask about. A `choice` slide can ask "which method?" and get a lucky
   * guess from four options; walking the tree makes the learner say *why* at
   * every fork, and a wrong turn early leads somewhere visibly different.
   */
  | ({ kind: 'flow' } & Prompted & {
      /** What is being decided about, shown above the first question. TeX. */
      subject: string;
      /** Every question. The first is where the learner starts. */
      steps: {
        id: string;
        /** The question this fork asks. Plain prose. */
        ask: string;
        /** Exactly one of `to` (another step) or `outcome` (a leaf) per branch. */
        branches: { label: string; to?: string; outcome?: string }[];
      }[];
      /** The branch labels along the correct path, in order. */
      answer: string[];
    })
  /**
   * Move a curve until it is the one asked for.
   *
   * The base curve `y = f(x)` is drawn dashed and a live copy of it moves as
   * the learner taps steppers (move, stretch) and flips. Two directions, one
   * kind: `apply` names the target equation in the prompt and asks for the
   * curve; `match` draws the target curve and asks for the transformation,
   * which the readout writes out as the learner builds it.
   *
   * Graded by comparing curves, not parameters (`sameCurve` in
   * `src/content/transform.ts`): for an even `f` a flip left to right draws
   * the same curve as no flip, and the learner who drew it is right.
   */
  | ({ kind: 'transform' } & Prompted & {
      direction: 'apply' | 'match';
      base: BaseCurve;
      /** Drawn and graded over this window. */
      window: Window;
      /** The transformation that draws the target, as `encodeTransform` writes it. */
      answer: string;
    })
  /**
   * Put the steps of a proof in order.
   *
   * The learner builds the proof rather than writing it: numbered slots, one
   * per step, filled by tapping steps from a bank that also holds distractors —
   * a step from a different strategy, an algebra slip, a true statement the
   * proof never needs, a conclusion that does not follow. Distractors are the
   * steps whose id is in no answer.
   *
   * Graded in exact order. Where two steps could genuinely swap, the generator
   * writes the proof so that they cannot (each step leans on the one above it)
   * rather than the grader accepting both.
   */
  | ({ kind: 'order' } & Prompted & {
      /**
       * Every step offered, in bank order. `text` is prose with inline `$...$`
       * TeX, rendered the way a `prose` block is.
       *
       * Bank order is fixed by the steps themselves (`orderBank`), never by a
       * per-draw shuffle and never by the answer order.
       */
      steps: { id: string; text: string }[];
      /** Ids of the proof's steps, in slot order. */
      answer: string[];
    })
  /**
   * Fill the intermediate values of an evaluation tree.
   *
   * Nodes are listed in evaluation order and each names the nodes feeding it,
   * which is enough to lay out rows and draw the connectors without the content
   * author positioning anything by hand.
   */
  | ({ kind: 'tree' } & Prompted & {
      /** The expression the tree evaluates. TeX. */
      expression: string;
      /** In evaluation order. `from` holds ids of nodes feeding this one. */
      nodes: { id: string; from: string[] }[];
      /** Values offered, including distractors. */
      bank: string[];
      /** Expected value per node, in `nodes` order. */
      answer: string[];
    })
  /**
   * Fill in a table of terms: a sequence worked row by row.
   *
   * The rule sits in the prompt, and the learner fills the gaps from a bank —
   * the same two taps as `tree`, but laid out as the table a sequence is
   * written in on paper. It asks for several terms in one slide, which a typed
   * `expression` cannot without asking for the closed form instead, and it
   * lets a third column (a difference, a running sum) be asked beside the
   * terms.
   *
   * Every cell is its own KaTeX call, so the `{0}` markers of `tiles` play no
   * part here and braces round a number are harmless.
   */
  | ({ kind: 'table' } & Prompted & {
      /** Column headers, TeX: `n`, `u_n`, and optionally a third. */
      columns: string[];
      /**
       * One entry per row and column. A string is a given cell, TeX, where the
       * empty string shows nothing; `null` is a blank for the learner to fill.
       */
      rows: (string | null)[][];
      /** Values offered, including distractors. Sorted, never shuffled. */
      bank: string[];
      /** Expected token per blank, reading rows top to bottom, left to right. */
      answer: string[];
    })
  /**
   * Run an iteration by hand: fill in `x_1`, `x_2`, … from a given `x_0`, then
   * say what the iterates tell you about the root.
   *
   * The scheme and the precision live in the prompt; the widget draws the
   * `n | x_n` table under it with `x_0` filled in, one blank per iterate, and
   * one more blank for the conclusion. Values come from a bank, as `tree` does
   * it, so the grade is exact tokens: every iterate is written to the places
   * the prompt states, and the generator refuses draws where rounding is a
   * coin toss.
   */
  | ({ kind: 'iterate' } & Prompted & {
      /** `x_0`, shown in the first row. TeX. */
      start: string;
      /**
       * What the last cell asks for: the value the iterates settle on to the
       * stated precision, or the two consecutive tenths either side of the
       * root, written as one token (`1.8 < \alpha < 1.9`).
       */
      conclusion: 'limit' | 'bracket';
      /** Values offered, including distractors. Sorted, never shuffled. */
      bank: string[];
      /** `x_1` onwards, one per blank row, then the conclusion. */
      answer: string[];
    })
  /**
   * A two-stage probability tree, drawn root on the left as it is on paper.
   *
   * At most three first-stage branches and two under each. Two modes, one
   * picture: `fill` leaves some branch probabilities blank and fills them from
   * the bank in any order, as `iterate` does; `path` shows every probability
   * and asks the learner to tap one branch per stage, as `flow` does, so what
   * is graded is which outcome they picked rather than a value.
   */
  | ({ kind: 'probTree' } & Prompted & {
      mode: 'fill' | 'path';
      /**
       * First-stage branches, top to bottom, each with the two under it. A
       * label is TeX and unique among its siblings; a probability is TeX, or
       * `null` for a blank (fill mode only).
       */
      branches: {
        label: string;
        p: string | null;
        next: { label: string; p: string | null }[];
      }[];
      /** Values offered in fill mode, including distractors. Sorted, never shuffled. Empty in path mode. */
      bank: string[];
      /**
       * Fill: one token per blank, first-stage blanks top to bottom, then the
       * second stage top to bottom. Path: the two branch labels, first stage
       * then the one under it.
       */
      answer: string[];
    })
  /**
   * A Venn diagram of two sets in a rectangle, its four regions filled from a
   * bank: only in the first set, in both, only in the second, in neither.
   * The regions hold counts or probabilities, and a region may be given.
   */
  | ({ kind: 'venn' } & Prompted & {
      /** The two circles' labels, left then right. TeX. */
      sets: [string, string];
      /**
       * The size of the universal set when the regions are counts, shown in the
       * corner as `n(\xi)`. Absent for probabilities, whose regions sum to 1.
       */
      total?: number;
      /** Only the first, both, only the second, neither. TeX, or `null` for a blank. */
      regions: (string | null)[];
      /** Values offered, including distractors. Sorted, never shuffled. */
      bank: string[];
      /** One token per blank region, in `regions` order. */
      answer: string[];
    })
  /**
   * Draw or complete a free-body diagram.
   *
   * A box on a level floor, on a slope drawn at its stated angle, or hanging
   * from a string, with arrows from its centre. Two modes, one kind:
   *
   * - `pick`: every candidate arrow is drawn faint, and the learner taps on
   *   the ones that act. The answer is a set of arrow ids (which are their
   *   directions), graded after sorting, so tap order cannot matter.
   * - `fill`: every arrow drawn acts, and some magnitudes are blanks filled
   *   from a bank as `iterate` does it, graded by `gradeSequence`.
   *
   * The model, geometry and the `pick` grade live in `src/content/forces.ts`.
   */
  | ({ kind: 'forces' } & Prompted & {
      scene: ForceScene;
      /** No two share a direction, so an arrow's id is its direction. */
      arrows: ForceArrow[];
    } & (
        | {
            mode: 'pick';
            /** The ids that act, sorted and joined by `|`. Never displayed. */
            answer: string;
          }
        | {
            mode: 'fill';
            /** Magnitudes offered, including distractors. Sorted, never shuffled. */
            bank: string[];
            /** One token per blank, in arrow order. */
            answer: string[];
          }
      ));

/**
 * Produces a slide from randomised parameters.
 *
 * `render` and `solution` both receive the same parameters, which is what lets
 * the opt-in worked solution use the learner's actual numbers rather than a
 * generic template.
 */
export interface Generator<P = unknown> {
  id: string;
  sample(rng: Rng, difficulty: number): P;
  render(params: P): Slide;
  solution(params: P): SolutionStep[];
  /**
   * The same question, asked as multiple choice.
   *
   * Optional, and where it exists the registry derives a second generator from
   * it automatically under the id `<id>+choice`, which a lesson references like
   * any other. That is what keeps a lesson from asking seven questions through
   * one widget: the same skill, a different shape, with no second generator to
   * write and keep in step.
   *
   * Return the correct option flagged and the rest as distractors. Order does
   * not matter — the wrapper rotates them by the question's own numbers, so the
   * answer is not always first yet one question still renders one way.
   *
   * Every label is TeX the learner reads, so it follows the same rule as the
   * rest of the displayed strings: written by hand, not derived from `answer`.
   * A test renders each one and checks every distractor is genuinely wrong.
   */
  choices?(params: P): ChoiceOption[];
  /**
   * The prompt of the derived `evaluate` slide, for a `reduce` generator with
   * `choices`. Without it that slide reads only "Evaluate the expression.",
   * which is right for bare arithmetic and wrong for a line that came out of a
   * model: the owner found `16 + 32 \div 2^{4}` in a lesson on cooling tea and
   * could not see what it had to do with it.
   */
  evaluatePrompt?(params: P): Block[];
}

/** One option of a generator's multiple-choice form. */
export interface ChoiceOption {
  /** What the learner reads. TeX. */
  tex: string;
  /** Exactly one option per question sets this. */
  correct?: boolean;
  /**
   * The same value in mathjs syntax, where the option is an expression.
   *
   * Only used by the test that proves a distractor is really wrong; it is never
   * displayed. Leave it off for an option that is not an expression at all — a
   * count, a yes/no, a coordinate pair — and the check is skipped.
   */
  answer?: string;
}

export type GeneratorRegistry = Record<string, Generator<never>>;

export type SlideRef =
  | { type: 'literal'; slide: Slide; solution?: SolutionStep[] }
  | {
      type: 'generated';
      generatorId: string;
      difficulty?: number;
      /**
       * Teaching prose shown above the generated question, on the same slide.
       *
       * A lesson reads as one thread rather than a teaching block followed by a
       * quiz block: "Let's think about what we just did in reverse" belongs with
       * the question it sets up, not on a slide of its own the learner has to
       * remember across a tap.
       *
       * It is a property of the *reference* rather than the generator because
       * the continuity belongs to the lesson: the same generator is set up
       * differently depending on what came before it.
       */
      leadIn?: Block[];
    };

export interface Lesson {
  id: string;
  title: string;
  /**
   * Assessment flow: one attempt per question, no worked solutions, scored as
   * a percentage.
   *
   * Set by `levelCheckLesson`. It is a property of the lesson rather than of
   * the phase because the seal has to hold from the very first question, and
   * the reducer is the only thing that reads it.
   */
  assessment?: boolean;
  /** Roughly ten slides: teach, practise x3, teach, practise x2-3. */
  slides: SlideRef[];
  /** Three sealed questions. Guided slides cannot be reviewed from here. */
  skillCheck: SlideRef[];
}

export interface Level {
  id: string;
  title: string;
  lessons: Lesson[];
  /**
   * The assessment closing the level: questions only, no teaching slides.
   *
   * It reuses `Lesson` rather than inventing a second shape — a level check is
   * a lesson whose guided deck is empty, which the session reducer already
   * treats as sealed from the first question.
   */
  levelCheck?: SlideRef[];
}

/** The tabs on the home screen; `courses/index.ts` gives each its title. */
export type CategoryId =
  | 'algebra-fundamentals'
  | 'advanced-algebra'
  | 'advanced-maths'
  | 'contest-math'
  | 'statistics'
  | 'mechanics';

export interface Course {
  id: string;
  /** Which home-screen tab the course sits in. */
  category: CategoryId;
  /**
   * Where in that tab, smallest first. Spaced in tens so a new course can go
   * between two others; a tie is broken by id, so two new courses picking the
   * same number still get a fixed order.
   */
  position: number;
  title: string;
  blurb: string;
  levels: Level[];
}

/**
 * A group of related courses, shown as one tab on the home screen.
 *
 * Categories carry the difficulty banding — Foundations through Advanced — so a
 * course does not have to name its own level, and a topic studied at both A
 * level and undergraduate simply has more levels rather than two entries.
 */
export interface Category {
  id: string;
  title: string;
  blurb: string;
  courses: Course[];
}

/**
 * The level check as a playable lesson.
 *
 * Returns undefined when the level has no check, so the caller can leave the
 * row out rather than offering an empty assessment.
 */
export function levelCheckLesson(level: Level): Lesson | undefined {
  if (!level.levelCheck || level.levelCheck.length === 0) return undefined;
  return {
    id: `${level.id}:check`,
    title: `${level.title} — Level Check`,
    assessment: true,
    slides: [],
    skillCheck: level.levelCheck,
  };
}
