/**
 * Contest Math, Level 10: Factorization. Every lesson writes a number as a
 * product of prime powers and reads the answer off the exponents: topping
 * them up to a square or a cube, adding one to each to count divisors, taking
 * the lower or higher of two for the HCF and LCM, counting the 5s in a
 * factorial, and, in the cryptograms, factorising the place values
 * themselves (AB + BA = 11(A + B), ABCABC = ABC × 7 × 11 × 13).
 * Generators in `generators/contestFactorization.ts`.
 */
import type { Level } from '../../types';
import { teach, ask, prose, maths, askAfter } from './blocks';

export const factorization: Level = {
  id: 'cm-l10',
  title: 'Factorization',
  lessons: [
    {
      id: 'cm-l10-factorization',
      title: 'Factorization',
      slides: [
        teach(
          prose('Every whole number above 1 is a product of primes in exactly one way. Problems about factors start by writing it down:'),
          maths('360 = 2^{3} \\times 3^{2} \\times 5'),
          prose('In a **perfect square** every prime has an even power. To make $360k$ a perfect square, give each odd power one more of its prime:'),
          maths('k = 2 \\times 5 = 10'),
          maths('360 \\times 10 = 3600 = 60^2'),
          prose('The trap is to multiply by every prime once, $2 \\times 3 \\times 5 = 30$: the $3^{2}$ was already paired.'),
        ),
        ask('cm-fz-square-multiplier'),
        askAfter(
          'cm-fz-square-multiplier-tiles',
          1,
          prose('The square root comes straight from the powers: halve each one.'),
          maths('3600 = 2^{4} \\times 3^{2} \\times 5^{2}'),
          maths('\\sqrt{3600} = 2^{2} \\times 3 \\times 5 = 60'),
        ),
        askAfter(
          'cm-fz-square-multiplier+choice',
          2,
          prose('In a **perfect cube** every power is a multiple of 3, so top each power up to the next multiple of 3. With $72$ the 2s are done and the 3s need one more:'),
          maths('72 = 2^{3} \\times 3^{2}'),
          maths('72 \\times 3 = 216 = 6^3'),
          prose('The square rule would give $k = 2$, the trap.'),
        ),
        teach(
          prose('A zero at the end of a number is a factor $10 = 2 \\times 5$. Each zero needs one 2 and one 5, so count both and the scarcer prime decides:'),
          maths('N = 2^{7} \\times 3^{4} \\times 5^{3}'),
          prose('Seven 2s but only three 5s, so $N$ ends in $3$ zeros, not $10$.'),
          prose('Powers of composite numbers need factorising first:'),
          maths('4^{3} \\times 25^{2} \\times 6 = 2^{6} \\times 5^{4} \\times 2 \\times 3'),
          prose('That is seven 2s and four 5s: $4$ zeros. Reading $25^{2}$ as two 5s rather than four is the trap.'),
        ),
        ask('cm-fz-zeros-product'),
        askAfter(
          'cm-fz-near-square',
          1,
          prose('A number just below a round square may be a difference of two squares, which factorises:'),
          maths('4891 = 4900 - 9 = 70^2 - 3^2'),
          maths('70^2 - 3^2 = (70 - 3)(70 + 3)'),
          maths('4891 = 67 \\times 73'),
          prose('Both are prime, and neither is quick to find by trying divisors.'),
        ),
        ask('cm-fz-zeros-product+choice', 2),
        askAfter(
          'cm-fz-near-square+choice',
          2,
          prose('The square need not be round. Find the first square above the number and check whether the gap is a square too:'),
          maths('1073 = 1089 - 16 = 33^2 - 4^2'),
          maths('1073 = 29 \\times 37'),
        ),
        ask('cm-fz-square-multiplier-tiles', 2),
      ],
      skillCheck: [ask('cm-fz-square-multiplier', 2), ask('cm-fz-zeros-product', 2), ask('cm-fz-near-square', 2)],
    },
    {
      id: 'cm-l10-divisors',
      title: 'Number of Divisors',
      slides: [
        teach(
          prose('A divisor of $72 = 2^{3} \\times 3^{2}$ is $2^a \\times 3^b$, with $a$ from $0$ to $3$ and $b$ from $0$ to $2$. That is $4$ choices for $a$ and $3$ for $b$:'),
          maths('(3 + 1)(2 + 1) = 12'),
          prose('So add one to each power and multiply. Multiplying the powers themselves, $3 \\times 2 = 6$, forgets the choice of none at all.'),
        ),
        ask('cm-fz-divisor-count'),
        askAfter(
          'cm-fz-divisor-table',
          1,
          prose('Set the count out prime by prime. $200 = 2^{3} \\times 5^{2}$: the 2 has power $3$, so $4$ choices, and the 5 has power $2$, so $3$ choices.'),
          maths('4 \\times 3 = 12'),
        ),
        askAfter(
          'cm-fz-divisor-count+choice',
          2,
          prose('A power of a composite number needs factorising first. $12^{3}$ is not a prime cube:'),
          maths('12^{3} = (2^{2} \\times 3)^{3} = 2^{6} \\times 3^{3}'),
          maths('(6 + 1)(3 + 1) = 28'),
          prose('Reading $12^{3}$ as if $12$ were prime gives $4$, the trap.'),
        ),
        askAfter(
          'cm-fz-special-divisors',
          1,
          prose('An odd divisor of $360 = 2^{3} \\times 3^{2} \\times 5$ has no 2 in it, so only the 3 and the 5 choose:'),
          maths('\\text{odd} = (2 + 1)(1 + 1) = 6'),
          prose('Every other divisor is even: the 2 goes in $1$ to $3$ times, $3$ choices.'),
          maths('\\text{even} = 3 \\times 6 = 18'),
        ),
        teach(
          prose('The **sum** of the divisors comes from the same choices. Multiply out one bracket of powers for each prime:'),
          maths('(1 + 2 + 4)(1 + 3)'),
          prose('Each term of the expansion picks one power of 2 and one power of 3, which is one divisor of $12 = 2^{2} \\times 3$, and every divisor turns up once. So'),
          maths('1 + 2 + 3 + 4 + 6 + 12 = 7 \\times 4 = 28'),
          prose('Adding the brackets, $7 + 4 = 11$, is the trap.'),
        ),
        ask('cm-fz-divisor-sum'),
        askAfter(
          'cm-fz-special-divisors',
          2,
          prose('A **perfect square** divisor has every power even. In $2^{5} \\times 3^{2}$ the 2 can go in $0$, $2$ or $4$ times and the 3 in $0$ or $2$ times:'),
          maths('3 \\times 2 = 6'),
          prose('Count the $0$: it gives the square divisor $1$.'),
        ),
        ask('cm-fz-divisor-sum+choice', 2),
        ask('cm-fz-divisor-table', 2),
      ],
      skillCheck: [ask('cm-fz-divisor-count', 2), ask('cm-fz-divisor-sum', 2), ask('cm-fz-special-divisors', 2)],
    },
    {
      id: 'cm-l10-gcd-lcm',
      title: 'GCD and LCM',
      slides: [
        teach(
          prose('The **greatest common divisor** (GCD, also called the HCF) and the **lowest common multiple** (LCM) can be read off the prime factorisations:'),
          maths('a = 2^{3} \\times 3 \\times 5^{2}'),
          maths('b = 2 \\times 3^{2} \\times 7'),
          prose('The HCF divides both, so it keeps only the shared primes, each to the lower power. The LCM is a multiple of both, so it takes every prime, each to the higher power:'),
          maths('\\text{HCF} = 2 \\times 3'),
          maths('\\text{LCM} = 2^{3} \\times 3^{2} \\times 5^{2} \\times 7'),
        ),
        ask('cm-fz-hcf-lcm-tiles'),
        askAfter(
          'cm-fz-together',
          1,
          prose('Two lights flash every $6$ and every $10$ seconds. They next flash together after a time that is a multiple of both, the LCM:'),
          maths('6 = 2 \\times 3, \\quad 10 = 2 \\times 5'),
          maths('\\text{LCM} = 2 \\times 3 \\times 5 = 30'),
          prose('Multiplying, $60$, is a time they meet, but not the first.'),
        ),
        askAfter(
          'cm-fz-pieces',
          1,
          prose('To cut a $12$ by $18$ rectangle into equal squares with nothing left over, the side must divide both lengths. The largest such side is the HCF:'),
          maths('12 = 2^{2} \\times 3, \\quad 18 = 2 \\times 3^{2}'),
          maths('\\text{HCF} = 2 \\times 3 = 6'),
          prose('That is 2 rows of 3 squares, each of side $6$.'),
        ),
        teach(
          prose('Each prime’s lower power goes into the HCF and its higher power into the LCM, so between them they hold every power of both numbers:'),
          maths('\\text{HCF} \\times \\text{LCM} = a \\times b'),
          prose('With HCF $6$, LCM $180$ and one number $36$:'),
          maths('6 \\times 180 = 36 \\times b'),
          maths('b = 1080 \\div 36 = 30'),
        ),
        ask('cm-fz-hcf-lcm-product'),
        askAfter(
          'cm-fz-hcf-lcm-product+choice',
          2,
          prose('Write the two numbers as $6x$ and $6y$, where $x$ and $y$ share no factor, so the LCM is $6xy$. With HCF $6$ and LCM $72$:'),
          maths('xy = 72 \\div 6 = 12'),
          prose('$x$ and $y$ share no factor, so the $2^{2}$ in $12$ goes whole to one of them: $x$ and $y$ are $1$ and $12$, or $4$ and $3$. If neither number is $6$, they are'),
          maths('6 \\times 4 + 6 \\times 3 = 24 + 18 = 42'),
          prose('The pair $6$ and $72$, with sum $78$, is the trap.'),
        ),
        askAfter(
          'cm-fz-together',
          2,
          prose('Buses every $10$ and every $15$ minutes leave together every $30$ minutes. From 8:00 to 10:00 there are'),
          maths('120 \\div 30 = 4'),
          prose('gaps, and one more departure than gaps, since 8:00 counts too: $5$ times. Answering $4$ is the fence-post trap.'),
        ),
        askAfter(
          'cm-fz-pieces+choice',
          2,
          prose('Ribbons of $12$, $18$ and $30$ cm are cut into equal pieces, as long as possible. Each piece is the HCF, $6$ cm, and each ribbon gives its length over $6$:'),
          maths('2 + 3 + 5 = 10'),
          prose('The piece length, $6$, is not the number of pieces.'),
        ),
        ask('cm-fz-hcf-lcm-tiles', 2),
      ],
      skillCheck: [ask('cm-fz-hcf-lcm-product', 2), ask('cm-fz-together', 2), ask('cm-fz-pieces', 2)],
    },
    {
      id: 'cm-l10-factorials',
      title: 'Factorials',
      slides: [
        teach(
          prose('How many zeros end $100!$? Each zero is a factor $10 = 2 \\times 5$, and there are far more 2s than 5s, so count the 5s.'),
          prose('Every multiple of 5 gives one 5, and every multiple of 25 gives a second:'),
          maths('100 \\div 5 \\to 20'),
          maths('100 \\div 25 \\to 4'),
          maths('20 + 4 = 24'),
          prose('Stopping at $20$ misses the second 5 in each of 25, 50, 75 and 100. Beyond $125$, each multiple of 125 gives a third, and beyond $625$ each multiple of 625 a fourth.'),
        ),
        ask('cm-fz-factorial-zeros'),
        askAfter(
          'cm-fz-factorial-table',
          1,
          prose('The same count works for any prime. The 3s in $30!$ come from the multiples of 3, of 9 and of 27:'),
          maths('10 + 3 + 1 = 14'),
        ),
        askAfter(
          'cm-fz-factorial-power',
          1,
          prose('So $3^{14}$ divides $30!$ and $3^{15}$ does not. The 2s in $20!$:'),
          maths('\\lfloor 20/2 \\rfloor + \\lfloor 20/4 \\rfloor + \\lfloor 20/8 \\rfloor + \\lfloor 20/16 \\rfloor'),
          maths('10 + 5 + 2 + 1 = 18'),
        ),
        ask('cm-fz-factorial-zeros+choice', 2),
        teach(
          prose('For a composite base, count each of its primes. $12 = 2^{2} \\times 3$, and $20!$ holds $18$ twos and $8$ threes:'),
          maths('\\text{threes}: \\; 6 + 2 = 8'),
          maths('\\text{pairs of twos}: \\; 18 \\div 2 = 9'),
          prose('Each 12 uses a pair of 2s and one 3, so the 3s run out first: $12^{8}$ divides $20!$, and no higher power does. With $6 = 2 \\times 3$ the 3s always run out first; $18 = 2 \\times 3^{2}$ uses two 3s, so halve the count of 3s. Counting the multiples of 12, just $1$, is the trap.'),
        ),
        ask('cm-fz-factorial-power', 2),
        askAfter(
          'cm-fz-factorial-smallest',
          1,
          prose('Run the count backwards: the smallest $n$ for which $5^{7}$ divides $n!$. Only multiples of 5 add 5s, so try them in turn:'),
          maths('25!: \\; 5 + 1 = 6'),
          maths('30!: \\; 6 + 1 = 7'),
          prose('So $n = 30$. Guessing $5 \\times 7 = 35$ forgets the second 5 in 25.'),
        ),
        askAfter(
          'cm-fz-factorial-smallest+choice',
          2,
          prose('At least $k$ zeros means at least $k$ fives. For a power of 2, step through the even numbers: the multiples of 4, 8 and 16 bring several 2s each, so the answer is well below $2k$. For $2^{10}$:'),
          maths('10!: \\; 5 + 2 + 1 = 8'),
          maths('12!: \\; 6 + 3 + 1 = 10'),
          prose('So $2^{10}$ first divides $12!$, not $20!$.'),
        ),
        ask('cm-fz-factorial-table', 2),
      ],
      skillCheck: [ask('cm-fz-factorial-zeros', 2), ask('cm-fz-factorial-power', 2), ask('cm-fz-factorial-smallest', 2)],
    },
    {
      id: 'cm-l10-cryptograms',
      title: 'Cryptograms',
      slides: [
        teach(
          prose('In a **cryptogram** each letter stands for a digit. The key move is to write each number by place value: $AB$ means $10A + B$.'),
          maths('AB + BA = (10A + B) + (10B + A) = 11(A + B)'),
          prose('So if $AB + BA = 121$, then $A + B = 11$, whatever the digits. If also $A \\times B = 24$, with $A$ the larger, then $A = 8$ and $B = 3$:'),
          maths('83 + 38 = 121'),
          prose('A three-digit number and its reverse differ by a multiple of 99, because the middle digit cancels:'),
          maths('ABC - CBA = 99(A - C)'),
        ),
        ask('cm-fz-crypt-reverse'),
        askAfter(
          'cm-fz-crypt-place',
          1,
          prose('Place value also untangles a number added to its front parts:'),
          maths('ABC + AB + A = 111A + 11B + C'),
          prose('$11B + C$ is at most $108$, less than $111$, so $A$ is the number of whole 111s in the total. If the total is $500$:'),
          maths('500 = 111 \\times 4 + 56'),
          maths('56 = 11 \\times 5 + 1'),
          prose('so $ABC = 451$.'),
        ),
        askAfter(
          'cm-fz-crypt-reverse+choice',
          2,
          prose('With the difference: $ABC - CBA = 297$ gives $A - C = 3$. If $A \\times C = 10$, then $A = 5$ and $C = 2$, and a digit sum of $14$ leaves'),
          maths('B = 14 - 5 - 2 = 7'),
          prose('so $ABC = 572$. Its reverse, $275$, is the trap.'),
        ),
        teach(
          prose('Divisibility pins digits down too. $72 = 8 \\times 9$, and 8 and 9 share no factor, so a multiple of 72 is exactly a number that passes both tests: its last three digits make a multiple of 8, and its digits add to a multiple of 9.'),
          prose('Take $3A51B$. Of $510$ to $519$, only $512$ is a multiple of 8:'),
          maths('B = 2'),
          prose('The digits then add to'),
          maths('3 + A + 5 + 1 + 2 = 11 + A'),
          prose('which is a multiple of 9 only for $A = 7$: the number is $37512 = 72 \\times 521$.'),
          prose('Splitting 72 as $4 \\times 18$ does not work: $36$ is a multiple of both but not of 72. The two parts must share no factor.'),
        ),
        ask('cm-fz-crypt-divisible'),
        askAfter(
          'cm-fz-crypt-block',
          1,
          prose('Writing a three-digit block twice multiplies it by 1001, and 1001 factorises neatly:'),
          maths('ABCABC = ABC \\times 1000 + ABC = ABC \\times 1001'),
          maths('1001 = 7 \\times 11 \\times 13'),
          prose('So take one 7, one 11 and one 13 out of the factorisation of $ABCABC$, and what is left is $ABC$. From $7 \\times 11 \\times 13 \\times 17 \\times 23$ that leaves'),
          maths('ABC = 17 \\times 23 = 391'),
        ),
        askAfter(
          'cm-fz-crypt-divisible',
          2,
          prose('With a 4 or a 5 in place of the 8, $B$ has more than one candidate, so try each. For $44 = 4 \\times 11$ and $3A21B$, the last two digits $1B$ are a multiple of 4 for $B = 2$ or $6$. A multiple of 11 has its digits, with signs $+, -, +, -, +$, adding to a multiple of 11:'),
          maths('3 - A + 2 - 1 + B = 4 - A + B'),
          prose('$B = 6$ would need $A = 10$, so $B = 2$ and $A = 6$: the number is $36212 = 44 \\times 823$.'),
        ),
        askAfter(
          'cm-fz-crypt-block+choice',
          2,
          prose('If $ABC$ is itself a multiple of 7, 11 or 13, that prime appears twice. Take out only one copy:'),
          maths('ABCABC = 3 \\times 5 \\times 7^{2} \\times 11 \\times 13'),
          maths('ABC = 3 \\times 5 \\times 7 = 105'),
          prose('Taking out both 7s gives $15$, the trap.'),
        ),
        askAfter(
          'cm-fz-crypt-place',
          2,
          prose('With four letters the place values are $1111$, $111$, $11$ and $1$:'),
          maths('ABCD + ABC + AB + A = 1111A + 111B + 11C + D'),
          prose('The rest is at most $999 + 99 + 9 = 1107$, less than $1111$, so peel off the 1111s, then the 111s, then the 11s.'),
        ),
      ],
      skillCheck: [ask('cm-fz-crypt-reverse', 2), ask('cm-fz-crypt-block', 2), ask('cm-fz-crypt-divisible', 2)],
    },
  ],
  levelCheck: [
    ask('cm-fz-square-multiplier', 2),
    ask('cm-fz-zeros-product+choice', 2),
    ask('cm-fz-near-square', 2),
    ask('cm-fz-divisor-count', 2),
    ask('cm-fz-divisor-sum+choice', 2),
    ask('cm-fz-special-divisors', 2),
    ask('cm-fz-hcf-lcm-product', 2),
    ask('cm-fz-together+choice', 2),
    ask('cm-fz-factorial-zeros', 2),
    ask('cm-fz-factorial-power+choice', 2),
    ask('cm-fz-factorial-smallest', 2),
    ask('cm-fz-crypt-place', 2),
    ask('cm-fz-crypt-reverse+choice', 2),
  ],
};
