/**
 * Contest Math, Level 4: Geometry Fundamentals. Lengths and areas measured
 * in one unit, angles hunted with a parallel line or an isosceles triangle,
 * the turning that sums a star's tips, the two special right triangles, and
 * a perpendicular dropped to make a right triangle where there is none.
 * Generators in `generators/contestGeometryFundamentals.ts`.
 */
import type { Level } from '../../types';
import { teach, ask, prose, maths, askAfter } from './blocks';

export const geometryFundamentals: Level = {
  id: 'cm-l4',
  title: 'Geometry Fundamentals',
  lessons: [
    {
      id: 'cm-l4-measures',
      title: 'Measures',
      slides: [
        teach(
          prose('Measure in one unit before you count. A floor $3$ m by $2$ m, tiled with squares of side $25$ cm, is $300$ cm by $200$ cm. Count the tiles along each side:'),
          maths('300 \\div 25 = 12'),
          maths('200 \\div 25 = 8'),
          prose('The tiles make a grid of rows and columns:'),
          maths('12 \\times 8 = 96'),
          prose('The trap is converting the area. A square metre is $100$ cm by $100$ cm, which is $10\\,000$ cm², not $100$ cm².'),
        ),
        ask('cm-floor-tiles'),
        askAfter(
          'cm-four-rectangles',
          1,
          prose('A rectangle cut by one line across and one line down: pieces side by side share a height, so their areas are in the ratio of their widths, and both rows have the same widths.'),
          prose('So the products across the two diagonals match. With $6$ and $10$ along the top and $9$ under the $6$, the last piece is $x$:'),
          maths('x \\times 6 = 10 \\times 9'),
          maths('x = 15'),
        ),
        askAfter(
          'cm-floor-tiles+choice',
          2,
          prose('With decimals, turn each side into centimetres first. $3.6$ m is $360$ cm, and with $30$ cm tiles that side takes'),
          maths('360 \\div 30 = 12'),
        ),
        teach(
          prose('A square is cut into $4$ identical strips, each with a perimeter of $40$ cm. Call the square’s side $s$. A strip is $s$ long and $s \\div 4$ wide, and half its perimeter is one length and one width:'),
          maths('s + \\frac{s}{4} = 20'),
          maths('\\frac{5s}{4} = 20'),
          maths('s = 16'),
          prose('So the square’s perimeter is $64$ cm, not the $40$ cm of one strip. Cutting a shape up adds new edges inside it.'),
        ),
        ask('cm-strip-square'),
        ask('cm-strip-square-tiles'),
        askAfter('cm-four-rectangles+choice', 2, prose('For the whole rectangle, find the missing piece first, then add all four.')),
        askAfter('cm-strip-square+choice', 2, prose('For the area, find the side the same way, then square it.')),
        ask('cm-strip-square-tiles', 2),
      ],
      skillCheck: [ask('cm-floor-tiles', 2), ask('cm-four-rectangles', 2), ask('cm-strip-square', 2)],
    },
    {
      id: 'cm-l4-angle-hunting',
      title: 'Angle Hunting',
      slides: [
        teach(
          prose('Angle hunting: mark every angle you know, and add a line when it makes more of them known.'),
          prose('A path bends once between two parallel lines. It meets the top line at $35^\\circ$ and the bottom line at $50^\\circ$. Draw a third parallel line through the bend. It splits the bend into two parts, each alternate (a Z shape) to one of the given angles:'),
          maths('x = 35 + 50 = 85'),
        ),
        ask('cm-parallel-bend'),
        askAfter(
          'cm-isosceles-cases+choice',
          1,
          prose('An isosceles triangle with a $40^\\circ$ angle could have it between the equal sides, or as one of the equal pair. Try both:'),
          maths('(180 - 40) \\div 2 = 70'),
          maths('180 - 2 \\times 40 = 100'),
          prose('The triangle is $40^\\circ, 70^\\circ, 70^\\circ$ or $40^\\circ, 40^\\circ, 100^\\circ$, so the largest angle it could have is $100^\\circ$.'),
        ),
        askAfter(
          'cm-parallel-bend+choice',
          2,
          prose('With two bends, draw a parallel line through each. At the first bend, take off the part alternate to the top angle. What is left is alternate to part of the second bend.'),
          prose('A top angle of $50^\\circ$, a first bend of $80^\\circ$ and a bottom angle of $40^\\circ$:'),
          maths('80 - 50 = 30'),
          maths('x = 30 + 40 = 70'),
        ),
        teach(
          prose('Isosceles triangles pass angles along. In triangle $ABC$, $AB = AC$ and $\\angle A = 30^\\circ$, so the base angles are'),
          maths('(180 - 30) \\div 2 = 75'),
          prose('Put $D$ on $AC$ with $BD = BC$. Triangle $DBC$ is isosceles too, with equal angles at $D$ and $C$:'),
          maths('\\angle BDC = \\angle C = 75'),
          maths('\\angle DBC = 180 - 2 \\times 75 = 30'),
          prose('the same as $\\angle A$. What is left at $B$:'),
          maths('\\angle ABD = 75 - 30 = 45'),
          prose('And $A$, $D$ and $C$ are on a straight line:'),
          maths('\\angle ADB = 180 - 75 = 105'),
        ),
        ask('cm-isosceles-chain'),
        ask('cm-isosceles-chain-tiles'),
        askAfter(
          'cm-isosceles-cases',
          2,
          prose('When the given angle is over $60^\\circ$, the smallest angle comes from making it one of the equal pair. With $70^\\circ$:'),
          maths('180 - 2 \\times 70 = 40'),
          prose('That beats the $55^\\circ$ base angles you get with the $70^\\circ$ between the equal sides.'),
        ),
        ask('cm-isosceles-chain+choice', 2),
        ask('cm-isosceles-chain-tiles', 2),
      ],
      skillCheck: [ask('cm-parallel-bend', 2), ask('cm-isosceles-chain', 2), ask('cm-isosceles-cases+choice', 2)],
    },
    {
      id: 'cm-l4-polygon-angles',
      title: 'Polygon Angle Hunting',
      slides: [
        teach(
          prose('Walk round a shape and add up the turning. Round a polygon you turn once, $360^\\circ$. Round a five-pointed star you turn twice, $720^\\circ$.'),
          prose('At each tip of the star you turn through $180^\\circ$ less the tip angle, so'),
          maths('5 \\times 180 - \\text{tips} = 720'),
          maths('\\text{tips} = 900 - 720 = 180'),
          prose('The five tips of any five-pointed star add to $180^\\circ$, however lopsided it is.'),
        ),
        ask('cm-star-tips'),
        askAfter(
          'cm-missing-angle',
          1,
          prose('A polygon with $n$ sides has angles adding to $(n - 2) \\times 180^\\circ$. Say all but one angle of a convex polygon add to $1000^\\circ$. The missing one is under $180^\\circ$, so the full sum is the next multiple of $180$:'),
          maths('1000 = 5 \\times 180 + 100'),
          maths('\\text{full sum} = 6 \\times 180 = 1080'),
          maths('n - 2 = 6'),
          prose('So $n = 8$, and the missing angle is $80^\\circ$.'),
        ),
        ask('cm-missing-angle-tiles'),
        askAfter(
          'cm-star-tips+choice',
          2,
          prose('A regular star joining each of $8$ points to the one $3$ along goes round the centre $3$ times. The turning at each tip is'),
          maths('3 \\times 360 \\div 8 = 135'),
          maths('\\text{tip} = 180 - 135 = 45'),
        ),
        teach(
          prose('The corners of a regular polygon lie on a circle. Each side takes $360^\\circ \\div n$ at the centre, and an angle at the circle is half the angle at the centre, so from any other corner each side is seen at $180^\\circ \\div n$.'),
          prose('In a regular hexagon $ABCDEF$ each side is seen at'),
          maths('180 \\div 6 = 30'),
          prose('so $\\angle BAC = 30^\\circ$, and $\\angle CAE$, across the two sides $CD$ and $DE$, is $60^\\circ$.'),
        ),
        ask('cm-polygon-seen-angle'),
        askAfter(
          'cm-polygons-meet+choice',
          1,
          prose('Regular polygons fitted round a point fill $360^\\circ$. A square and a regular hexagon, $90^\\circ$ and $120^\\circ$, leave'),
          maths('360 - 90 - 120 = 150'),
          prose('That interior angle has an exterior angle of $30^\\circ$, and the exterior angles add to $360^\\circ$:'),
          maths('360 \\div 30 = 12'),
        ),
        ask('cm-missing-angle+choice', 2),
        askAfter(
          'cm-polygon-seen-angle',
          2,
          prose('Across several sides, add a share for each. In a regular decagon each side is seen at $18^\\circ$, so $\\angle CAF$, across $CD$, $DE$ and $EF$, is'),
          maths('3 \\times 18 = 54'),
        ),
        askAfter('cm-polygons-meet', 2, prose('Four or more polygons work the same way: take every angle you know from $360^\\circ$.')),
      ],
      skillCheck: [ask('cm-star-tips', 2), ask('cm-polygon-seen-angle+choice', 2), ask('cm-missing-angle', 2)],
    },
    {
      id: 'cm-l4-special-triangles',
      title: 'Special Right Triangles',
      slides: [
        teach(
          prose('Two right triangles come up so often that their sides are worth knowing by heart.'),
          prose('Half a square, cut along its diagonal, has angles $45^\\circ$, $45^\\circ$, $90^\\circ$. With legs of $5$:'),
          maths('d^2 = 5^2 + 5^2 = 50'),
          maths('d = \\sqrt{50} = 5\\sqrt{2}'),
          prose('Half an equilateral triangle of side $2$ has angles $30^\\circ$, $60^\\circ$, $90^\\circ$, a hypotenuse of $2$ and a shorter leg of $1$. The longer leg is'),
          maths('\\sqrt{2^2 - 1^2} = \\sqrt{3}'),
          prose('So the sides run $1 : 1 : \\sqrt{2}$ and $1 : \\sqrt{3} : 2$. Type $5\\sqrt{2}$ as 5√(2), with the √( key.'),
        ),
        ask('cm-square-diagonal'),
        ask('cm-thirty-sixty'),
        ask('cm-thirty-sixty-tiles'),
        askAfter(
          'cm-square-diagonal+choice',
          2,
          prose('A square’s area needs no root. With a diagonal of $10$, Pythagoras gives the side squared straight away:'),
          maths('2s^2 = 10^2 = 100'),
          maths('s^2 = 50'),
          prose('and $s^2$ is the area.'),
        ),
        teach(
          prose('An equilateral triangle of side $6$ splits down its height into two $30^\\circ$-$60^\\circ$-$90^\\circ$ triangles with hypotenuse $6$ and shorter leg $3$. The height is $3\\sqrt{3}$, and the area is'),
          maths('\\tfrac{1}{2} \\times 6 \\times 3\\sqrt{3} = 9\\sqrt{3}'),
          prose('Whole-number right triangles are usually a Pythagorean triple in disguise: $3, 4, 5$, $5, 12, 13$, $8, 15, 17$, $7, 24, 25$. Legs of $15$ and $36$ are $3 \\times 5$ and $3 \\times 12$, so the hypotenuse is'),
          maths('3 \\times 13 = 39'),
        ),
        ask('cm-equilateral-height'),
        ask('cm-triple-scale+choice'),
        askAfter(
          'cm-thirty-sixty+choice',
          2,
          prose('Given the longer leg, divide by $\\sqrt{3}$, then multiply top and bottom by $\\sqrt{3}$ to clear the root from the bottom. A longer leg of $12$:'),
          maths('\\frac{12}{\\sqrt{3}} = \\frac{12\\sqrt{3}}{3} = 4\\sqrt{3}'),
          prose('The hypotenuse is twice that, $8\\sqrt{3}$.'),
        ),
        askAfter('cm-equilateral-height', 2, prose('The area is half the side times the height. Given the perimeter, divide it by $3$ for the side first.')),
        askAfter(
          'cm-triple-scale',
          2,
          prose('For a missing leg, spot the triple from the hypotenuse. A hypotenuse of $52$ and a leg of $20$ are $4 \\times 13$ and $4 \\times 5$, so the other leg is'),
          maths('4 \\times 12 = 48'),
        ),
      ],
      skillCheck: [ask('cm-thirty-sixty', 2), ask('cm-equilateral-height+choice', 2), ask('cm-triple-scale', 2)],
    },
    {
      id: 'cm-l4-right-triangles',
      title: 'Creating Right Triangles',
      slides: [
        teach(
          prose('No right angle in the picture? Make one. Drop a perpendicular, and the shape falls into right triangles.'),
          prose('A triangle with sides $13$, $13$ and $10$: the perpendicular from the top halves the base, making a right triangle with hypotenuse $13$ and base $5$:'),
          maths('h^2 = 13^2 - 5^2 = 144'),
          maths('h = 12'),
          maths('\\text{area} = \\tfrac{1}{2} \\times 10 \\times 12 = 60'),
        ),
        ask('cm-isosceles-area'),
        askAfter(
          'cm-trapezium-area',
          1,
          prose('An isosceles trapezium with parallel sides $6$ and $16$ and slanted sides of $13$: perpendiculars from the ends of the top side cut off'),
          maths('(16 - 6) \\div 2 = 5'),
          prose('at each end, so the height is $12$, from the $5, 12, 13$ triangle.'),
        ),
        askAfter(
          'cm-isosceles-area+choice',
          2,
          prose('A rhombus’s diagonals cross at right angles and cut each other in half. Sides of $13$ and a diagonal of $10$ make right triangles with hypotenuse $13$ and leg $5$, so half the other diagonal is $12$ and the whole of it $24$:'),
          maths('\\text{area} = \\tfrac{1}{2} \\times 10 \\times 24 = 120'),
        ),
        teach(
          prose('A triangle with sides $13$, $14$ and $15$: drop the height onto the $14$, cutting it into $x$ next to the $13$ and $y$ next to the $15$. Both right triangles share the height:'),
          maths('13^2 - x^2 = 15^2 - y^2'),
          maths('y^2 - x^2 = 225 - 169 = 56'),
          prose('A difference of two squares is $(y + x)(y - x)$, and the two pieces make up the $14$:'),
          maths('y + x = 14'),
          maths('y - x = 56 \\div 14 = 4'),
          prose('So $x = 5$ and $y = 9$, and the height is $12$ from either triangle.'),
        ),
        askAfter(
          'cm-wide-angle',
          1,
          prose('Given two sides and the angle between them, drop a perpendicular from the end of one side onto the other. Sides of $8$ and $10$ with $30^\\circ$ between them: the $10$ is the hypotenuse of a $30^\\circ$-$60^\\circ$-$90^\\circ$ triangle, so the height is half of it, $5$:'),
          maths('\\text{area} = \\tfrac{1}{2} \\times 8 \\times 5 = 20'),
        ),
        ask('cm-glued-triangles'),
        ask('cm-glued-triangles-table'),
        askAfter(
          'cm-wide-angle+choice',
          2,
          prose('With $150^\\circ$ between the sides, the perpendicular lands outside the triangle, on the base extended. The angle there is $30^\\circ$, so the height is still half the slanted side.'),
        ),
        askAfter(
          'cm-trapezium-area+choice',
          2,
          prose('A trapezium’s area is the mean of its parallel sides times the height. For the one with sides $6$, $16$ and $13$:'),
          maths('\\tfrac{1}{2}(6 + 16) \\times 12 = 132'),
        ),
        askAfter(
          'cm-glued-triangles',
          2,
          prose('With the height found, the area is half the base times the height. For $13$, $14$, $15$:'),
          maths('\\tfrac{1}{2} \\times 14 \\times 12 = 84'),
        ),
      ],
      skillCheck: [ask('cm-isosceles-area', 2), ask('cm-wide-angle', 2), ask('cm-glued-triangles', 2)],
    },
  ],
  levelCheck: [
    ask('cm-floor-tiles', 2),
    ask('cm-four-rectangles', 2),
    ask('cm-strip-square+choice', 2),
    ask('cm-parallel-bend', 2),
    ask('cm-isosceles-chain', 2),
    ask('cm-isosceles-cases', 2),
    ask('cm-star-tips', 2),
    ask('cm-polygon-seen-angle', 2),
    ask('cm-missing-angle+choice', 2),
    ask('cm-thirty-sixty', 2),
    ask('cm-square-diagonal', 2),
    ask('cm-triple-scale', 2),
    ask('cm-trapezium-area', 2),
    ask('cm-glued-triangles', 2),
  ],
};
