/**
 * Contest Math, Level 16: Finding and Counting Factors. A step on from
 * Level 10: the largest k with N a perfect k-th power is the HCF of its
 * powers, a digit product packs into the largest digits, unique factorisation
 * turns an equation of powers into two equations; a common divisor divides
 * the difference, the pairs with a given LCM count 2e + 1 a prime, equal
 * remainders shift a multiple of the LCM; divisors pair d with N/d, so only
 * squares have an odd count, the product of the divisors is N to half the
 * count, and the divisors of N² pair around N.
 * Generators in `generators/contestFactors.ts`.
 */
import type { Level } from '../../types';
import { teach, ask, prose, maths, askAfter } from './blocks';

export const countingFactors: Level = {
  id: 'cm-l16',
  title: 'Finding and Counting Factors',
  lessons: [
    {
      id: 'cm-l16-prime-factorization',
      title: 'Prime Factorization',
      slides: [
        teach(
          prose('Every whole number above 1 is a product of primes in exactly one way, and many contest questions are answered by reading the powers.'),
          prose('When is $N$ a perfect $k$-th power, $m^{k}$? Each power in $m^{k}$ is $k$ times a power in $m$, so every power in $N$ must be a multiple of $k$. The largest $k$ is the HCF of the powers:'),
          maths('N = 2^{12} \\times 3^{18} \\times 5^{30}'),
          maths('\\text{HCF}(12, 18, 30) = 6'),
          maths('N = (2^{2} \\times 3^{3} \\times 5^{5})^{6}'),
          prose('So $k = 6$. The smallest power, $12$, is the trap: 12 does not divide 18.'),
        ),
        ask('cm-fc-perfect-power'),
        askAfter(
          'cm-fc-perfect-power+choice',
          2,
          prose('With composite bases, factorise first. The powers as written can mislead:'),
          maths('8^{2} \\times 18^{3} = 2^{6} \\times 2^{3} \\times 3^{6}'),
          maths('= 2^{9} \\times 3^{6}'),
          prose('The HCF of 9 and 6 is 3, though the written powers 2 and 3 share nothing:'),
          maths('8^{2} \\times 18^{3} = (2^{3} \\times 3^{2})^{3} = 72^{3}'),
        ),
        askAfter(
          'cm-fc-digit-product',
          1,
          prose('The smallest number whose digits multiply to $360$: fewer digits make a smaller number, so pack the primes into the largest digits. Take out 9s first, then 8s, and so on down:'),
          maths('360 = 2^{3} \\times 3^{2} \\times 5'),
          maths('360 = 9 \\times 8 \\times 5'),
          prose('Smallest digit first gives $589$. Using the primes as digits, $222335$, is the trap.'),
        ),
        teach(
          prose('Because the factorisation is unique, the powers of each prime on the two sides of an equation must match. Find $a$ and $b$ when'),
          maths('4^{a} \\times 6^{b} = 2^{10} \\times 3^{4}'),
          prose('Write $4 = 2^{2}$ and $6 = 2 \\times 3$. Only the 6s bring 3s, and the 2s come from both:'),
          maths('b = 4'),
          maths('2a + b = 10'),
          maths('2a = 6'),
          prose('So $a = 3$ and $b = 4$. Reading the powers straight off, $a = 10$, is the trap.'),
        ),
        ask('cm-fc-exponent-match'),
        ask('cm-fc-exponent-match-tiles'),
        askAfter(
          'cm-fc-exponent-match+choice',
          2,
          prose('When both bases are composite, both letters appear in both equations, so take one from the other:'),
          maths('6^{a} \\times 12^{b} = 2^{8} \\times 3^{5}'),
          maths('a + 2b = 8'),
          maths('a + b = 5'),
          prose('Subtracting leaves $b = 3$, and then $a = 2$.'),
        ),
        askAfter(
          'cm-fc-digit-product+choice',
          2,
          prose('Leftover primes still pack: two 2s make a 4, and a 2 with a 3 makes a 6. For $864$, take out a 9 and an 8, leaving 12:'),
          maths('864 = 9 \\times 8 \\times 12'),
          prose('$12$ is $6 \\times 2$ or $4 \\times 3$, two digits either way. Taking the 6 first leaves the smaller leading digit:'),
          maths('864 = 9 \\times 8 \\times 6 \\times 2'),
          prose('So the number is $2689$, not $3489$. Splitting 12 into three digits, $22389$, costs a digit.'),
        ),
        askAfter(
          'cm-fc-root-table',
          1,
          prose('Roots come straight from the powers, so never multiply out. Factorise each number and add the powers:'),
          maths('N = 12 \\times 18 \\times 24'),
          maths('N = 2^{6} \\times 3^{4}'),
          prose('Every power is even, so $N$ is a square. Halve the powers:'),
          maths('\\sqrt{N} = 2^{3} \\times 3^{2} = 72'),
          prose('For a cube root, divide each power by 3 instead.'),
        ),
      ],
      skillCheck: [ask('cm-fc-perfect-power', 2), ask('cm-fc-exponent-match', 2), ask('cm-fc-digit-product', 2)],
    },
    {
      id: 'cm-l16-gcd-lcm',
      title: 'GCD/LCM',
      slides: [
        teach(
          prose('Write $\\gcd(a, b)$ for the greatest common divisor of $a$ and $b$. Any common divisor of two numbers also divides their difference, so large numbers close together are quick:'),
          maths('4047 - 4009 = 38'),
          maths('\\gcd(4009, 4047) = \\gcd(4009, 38)'),
          prose('Do it again: take as many 38s from 4009 as will go, and only the remainder matters:'),
          maths('4009 = 105 \\times 38 + 19'),
          maths('\\gcd(38, 19) = 19'),
          prose('So the answer is $19$. The difference, $38$, is the trap: $4009$ is odd.'),
        ),
        ask('cm-fc-euclid'),
        askAfter(
          'cm-fc-euclid+choice',
          2,
          prose('The same subtraction works on numbers one less than a power:'),
          maths('(2^{12} - 1) - 2^{4}(2^{8} - 1) = 2^{4} - 1'),
          prose('So the exponents are taken from each other exactly as in Euclid’s algorithm:'),
          maths('\\gcd(2^{12} - 1, 2^{8} - 1) = 2^{\\gcd(12, 8)} - 1'),
          maths('2^{4} - 1 = 15'),
        ),
        askAfter(
          'cm-fc-remainder-lcm',
          1,
          prose('A number leaves remainder 1 when divided by 4, 6 and 9, and is a multiple of 7. Take the 1 away and it divides by all three, so it is 1 more than a multiple of their LCM:'),
          maths('\\text{LCM}(4, 6, 9) = 36'),
          maths('N = 36k + 1'),
          prose('Try $k = 1, 2, 3, \\ldots$ until $N$ is a multiple of 7:'),
          maths('37, 73, 109, 145, 181, 217'),
          maths('217 = 7 \\times 31'),
        ),
        teach(
          prose('How many ordered pairs $(a, b)$ have lowest common multiple $72$? Factorise it and take one prime at a time:'),
          maths('72 = 2^{3} \\times 3^{2}'),
          prose('Each of $a$ and $b$ has the 2 from $0$ to $3$ times, and at least one has all $3$. That is four pairs with $a$ at 3, four with $b$ at 3, and the pair with both at 3 counted twice:'),
          maths('4 + 4 - 1 = 7'),
          prose('In general a power $e$ gives $2e + 1$ pairs. The 3s give $5$, so'),
          maths('7 \\times 5 = 35'),
          prose('Counting the divisors of 72, $12$, is the trap.'),
        ),
        ask('cm-fc-lcm-pairs'),
        ask('cm-fc-lcm-pairs-table'),
        askAfter(
          'cm-fc-lcm-pairs+choice',
          2,
          prose('Unordered pairs $a \\le b$: of the $35$ ordered pairs with LCM 72, only $(72, 72)$ has the two equal. The other $34$ come in swapped twos:'),
          maths('\\frac{35 - 1}{2} + 1 = 18'),
        ),
        askAfter(
          'cm-fc-gcd-sum',
          1,
          prose('A gcd and a sum. Take'),
          maths('a + b = 120, \\qquad \\gcd(a, b) = 10'),
          prose('Write $a = 10x$ and $b = 10y$, where $x$ and $y$ share no factor:'),
          maths('x + y = 12'),
          prose('A factor of $x$ and 12 would also divide $y = 12 - x$, so $x$ shares no factor with 12. With $x < y$ that leaves $x = 1$ or $x = 5$: two pairs, $(10, 110)$ and $(50, 70)$. Counting all five splits is the trap.'),
        ),
        askAfter(
          'cm-fc-remainder-lcm+choice',
          2,
          prose('When each remainder is one less than its divisor, add 1 instead. Remainder 3 on division by 4, 4 by 5 and 5 by 6 makes $N + 1$ a multiple of all three:'),
          maths('N = 60k - 1'),
          prose('For a multiple of 7, try $k = 1, 2, \\ldots$:'),
          maths('59, 119'),
          maths('119 = 7 \\times 17'),
        ),
        ask('cm-fc-gcd-sum+choice', 2),
      ],
      skillCheck: [ask('cm-fc-euclid', 2), ask('cm-fc-lcm-pairs', 2), ask('cm-fc-gcd-sum', 2)],
    },
    {
      id: 'cm-l16-counting-factors',
      title: 'Counting Factors',
      slides: [
        teach(
          prose('Divisors come in pairs: $d$ goes with $n \\div d$. For $36$:'),
          maths('1 \\times 36, \\qquad 2 \\times 18, \\qquad 3 \\times 12, \\qquad 4 \\times 9, \\qquad 6 \\times 6'),
          prose('Only $6$ pairs with itself, so $36$ has $9$ divisors, an odd number. A number has an odd count of divisors exactly when it is a perfect square.'),
          prose('So from 1 to 50 the numbers with an odd count are the squares $1^{2}$ to $7^{2}$: $7$ of them, not the $25$ odd numbers.'),
        ),
        ask('cm-fc-few-divisors'),
        askAfter(
          'cm-fc-divisor-product',
          1,
          prose('The pairs also give the product of all the divisors. The divisors of $12$ pair as $1 \\times 12$, $2 \\times 6$ and $3 \\times 4$, three pairs each making 12:'),
          maths('1 \\times 2 \\times 3 \\times 4 \\times 6 \\times 12 = 12^{3}'),
          prose('So a number that is not a square, with $t$ divisors, has divisor product $N^{t/2}$.'),
        ),
        askAfter(
          'cm-fc-few-divisors+choice',
          2,
          prose('Exactly 3 divisors: an odd count, so a square, and $p^{2}$ for a prime $p$ has just $1$, $p$ and $p^{2}$. A square like $36$ has more. Up to $200$, count the primes with $p^{2} \\le 200$:'),
          maths('14^{2} = 196 \\le 200 < 225 = 15^{2}'),
          maths('2, 3, 5, 7, 11, 13'),
          prose('That is $6$ numbers, not the $14$ squares.'),
        ),
        askAfter(
          'cm-fc-divisor-product+choice',
          2,
          prose('With $N$ in prime powers, raise each power to $t/2$. For'),
          maths('N = 2^{3} \\times 3'),
          prose('the number of divisors is'),
          maths('(3 + 1)(1 + 1) = 8'),
          maths('N^{4} = 2^{12} \\times 3^{4}'),
          prose('so the power of 2 in the product is $12$. Forgetting to halve gives $24$.'),
        ),
        teach(
          prose('A divisor of $N$ that is a multiple of $m$ is $m$ times a divisor of $N \\div m$. For the divisors of $720$ that are multiples of $12$:'),
          maths('720 = 2^{4} \\times 3^{2} \\times 5'),
          maths('720 \\div 12 = 60 = 2^{2} \\times 3 \\times 5'),
          maths('(2 + 1)(1 + 1)(1 + 1) = 12'),
          prose('Prime by prime, with $12$ written as $2^{2} \\times 3$: a multiple of 12 takes the 2 from 2 to 4 times, $3$ choices, the 3 once or twice, $2$ choices, and the 5 none or once, $2$ choices.'),
        ),
        ask('cm-fc-multiple-divisors'),
        ask('cm-fc-multiple-divisors-table'),
        askAfter(
          'cm-fc-square-pairs',
          1,
          prose('Divisors of $N^{2}$ pair around $N$: $d$ goes with $N^{2} \\div d$, one below $N$ and one above, except $N$ itself. For $N = 12$:'),
          maths('144 = 2^{4} \\times 3^{2}'),
          maths('(4 + 1)(2 + 1) = 15'),
          maths('\\frac{15 - 1}{2} = 7'),
          prose('So $7$ divisors of $144$ are below $12$.'),
        ),
        askAfter(
          'cm-fc-square-pairs+choice',
          2,
          prose('Of those $7$, the divisors of $12$ itself below $12$ are $1, 2, 3, 4, 6$. So only $8$ and $9$ do not divide $12$. In general take off one less than the number of divisors of $N$:'),
          maths('7 - (6 - 1) = 2'),
        ),
        askAfter(
          'cm-fc-multiple-divisors+choice',
          2,
          prose('A power of a composite number needs factorising first:'),
          maths('12^{4} = (2^{2} \\times 3)^{4} = 2^{8} \\times 3^{4}'),
        ),
      ],
      skillCheck: [ask('cm-fc-divisor-product', 2), ask('cm-fc-square-pairs', 2), ask('cm-fc-multiple-divisors', 2)],
    },
  ],
  levelCheck: [
    ask('cm-fc-perfect-power', 2),
    ask('cm-fc-digit-product+choice', 2),
    ask('cm-fc-exponent-match', 2),
    ask('cm-fc-root-table', 2),
    ask('cm-fc-euclid+choice', 2),
    ask('cm-fc-lcm-pairs', 2),
    ask('cm-fc-gcd-sum+choice', 2),
    ask('cm-fc-remainder-lcm', 2),
    ask('cm-fc-few-divisors', 2),
    ask('cm-fc-divisor-product+choice', 2),
    ask('cm-fc-square-pairs', 2),
    ask('cm-fc-multiple-divisors+choice', 2),
  ],
};
