/**
 * Contest Math, Level 5: Similarity and Scaling. Similar triangles found in a
 * parallel line, an hourglass, a right triangle's altitude and a shadow;
 * lengths, areas and volumes scaled; and coordinate geometry. Generators in
 * `generators/contestSimilarity.ts`.
 */
import type { Level } from '../../types';
import { teach, ask, prose, maths, askAfter } from './blocks';

export const similarityScaling: Level = {
  id: 'cm-l5',
  title: 'Similarity and Scaling',
  lessons: [
    {
      id: 'cm-l5-similarity',
      title: 'Similarity',
      slides: [
        teach(
          prose('Two triangles are **similar** when they have the same angles. Then every side of one is the same multiple of the matching side of the other.'),
          prose('Draw $DE$ parallel to $BC$, with $D$ on $AB$ and $E$ on $AC$. Triangle $ADE$ shares the angle at $A$ with $ABC$, and the parallel lines make the other angles equal, so the two are similar.'),
          prose('With $AD = 3$, $DB = 6$ and $BC = 12$, compare with the **whole** side $AB$:'),
          maths('AB = 3 + 6 = 9'),
          maths('DE = 12 \\times \\tfrac{3}{9} = 4'),
          prose('Using $AD : DB = 3 : 6$ gives $6$, the trap: $DB$ is not a side of the small triangle.'),
        ),
        ask('cm-parallel-cut'),
        askAfter(
          'cm-similar-table',
          1,
          prose('Similar triangles side by side: find the scale factor from one matching pair, then multiply. Small sides $4, 6, 8$ and a large shortest side of $6$ give a factor of'),
          maths('6 \\div 4 = \\tfrac{3}{2}'),
          maths('6 \\times \\tfrac{3}{2} = 9'),
          maths('8 \\times \\tfrac{3}{2} = 12'),
          prose('Adding $2$ to every side is the trap: similar shapes multiply, they do not add.'),
        ),
        askAfter(
          'cm-parallel-cut+choice',
          2,
          prose('Going the other way: $AD = 4$, $DE = 6$ and $BC = 15$. The whole side $AB$ is $AD$ scaled up by $BC \\div DE$:'),
          maths('AB = 4 \\times \\tfrac{15}{6} = 10'),
          maths('DB = 10 - 4 = 6'),
        ),
        teach(
          prose('The **hourglass**: $AB$ is parallel to $CD$, and the lines $AD$ and $BC$ cross at $X$. The angles at $X$ are vertically opposite and the parallel lines make the alternate angles equal, so triangles $ABX$ and $DCX$ are similar.'),
          maths('AX : XD = AB : CD'),
          prose('With $AB = 4$, $CD = 6$ and $AX = 6$:'),
          maths('XD = 6 \\times \\tfrac{6}{4} = 9'),
          prose('Every side is multiplied by the scale factor, so the **perimeter** is too. Sides $3, 4, 5$ scaled to a perimeter of $36$: the factor is $36 \\div 12 = 3$, and the longest side is $15$.'),
        ),
        ask('cm-hourglass'),
        ask('cm-similar-perimeter'),
        askAfter(
          'cm-hourglass+choice',
          2,
          prose('Given the whole of $AD$, share it in the ratio $AB : CD$. With $AB = 2$, $CD = 3$ and $AD = 20$, there are $5$ parts:'),
          maths('AX = 20 \\times \\tfrac{2}{5} = 8'),
        ),
        askAfter(
          'cm-similar-perimeter+choice',
          2,
          prose('Sides $3, 4, 5$, and a similar triangle whose longest side is $10$ longer. That side is $15$, so the factor is'),
          maths('15 \\div 5 = 3'),
          maths('\\text{perimeter} = 12 \\times 3 = 36'),
          prose('Adding $10$ to the perimeter, to get $22$, is the trap.'),
        ),
        askAfter('cm-similar-table', 2, prose('Going from the large triangle to the small one, divide by the scale factor instead of multiplying.')),
      ],
      skillCheck: [ask('cm-parallel-cut', 2), ask('cm-hourglass', 2), ask('cm-similar-perimeter', 2)],
    },
    {
      id: 'cm-l5-scaling',
      title: 'Scaling',
      slides: [
        teach(
          prose('Multiply every length by $k$ and areas are multiplied by $k^2$, volumes by $k^3$. A percentage change on every length is a multiplier too.'),
          prose('Each side of a square goes up by $20\\%$, a multiplier of $1.2$. Its area is multiplied by'),
          maths('1.2^2 = 1.44'),
          prose('so the area rises by $44\\%$, not $40\\%$: the $20\\%$ is applied twice, the second time to a bigger square.'),
          prose('Going down works the same way. A cut of $20\\%$ multiplies by $0.8$:'),
          maths('0.8^2 = 0.64'),
          prose('so the area falls by $36\\%$.'),
        ),
        ask('cm-scale-percent'),
        askAfter(
          'cm-statue-weight',
          1,
          prose('Weight goes with volume. A solid statue $3$ m tall weighs $5400$ kg. A copy $1$ m tall has every length a third as long, so'),
          maths('5400 \\div 3^3 = 5400 \\div 27 = 200'),
          prose('kilograms. Dividing by $3$ is the trap.'),
        ),
        askAfter(
          'cm-scale-percent+choice',
          2,
          prose('Volumes cube the multiplier. Every edge of a cube up by $10\\%$:'),
          maths('1.1^3 = 1.331'),
          prose('a rise of $33.1\\%$. Every edge down by $10\\%$:'),
          maths('0.9^3 = 0.729'),
          prose('a fall of $27.1\\%$.'),
        ),
        teach(
          prose('A map with scale $1 : 50\\,000$ shows $1$ cm for every $50\\,000$ cm on the ground, which is $0.5$ km.'),
          prose('A square centimetre on the map is a square $0.5$ km each way on the ground:'),
          maths('0.5^2 = 0.25 \\text{ km}^2'),
          prose('So a wood covering $8\\text{ cm}^2$ of the map is'),
          maths('8 \\times 0.25 = 2 \\text{ km}^2'),
          prose('Going back, from the ground to the map, divide by $0.25$ instead.'),
        ),
        ask('cm-map-area'),
        ask('cm-map-tiles'),
        askAfter(
          'cm-statue-weight+choice',
          2,
          prose('When neither height divides the other, use the ratio. Heights $2 : 3$ give weights $2^3 : 3^3 = 8 : 27$, so a $16$ g figure has a larger twin of'),
          maths('16 \\times \\tfrac{27}{8} = 54'),
          prose('grams.'),
        ),
        ask('cm-map-area+choice', 2),
        ask('cm-map-tiles', 2),
      ],
      skillCheck: [ask('cm-scale-percent', 2), ask('cm-statue-weight', 2), ask('cm-map-area', 2)],
    },
    {
      id: 'cm-l5-exploring',
      title: 'Exploring Similarity',
      slides: [
        teach(
          prose('Triangle $ABC$ has a right angle at $C$. Drop the altitude $CD$ to the hypotenuse $AB$. It makes two smaller right triangles, $ACD$ and $CBD$, and each shares an angle with $ABC$, so **all three are similar**.'),
          prose('Matching their sides gives three rules:'),
          maths('CD^2 = AD \\times DB'),
          maths('AC^2 = AD \\times AB'),
          maths('BC^2 = DB \\times AB'),
          prose('With $AD = 9$ and $DB = 16$, $AB = 25$:'),
          maths('CD^2 = 9 \\times 16 = 144'),
          maths('AC^2 = 9 \\times 25 = 225'),
          maths('BC^2 = 16 \\times 25 = 400'),
          prose('So $CD = 12$, $AC = 15$ and $BC = 20$.'),
        ),
        ask('cm-altitude-hyp'),
        ask('cm-altitude-tiles'),
        askAfter(
          'cm-altitude-hyp+choice',
          2,
          prose('The rules work backwards too. With $AD = 4$ and $CD = 6$:'),
          maths('6^2 = 4 \\times DB'),
          maths('DB = 36 \\div 4 = 9'),
        ),
        teach(
          prose('Triangles with the **same height** have areas in the ratio of their bases. Write $[ABD]$ for the area of triangle $ABD$.'),
          prose('$D$ is on $BC$ with $BD : DC = 2 : 3$, and $[ABC] = 40$. Triangles $ABD$ and $ABC$ share the height from $A$, so compare $BD$ with the whole of $BC$:'),
          maths('[ABD] = 40 \\times \\tfrac{2}{5} = 16'),
          prose('Now put $E$ on $AB$ with $AE : EB = 1 : 3$. Triangles $EBD$ and $ABD$ share the height from $D$, so compare $EB$ with $AB$:'),
          maths('[EBD] = 16 \\times \\tfrac{3}{4} = 12'),
        ),
        ask('cm-shared-height'),
        askAfter(
          'cm-trapezium',
          1,
          prose('A trapezium $ABCD$ with $AB$ parallel to $DC$ has diagonals crossing at $X$. Triangles $ABX$ and $CDX$ make an hourglass, so they are similar with factor $DC \\div AB$, and areas go by its square.'),
          prose('With $AB = 2$, $DC = 3$ and $[ABX] = 8$:'),
          maths('[DCX] = 8 \\times \\tfrac{9}{4} = 18'),
        ),
        ask('cm-shared-height+choice', 2),
        askAfter(
          'cm-trapezium+choice',
          2,
          prose('The other two pieces: triangles $ABX$ and $ADX$ share the height from $A$, and their bases are $BX : XD = 2 : 3$. So in the trapezium above'),
          maths('[ADX] = 8 \\times \\tfrac{3}{2} = 12'),
          prose('and $[BCX] = 12$ in the same way. The whole trapezium is'),
          maths('8 + 18 + 12 + 12 = 50'),
        ),
        ask('cm-altitude-tiles', 2),
      ],
      skillCheck: [ask('cm-altitude-hyp', 2), ask('cm-shared-height', 2), ask('cm-trapezium', 2)],
    },
    {
      id: 'cm-l5-applying',
      title: 'Applying Similarity',
      slides: [
        teach(
          prose('Similar triangles measure things you cannot reach.'),
          prose('**Shadows.** The sun’s rays are parallel, so at one moment every upright thing and its shadow make the same shape of triangle. A $2$ m post casts a $3$ m shadow, and a tree a $12$ m shadow. The tree’s shadow is $4$ times as long, so the tree is'),
          maths('2 \\times 4 = 8'),
          prose('metres tall.'),
          prose('**Mirrors.** Light leaves a mirror at the same angle it arrives. Eyes $1.5$ m up, standing $2$ m from a mirror that is $20$ m from a building: the building’s triangle is $10$ times as big, so it is'),
          maths('1.5 \\times 10 = 15'),
          prose('metres tall.'),
        ),
        ask('cm-shadow-height'),
        ask('cm-shadow-table'),
        ask('cm-mirror-height'),
        askAfter(
          'cm-shadow-height+choice',
          2,
          prose('A lamp post is different: its rays spread out, so compare with the whole ground from the post to the tip of the shadow. Jo is $1.6$ m tall, $3$ m from the post, with a $2$ m shadow:'),
          maths('3 + 2 = 5'),
          maths('\\text{post} = 1.6 \\times \\tfrac{5}{2} = 4'),
        ),
        teach(
          prose('**Crossed wires.** Poles of heights $a$ and $b$ stand some distance apart, with a wire from the top of each to the foot of the other. Say the wires cross at height $h$, a distance $x$ from the first pole, with the poles $g$ apart. Each wire gives a pair of similar triangles:'),
          maths('\\frac{h}{a} = \\frac{g - x}{g}'),
          maths('\\frac{h}{b} = \\frac{x}{g}'),
          prose('Add them and the distances cancel:'),
          maths('\\frac{h}{a} + \\frac{h}{b} = 1'),
          prose('So the height does not depend on how far apart the poles are. For poles of $6$ m and $12$ m:'),
          maths('\\frac{1}{h} = \\frac{1}{6} + \\frac{1}{12} = \\frac{1}{4}'),
          maths('h = 4'),
        ),
        ask('cm-crossed-poles'),
        askAfter(
          'cm-mirror-height+choice',
          2,
          prose('To find where to stand, turn the ratio round. Eyes $1.5$ m up, a $15$ m building and a mirror $20$ m from it:'),
          maths('\\text{distance} = 20 \\times \\tfrac{1.5}{15} = 2'),
        ),
        askAfter(
          'cm-crossed-poles+choice',
          2,
          prose('Going back from the crossing height: $h = 4$ and one pole is $6$ m.'),
          maths('\\frac{1}{b} = \\frac{1}{4} - \\frac{1}{6} = \\frac{1}{12}'),
          maths('b = 12'),
        ),
        askAfter('cm-shadow-table', 2, prose('When the stick’s height and shadow are not a whole multiple of each other, simplify the ratio first, then scale each row by it.')),
      ],
      skillCheck: [ask('cm-shadow-height', 2), ask('cm-mirror-height', 2), ask('cm-crossed-poles', 2)],
    },
    {
      id: 'cm-l5-coordinates',
      title: 'Coordinate Geometry',
      slides: [
        teach(
          prose('**Distance** is Pythagoras. From $(1, 2)$ to $(7, 10)$ is $6$ across and $8$ up:'),
          maths('\\sqrt{6^2 + 8^2} = \\sqrt{100} = 10'),
          prose('The **midpoint** is the average of the coordinates. A parallelogram’s diagonals cut each other in half, so $AC$ and $BD$ share a midpoint, and'),
          maths('A + C = B + D'),
          prose('With $A = (1, 1)$, $B = (5, 2)$ and $C = (6, 5)$:'),
          maths('D = A + C - B'),
          maths('D = (1 + 6 - 5, 1 + 5 - 2) = (2, 4)'),
        ),
        ask('cm-coord-distance'),
        ask('cm-parallelogram-vertex'),
        askAfter(
          'cm-collinear',
          1,
          prose('Points on a straight line: equal steps across give equal steps up. For $(1, 3)$, $(4, 9)$ and $(7, k)$ the steps across are both $3$, and the first step up is'),
          maths('9 - 3 = 6'),
          maths('k = 9 + 6 = 15'),
        ),
        askAfter(
          'cm-coord-distance+choice',
          2,
          prose('Going back: $(1, 2)$ and $(6, k)$ are $13$ apart, with $k > 2$. Across is $5$, so'),
          maths('\\text{up}^2 = 13^2 - 5^2 = 144'),
          maths('\\text{up} = 12'),
          maths('k = 2 + 12 = 14'),
        ),
        teach(
          prose('**Area from coordinates.** One way is to box the shape in a rectangle and take off the right triangles round it. Triangle $(0, 0)$, $(4, 1)$, $(1, 3)$ sits in a $4 \\times 3$ box, and the three corner triangles are'),
          maths('\\tfrac{1}{2} \\times 4 \\times 1 = 2'),
          maths('\\tfrac{1}{2} \\times 3 \\times 2 = 3'),
          maths('\\tfrac{1}{2} \\times 1 \\times 3 = 1.5'),
          prose('Take them off the box:'),
          maths('12 - 2 - 3 - 1.5 = 5.5'),
          prose('The **shoelace** method always works. Go round the corners in order and for each corner and the next work out $x_1 y_2 - x_2 y_1$:'),
          maths('0 \\times 1 - 4 \\times 0 = 0'),
          maths('4 \\times 3 - 1 \\times 1 = 11'),
          maths('1 \\times 0 - 0 \\times 3 = 0'),
          prose('Add them and halve: $\\tfrac{1}{2} \\times 11 = 5.5$.'),
        ),
        ask('cm-coord-area'),
        askAfter(
          'cm-collinear+choice',
          2,
          prose('When the steps across are not equal, use the gradient. For $(2, 1)$, $(5, 3)$ and $(11, k)$ the gradient is $\\tfrac{2}{3}$, and from $x = 5$ to $x = 11$ is $6$ across:'),
          maths('6 \\times \\tfrac{2}{3} = 4'),
          maths('k = 3 + 4 = 7'),
          prose('Adding the first rise of $2$ again, to get $5$, is the trap.'),
        ),
        askAfter(
          'cm-parallelogram-vertex',
          2,
          prose('Given the centre $M$ where the diagonals cross: it is the midpoint of $AC$, so go from $A$ to $M$ and the same again. With $A = (1, 2)$ and $M = (4, 5)$:'),
          maths('C = 2M - A = (8 - 1, 10 - 2) = (7, 8)'),
          prose('$D = 2M - B$ in the same way.'),
        ),
        askAfter('cm-coord-area+choice', 2, prose('The shoelace works for a quadrilateral too: take its four corners in order round the shape and add four terms instead of three.')),
      ],
      skillCheck: [ask('cm-coord-distance', 2), ask('cm-collinear', 2), ask('cm-coord-area', 2)],
    },
  ],
  levelCheck: [
    ask('cm-parallel-cut', 2),
    ask('cm-similar-table', 2),
    ask('cm-hourglass+choice', 2),
    ask('cm-scale-percent', 2),
    ask('cm-statue-weight', 2),
    ask('cm-map-area+choice', 2),
    ask('cm-altitude-hyp', 2),
    ask('cm-trapezium', 2),
    ask('cm-shadow-height', 2),
    ask('cm-crossed-poles', 2),
    ask('cm-parallelogram-vertex', 2),
    ask('cm-coord-area', 2),
  ],
};
