/**
 * Contest Math, Level 23: Contest Problem Strategies. The last level, about
 * how to start rather than what to know: split into cases, look at the worst
 * case or at what never changes, try small cases until a pattern shows, use a
 * symmetry, let the options do the work, and simplify before calculating.
 * Generators in `generators/contestStrategies.ts`.
 */
import type { Level } from '../../types';
import { teach, ask, prose, maths, askAfter } from './blocks';

export const problemStrategies: Level = {
  id: 'cm-l23',
  title: 'Contest Problem Strategies',
  lessons: [
    {
      id: 'cm-l23-casework',
      title: 'Casework',
      slides: [
        teach(
          prose('Casework: when one question is really several, split it on one choice, count each case, and add. Pick the split that makes every case easy.'),
          prose('Triangles with whole-number sides and a perimeter of $12$: split on the longest side $c$. The other two add to $12 - c$ and must be longer together than $c$, so $c < 6$; being the longest, $c$ is at least $4$.'),
          maths('c = 4: \\ (4, 4, 4)'),
          maths('c = 5: \\ (5, 5, 2), \\ (5, 4, 3)'),
          prose('So there are $3$ triangles. Fixing the longest side first is what stops $(5, 4, 3)$ and $(3, 4, 5)$ being counted as two.'),
        ),
        ask('cm-st-triangles'),
        askAfter(
          'cm-st-abs-regions',
          1,
          prose('Absolute values split the number line. For $|x - 1| + |x - 5| = 8$, cut at $1$ and $5$. Below $1$ both brackets turn round:'),
          maths('(1 - x) + (5 - x) = 8, \\qquad x = -1'),
          prose('Between $1$ and $5$ the $x$ cancels:'),
          maths('(x - 1) + (5 - x) = 4'),
          prose('That is never $8$, so no solution there. Above $5$:'),
          maths('(x - 1) + (x - 5) = 8, \\qquad x = 7'),
        ),
        askAfter(
          'cm-st-triangles+choice',
          2,
          prose('All three sides different: the middle side must now be less than $c$ and more than the shortest. For a perimeter of $12$ only $(5, 4, 3)$ is left.'),
        ),
        ask('cm-st-abs-regions', 2),
        teach(
          prose('Split on the last digit. The last digit of $n^2$ depends only on the last digit of $n$, and $n^2$ ends in $9$ only when $n$ ends in $3$ or $7$.'),
          prose('From $1$ to $45$ those are $3, 13, 23, 33, 43$ and $7, 17, 27, 37$:'),
          maths('5 + 4 = 9'),
          prose('Or split on one variable. For positive whole numbers with $x + 2y \\le 9$, take each $y$ in turn:'),
          maths('y = 1: \\ x \\le 7, \\qquad y = 2: \\ x \\le 5, \\qquad y = 3: \\ x \\le 3, \\qquad y = 4: \\ x \\le 1'),
          maths('7 + 5 + 3 + 1 = 16'),
        ),
        ask('cm-st-case-table'),
        ask('cm-st-square-ends'),
        askAfter(
          'cm-st-case-table',
          2,
          prose('With $2x$ in place of $x$, halve what is left and round down: $2x \\le 7$ allows $x = 1, 2, 3$.'),
        ),
        askAfter(
          'cm-st-square-ends+choice',
          2,
          prose('For $n^2 + n = n(n + 1)$, list the last digits the same way. For $n$ ending in $0$ to $9$, it ends in'),
          maths('0, 2, 6, 2, 0, 0, 2, 6, 2, 0'),
          prose('so it ends in $6$ only when $n$ ends in $2$ or $7$.'),
        ),
      ],
      skillCheck: [ask('cm-st-triangles', 2), ask('cm-st-case-table', 2), ask('cm-st-square-ends+choice', 2)],
    },
    {
      id: 'cm-l23-extremes',
      title: 'Extreme Cases and Invariants',
      slides: [
        teach(
          prose('Extreme cases: to be sure of something, imagine the unluckiest possible run, then add one.'),
          prose('A drawer has $2$ red, $10$ blue and $10$ green socks. To be sure of $4$ of one colour, the worst case holds both red socks, $3$ blue and $3$ green:'),
          maths('2 + 3 + 3 + 1 = 9'),
          prose('Largest sets work the same way. From $1$ to $12$, choose numbers with no two adding to $11$. The pairs $(1, 10), (2, 9), \\ldots, (5, 6)$ allow one each, and $11$ and $12$ have no partner (nor would half the total, if it were whole):'),
          maths('5 + 2 = 7'),
        ),
        ask('cm-st-socks-table'),
        ask('cm-st-pair-sum'),
        ask('cm-st-socks-table', 2),
        askAfter(
          'cm-st-pair-sum+choice',
          2,
          prose('To be sure of a pair, choose one more than the largest safe set.'),
          prose('When the total is bigger than the top number plus one, the pairs start higher. From $1$ to $10$ with a total of $15$ they are $(5, 10), (6, 9), (7, 8)$, and $1$ to $4$ are all safe, so $3 + 4 = 7$ can avoid a pair and $8$ make sure.'),
        ),
        teach(
          prose('Invariants: when a process is too long to follow, find something it never changes.'),
          prose('The numbers $1$ to $10$ are on a board. A move replaces two numbers $a$ and $b$ by $a + b - 1$, so every move lowers the total by exactly $1$. The total starts at $55$ and there are $9$ moves, so the last number is'),
          maths('55 - 9 = 46'),
          prose('Parity is the commonest invariant. $6$ cups stand upside down and each move turns exactly $4$. Every cup needs an odd number of turns, so the turns beyond one each come in pairs, and no cup can be turned more often than there are moves.'),
          prose('Two moves give $8$ turns, but then each cup is turned once, which is only $6$. Three moves give $12$: three cups turned three times and three turned once. So $3$ moves.'),
        ),
        ask('cm-st-board'),
        ask('cm-st-cups+choice'),
        askAfter(
          'cm-st-board+choice',
          2,
          prose('A rule like $ab + a + b$ hides a product: it is $(a + 1)(b + 1) - 1$. Add $1$ to every number and a move just multiplies two of them, so the product of all the numbers plus $1$ never changes. From $1, 2, 3$:'),
          maths('2 \\times 3 \\times 4 = 24'),
          prose('so the last number is $23$.'),
        ),
        ask('cm-st-cups', 2),
      ],
      skillCheck: [ask('cm-st-pair-sum', 2), ask('cm-st-cups', 2), ask('cm-st-board', 2)],
    },
    {
      id: 'cm-l23-generalization',
      title: 'Generalization',
      slides: [
        teach(
          prose('Generalise: when a question names a big number, try $1$, $2$ and $3$ first, find the pattern, then see why it holds.'),
          prose('Lines on a page, no two parallel and no three through a point: $1$ line makes $2$ regions, $2$ make $4$, $3$ make $7$. The $n$-th line crosses all the earlier ones, so it passes through $n$ regions and adds $n$:'),
          maths('f(n) = 1 + (1 + 2 + \\cdots + n)'),
          maths('f(10) = 1 + 55 = 56'),
        ),
        ask('cm-st-pattern-table'),
        askAfter(
          'cm-st-alt-squares',
          1,
          prose('Small cases of $1^2 - 2^2 + 3^2 - \\cdots$ give $1, -3, 6, -10$: triangular numbers, with signs. Pairing shows why:'),
          maths('1^2 - 2^2 = -(1 + 2)'),
          maths('3^2 - 4^2 = -(3 + 4)'),
          prose('so up to an even last term the sum is minus the sum of every number used.'),
        ),
        ask('cm-st-pattern-table', 2),
        askAfter(
          'cm-st-alt-squares+choice',
          2,
          prose('With an odd last term, pair everything before it, then add the last square back:'),
          maths('1^2 - 2^2 + 3^2 = -3 + 9 = 6'),
        ),
        teach(
          prose('Positions in a run. In $1, 2, 2, 3, 3, 3, \\ldots$ the last copy of $k$ sits at position $1 + 2 + \\cdots + k$. For term $20$:'),
          maths('1 + 2 + \\cdots + 5 = 15'),
          maths('1 + 2 + \\cdots + 6 = 21'),
          prose('Positions $16$ to $21$ hold $6$, so term $20$ is $6$.'),
          prose('A circle of $n$ people where every second one leaves: small cases give the last person $1, 1, 3, 1, 3, 5, 7, 1$ for $n = 1$ to $8$. It is $1$ at each power of $2$ and climbs by $2$ after it, so for $n$ a power of $2$ plus $L$ it is $2L + 1$. For $12$ people:'),
          maths('12 = 8 + 4, \\qquad 2 \\times 4 + 1 = 9'),
        ),
        ask('cm-st-nth-term'),
        ask('cm-st-josephus'),
        askAfter(
          'cm-st-nth-term+choice',
          2,
          prose('If each $k$ appears $2k - 1$ times, the last copy of $k$ sits at'),
          maths('1 + 3 + \\cdots + (2k - 1) = k^2'),
          prose('and if it appears $2k$ times, at'),
          maths('2 + 4 + \\cdots + 2k = k(k + 1)'),
        ),
        ask('cm-st-josephus+choice', 2),
      ],
      skillCheck: [ask('cm-st-alt-squares', 2), ask('cm-st-nth-term', 2), ask('cm-st-josephus', 2)],
    },
    {
      id: 'cm-l23-symmetry',
      title: 'Using Symmetry',
      slides: [
        teach(
          prose('Symmetry can turn a bent path straight. To walk from $A$ to a straight river and on to $B$, reflect $B$ in the bank: each walk to $B$ is as long as the same walk to the reflection, and the shortest of those is a straight line.'),
          prose('With $A$ $3$ m from the bank, $B$ $5$ m from it, and the nearest points of the bank $6$ m apart, the straight line is $6$ across and $3 + 5 = 8$ down:'),
          maths('\\sqrt{6^2 + 8^2} = \\sqrt{100} = 10'),
        ),
        ask('cm-st-river'),
        ask('cm-st-river-tiles'),
        askAfter(
          'cm-st-river+choice',
          2,
          prose('The line to the reflection meets the bank where the right triangles either side are similar, so it splits the $6$ m in the ratio of the heights, $3 : 5$:'),
          maths('\\frac{3}{8} \\times 6 = \\frac{9}{4}'),
        ),
        ask('cm-st-river-tiles', 2),
        teach(
          prose('Pair terms that mirror each other. Take'),
          maths('f(x) = \\frac{4^x}{4^x + 2}'),
          prose('Multiplying the top and bottom of $f(1 - x)$ by $4^x$ gives'),
          maths('f(1 - x) = \\frac{2}{2 + 4^x}'),
          maths('f(x) + f(1 - x) = 1'),
          prose('So $f(\\tfrac{1}{5}) + f(\\tfrac{2}{5}) + f(\\tfrac{3}{5}) + f(\\tfrac{4}{5})$ is two pairs, $2$.'),
          prose('Equal gaps: pick $2$ different numbers from $1$ to $8$ at random and put markers at $0$ and $9$. The picks cut the stretch into $3$ gaps adding to $9$, and swapping two gaps gives another pick just as likely, so each gap averages $3$. The smaller pick is $3$ on average.'),
        ),
        ask('cm-st-pair-function'),
        ask('cm-st-gap-min'),
        askAfter('cm-st-pair-function+choice', 2, prose('A term with no mirror image in the sum, such as $f(1)$, is worked out on its own and added on.')),
        askAfter(
          'cm-st-gap-min+choice',
          2,
          prose('The second smallest pick sits two gaps from $0$, and the largest one gap below the top marker. With $3$ picks from $1$ to $11$ the $4$ gaps average $3$, so the largest averages $9$.'),
        ),
      ],
      skillCheck: [ask('cm-st-river', 2), ask('cm-st-pair-function', 2), ask('cm-st-gap-min', 2)],
    },
    {
      id: 'cm-l23-eliminating',
      title: 'Eliminating Choices',
      slides: [
        teach(
          prose('With options to pick from, you often need not work the answer out: rule out the ones that cannot be right.'),
          prose('Last digits: $4827 \\times 356$ ends in the last digit of $7 \\times 6 = 42$, so any option not ending in $2$ is out.'),
          prose('Squares only end in $0, 1, 4, 5, 6$ or $9$, so a number ending in $2, 3, 7$ or $8$ is never a square.'),
          prose('Size: two consecutive numbers that multiply to $3782$ sit either side of its square root.'),
          maths('61^2 = 3721, \\qquad 62^2 = 3844'),
          prose('So they are $61$ and $62$, and $1 \\times 2$ ends in $2$, as $3782$ does.'),
        ),
        ask('cm-st-product-elim'),
        ask('cm-st-square-elim'),
        ask('cm-st-consecutive-product'),
        askAfter(
          'cm-st-product-elim',
          2,
          prose('When every option ends in the same digit, use digit sums, taken down to one digit: a product’s matches the product of its factors’.'),
          prose('$4827 \\to 21 \\to 3$ and $356 \\to 14 \\to 5$, and $3 \\times 5 = 15 \\to 6$, so the digit sum of $4827 \\times 356$ must come to $6$.'),
        ),
        teach(
          prose('Test the options when solving is slow. Which of $38, 41, 44, 47$ leaves a remainder of $2$ on division by $3$ and of $3$ on division by $5$? Their remainders:'),
          maths('38: \\ 2, 3, \\qquad 41: \\ 2, 1, \\qquad 44: \\ 2, 4, \\qquad 47: \\ 2, 2'),
          prose('Only $38$ passes both; checking the first condition alone would leave all four.'),
          prose('Square roots: $5329$ is a square.'),
          maths('70^2 = 4900, \\qquad 80^2 = 6400'),
          prose('So its root is in the $70$s, and since $5329$ ends in $9$ the root ends in $3$ or $7$. Halfway,'),
          maths('75^2 = 5625'),
          prose('is too big, so the root is $73$.'),
        ),
        ask('cm-st-remainder-elim'),
        ask('cm-st-root-table'),
        askAfter(
          'cm-st-square-elim',
          2,
          prose('The digit sum of a square, taken down to one digit, is always $1$, $4$, $7$ or $9$. So $1936 \\to 19 \\to 1$ passes (it is $44^2$), but $1946 \\to 20 \\to 2$ cannot be a square.'),
        ),
        askAfter(
          'cm-st-consecutive-product',
          2,
          prose('Three consecutive numbers multiply to just under the cube of the middle one. For $9240$:'),
          maths('21^3 = 9261'),
          prose('so the numbers are $20, 21$ and $22$.'),
        ),
        askAfter('cm-st-remainder-elim', 2, prose('With three conditions, an option can pass two and still fail the third: test all three.')),
      ],
      skillCheck: [ask('cm-st-product-elim', 2), ask('cm-st-square-elim', 2), ask('cm-st-consecutive-product', 2)],
    },
    {
      id: 'cm-l23-simplifications',
      title: 'Simplifications',
      slides: [
        teach(
          prose('Simplify before you calculate. In a fraction of huge powers, take the smallest power out of the top and the bottom:'),
          maths('\\frac{2^{2027} + 2^{2025}}{2^{2026} - 2^{2024}} = \\frac{2^{2024}(8 + 2)}{2^{2024}(4 - 1)}'),
          maths('= \\frac{10}{3}'),
          prose('Or name a number. With $x = 2025$:'),
          maths('2024 \\times 2026 = x^2 - 1'),
          maths('2023 \\times 2027 = x^2 - 4'),
          maths('(x^2 - 1) - (x^2 - 4) = 3'),
        ),
        ask('cm-st-power-fraction'),
        ask('cm-st-name-number'),
        askAfter(
          'cm-st-power-fraction+choice',
          2,
          prose('Different bases? Write them all as powers of one: $4 = 2^2$, so'),
          maths('4^{1012} = 2^{2024}'),
        ),
        askAfter(
          'cm-st-name-number+choice',
          2,
          prose('Pairs that are not centred still work when both pairs add to the same total. Call the smallest number $x = 2020$:'),
          maths('2020 \\times 2027 = x(x + 7) = x^2 + 7x'),
          maths('2022 \\times 2025 = (x + 2)(x + 5) = x^2 + 7x + 10'),
          prose('so the first product minus the second is $-10$.'),
        ),
        teach(
          prose('Expressions that treat $a$ and $b$ alike can be found from $a + b$ and $ab$, without finding $a$ and $b$. Squaring $a + b$ gives $a^2 + b^2$ plus $2ab$:'),
          maths('a^2 + b^2 = (a + b)^2 - 2ab'),
          maths('\\frac{1}{a} + \\frac{1}{b} = \\frac{a + b}{ab}'),
          prose('With $a + b = 5$ and $ab = 3$:'),
          maths('a^2 + b^2 = 25 - 6 = 19, \\qquad \\frac{1}{a} + \\frac{1}{b} = \\frac{5}{3}'),
        ),
        ask('cm-st-sym-sum-tiles'),
        ask('cm-st-sym-sum'),
        askAfter(
          'cm-st-sym-sum-tiles',
          2,
          prose('Cubing works the same way:'),
          maths('(a + b)^3 = a^3 + b^3 + 3ab(a + b)'),
          maths('a^3 + b^3 = (a + b)^3 - 3ab(a + b)'),
        ),
        askAfter(
          'cm-st-sym-sum+choice',
          2,
          prose('Over a common denominator:'),
          maths('\\frac{a}{b} + \\frac{b}{a} = \\frac{a^2 + b^2}{ab}'),
        ),
      ],
      skillCheck: [ask('cm-st-power-fraction', 2), ask('cm-st-name-number', 2), ask('cm-st-sym-sum', 2)],
    },
  ],
  levelCheck: [
    ask('cm-st-triangles', 2),
    ask('cm-st-square-ends+choice', 2),
    ask('cm-st-pair-sum', 2),
    ask('cm-st-cups+choice', 2),
    ask('cm-st-board', 2),
    ask('cm-st-josephus', 2),
    ask('cm-st-alt-squares+choice', 2),
    ask('cm-st-river+choice', 2),
    ask('cm-st-pair-function', 2),
    ask('cm-st-product-elim', 2),
    ask('cm-st-remainder-elim', 2),
    ask('cm-st-power-fraction', 2),
    ask('cm-st-sym-sum', 2),
  ],
};
