/**
 * Contest Math, Level 22: More Advanced Probability. A step past Level 8:
 * probability as an area, chances that shrink one at a time, "exactly" as a
 * difference of "at most"s; conditioning by picturing a crowd and by weighing
 * the evidence; expected values read forwards, backwards and from the tail;
 * answers written in terms of themselves; indicators that add however they
 * depend on each other; and states that remember only what matters.
 * Generators in `generators/contestAdvancedProbability.ts`.
 */
import type { Level } from '../../types';
import { teach, ask, prose, maths, askAfter } from './blocks';

/** A 6 by 6 square of points (x, y), the corner where x + y < 4 shaded. */
const SQUARE_SVG = [
  '<svg viewBox="0 0 300 215" width="100%" role="img" aria-label="A square from 0 to 6 on both axes, with the triangle below the line x plus y equals 4 shaded">',
  '<path class="plot-shade" d="M 90 185 L 196.7 185 L 90 78.3 Z" />',
  '<path d="M 90 25 L 250 25 L 250 185 L 90 185 Z" fill="none" stroke="currentColor" stroke-width="2" />',
  '<line x1="196.7" y1="185" x2="90" y2="78.3" stroke="currentColor" stroke-width="2" stroke-dasharray="5 4" />',
  '<text x="90" y="202" font-size="13" fill="currentColor" text-anchor="middle">0</text>',
  '<text x="196.7" y="202" font-size="13" fill="currentColor" text-anchor="middle">4</text>',
  '<text x="250" y="202" font-size="13" fill="currentColor" text-anchor="middle">6</text>',
  '<text x="76" y="82" font-size="13" fill="currentColor" text-anchor="middle">4</text>',
  '<text x="76" y="29" font-size="13" fill="currentColor" text-anchor="middle">6</text>',
  '<text x="270" y="189" font-size="13" fill="currentColor" text-anchor="middle" font-style="italic">x</text>',
  '<text x="90" y="14" font-size="13" fill="currentColor" text-anchor="middle" font-style="italic">y</text>',
  '<text x="126" y="171" font-size="13" fill="currentColor" text-anchor="middle"><tspan font-style="italic">x</tspan> + <tspan font-style="italic">y</tspan> &lt; 4</text>',
  '</svg>',
].join('');

export const advancedProbability: Level = {
  id: 'cm-l22',
  title: 'More Advanced Probability',
  lessons: [
    {
      id: 'cm-l22-probability',
      title: 'Probability',
      slides: [
        teach(
          prose('Two numbers are chosen at random between 0 and 6. Together they are one point $(x, y)$ in a 6 by 6 square, and every point is equally likely, so a probability is an **area** over the area of the square.'),
          prose('Their sum is less than 4 in the corner triangle below the line through $(4, 0)$ and $(0, 4)$:'),
          { kind: 'diagram', svg: SQUARE_SVG },
          maths('\\text{triangle} = \\frac{1}{2} \\times 4 \\times 4 = 8'),
          maths('P = \\frac{8}{36} = \\frac{2}{9}'),
          prose('The trap is $\\tfrac{4}{12}$, reading the sum as equally likely to be anything from 0 to 12. Sums near 6 have far more room than sums near 0.'),
        ),
        ask('cm-ap-geom-square'),
        askAfter(
          'cm-ap-birthday',
          1,
          prose('**All different**: take them one at a time and multiply the shrinking chances. Three people each pick a whole number from 1 to 10. The second must miss 1 number, the third must miss 2:'),
          maths('\\frac{10}{10} \\times \\frac{9}{10} \\times \\frac{8}{10} = \\frac{18}{25}'),
          prose('At least two the same is everything else:'),
          maths('1 - \\frac{18}{25} = \\frac{7}{25}'),
          prose('Adding a chance of $\\tfrac{1}{10}$ for each of the 3 pairs gives $\\tfrac{3}{10}$, the trap: it counts all three matching more than once.'),
        ),
        askAfter(
          'cm-ap-geom-square+choice',
          2,
          prose('Two numbers between 0 and 10 **differ by less than** 4 everywhere except two corner triangles, away from the diagonal, each with short sides 6. Slid together the two make a 6 by 6 square:'),
          maths('P = 1 - \\frac{6^2}{10^2} = 1 - \\frac{36}{100} = \\frac{16}{25}'),
          prose('Two friends arriving between 12:00 and 1:00, each waiting 20 minutes, is the same square with side 60: they meet unless their times differ by 20 or more.'),
          maths('P = 1 - \\frac{40^2}{60^2} = \\frac{5}{9}'),
          prose('The trap is $\\tfrac{20}{60}$, as if only one of them were random.'),
        ),
        ask('cm-ap-birthday+choice', 2),
        teach(
          prose('**Exactly** is hard to count; **at most** is easy. Two dice: the largest is at most 4 when both are, 16 outcomes. Take away the 9 where both are at most 3, which never reach 4:'),
          maths('4^2 - 3^2 = 16 - 9 = 7'),
          maths('P(\\text{largest} = 4) = \\frac{7}{36}'),
          prose('The trap is $\\tfrac{1}{6}$: the largest is not equally likely to be each number, since 6 is the largest far more often than 1.'),
          prose('The smallest works from the top instead. The smallest is at least 3 when both dice show 3 to 6, which is 4 choices each:'),
          maths('4^2 - 3^2 = 7'),
          maths('P(\\text{smallest} = 3) = \\frac{7}{36}'),
        ),
        ask('cm-ap-dice-max'),
        askAfter(
          'cm-ap-dice-max-table',
          1,
          prose('Set the counts out row by row: at most $j$ is $j$ choices on every die, and exactly $j$ is that count less the one in the row above it.'),
        ),
        askAfter(
          'cm-ap-dice-max+choice',
          2,
          prose('**Smallest 2 and largest 5** on three dice: count every die from 2 to 5, take off those with no 2 and those with no 5, and add back the ones with neither, which were taken off twice:'),
          maths('4^3 - 2 \\times 3^3 + 2^3'),
          maths('= 64 - 54 + 8 = 18'),
          maths('P = \\frac{18}{216} = \\frac{1}{12}'),
        ),
        ask('cm-ap-dice-max-table', 2),
      ],
      skillCheck: [ask('cm-ap-geom-square', 2), ask('cm-ap-birthday', 2), ask('cm-ap-dice-max', 2)],
    },
    {
      id: 'cm-l22-conditional',
      title: 'Conditional Probability',
      slides: [
        teach(
          prose('To condition on a test result, **picture a crowd** and count it. In a town 5% of people have a condition. A test is positive for 90% of those who have it, and for 10% of those who do not.'),
          prose('Picture 1000 people: 50 have it and 950 do not.'),
          maths('50 \\times 90\\% = 45'),
          maths('950 \\times 10\\% = 95'),
          prose('So 140 people test positive, and only 45 of them have the condition:'),
          maths('P = \\frac{45}{140} = \\frac{9}{28}'),
          prose('The trap is $\\tfrac{9}{10}$: that is the chance of a positive test given the condition, the question turned the wrong way round. The 950 who are well swamp the few who are not.'),
        ),
        ask('cm-ap-test-bayes'),
        askAfter(
          'cm-ap-test-table',
          1,
          prose('The same crowd fits a two-way table: a row for each group, a column for each result. Each row splits by its own percentage, and each row adds up to its group.'),
        ),
        askAfter(
          'cm-ap-test-bayes+choice',
          2,
          prose('**Two tests**, independent for each person, both positive: picture 10000 people so the counts stay whole. With the numbers above, 500 have the condition and 9500 do not.'),
          maths('500 \\times 90\\% \\times 90\\% = 405'),
          maths('9500 \\times 10\\% \\times 10\\% = 95'),
          maths('P = \\frac{405}{405 + 95} = \\frac{81}{100}'),
          prose('Each positive result multiplies both counts by its own rate, so a second test sharpens the answer.'),
        ),
        askAfter(
          'cm-ap-cond-pair',
          1,
          prose('**Given at least one**: a bag holds 4 red and 3 blue counters, and two are taken out. Keep every pair with at least one red, which is all of them less the pairs with none:'),
          maths('\\binom{7}{2} - \\binom{3}{2} = 21 - 3 = 18'),
          prose('Both red is 6 of those, the pairs from the 4 red:'),
          maths('\\binom{4}{2} = 6'),
          maths('P = \\frac{6}{18} = \\frac{1}{3}'),
          prose('The trap is $\\tfrac{3}{6}$: that is the answer given that the **first** counter is red, which tells you more than "at least one".'),
        ),
        teach(
          prose('**Weigh by the evidence.** A bag holds 2 fair coins and 1 two-headed coin. One is taken at random and tossed twice: heads both times. Multiply along each path:'),
          maths('P(\\text{two-headed, 2 heads}) = \\frac{1}{3} \\times 1 = \\frac{1}{3}'),
          maths('P(\\text{fair, 2 heads}) = \\frac{2}{3} \\times \\frac{1}{4} = \\frac{1}{6}'),
          prose('Given the heads, only these two paths are left, in the ratio $2 : 1$:'),
          maths('P(\\text{two-headed}) = \\frac{2}{3}'),
          prose('The trap is $\\tfrac{1}{3}$, which ignores the tosses. The chance that the next toss is heads too uses the new weights:'),
          maths('\\frac{2}{3} \\times 1 + \\frac{1}{3} \\times \\frac{1}{2} = \\frac{5}{6}'),
        ),
        ask('cm-ap-coin-bag'),
        askAfter(
          'cm-ap-cond-pair+choice',
          2,
          prose('Three counters from 4 red and 3 blue, **given at least two red**: exactly two red (with one blue), or three red.'),
          maths('\\binom{4}{2} \\times 3 + \\binom{4}{3} = 18 + 4 = 22'),
          maths('P(\\text{all red}) = \\frac{4}{22} = \\frac{2}{11}'),
        ),
        ask('cm-ap-coin-bag+choice', 2),
        ask('cm-ap-test-table', 2),
      ],
      skillCheck: [ask('cm-ap-test-bayes', 2), ask('cm-ap-coin-bag', 2), ask('cm-ap-cond-pair', 2)],
    },
    {
      id: 'cm-l22-expected',
      title: 'Expected Value',
      slides: [
        teach(
          prose('An **expected value** adds each value times its chance: the average over a great many tries.'),
          prose('20 raffle tickets: 1 wins £30 and 4 win £5. Over all 20 tickets the prizes add to'),
          maths('30 \\times 1 + 5 \\times 4 = 50'),
          maths('E = \\frac{50}{20} = 2.5'),
          prose('Read it backwards to find a missing prize. A spinner has 10 equal sectors: 2 pay the top prize, 3 pay £4, the rest nothing, and the expected payout is £3.20. Over 10 spins, one on each sector:'),
          maths('10 \\times 3.2 = 32'),
          maths('32 - 3 \\times 4 = 20'),
          maths('\\text{prize} = 20 \\div 2 = 10'),
        ),
        ask('cm-ap-ev-table'),
        ask('cm-ap-ev-missing'),
        askAfter(
          'cm-ap-ev-missing+choice',
          2,
          prose('A **fair game** has an expected payout equal to its cost. A game costs £2 and pays a prize on a total of 11 with two dice, which is 2 of the 36 outcomes:'),
          maths('\\text{prize} \\times \\frac{2}{36} = 2'),
          maths('\\text{prize} = 2 \\times 18 = 36'),
          prose('The trap is £22, from treating the 11 totals as equally likely.'),
        ),
        ask('cm-ap-ev-table', 2),
        teach(
          prose('**The largest of several** by symmetry. Two tickets are drawn from tickets numbered 1 to 11. Put fences at 0 and 12: the two numbers cut the space into three gaps that add up to 12, and no gap is favoured over another, so each is 4 on average.'),
          maths('E(\\text{smallest}) = 4, \\qquad E(\\text{largest}) = 12 - 4 = 8'),
          prose('With $k$ tickets from 1 to $n$ there are $k + 1$ gaps, each averaging'),
          maths('\\frac{n + 1}{k + 1}'),
          prose('The trap for the largest is $n$ itself, or the plain average $\\tfrac{n + 1}{2}$.'),
        ),
        ask('cm-ap-ev-max'),
        askAfter(
          'cm-ap-ev-respin',
          1,
          prose('**Should you spin again?** A fresh spin is worth its average, so keep what beats it. A spinner marked 1, 4, 7 and 8 averages 5. You may spin once more but must then keep it: keep a 7 or 8, spin again after a 1 or 4.'),
          maths('E = \\frac{7 + 8}{4} + \\frac{2}{4} \\times 5 = \\frac{25}{4}'),
        ),
        askAfter(
          'cm-ap-ev-max+choice',
          2,
          prose('**Tail chances.** A whole-number score has expected value'),
          maths('P(\\ge 1) + P(\\ge 2) + P(\\ge 3) + \\cdots'),
          prose('since a score of 3 is counted in exactly three of them. The smaller of two dice is at least $j$ when both are:'),
          maths('E(\\text{smaller}) = \\frac{36 + 25 + 16 + 9 + 4 + 1}{36} = \\frac{91}{36}'),
          prose('Turn both dice over, $a$ to $7 - a$, and the smaller becomes the larger:'),
          maths('E(\\text{larger}) = 7 - \\frac{91}{36} = \\frac{161}{36}'),
          prose('Dice can repeat, so the ticket formula does not apply here.'),
        ),
        askAfter(
          'cm-ap-ev-respin+choice',
          2,
          prose('**Three spins**: work backwards. With the spinner 1, 4, 7, 8, a last spin is worth 5, and two spins left are worth $\\tfrac{25}{4}$, as above. On the first spin keep anything above $\\tfrac{25}{4}$:'),
          maths('E = \\frac{7 + 8}{4} + \\frac{2}{4} \\times \\frac{25}{4} = \\frac{55}{8}'),
        ),
      ],
      skillCheck: [ask('cm-ap-ev-missing', 2), ask('cm-ap-ev-max', 2), ask('cm-ap-ev-respin', 2)],
    },
    {
      id: 'cm-l22-recursion',
      title: 'Recursion',
      slides: [
        teach(
          prose('Some answers are easiest written **in terms of themselves**, because after one step the problem starts again.'),
          prose('Roll a die until a six. Call the expected number of rolls $E$. One roll is used, and 5 times in 6 you are back at the start:'),
          maths('E = 1 + \\frac{5}{6}E'),
          maths('\\frac{1}{6}E = 1'),
          maths('E = 6'),
          prose('Ana and Ben take turns rolling, Ana first, and the first six wins. Ana wins at once, or both miss and it all starts again:'),
          maths('P = \\frac{1}{6} + \\frac{5}{6} \\times \\frac{5}{6} \\times P'),
          maths('\\frac{11}{36}P = \\frac{1}{6}'),
          maths('P = \\frac{6}{11}'),
          prose('Going first is worth something, so $\\tfrac{1}{2}$ is the trap.'),
        ),
        ask('cm-ap-wait'),
        ask('cm-ap-first-to-win'),
        askAfter(
          'cm-ap-wait+choice',
          2,
          prose('**Both colours**: a fair die has 2 red faces, 1 blue face and 3 white. Roll until red and blue have both come up. First wait for either colour, 3 of the 6 faces, which takes 2 rolls on average. It is red 2 times in 3, and then blue takes 6 more; if it was blue, red takes 3 more:'),
          maths('E = 2 + \\frac{2}{3} \\times 6 + \\frac{1}{3} \\times 3 = 7'),
          prose('Adding the two separate waits, 3 and 6, to make 9 is the trap: the first coloured face counts towards both.'),
        ),
        askAfter(
          'cm-ap-first-to-win+choice',
          2,
          prose('**Different chances**: Ana needs a six, Ben needs heads on a coin, Ana first.'),
          maths('P = \\frac{1}{6} + \\frac{5}{6} \\times \\frac{1}{2} \\times P'),
          maths('\\frac{7}{12}P = \\frac{1}{6}'),
          maths('P = \\frac{2}{7}'),
        ),
        teach(
          prose('A token starts on square 0 and moves 1 or 2 squares forward, each with probability $\\tfrac{1}{2}$. Write $p_k$ for the chance it lands on square $k$. It reaches $k$ either from $k - 1$ with a 1 or from $k - 2$ with a 2, never both:'),
          maths('p_k = \\frac{1}{2}p_{k-1} + \\frac{1}{2}p_{k-2}'),
          prose('Start from $p_0 = 1$ and $p_1 = \\tfrac{1}{2}$ and build up:'),
          maths('p_2 = \\frac{1}{2} \\times \\frac{1}{2} + \\frac{1}{2} \\times 1 = \\frac{3}{4}'),
          maths('p_3 = \\frac{1}{2} \\times \\frac{3}{4} + \\frac{1}{2} \\times \\frac{1}{2} = \\frac{5}{8}'),
          prose('Other chances work the same way: with $\\tfrac{1}{3}$ for a 1 and $\\tfrac{2}{3}$ for a 2, the rule has those two numbers in front.'),
        ),
        ask('cm-ap-land-on'),
        ask('cm-ap-land-table'),
        askAfter(
          'cm-ap-land-on+choice',
          2,
          prose('**Jumping over** square 3 means landing on 2 and then moving 2, the only way past it:'),
          maths('\\frac{3}{4} \\times \\frac{1}{2} = \\frac{3}{8}'),
          prose('That is $1 - p_3$, as it must be: the token either lands on 3 or jumps over it.'),
        ),
        ask('cm-ap-land-table', 2),
      ],
      skillCheck: [ask('cm-ap-wait', 2), ask('cm-ap-first-to-win', 2), ask('cm-ap-land-on', 2)],
    },
    {
      id: 'cm-l22-linearity',
      title: 'Linearity of Expectation',
      slides: [
        teach(
          prose('**Expected values add**, even when the parts depend on each other. Five tickets are drawn, without putting any back, from tickets numbered 1 to 20. Each ticket drawn, looked at alone, is equally likely to be any of the 20, so it averages'),
          maths('\\frac{1 + 20}{2} = \\frac{21}{2}'),
          maths('E(\\text{total}) = 5 \\times \\frac{21}{2} = \\frac{105}{2}'),
          prose('A **count** is a sum of scores of 1 or 0, one for each thing that might count, so its expected value is the sum of their chances. $n$ people take back hats at random: each gets their own with chance $\\tfrac{1}{n}$, so on average exactly 1 person does, whatever $n$ is.'),
        ),
        ask('cm-ap-draw-sum'),
        askAfter(
          'cm-ap-draw-sum+choice',
          2,
          prose('**Only some faces score.** Three dice score the total of those showing more than 4. One die scores 5, 6 or nothing:'),
          maths('\\frac{5 + 6}{6} = \\frac{11}{6}'),
          maths('E = 3 \\times \\frac{11}{6} = \\frac{11}{2}'),
          prose('The trap is $3 \\times 5.5$, which forgets that most dice score nothing.'),
        ),
        askAfter(
          'cm-ap-distinct',
          1,
          prose('**How many different numbers** on three dice? Score each of the 6 numbers 1 if it comes up. A number is missed by all three dice with probability'),
          maths('\\left(\\frac{5}{6}\\right)^3 = \\frac{125}{216}'),
          maths('E = 6 \\times \\left(1 - \\frac{125}{216}\\right)'),
          maths('= 6 \\times \\frac{91}{216} = \\frac{91}{36}'),
        ),
        askAfter(
          'cm-ap-distinct+choice',
          2,
          prose('**Exactly once**: a number comes up on exactly one of three dice when one die shows it (3 ways to say which) and the other two miss it:'),
          maths('3 \\times \\frac{1}{6} \\times \\left(\\frac{5}{6}\\right)^2 = \\frac{75}{216}'),
          maths('E = 6 \\times \\frac{75}{216} = \\frac{25}{12}'),
        ),
        teach(
          prose('**Neighbours.** 3 boys and 2 girls stand in a line in a random order. Score each of the 4 neighbouring pairs 1 if it is a boy and a girl. The two people in any one pair are a random pair of the 5, and 6 of the 10 pairs are mixed:'),
          maths('\\frac{3 \\times 2}{\\binom{5}{2}} = \\frac{6}{10} = \\frac{3}{5}'),
          maths('E = 4 \\times \\frac{3}{5} = \\frac{12}{5}'),
          prose('Round a table the ends meet, so there are 5 neighbouring pairs, not 4:'),
          maths('E = 5 \\times \\frac{3}{5} = 3'),
        ),
        ask('cm-ap-adjacent'),
        ask('cm-ap-adjacent-tiles'),
        ask('cm-ap-adjacent+choice', 2),
        ask('cm-ap-adjacent-tiles', 2),
      ],
      skillCheck: [ask('cm-ap-draw-sum', 2), ask('cm-ap-distinct', 2), ask('cm-ap-adjacent', 2)],
    },
    {
      id: 'cm-l22-states',
      title: 'Events with States',
      slides: [
        teach(
          prose('**States** keep track of only what matters so far. Roll a die until two sixes come up in a row. Let $T_1$ and $T_2$ be the expected rolls to first reach a run of one six and of two.'),
          maths('T_1 = 6'),
          prose('From a run of one, the next roll is a six, or it breaks the run and the whole run of two must be built again:'),
          maths('T_2 = T_1 + 1 + \\frac{5}{6}T_2'),
          maths('T_2 = 6(T_1 + 1) = 42'),
          prose('The trap is 36, the wait for an event of chance $\\tfrac{1}{36}$: a failed attempt at a run does not cost a fresh pair of rolls. Each step adds 1 and multiplies by 6, so a run of three takes'),
          maths('T_3 = 6(T_2 + 1) = 6 \\times 43 = 258'),
          prose('With a run of one already, the rolls still to come are the second step alone:'),
          maths('T_2 - T_1 = 42 - 6 = 36'),
        ),
        ask('cm-ap-streak'),
        ask('cm-ap-streak-table'),
        askAfter(
          'cm-ap-pattern',
          1,
          prose('**A six, then a non-six**: once a six comes up, nothing is lost. Another six keeps you where you are, and the first non-six finishes. So wait for a six, then for a non-six:'),
          maths('E = 6 + \\frac{6}{5} = \\frac{36}{5}'),
          prose('Far quicker than two sixes in a row, although both patterns have chance $\\tfrac{1}{36}$ at any given place.'),
        ),
        ask('cm-ap-streak+choice', 2),
        teach(
          prose('**The gambler.** Ana has £2 and bets £1 at a time on a fair coin until she has £5 or nothing. Let $P_j$ be her chance of reaching £5 from £$j$, so $P_0 = 0$ and $P_5 = 1$:'),
          maths('P_j = \\frac{1}{2}P_{j+1} + \\frac{1}{2}P_{j-1}'),
          prose('Each $P_j$ is halfway between its neighbours, so they climb in 5 equal steps from 0 to 1, and $P_2 = \\tfrac{2}{5}$.'),
          prose('Now she wins each bet with probability $\\tfrac{2}{3}$, aiming for £3. Split $P_j$ as $\\tfrac{2}{3}P_j + \\tfrac{1}{3}P_j$ and rearrange:'),
          maths('\\frac{2}{3}(P_{j+1} - P_j) = \\frac{1}{3}(P_j - P_{j-1})'),
          prose('Each step up is half the one before, so the three steps from 0 to 1 are in the ratio $4 : 2 : 1$, and'),
          maths('P_1 = \\frac{4}{7}, \\qquad P_2 = \\frac{6}{7}'),
        ),
        ask('cm-ap-ruin'),
        askAfter(
          'cm-ap-pattern+choice',
          2,
          prose('**A race of patterns.** Toss a coin until HH or TH appears. Once a tail comes up, the next head completes TH before HH can happen. So HH wins only if the first two tosses are heads:'),
          maths('P(\\text{HH first}) = \\frac{1}{2} \\times \\frac{1}{2} = \\frac{1}{4}'),
          prose('The trap is $\\tfrac{1}{2}$: the two patterns are equally likely at any one place, but TH is waiting in ambush.'),
        ),
        ask('cm-ap-ruin+choice', 2),
        ask('cm-ap-streak-table', 2),
      ],
      skillCheck: [ask('cm-ap-streak', 2), ask('cm-ap-pattern', 2), ask('cm-ap-ruin', 2)],
    },
  ],
  levelCheck: [
    ask('cm-ap-geom-square', 2),
    ask('cm-ap-birthday+choice', 2),
    ask('cm-ap-dice-max', 2),
    ask('cm-ap-test-bayes', 2),
    ask('cm-ap-coin-bag+choice', 2),
    ask('cm-ap-cond-pair', 2),
    ask('cm-ap-ev-missing', 2),
    ask('cm-ap-ev-respin', 2),
    ask('cm-ap-first-to-win', 2),
    ask('cm-ap-land-on+choice', 2),
    ask('cm-ap-distinct', 2),
    ask('cm-ap-adjacent+choice', 2),
    ask('cm-ap-streak', 2),
    ask('cm-ap-ruin', 2),
  ],
};
