/**
 * Contest Math, Level 18: Synthetic Geometry. The classical results a contest
 * expects without proof: the British flag rule and unfolding, Heron and the
 * inradius, similar triangles from one pair of angles, the angle bisector's
 * split and length, the power of a point, cyclic quadrilaterals with Ptolemy
 * and Brahmagupta, and tangents. Generators in
 * `generators/contestSyntheticGeometry.ts`.
 */
import type { Level } from '../../types';
import { teach, ask, prose, maths, askAfter } from './blocks';

export const syntheticGeometry: Level = {
  id: 'cm-l18',
  title: 'Synthetic Geometry',
  lessons: [
    {
      id: 'cm-l18-pythagoras',
      title: 'Pythagorean Theorem',
      slides: [
        teach(
          prose('**The British flag rule.** Join a point $P$ inside rectangle $ABCD$ to the four corners. Drop perpendiculars from $P$ to the sides: they cut the width into $w_1$ and $w_2$ and the height into $h_1$ and $h_2$, and each line to a corner is a hypotenuse.'),
          maths('PA^{2} = w_1^{2} + h_1^{2}, \\qquad PC^{2} = w_2^{2} + h_2^{2}'),
          maths('PB^{2} = w_2^{2} + h_1^{2}, \\qquad PD^{2} = w_1^{2} + h_2^{2}'),
          prose('Each pair of opposite corners uses all four pieces once, so'),
          maths('PA^{2} + PC^{2} = PB^{2} + PD^{2}'),
          prose('With $PA = 4$, $PB = 5$ and $PC = 6$:'),
          maths('PD^{2} = 16 + 36 - 25 = 27'),
          maths('PD = \\sqrt{27} = 3\\sqrt{3}'),
          prose('Type a surd with the √( key. Adding and taking away the lengths themselves, $5$, is the trap.'),
        ),
        ask('cm-sg-british-flag'),
        askAfter(
          'cm-sg-british-flag+choice',
          2,
          prose('When $PB = PD$, call them both $x$. With $PA = 2$ and $PC = 4$:'),
          maths('2^{2} + 4^{2} = 2x^{2}'),
          maths('x^{2} = 20 \\div 2 = 10'),
          maths('x = \\sqrt{10}'),
          prose('The average of $2$ and $4$, $3$, is the trap.'),
        ),
        askAfter(
          'cm-sg-pole-tiles',
          1,
          prose('A pole $8$ m tall snaps and its top folds over, its tip landing $4$ m from the foot. Let the break be $x$ m up. The fallen part is the rest of the pole, $8 - x$, and it is the hypotenuse:'),
          maths('x^{2} + 4^{2} = (8 - x)^{2}'),
          maths('x^{2} + 16 = 64 - 16x + x^{2}'),
          prose('The $x^{2}$ cancel:'),
          maths('16x = 48'),
          maths('x = 3'),
        ),
        ask('cm-sg-broken-pole'),
        teach(
          prose('**Unfold it.** An ant walks over the outside of a $1 \\times 2 \\times 4$ box from one corner to the opposite one. Unfold the two faces it crosses flat: the path is the diagonal of a rectangle, and there are three ways to pair the edges.'),
          maths('\\sqrt{(1 + 2)^{2} + 4^{2}} = 5'),
          maths('\\sqrt{(1 + 4)^{2} + 2^{2}} = \\sqrt{29}'),
          maths('\\sqrt{(2 + 4)^{2} + 1^{2}} = \\sqrt{37}'),
          prose('The shortest puts the two shorter edges together, so the path is $5$. The straight line through the inside, $\\sqrt{21}$, is not allowed: the ant stays on the surface.'),
        ),
        ask('cm-sg-unfold'),
        askAfter(
          'cm-sg-broken-pole+choice',
          2,
          prose('A rope hangs from the top of a flagpole with $2$ m lying on the ground. Pulled tight, its end reaches $6$ m from the foot. Let the pole be $x$ m, so the rope is $x + 2$:'),
          maths('(x + 2)^{2} = x^{2} + 6^{2}'),
          maths('x^{2} + 4x + 4 = x^{2} + 36'),
          maths('4x = 32'),
          maths('x = 8'),
        ),
        askAfter(
          'cm-sg-unfold+choice',
          2,
          prose('A string wound $3$ times round a cylinder $4$ cm round and $9$ cm tall, climbing evenly. Cut the cylinder down one side and unroll it $3$ times side by side: the string becomes one straight line across a rectangle.'),
          maths('\\text{width} = 3 \\times 4 = 12'),
          maths('\\text{string} = \\sqrt{12^{2} + 9^{2}} = 15'),
          prose('Going round and then up, $21$, is the trap.'),
        ),
        ask('cm-sg-pole-tiles', 2),
      ],
      skillCheck: [ask('cm-sg-british-flag', 2), ask('cm-sg-broken-pole', 2), ask('cm-sg-unfold', 2)],
    },
    {
      id: 'cm-l18-areas',
      title: 'Triangle Areas',
      slides: [
        teach(
          prose('**Heron’s formula** gives a triangle’s area from its three sides, with $s$ half the perimeter:'),
          maths('\\text{area} = \\sqrt{s(s - a)(s - b)(s - c)}'),
          prose('For sides $4$, $13$ and $15$:'),
          maths('s = (4 + 13 + 15) \\div 2 = 16'),
          maths('\\text{area} = \\sqrt{16 \\times 12 \\times 3 \\times 1}'),
          maths('\\text{area} = \\sqrt{576} = 24'),
          prose('Half of two sides multiplied is the trap: that needs a right angle, and this triangle has none.'),
        ),
        ask('cm-sg-heron'),
        ask('cm-sg-heron-table'),
        askAfter(
          'cm-sg-inradius',
          1,
          prose('**The inradius.** Join the centre of the circle inside a triangle to its corners. That makes three triangles, each with a side as its base and the radius $r$ as its height, so'),
          maths('\\text{area} = \\tfrac{1}{2}ar + \\tfrac{1}{2}br + \\tfrac{1}{2}cr = rs'),
          prose('Sides $13$, $14$ and $15$ give $s = 21$ and, by Heron, area $84$:'),
          maths('r = 84 \\div 21 = 4'),
        ),
        askAfter(
          'cm-sg-heron+choice',
          2,
          prose('The area is half a side times the height onto it, whichever side you use. So the longest side has the shortest height. For sides $4$, $13$ and $15$, area $24$:'),
          maths('h = 2 \\times 24 \\div 15 = 3.2'),
        ),
        teach(
          prose('**Extend each side.** Triangle $ABC$ has area $5$. Extend $AB$ past $B$ to $B\'$, $BC$ past $C$ to $C\'$ and $CA$ past $A$ to $A\'$, each by its own length. Write $[XYZ]$ for the area of triangle $XYZ$.'),
          prose("Triangles $BB'C$ and $ABC$ share the height from $C$, and $BB' = AB$:"),
          maths("[BB'C] = [ABC] = 5"),
          prose("Triangles $B'CC'$ and $B'BC$ share the height from $B'$, and $CC' = BC$:"),
          maths("[B'CC'] = [B'BC] = 5"),
          prose('The three outside triangles each come to $10$ the same way:'),
          maths("[A'B'C'] = 5 + 3 \\times 10 = 35"),
          prose("Scaling by $3$ each way, $45$, is the trap: $A'B'C'$ is not the same shape as $ABC$."),
        ),
        ask('cm-sg-extended-sides'),
        askAfter(
          'cm-sg-inradius+choice',
          2,
          prose('Any point inside works the same way. In the $13$, $14$, $15$ triangle, area $84$, a point is $6$ from the side $13$ and $3$ from the side $14$. The three triangles it makes add up to the whole:'),
          maths('\\tfrac{1}{2}(13 \\times 6 + 14 \\times 3 + 15d) = 84'),
          maths('78 + 42 + 15d = 168'),
          maths('15d = 48'),
          maths('d = 3.2'),
        ),
        askAfter(
          'cm-sg-extended-sides+choice',
          2,
          prose("Each side extended by twice its length, from area $1$: now $BB'$ is $2$ times $AB$, and $CC'$ is $2$ times $BC$."),
          maths("[BB'C] = 2 \\times 1 = 2"),
          maths("[B'CC'] = 2 \\times 2 = 4"),
          maths("[A'B'C'] = 1 + 3 \\times 6 = 19"),
        ),
        ask('cm-sg-heron-table', 2),
      ],
      skillCheck: [ask('cm-sg-heron', 2), ask('cm-sg-inradius', 2), ask('cm-sg-extended-sides', 2)],
    },
    {
      id: 'cm-l18-similar',
      title: 'Similar Triangles',
      slides: [
        teach(
          prose('**A square in a triangle.** A triangle has base $12$ and height $6$, and a square of side $s$ stands on the base with its top corners on the other two sides.'),
          prose('Above the square is a small triangle with base $s$ and height $6 - s$. Its base is parallel to the big one’s, so the two are similar:'),
          maths('\\frac{s}{12} = \\frac{6 - s}{6}'),
          maths('6s = 72 - 12s'),
          maths('18s = 72'),
          maths('s = 4'),
          prose('Half the height, $3$, is the trap.'),
        ),
        ask('cm-sg-inscribed-square'),
        askAfter(
          'cm-sg-angle-similar-tiles',
          1,
          prose('**One pair of angles is enough.** $D$ is on $AC$ with $\\angle ABD = \\angle ACB$. Triangles $ABD$ and $ACB$ also share the angle at $A$, so they are similar, $A$ to $A$, $B$ to $C$ and $D$ to $B$:'),
          maths('\\triangle ABD \\sim \\triangle ACB'),
          maths('\\frac{AB}{AC} = \\frac{AD}{AB} = \\frac{BD}{CB}'),
          prose('With $AD = 4$, $DC = 5$ and $BC = 12$, the whole of $AC$ is $9$:'),
          maths('AB^{2} = 4 \\times 9 = 36'),
          maths('AB = 6'),
          maths('BD = 12 \\times \\frac{6}{9} = 8'),
        ),
        ask('cm-sg-angle-similar'),
        askAfter(
          'cm-sg-inscribed-square+choice',
          2,
          prose('A square in the right-angled corner of a right triangle with legs $3$ and $6$: above it is a small right triangle with legs $s$ and $6 - s$, similar to the whole.'),
          maths('\\frac{s}{3} = \\frac{6 - s}{6}'),
          maths('6s = 18 - 3s'),
          maths('9s = 18'),
          maths('s = 2'),
        ),
        teach(
          prose('**Areas go by the square.** $DE$ is parallel to $BC$, with $D$ on $AB$, $E$ on $AC$ and $AD : DB = 2 : 1$. Write $[XYZ]$ for the area of triangle $XYZ$. Then $AD : AB = 2 : 3$, so'),
          maths('[ADE] : [ABC] = 4 : 9'),
          prose('The trapezium $DBCE$ is the difference, $5$ parts. If it has area $25$:'),
          maths('1 \\text{ part} = 25 \\div 5 = 5'),
          maths('[ADE] = 4 \\times 5 = 20'),
          prose('Comparing $AD$ with $DB$ instead of with the whole of $AB$ is the trap.'),
        ),
        ask('cm-sg-parallel-area'),
        askAfter(
          'cm-sg-angle-similar+choice',
          2,
          prose('Backwards: with $AB = 6$ and $AD = 4$, the rule gives $AC$ first.'),
          maths('6^{2} = 4 \\times AC'),
          maths('AC = 36 \\div 4 = 9'),
          maths('DC = 9 - 4 = 5'),
        ),
        askAfter(
          'cm-sg-parallel-area+choice',
          2,
          prose('Backwards from areas: triangle $ADE$ has area $4$ and the trapezium $5$.'),
          maths('[ABC] = 4 + 5 = 9'),
          maths('[ADE] : [ABC] = 4 : 9'),
          prose('Lengths go by the square roots:'),
          maths('AD : AB = 2 : 3'),
          maths('AD : DB = 2 : 1'),
          prose('So $\\frac{AD}{DB} = 2$. The areas themselves, $\\frac{4}{5}$, are the trap.'),
        ),
        ask('cm-sg-angle-similar-tiles', 2),
      ],
      skillCheck: [ask('cm-sg-inscribed-square', 2), ask('cm-sg-angle-similar', 2), ask('cm-sg-parallel-area', 2)],
    },
    {
      id: 'cm-l18-bisector',
      title: 'Angle Bisector Theorem',
      slides: [
        teach(
          prose('**The angle bisector theorem.** The bisector of angle $A$ meets $BC$ at $D$ and splits it in the ratio of the two sides next to $A$:'),
          maths('BD : DC = AB : AC'),
          prose('With $AB = 6$, $AC = 9$ and $BC = 10$, $BD$ takes $6$ of the $15$ parts:'),
          maths('BD = 10 \\times \\frac{6}{15} = 4'),
          prose('$D$ is not the midpoint: $5$ is the trap.'),
        ),
        ask('cm-sg-bisector-split'),
        askAfter(
          'cm-sg-bisector-length',
          1,
          prose('**The bisector’s length** comes from Stewart’s theorem, which for a bisector comes down to one rule:'),
          maths('AD^{2} = AB \\times AC - BD \\times DC'),
          prose('With $AB = 6$, $AC = 8$ and $BC = 7$, split $BC$ first:'),
          maths('BD = 7 \\times \\frac{6}{14} = 3, \\qquad DC = 4'),
          maths('AD^{2} = 48 - 12 = 36'),
          maths('AD = 6'),
        ),
        ask('cm-sg-bisector-tiles'),
        askAfter(
          'cm-sg-bisector-split+choice',
          2,
          prose('From the split back to the sides: $BD = 4$, $DC = 6$ and the perimeter is $25$.'),
          maths('AB : AC = 4 : 6'),
          maths('AB + AC = 25 - 10 = 15'),
          maths('AB = 15 \\times \\frac{4}{10} = 6'),
        ),
        teach(
          prose('**The incentre.** The three bisectors meet at $I$, the centre of the circle inside the triangle. $BI$ bisects angle $B$ of triangle $ABD$, so it splits $AD$ by the same rule:'),
          maths('AI : ID = BA : BD'),
          prose('In the $6$, $9$, $10$ triangle, $BD = 4$:'),
          maths('AI : ID = 6 : 4 = 3 : 2'),
          prose('Put the value of $BD$ in and the rule becomes'),
          maths('AI : ID = (AB + AC) : BC'),
          prose('which here is $15 : 10$ again. The bisector’s own ratio, $6 : 9$, is the trap: that splits $BC$, not $AD$.'),
        ),
        ask('cm-sg-incentre-ratio'),
        askAfter(
          'cm-sg-bisector-length+choice',
          2,
          prose('Backwards from the bisector: $AB = 6$, $AC = 8$ and $AD = 6$. The split is $6 : 8$, so write $BD = 6t$ and $DC = 8t$:'),
          maths('6^{2} = 48 - 48t^{2}'),
          maths('48t^{2} = 12'),
          maths('t = \\frac{1}{2}'),
          maths('BC = 14 \\times \\frac{1}{2} = 7'),
        ),
        askAfter(
          'cm-sg-incentre-ratio+choice',
          2,
          prose('From the ratio to a length: in the $6$, $8$, $7$ triangle the bisector $AD$ is $6$.'),
          maths('AI : ID = (6 + 8) : 7 = 2 : 1'),
          maths('AI = 6 \\times \\frac{2}{3} = 4'),
        ),
        ask('cm-sg-bisector-tiles', 2),
      ],
      skillCheck: [ask('cm-sg-bisector-split', 2), ask('cm-sg-bisector-length', 2), ask('cm-sg-incentre-ratio', 2)],
    },
    {
      id: 'cm-l18-power',
      title: 'Power of a Point',
      slides: [
        teach(
          prose('**Crossing chords.** Chords $AB$ and $CD$ cross at $P$. Triangles $APC$ and $DPB$ have equal angles at $P$, and $\\angle CAB = \\angle CDB$ stand on the same arc, so they are similar, and'),
          maths('AP \\times PB = CP \\times PD'),
          prose('With $AP = 3$, $PB = 8$ and $CP = 4$:'),
          maths('3 \\times 8 = 4 \\times PD'),
          maths('PD = 24 \\div 4 = 6'),
          prose('Every chord through $P$ gives the same product, the **power** of $P$.'),
        ),
        ask('cm-sg-chords'),
        ask('cm-sg-power-table'),
        askAfter(
          'cm-sg-secants',
          1,
          prose('**From outside.** Two lines from $P$ outside a circle cut it at $A$ then $B$, and at $C$ then $D$. The same rule holds, with both lengths on each line measured from $P$:'),
          maths('PA \\times PB = PC \\times PD'),
          prose('With $PA = 4$, $AB = 5$ and $PC = 3$, first $PB = 9$:'),
          maths('4 \\times 9 = 3 \\times PD'),
          maths('PD = 12'),
          maths('CD = 12 - 3 = 9'),
          prose('Multiplying the outside part by the chord, $PA \\times AB$, is the trap.'),
        ),
        askAfter(
          'cm-sg-chords+choice',
          2,
          prose('Given the whole chord: $CD = 10$ and $AP \\times PB = 21$. With $PD = 10 - CP$:'),
          maths('CP(10 - CP) = 21'),
          maths('CP^{2} - 10CP + 21 = 0'),
          maths('(CP - 7)(CP - 3) = 0'),
          prose('The pieces are $7$ and $3$, so the longer one is $7$.'),
        ),
        teach(
          prose('**Power from the radius.** The diameter through $P$ is a chord through $P$ too. If $P$ is $d$ from the centre $O$ of a circle of radius $r$, its pieces are $r - d$ and $r + d$:'),
          maths('PA \\times PB = (r - d)(r + d)'),
          prose('With $r = 7$ and $d = 5$, any chord $AB$ through $P$ with $PA = 8$ has'),
          maths('PA \\times PB = 2 \\times 12 = 24'),
          maths('PB = 24 \\div 8 = 3'),
        ),
        ask('cm-sg-power-radius'),
        askAfter(
          'cm-sg-secants+choice',
          2,
          prose('A **tangent** $PT$ touches the circle at one point: it is a line whose two meeting points have come together. So'),
          maths('PT^{2} = PA \\times PB'),
          prose('With $PT = 6$ and $PA = 4$:'),
          maths('PB = 36 \\div 4 = 9'),
          maths('AB = 9 - 4 = 5'),
        ),
        askAfter(
          'cm-sg-power-radius+choice',
          2,
          prose('**The shortest chord** through $P$ is the one at right angles to $OP$, with $P$ as its midpoint. Half of it is a leg of a right triangle with hypotenuse $r$. With $r = 13$ and $OP = 5$:'),
          maths('\\text{half}^{2} = 13^{2} - 5^{2} = 144'),
          maths('\\text{chord} = 2 \\times 12 = 24'),
        ),
        ask('cm-sg-power-table', 2),
      ],
      skillCheck: [ask('cm-sg-chords', 2), ask('cm-sg-secants', 2), ask('cm-sg-power-radius', 2)],
    },
    {
      id: 'cm-l18-cyclic',
      title: 'Cyclic Quadrilaterals',
      slides: [
        teach(
          prose('A **cyclic quadrilateral** $ABCD$ has its corners on a circle. Two facts do most of the work: angles standing on the same arc are equal, and opposite angles add to $180^\\circ$.'),
          prose('With $\\angle CAD = 30^\\circ$ and $\\angle ABD = 45^\\circ$: $\\angle DBC$ stands on the arc $DC$, as $\\angle DAC$ does.'),
          maths('\\angle DBC = \\angle DAC = 30^\\circ'),
          maths('\\angle ABC = 45^\\circ + 30^\\circ = 75^\\circ'),
          maths('\\angle ADC = 180^\\circ - 75^\\circ = 105^\\circ'),
        ),
        ask('cm-sg-cyclic-angles'),
        ask('cm-sg-cyclic-table'),
        askAfter(
          'cm-sg-ptolemy',
          1,
          prose('**Ptolemy’s theorem.** In a cyclic quadrilateral the product of the diagonals is the sum of the products of opposite sides:'),
          maths('AC \\times BD = AB \\times CD + BC \\times DA'),
          prose('$ABC$ is equilateral with side $s$, and $P$ is on the arc $BC$ with $PB = 3$ and $PC = 5$. Going round $ABPC$:'),
          maths('PA \\times s = 3s + 5s'),
          maths('PA = 3 + 5 = 8'),
        ),
        askAfter(
          'cm-sg-cyclic-angles+choice',
          2,
          prose('When the diagonals cross at $X$, $\\angle AXB$ is an exterior angle of triangle $AXD$. With $\\angle CAD = 40^\\circ$ and $\\angle ACB = 35^\\circ$:'),
          maths('\\angle ADB = \\angle ACB = 35^\\circ'),
          maths('\\angle AXB = 40^\\circ + 35^\\circ = 75^\\circ'),
        ),
        teach(
          prose('**Brahmagupta’s formula** is Heron’s for a cyclic quadrilateral, with $s$ half the perimeter:'),
          maths('\\text{area} = \\sqrt{(s - a)(s - b)(s - c)(s - d)}'),
          prose('For sides $6$, $7$, $11$ and $8$ in order:'),
          maths('s = (6 + 7 + 11 + 8) \\div 2 = 16'),
          maths('\\text{area} = \\sqrt{10 \\times 9 \\times 5 \\times 8}'),
          maths('\\text{area} = \\sqrt{3600} = 60'),
          prose('Averaging opposite sides and multiplying, $63.75$, is the trap: that is only right for a rectangle.'),
        ),
        ask('cm-sg-brahmagupta'),
        askAfter(
          'cm-sg-ptolemy+choice',
          2,
          prose('When the diagonal $AC$ is a diameter, the angles at $B$ and $D$ are right angles, so the sides come in right-triangle pairs. With $AC = 25$, $AB = 7$, $BC = 24$, $CD = 20$ and $DA = 15$:'),
          maths('25 \\times BD = 7 \\times 20 + 24 \\times 15'),
          maths('25 \\times BD = 500'),
          maths('BD = 20'),
        ),
        askAfter(
          'cm-sg-brahmagupta+choice',
          2,
          prose('If a circle also touches all four sides, the two tangents from each corner are equal, so opposite sides add to the same total. With $AB = 2$, $BC = 5$ and $CD = 8$:'),
          maths('DA = 2 + 8 - 5 = 5'),
          prose('Then $s = a + c$, so each $s - a$ is the side opposite $a$, and the formula becomes'),
          maths('\\text{area} = \\sqrt{abcd}'),
          maths('\\text{area} = \\sqrt{2 \\times 5 \\times 8 \\times 5} = 20'),
        ),
        ask('cm-sg-cyclic-table', 2),
      ],
      skillCheck: [ask('cm-sg-cyclic-angles', 2), ask('cm-sg-ptolemy', 2), ask('cm-sg-brahmagupta', 2)],
    },
    {
      id: 'cm-l18-circles',
      title: 'Circles',
      slides: [
        teach(
          prose('**Two tangents from a point are equal.** A circle inside triangle $ABC$ touches each side, and each side is made of two tangents. Call the tangent from $A$ $t_A$, and so on. With $BC = 8$, $CA = 7$ and $AB = 5$:'),
          maths('t_A + t_B = 5, \\qquad t_B + t_C = 8, \\qquad t_C + t_A = 7'),
          maths('t_A + t_B + t_C = 20 \\div 2 = 10'),
          maths('t_A = 10 - 8 = 2, \\qquad t_B = 10 - 7 = 3, \\qquad t_C = 10 - 5 = 5'),
          prose('In a quadrilateral with a circle inside, the same tangents make opposite sides add to the same total. With $AB = 7$, $BC = 9$ and $CD = 8$:'),
          maths('AB + CD = BC + DA'),
          maths('DA = 7 + 8 - 9 = 6'),
        ),
        ask('cm-sg-pitot'),
        ask('cm-sg-tangent-table'),
        askAfter(
          'cm-sg-parallel-chords',
          1,
          prose('**Parallel chords.** Half a chord, its distance from the centre and a radius make a right triangle. Chords $6$ and $8$ long, $7$ apart on opposite sides of the centre: say the $6$ chord is $x$ from the centre.'),
          maths('3^{2} + x^{2} = 4^{2} + (7 - x)^{2}'),
          maths('9 + x^{2} = 16 + 49 - 14x + x^{2}'),
          maths('14x = 56'),
          maths('x = 4'),
          maths('r^{2} = 3^{2} + 4^{2} = 25'),
          prose('So $r = 5$.'),
        ),
        askAfter(
          'cm-sg-pitot+choice',
          2,
          prose('An isosceles trapezium with parallel sides $2$ and $8$ and a circle inside it: opposite sides add to the same total, and the two slanted sides are equal.'),
          maths('\\text{slant} = (2 + 8) \\div 2 = 5'),
          prose('Dropping perpendiculars from the short side cuts off $3$ at each end, and the height is the circle’s diameter:'),
          maths('h^{2} = 5^{2} - 3^{2} = 16'),
          maths('h = 4'),
          prose('So $r = 2$.'),
        ),
        teach(
          prose('**Tangents and angles.** $PA$ and $PB$ touch a circle, centre $O$, at $A$ and $B$, with $\\angle APB = 50^\\circ$. A tangent is at right angles to the radius, so $OAPB$ has two right angles:'),
          maths('\\angle AOB = 360^\\circ - 90^\\circ - 90^\\circ - 50^\\circ = 130^\\circ'),
          prose('A point $C$ on the longer arc sees $AB$ at half the angle at the centre:'),
          maths('\\angle ACB = 130^\\circ \\div 2 = 65^\\circ'),
          prose('Halving $50^\\circ$ is the trap.'),
        ),
        ask('cm-sg-tangent-angle'),
        askAfter(
          'cm-sg-parallel-chords+choice',
          2,
          prose('On the same side of the centre, the shorter chord is further out. Chords $6$ and $8$, $1$ apart: the $6$ chord is $x$ from the centre, the $8$ chord $x - 1$.'),
          maths('3^{2} + x^{2} = 4^{2} + (x - 1)^{2}'),
          maths('9 + x^{2} = 16 + x^{2} - 2x + 1'),
          maths('2x = 8'),
          maths('x = 4'),
          prose('So $r = 5$ again.'),
        ),
        askAfter(
          'cm-sg-tangent-angle+choice',
          2,
          prose('A point on the **shorter** arc makes a cyclic quadrilateral with $A$, $B$ and a point on the longer arc, so its angle is the rest of $180^\\circ$. With $\\angle APB = 50^\\circ$:'),
          maths('\\angle ACB = 180^\\circ - 65^\\circ = 115^\\circ'),
        ),
        askAfter(
          'cm-sg-tangent-table',
          2,
          prose('Round a quadrilateral with a circle inside, walk from corner to corner: each side is two tangents, so take off the one you know. With $t_A = 3$, $AB = 7$, $BC = 9$ and $CD = 8$:'),
          maths('t_B = 7 - 3 = 4, \\qquad t_C = 9 - 4 = 5'),
          maths('t_D = 8 - 5 = 3, \\qquad DA = 3 + 3 = 6'),
        ),
      ],
      skillCheck: [ask('cm-sg-pitot', 2), ask('cm-sg-parallel-chords', 2), ask('cm-sg-tangent-angle', 2)],
    },
  ],
  levelCheck: [
    ask('cm-sg-british-flag', 2),
    ask('cm-sg-heron+choice', 2),
    ask('cm-sg-extended-sides', 2),
    ask('cm-sg-angle-similar+choice', 2),
    ask('cm-sg-parallel-area', 2),
    ask('cm-sg-bisector-split+choice', 2),
    ask('cm-sg-incentre-ratio', 2),
    ask('cm-sg-chords+choice', 2),
    ask('cm-sg-power-radius', 2),
    ask('cm-sg-cyclic-angles+choice', 2),
    ask('cm-sg-ptolemy', 2),
    ask('cm-sg-tangent-angle+choice', 2),
    ask('cm-sg-parallel-chords', 2),
    ask('cm-sg-unfold+choice', 2),
  ],
};
