/**
 * Contest Math, Level 14: Polynomials. Never solving the polynomial: the
 * remainder is one substitution, a shared root falls out of a subtraction,
 * the sum and product of the roots are read off the coefficients, and new
 * roots come from old ones without finding either. Generators in
 * `generators/contestPolynomials.ts`.
 */
import type { Level } from '../../types';
import { teach, ask, prose, maths, askAfter } from './blocks';

export const polynomialsLevel: Level = {
  id: 'cm-l14',
  title: 'Polynomials',
  lessons: [
    {
      id: 'cm-l14-roots',
      title: 'Roots',
      slides: [
        teach(
          prose('Divide a polynomial $p(x)$ by $x - a$. What is left over is a number $R$, the remainder:'),
          maths('p(x) = (x - a)q(x) + R'),
          prose('Put $x = a$ and the first part vanishes, so the remainder is $p(a)$. No long division needed. For $x^3 - 4x^2 + 5x - 7$ divided by $x - 3$:'),
          maths('p(3) = 27 - 36 + 15 - 7'),
          maths('p(3) = -1'),
          prose('When the remainder is $0$, $x - a$ is a **factor** and $a$ is a root. That is the factor theorem.'),
        ),
        ask('cm-po-remainder'),
        askAfter(
          'cm-po-remainder+choice',
          2,
          prose('Dividing by $x + 2$ is dividing by $x - (-2)$, so the remainder is $p(-2)$, not $p(2)$. For $x^3 + x^2 - 4$:'),
          maths('p(-2) = -8 + 4 - 4'),
          maths('p(-2) = -8'),
        ),
        askAfter(
          'cm-po-find-k',
          1,
          prose('An unknown coefficient: for which $k$ is $x - 2$ a factor of $x^3 + x^2 + kx - 2$? A factor means $p(2)$ is $0$:'),
          maths('8 + 4 + 2k - 2 = 0'),
          maths('2k = -10'),
          maths('k = -5'),
        ),
        teach(
          prose('Put $x = 1$ into any polynomial: every power of $x$ becomes $1$, so $p(1)$ is the **sum of its coefficients**. Multiplied out, $(2x - 1)^4(x + 2)^3$ has many terms, yet they add to'),
          maths('(2 - 1)^4 \\times (1 + 2)^3'),
          maths('= 1 \\times 27 = 27'),
          prose('**Whole-number roots divide the constant term.** Take'),
          maths('p(x) = x^3 - 2x^2 - 5x + 6'),
          prose('and try the divisors of $6$, smallest first. $p(1)$ is $0$, so $x - 1$ is a factor:'),
          maths('p(x) = (x - 1)(x^2 - x - 6)'),
          maths('p(x) = (x - 1)(x + 2)(x - 3)'),
          prose('The roots are $1$, $-2$ and $3$. Reading them off with the signs kept, $-1$, $2$ and $-3$, is the trap.'),
        ),
        ask('cm-po-sum-coeffs'),
        ask('cm-po-integer-roots'),
        askAfter(
          'cm-po-sum-coeffs+choice',
          2,
          prose('At $x = -1$ the even powers still give $1$ but the odd powers give $-1$. So $p(1) + p(-1)$ counts the even-power coefficients twice and cancels the rest. For $(x + 2)^3$, which is $x^3 + 6x^2 + 12x + 8$:'),
          maths('\\frac{p(1) + p(-1)}{2} = \\frac{27 + 1}{2} = 14'),
          prose('and indeed $6 + 8$ is $14$.'),
        ),
        askAfter(
          'cm-po-find-k+choice',
          2,
          prose('With a remainder instead of a factor, $p(a)$ is that remainder. $x^3 + kx + 4$ leaves $10$ when divided by $x - 2$:'),
          maths('8 + 2k + 4 = 10'),
          maths('2k = -2'),
          maths('k = -1'),
        ),
        ask('cm-po-integer-roots', 2),
      ],
      skillCheck: [ask('cm-po-find-k', 2), ask('cm-po-sum-coeffs', 2), ask('cm-po-integer-roots', 2)],
    },
    {
      id: 'cm-l14-equations',
      title: 'Equations',
      slides: [
        teach(
          prose('Some equations are quadratics in disguise. This one has only even powers of $x$:'),
          maths('x^4 - 13x^2 + 36 = 0'),
          prose('so put $y = x^2$:'),
          maths('y^2 - 13y + 36 = 0'),
          maths('(y - 4)(y - 9) = 0'),
          prose('So $x^2$ is $4$ or $9$, and each gives two solutions: $x = \\pm 2$ or $x = \\pm 3$. Four solutions, not two, and the positive ones add to $5$, not $13$.'),
        ),
        ask('cm-po-quartic'),
        askAfter(
          'cm-po-quartic+choice',
          2,
          prose('A negative value of $y$ gives no real $x$, since no real number squares to a negative. Put $y = x^2$ in'),
          maths('x^4 + 3x^2 - 4 = 0'),
          prose('and it factorises as'),
          maths('(y - 1)(y + 4) = 0'),
          prose('Only $y = 1$ counts, so the real solutions are $1$ and $-1$, and their squares add to $2$. Adding both values of $y$, which gives $-3$, is the trap.'),
        ),
        teach(
          prose('Two quadratics share a solution. Take one from the other: the $x^2$ terms cancel, and the shared solution still satisfies what is left.'),
          maths('x^2 + x - 6 = 0'),
          maths('x^2 - 7x + 10 = 0'),
          prose('The first minus the second:'),
          maths('8x - 16 = 0'),
          maths('x = 2'),
          prose('No need to factorise either one.'),
        ),
        ask('cm-po-shared-root-tiles'),
        askAfter(
          'cm-po-shared-root',
          2,
          prose('When the $x^2$ terms differ, scale one equation first. Take these two:'),
          maths('x^2 - x - 2 = 0'),
          maths('2x^2 - 3x - 2 = 0'),
          prose('Doubled, the first is'),
          maths('2x^2 - 2x - 4 = 0'),
          prose('and take the second away:'),
          maths('x - 2 = 0'),
          prose('So the shared solution is $2$.'),
        ),
        teach(
          prose('An equation can hand you a whole expression. Take'),
          maths('x^2 - 4x + 1 = 0'),
          prose('and divide by $x$, which is not $0$:'),
          maths('x - 4 + \\frac{1}{x} = 0'),
          maths('x + \\frac{1}{x} = 4'),
          prose('Square both sides. The middle term is $2 \\times x \\times \\frac{1}{x}$, which is $2$:'),
          maths('x^2 + 2 + \\frac{1}{x^2} = 16'),
          maths('x^2 + \\frac{1}{x^2} = 14'),
          prose('Answering $16$ forgets the middle term.'),
        ),
        ask('cm-po-reciprocal'),
        askAfter(
          'cm-po-fixed-values',
          1,
          prose('A cubic with leading coefficient $1$ has'),
          maths('p(1) = p(2) = p(3) = 7'),
          prose('Then $p(x) - 7$ is zero at $1$, $2$ and $3$. It is a cubic with leading coefficient $1$, so'),
          maths('p(x) - 7 = (x - 1)(x - 2)(x - 3)'),
          maths('p(5) = 4 \\times 3 \\times 2 + 7 = 31'),
          prose('Answering $7$ is the trap.'),
        ),
        askAfter(
          'cm-po-reciprocal+choice',
          2,
          prose('Cube instead of square. $(x + \\frac{1}{x})^3$ has middle terms $3x + \\frac{3}{x}$, three times the sum. With a sum of $4$:'),
          maths('x^3 + \\frac{1}{x^3} + 3 \\times 4 = 64'),
          maths('x^3 + \\frac{1}{x^3} = 52'),
        ),
        askAfter(
          'cm-po-fixed-values+choice',
          2,
          prose('If instead $p(1)$ is $1$, $p(2)$ is $2$ and $p(3)$ is $3$, then $p(x) - x$ has those three roots:'),
          maths('p(x) - x = (x - 1)(x - 2)(x - 3)'),
          maths('p(5) = 24 + 5 = 29'),
          prose('Answering $5$, as if $p(x)$ were just $x$, is the trap.'),
        ),
      ],
      skillCheck: [ask('cm-po-quartic', 2), ask('cm-po-shared-root', 2), ask('cm-po-fixed-values', 2)],
    },
    {
      id: 'cm-l14-vieta',
      title: "Vieta's Formulas",
      slides: [
        teach(
          prose('Multiply out a quadratic with leading coefficient $1$ and roots $r$ and $s$:'),
          maths('(x - r)(x - s) = {x^2 - (r + s)x + rs}'),
          prose("So for $x^2 + bx + c$ the roots add to $-b$ and multiply to $c$. These are **Vieta's formulas**, and they hold even when the roots are not whole numbers, or not real at all: complex roots count too."),
          prose('Many expressions in $r$ and $s$ are built from the sum and the product. The roots of this equation add to $5$ and multiply to $3$:'),
          maths('x^2 - 5x + 3 = 0'),
          prose('so'),
          maths('r^2 + s^2 = (r + s)^2 - 2rs'),
          maths('= 25 - 6 = 19'),
          maths('\\frac{1}{r} + \\frac{1}{s} = \\frac{r + s}{rs} = \\frac{5}{3}'),
        ),
        ask('cm-po-vieta-quad'),
        askAfter(
          'cm-po-vieta-quad+choice',
          2,
          prose('For cubes: $(r + s)^3$ is $r^3 + s^3$ plus $3r^2s + 3rs^2$, which is $3rs(r + s)$. So'),
          maths('r^3 + s^3 = (r + s)^3 - 3rs(r + s)'),
          prose('With a sum of $5$ and a product of $3$:'),
          maths('125 - 3 \\times 3 \\times 5 = 80'),
        ),
        askAfter(
          'cm-po-root-ratio',
          1,
          prose('Vieta runs backwards too. One root of this equation is twice the other:'),
          maths('x^2 - 15x + c = 0'),
          prose('Call them $r$ and $2r$; they add to $15$:'),
          maths('3r = 15'),
          maths('r = 5'),
          prose('So the roots are $5$ and $10$, and $c$ is their product, $50$.'),
        ),
        teach(
          prose('A cubic with leading coefficient $1$ and roots $r$, $s$, $t$ multiplies out as'),
          maths('{x^3 - (r + s + t)x^2} + {(rs + rt + st)x - rst}'),
          prose('The signs alternate: the sum is minus the $x^2$ coefficient, the pairs add to the $x$ coefficient, and the product is minus the constant. With another leading coefficient, divide by it first. $2x^3 - 6x^2 + 4x + 10$ becomes'),
          maths('x^3 - 3x^2 + 2x + 5'),
          prose('so the roots add to $3$, the pairs add to $2$ and the product is $-5$. Squaring the sum gives every square once and every pair twice:'),
          maths('r^2 + s^2 + t^2 = 3^2 - 2 \\times 2 = 5'),
        ),
        ask('cm-po-vieta-table'),
        ask('cm-po-vieta-cubic'),
        ask('cm-po-vieta-table', 2),
        askAfter(
          'cm-po-vieta-cubic+choice',
          2,
          prose('Reciprocals go over a common denominator:'),
          maths('\\frac{1}{r} + \\frac{1}{s} + \\frac{1}{t} = \\frac{rs + rt + st}{rst}'),
          prose('For $2x^3 - 6x^2 + 4x + 10$ that is $2 \\div (-5)$, which is $-\\frac{2}{5}$. The leading $2$ divides the top and the bottom alike, so it cancels.'),
        ),
        askAfter(
          'cm-po-root-ratio+choice',
          2,
          prose('When the roots differ by a number, call them $r$ and $r + 4$. For this equation they add to $10$:'),
          maths('x^2 - 10x + c = 0'),
          prose('so'),
          maths('2r + 4 = 10'),
          maths('r = 3'),
          prose('The roots are $3$ and $7$, so $c$ is $21$.'),
        ),
      ],
      skillCheck: [ask('cm-po-vieta-quad', 2), ask('cm-po-vieta-cubic', 2), ask('cm-po-root-ratio', 2)],
    },
    {
      id: 'cm-l14-transformations',
      title: 'Transformations',
      slides: [
        teach(
          prose('A cubic with leading coefficient $1$ and roots $r$, $s$, $t$ is'),
          maths('p(x) = (x - r)(x - s)(x - t)'),
          prose('So putting in a number gives a product of differences at once. Take'),
          maths('p(x) = x^3 - 2x^2 + 3x - 5'),
          prose('Then'),
          maths('(2 - r)(2 - s)(2 - t) = p(2)'),
          maths('p(2) = 8 - 8 + 6 - 5 = 1'),
        ),
        ask('cm-po-shift-product'),
        askAfter(
          'cm-po-shift-product+choice',
          2,
          prose('For $(r + 1)(s + 1)(t + 1)$ put $x = -1$. Each bracket $(-1 - r)$ is minus $(r + 1)$, and three minus signs make one:'),
          maths('(r + 1)(s + 1)(t + 1) = -p(-1)'),
          prose('With the same $p$:'),
          maths('p(-1) = -1 - 2 - 3 - 5 = -11'),
          prose('so the product is $11$.'),
        ),
        teach(
          prose('Let the cubic $p$ have roots $r$, $s$, $t$ adding to $6$. The equation'),
          maths('p(x + 3) = 0'),
          prose('holds exactly when $x + 3$ is a root of $p$, so its roots are $r - 3$, $s - 3$ and $t - 3$. Every root moves, so the sum moves by three lots of $3$:'),
          maths('6 - 3 \\times 3 = -3'),
          prose('Taking $3$ off once, $3$, is the trap. For the equation'),
          maths('p(2x - 1) = 0'),
          prose('each new root solves'),
          maths('2x - 1 = r'),
          maths('x = \\frac{r + 1}{2}'),
          prose('so the new roots add to'),
          maths('\\frac{6 + 3 \\times 1}{2} = \\frac{9}{2}'),
        ),
        ask('cm-po-roots-sum-sub'),
        ask('cm-po-roots-sum-sub+choice', 2),
        askAfter(
          'cm-po-new-roots-table',
          1,
          prose('Doubling every root doubles their sum, multiplies each pair product by $4$ and the product of all three by $8$. The coefficients are those sums with alternating signs, so $x^3 + ax^2 + bx + c$ becomes'),
          maths('x^3 + 2ax^2 + 4bx + 8c'),
          prose('Tripling uses $3$, $9$ and $27$ the same way.'),
        ),
        askAfter(
          'cm-po-squared-roots-tiles',
          1,
          prose('For roots $r^2$ and $s^2$, find their sum and product from Vieta. If $r$ and $s$ are the roots of'),
          maths('x^2 - 3x + 1 = 0'),
          prose('then'),
          maths('r^2 + s^2 = 3^2 - 2 \\times 1 = 7'),
          maths('r^2 s^2 = (rs)^2 = 1'),
          prose('A quadratic with leading coefficient $1$ is $x^2$, minus the sum times $x$, plus the product:'),
          maths('x^2 - 7x + 1'),
        ),
        askAfter(
          'cm-po-new-roots-table',
          2,
          prose('A negative multiplier works the same way. For roots $-2r$, $-2s$, $-2t$ the multipliers are $-2$, $4$ and $-8$: the $x^2$ coefficient and the constant change sign, the $x$ coefficient does not.'),
        ),
        ask('cm-po-squared-roots-tiles', 2),
      ],
      skillCheck: [ask('cm-po-shift-product', 2), ask('cm-po-roots-sum-sub', 2), ask('cm-po-new-roots-table', 2)],
    },
  ],
  levelCheck: [
    ask('cm-po-remainder', 2),
    ask('cm-po-find-k+choice', 2),
    ask('cm-po-sum-coeffs', 2),
    ask('cm-po-integer-roots', 2),
    ask('cm-po-quartic', 2),
    ask('cm-po-shared-root+choice', 2),
    ask('cm-po-reciprocal', 2),
    ask('cm-po-fixed-values', 2),
    ask('cm-po-vieta-quad', 2),
    ask('cm-po-vieta-cubic+choice', 2),
    ask('cm-po-root-ratio', 2),
    ask('cm-po-shift-product', 2),
    ask('cm-po-roots-sum-sub', 2),
    ask('cm-po-new-roots-table', 2),
  ],
};
