/**
 * Contest Math, Level 19: Analytical Geometry. Coordinates used cleverly
 * (reflect to straighten a path, count lattice points with a gcd, work out an
 * area twice), the focus properties of the conics, mass points for ratios in
 * a triangle, and complex numbers as turns and distances. Generators in
 * `generators/contestAnalyticGeometry.ts`.
 */
import type { Level } from '../../types';
import { teach, ask, prose, maths, askAfter } from './blocks';

export const analyticalGeometry: Level = {
  id: 'cm-l19',
  title: 'Analytical Geometry',
  lessons: [
    {
      id: 'cm-l19-coordinates',
      title: 'Coordinate Geometry',
      slides: [
        teach(
          prose('A walker goes from $A = (1, 3)$ down to a river along the $x$-axis, then on to $B = (7, 5)$. Where should they touch the river?'),
          prose('**Reflect** $B$ in the $x$-axis to $B\' = (7, -5)$. From any point $P$ on the axis, $PB = PB\'$, so the walk is as long as $A$ to $P$ to $B\'$. That is shortest when it is a straight line.'),
          prose('From $A$ to $B\'$ is $6$ across and $8$ down:'),
          maths('3 + 5 = 8'),
          maths('6^{2} + 8^{2} = 100'),
          maths('\\sqrt{100} = 10'),
          prose('Walking straight down, along the river and back up, $14$, is the trap.'),
        ),
        ask('cm-ag-river'),
        askAfter(
          'cm-ag-lattice',
          1,
          prose('Points with whole-number coordinates are **lattice points**. From $(2, 1)$ to $(14, 10)$ is $12$ across and $9$ up. The smallest whole step along the segment divides both, so'),
          maths('\\gcd(12, 9) = 3'),
          prose('One step is $4$ across and $3$ up, and it takes $3$ steps to cross. Three steps have $4$ points at their ends, counting both ends of the segment.'),
        ),
        askAfter(
          'cm-ag-river+choice',
          2,
          prose('Two walls: from $A = (4, 1)$ to the $x$-axis, then to the $y$-axis, then to $B = (2, 7)$. Reflect each end in the wall it touches: $A$ in the $x$-axis to $A\' = (4, -1)$, and $B$ in the $y$-axis to $B\' = (-2, 7)$.'),
          prose('From $A\'$ to $B\'$ is $6$ across and $8$ up:'),
          maths('4 + 2 = 6, \\qquad 1 + 7 = 8'),
          maths('\\sqrt{6^{2} + 8^{2}} = 10'),
        ),
        askAfter(
          'cm-ag-lattice+choice',
          2,
          prose('Strictly between the ends leaves both ends out. From $(-3, 8)$ to $(9, -1)$ is $12$ across and $9$ down, so $3$ steps and $4$ points in all, and'),
          maths('4 - 2 = 2'),
          prose('lie strictly between.'),
        ),
        teach(
          prose('**Pick’s theorem.** A polygon with its corners on lattice points has'),
          maths('\\text{area} = I + \\frac{B}{2} - 1'),
          prose('where $B$ counts the lattice points on its edges and $I$ those strictly inside.'),
          prose('Take the triangle $(0, 0)$, $(6, 0)$, $(0, 4)$:'),
          maths('\\text{area} = \\frac{1}{2} \\times 6 \\times 4 = 12'),
          prose('Each side has as many lattice points as it takes whole steps, counting one end: $6$ along the bottom, $4$ up the side, and $\\gcd(6, 4) = 2$ on the slope.'),
          maths('B = 6 + 4 + 2 = 12'),
          maths('I = 12 - 6 + 1 = 7'),
          prose('Forgetting the point in the middle of the slope, and counting $B = 11$, is the trap.'),
        ),
        ask('cm-ag-pick'),
        askAfter(
          'cm-ag-line-distance',
          1,
          prose('**Work out an area twice.** How far is the origin from the line $4x + 3y = 24$? It meets the axes at $(6, 0)$ and $(0, 8)$, making a right triangle with the origin:'),
          maths('\\text{area} = \\frac{1}{2} \\times 6 \\times 8 = 24'),
          maths('\\sqrt{6^{2} + 8^{2}} = 10'),
          prose('The distance $d$ is the height onto the long side, so the area is also'),
          maths('\\frac{1}{2} \\times 10 \\times d = 24'),
          maths('d = \\frac{48}{10} = \\frac{24}{5}'),
        ),
        askAfter(
          'cm-ag-pick',
          2,
          prose('With a slanted base as well, count each slanted side by its own gcd. Triangle $(0, 0)$, $(8, 0)$, $(2, 6)$: the side to $(2, 6)$ has $\\gcd(2, 6) = 2$, and the side from $(8, 0)$ goes $6$ across and $6$ up, with $\\gcd(6, 6) = 6$.'),
          maths('\\text{area} = \\frac{1}{2} \\times 8 \\times 6 = 24'),
          maths('B = 8 + 2 + 6 = 16'),
          maths('I = 24 - 8 + 1 = 17'),
        ),
        askAfter(
          'cm-ag-line-distance+choice',
          2,
          prose('The same working shows how far the origin is from the line $ax + by = c$:'),
          maths('d = \\frac{|c|}{\\sqrt{a^{2} + b^{2}}}'),
          maths('\\sqrt{3^{2} + 4^{2}} = 5'),
          prose('So the line $3x + 4y = 10$ is $2$ from the origin, and $3x + 4y = -15$ is $3$ from it on the other side. Those two parallel lines are $5$ apart. In one step:'),
          maths('\\frac{|10 - (-15)|}{5} = 5'),
        ),
      ],
      skillCheck: [ask('cm-ag-river', 2), ask('cm-ag-pick', 2), ask('cm-ag-line-distance', 2)],
    },
    {
      id: 'cm-l19-conics',
      title: 'Conics',
      slides: [
        teach(
          prose('An **ellipse** is every point whose distances to two fixed points, the **foci**, add to the same total. That total is the length of the long axis, $2a$.'),
          maths('\\frac{x^{2}}{25} + \\frac{y^{2}}{9} = 1'),
          prose('The larger denominator, $25$, is under $x^{2}$, so the long axis is on the $x$-axis:'),
          maths('a = \\sqrt{25} = 5'),
          prose('From every point on it:'),
          maths('PF_{1} + PF_{2} = 10'),
          prose('So a point $3$ from one focus is $7$ from the other:'),
          maths('10 - 3 = 7'),
          prose('Saying $3$ again, by symmetry, is the trap.'),
        ),
        ask('cm-ag-ellipse'),
        askAfter(
          'cm-ag-ellipse+choice',
          2,
          prose('Each focus is $c$ from the centre, where'),
          maths('c^{2} = a^{2} - b^{2}'),
          prose('For the ellipse above:'),
          maths('c = \\sqrt{25 - 9} = 4'),
          prose('so the foci are $8$ apart. Triangle $PF_{1}F_{2}$ then has perimeter'),
          maths('10 + 8 = 18'),
          prose('wherever $P$ is on the ellipse.'),
        ),
        askAfter(
          'cm-ag-circle-centre',
          1,
          prose('A **circle** written out in full: group the $x$ terms and the $y$ terms, then complete each square.'),
          maths('x^{2} + y^{2} - 6x + 4y - 12 = 0'),
          maths('(x^{2} - 6x) + (y^{2} + 4y) = 12'),
          maths('(x - 3)^{2} + (y + 2)^{2} = 12 + 9 + 4'),
          maths('(x - 3)^{2} + (y + 2)^{2} = 25'),
          prose('The centre is $(3, -2)$, the signs turned round from the brackets, and the radius is $5$, not $25$.'),
        ),
        askAfter(
          'cm-ag-circle-chord',
          1,
          prose('Where does this circle cross the $x$-axis?'),
          maths('x^{2} + y^{2} - 4x + 6y - 5 = 0'),
          prose('Put $y = 0$:'),
          maths('x^{2} - 4x - 5 = 0'),
          prose('The two roots add to $4$ and multiply to $-5$, and you need only their difference:'),
          maths('(x_{1} - x_{2})^{2} = (x_{1} + x_{2})^{2} - 4x_{1}x_{2}'),
          maths('(x_{1} - x_{2})^{2} = 16 + 20 = 36'),
          prose('So the crossings are $6$ apart, with no need for the centre or the radius.'),
        ),
        teach(
          prose('A **parabola** is every point as far from a fixed point, the **focus**, as from a fixed line, the **directrix**.'),
          prose('For $y^{2} = 4px$ the focus is $(p, 0)$ and the directrix is the line $x = -p$. So the distance from the focus is just $x + p$, with no square root.'),
          maths('y^{2} = 12x'),
          maths('4p = 12'),
          prose('So $p = 3$. The point on it with $x = 5$ is'),
          maths('5 + 3 = 8'),
          prose('from the focus. For $x^{2} = 4py$ swap the letters: the focus is $(0, p)$ and the distance is $y + p$.'),
        ),
        ask('cm-ag-parabola'),
        askAfter(
          'cm-ag-circle-centre',
          2,
          prose('When $x^{2}$ and $y^{2}$ have a coefficient other than $1$, divide through by it first.'),
          maths('2x^{2} + 2y^{2} - 8x + 12y + 8 = 0'),
          maths('x^{2} + y^{2} - 4x + 6y + 4 = 0'),
          maths('(x - 2)^{2} + (y + 3)^{2} = -4 + 4 + 9'),
          maths('(x - 2)^{2} + (y + 3)^{2} = 9'),
          prose('The centre is $(2, -3)$ and the radius is $3$.'),
        ),
        askAfter(
          'cm-ag-parabola+choice',
          2,
          prose('Going back: a point on $y^{2} = 8x$ is $10$ from the focus. Here $p = 2$, so'),
          maths('x + 2 = 10'),
          maths('x = 8'),
          maths('y^{2} = 8 \\times 8 = 64'),
          prose('and $y = 8$ above the axis. Putting $x = 10$ into the equation is the trap.'),
        ),
        askAfter(
          'cm-ag-circle-chord+choice',
          2,
          prose('Crossing the $y$-axis instead, put $x = 0$ and work with the roots in $y$ the same way.'),
          maths('x^{2} + y^{2} - 6x - 2y - 8 = 0'),
          maths('y^{2} - 2y - 8 = 0'),
          maths('(y_{1} - y_{2})^{2} = 4 + 32 = 36'),
          prose('So they are $6$ apart.'),
        ),
      ],
      skillCheck: [ask('cm-ag-ellipse', 2), ask('cm-ag-circle-centre', 2), ask('cm-ag-parabola', 2)],
    },
    {
      id: 'cm-l19-mass-points',
      title: 'Mass Points',
      slides: [
        teach(
          prose('**Mass points** turn ratios in a triangle into a see-saw. Hang a mass on each end of a segment so it balances at a point: mass times distance is the same on both sides, so the heavier mass sits at the nearer end, and the balance point carries both masses.'),
          prose('A line from a corner of a triangle to the opposite side is a **cevian**. In triangle $ABC$, $D$ is on $BC$ with $BD : DC = 2 : 3$, and $E$ is on $AC$ with $AE : EC = 1 : 2$. The cevians $AD$ and $BE$ cross at $P$.'),
          prose('Balance at $D$ with $3$ at $B$ and $2$ at $C$. To balance at $E$, $A$ needs twice the mass at $C$:'),
          maths('m_{A} = 2 \\times 2 = 4'),
          maths('m_{D} = 3 + 2 = 5'),
          prose('$P$ balances $A$ against $D$, so the lengths go the other way round from the masses:'),
          maths('AP : PD = 5 : 4'),
        ),
        ask('cm-ag-mass-table'),
        ask('cm-ag-mass-cevians'),
        askAfter(
          'cm-ag-mass-cevians+choice',
          2,
          prose('The other cevian works the same way, with $E$ carrying the masses at $A$ and $C$. In the triangle above:'),
          maths('m_{E} = 4 + 2 = 6'),
          maths('BP : PE = 6 : 3 = 2 : 1'),
        ),
        ask('cm-ag-mass-table', 2),
        teach(
          prose('**Working back.** $D$ is on $BC$ with $BD : DC = 1 : 2$, $P$ is on $AD$ with $AP : PD = 3 : 2$, and $BP$ meets $AC$ at $E$. Find $AE : EC$.'),
          prose('Put $2$ at $B$ and $1$ at $C$, so $D$ carries $3$. $P$ balances $A$ against $D$:'),
          maths('m_{A} \\times 3 = 3 \\times 2'),
          maths('m_{A} = 2'),
          prose('$E$ balances $A$ against $C$:'),
          maths('AE : EC = m_{C} : m_{A} = 1 : 2'),
          prose('Copying $AP : PD = 3 : 2$ across is the trap.'),
        ),
        ask('cm-ag-mass-reverse'),
        askAfter(
          'cm-ag-mass-ceva',
          1,
          prose('Three cevians $AD$, $BE$ and $CF$ through one point all pass through the balance point of the whole triangle, so the third one balances too.'),
          prose('With $BD : DC = 2 : 3$ and $AE : EC = 1 : 2$, the masses are $4$ at $A$, $3$ at $B$ and $2$ at $C$, as before. $F$ balances $A$ against $B$:'),
          maths('AF : FB = m_{B} : m_{A} = 3 : 4'),
        ),
        askAfter(
          'cm-ag-mass-reverse+choice',
          2,
          prose('For $BP : PE$ in the working-back triangle, $E$ carries the masses at $A$ and $C$:'),
          maths('m_{E} = 2 + 1 = 3'),
          maths('BP : PE = m_{E} : m_{B} = 3 : 2'),
        ),
        askAfter(
          'cm-ag-mass-ceva',
          2,
          prose('Given $AF : FB$ instead, go round from $B$. With $BD : DC = 1 : 2$ and $AF : FB = 3 : 1$, put $2$ at $B$ and $1$ at $C$. $F$ balances $A$ against $B$, so $A$ gets a third of $B$’s mass:'),
          maths('m_{A} = \\frac{2}{3}'),
          prose('Scale every mass by $3$ to clear the fraction: $2$ at $A$, $6$ at $B$ and $3$ at $C$. Then'),
          maths('AE : EC = m_{C} : m_{A} = 3 : 2'),
        ),
      ],
      skillCheck: [ask('cm-ag-mass-cevians', 2), ask('cm-ag-mass-reverse', 2), ask('cm-ag-mass-ceva', 2)],
    },
    {
      id: 'cm-l19-complex',
      title: 'Complex Number Geometry',
      slides: [
        teach(
          prose('Multiplying by $i$ **turns a point $90^\\circ$ anticlockwise** about $0$, keeping its distance:'),
          maths('i(3 + 2i) = 3i + 2i^{2} = -2 + 3i'),
          prose('Multiplying by $-i$ turns it clockwise. To turn about another point $w$, move $w$ to the origin, turn, and move back. Turning $z = 4 + i$ anticlockwise about $w = 1 + 2i$:'),
          maths('z - w = 3 - i'),
          maths('i(3 - i) = 1 + 3i'),
          maths('(1 + 3i) + (1 + 2i) = 2 + 5i'),
        ),
        ask('cm-ag-rotate'),
        askAfter(
          'cm-ag-turn-area',
          1,
          prose('Since $iz$ is $z$ turned $90^\\circ$ about $0$, the triangle $0$, $z$, $iz$ has a right angle at $0$ and two sides of length $|z|$. For $z = 3 + i$:'),
          maths('|z|^{2} = 9 + 1 = 10'),
          maths('\\text{area} = \\frac{1}{2}|z|^{2} = 5'),
        ),
        askAfter(
          'cm-ag-rotate',
          2,
          prose('A square $ABCD$ going anticlockwise: each side is the one before turned $90^\\circ$ anticlockwise. With $A = 1$ and $B = 3 + i$:'),
          maths('B - A = 2 + i'),
          maths('i(2 + i) = -1 + 2i'),
          maths('C = (3 + i) + (-1 + 2i) = 2 + 3i'),
          maths('D = 1 + (-1 + 2i) = 2i'),
        ),
        askAfter(
          'cm-ag-turn-area+choice',
          2,
          prose('Turn $z$ again and again and you get $z$, $iz$, $-z$ and $-iz$: a square centred on $0$. Its diagonal runs from $z$ to $-z$, so it is $2|z|$ long, and a square’s area is half its diagonal squared:'),
          maths('\\frac{1}{2}(2|z|)^{2} = 2|z|^{2}'),
        ),
        teach(
          prose('**Moduli multiply**, so a modulus never needs anything multiplied out:'),
          maths('|zw| = |z||w|, \\qquad |z^{n}| = |z|^{n}'),
          maths('|(3 + 4i)^{2}(5 - 12i)| = 5^{2} \\times 13 = 325'),
          prose('**Circles.** $|z - c| = r$ is a circle of radius $r$ about $c$, and $|z|$ is the distance from $0$. The nearest and farthest points lie on the line through $0$ and the centre. For the circle'),
          maths('|z - 6 - 8i| = 3'),
          prose('the centre is $|6 + 8i|$, which is $10$, from $0$, so'),
          maths('10 + 3 = 13'),
          prose('is the greatest $|z|$ can be.'),
        ),
        ask('cm-ag-modulus'),
        ask('cm-ag-reach'),
        askAfter(
          'cm-ag-modulus+choice',
          2,
          prose('Dividing works the same way. A modulus like $|1 + 2i|$, which is $\\sqrt{5}$, is no trouble raised to an even power:'),
          maths('|1 + 2i|^{2} = 1 + 4 = 5'),
          maths('\\left|\\frac{(3 + 4i)^{3}}{(1 + 2i)^{2}}\\right| = \\frac{125}{5} = 25'),
        ),
        askAfter(
          'cm-ag-reach+choice',
          2,
          prose('The least value is one radius short of the centre, so $7$ for the circle above:'),
          maths('10 - 3 = 7'),
          prose('But if the radius is longer than the distance to the centre, the origin is inside the circle, and the nearest point is on the far side of it. For the circle'),
          maths('|z - 6 - 8i| = 14'),
          prose('the least value is'),
          maths('14 - 10 = 4'),
        ),
      ],
      skillCheck: [ask('cm-ag-rotate', 2), ask('cm-ag-modulus', 2), ask('cm-ag-reach', 2)],
    },
  ],
  levelCheck: [
    ask('cm-ag-river', 2),
    ask('cm-ag-lattice+choice', 2),
    ask('cm-ag-pick', 2),
    ask('cm-ag-line-distance', 2),
    ask('cm-ag-ellipse', 2),
    ask('cm-ag-circle-centre', 2),
    ask('cm-ag-parabola+choice', 2),
    ask('cm-ag-mass-cevians', 2),
    ask('cm-ag-mass-reverse+choice', 2),
    ask('cm-ag-mass-ceva', 2),
    ask('cm-ag-rotate', 2),
    ask('cm-ag-modulus', 2),
    ask('cm-ag-reach+choice', 2),
  ],
};
