/**
 * Contest Math, Level 9: Fast Problem-Solving. Mental shortcuts that beat long
 * arithmetic: friendly pairs, numbers near a round one, powers with a common
 * exponent, roots pulled apart, and chains of operations run backwards.
 * Generators in `generators/contestFast.ts`.
 */
import type { Level } from '../../types';
import { teach, ask, prose, maths, askAfter } from './blocks';

export const fastProblemSolving: Level = {
  id: 'cm-l9',
  title: 'Fast Problem-Solving',
  lessons: [
    {
      id: 'cm-l9-efficiency',
      title: 'Efficiency',
      slides: [
        teach(
          prose('Contest arithmetic is rarely long. Before multiplying, look for a pair that makes a round number:'),
          maths('25 \\times 4 = 100'),
          maths('125 \\times 8 = 1000'),
          prose('Multiplication works in any order, so bring the pair together first:'),
          maths('25 \\times 37 \\times 4 = 25 \\times 4 \\times 37'),
          maths('= 100 \\times 37 = 3700'),
        ),
        ask('cm-friendly-product'),
        askAfter(
          'cm-friendly-split-tiles',
          1,
          prose('When the partner is hidden inside another number, split that number to free it. $36$ is $4$ lots of $9$:'),
          maths('25 \\times 36 = 25 \\times 4 \\times 9'),
          maths('= 100 \\times 9 = 900'),
        ),
        askAfter(
          'cm-regroup-sum',
          1,
          prose('Sums regroup the same way. Pair the numbers whose units and tens make a whole hundred:'),
          maths('38 + 57 + 62 + 43'),
          maths('= (38 + 62) + (57 + 43)'),
          maths('= 100 + 100 = 200'),
        ),
        askAfter('cm-friendly-product+choice', 2, prose('One of the numbers hides the partner: split it, as $28$ is $4 \\times 7$.')),
        teach(
          prose('A number just under a round one is easier as the round one, minus a little:'),
          maths('298 + 399 = 300 + 400 - 2 - 1'),
          maths('= 700 - 3 = 697'),
          prose('Dividing by $25$ is multiplying by $4$ and dividing by $100$, since $25$ is $100 \\div 4$:'),
          maths('3700 \\times 4 = 14800'),
          maths('14800 \\div 100 = 148'),
          prose('In the same way, dividing by $5$ is doubling and dividing by $10$.'),
        ),
        ask('cm-divide-quick'),
        ask('cm-regroup-sum+choice', 2),
        askAfter(
          'cm-divide-quick+choice',
          2,
          prose('For $125$, use $1000 \\div 8$: multiply by $8$, then divide by $1000$. For $250$, use $1000 \\div 4$.'),
          maths('6000 \\div 125 = 6000 \\times 8 \\div 1000'),
          maths('= 48000 \\div 1000 = 48'),
        ),
        ask('cm-friendly-split-tiles', 2),
      ],
      skillCheck: [ask('cm-friendly-product', 2), ask('cm-regroup-sum', 2), ask('cm-divide-quick+choice', 2)],
    },
    {
      id: 'cm-l9-calculations',
      title: 'Calculations',
      slides: [
        teach(
          prose('Two numbers just under $100$ multiply fast. $97$ is $3$ under and $94$ is $6$ under. Take one gap off the other number and multiply by $100$:'),
          maths('97 - 6 = 91'),
          maths('91 \\times 100 = 9100'),
          prose('Then add the product of the gaps:'),
          maths('3 \\times 6 = 18'),
          maths('97 \\times 94 = 9100 + 18 = 9118'),
          prose('It works because $(100 - 3)(100 - 6)$ multiplies out to $100 \\times 91 + 18$.'),
        ),
        ask('cm-near-hundred'),
        askAfter(
          'cm-five-square',
          1,
          prose('To square a number ending in $5$, multiply its tens by the next number up, then write $25$ after. For $35^2$:'),
          maths('3 \\times 4 = 12'),
          maths('35^2 = 1225'),
        ),
        askAfter(
          'cm-mid-square-steps',
          1,
          prose('Two numbers either side of one ending in $5$ are a difference of two squares, and the square is quick:'),
          maths('63 \\times 67 = 65^2 - 2^2'),
          maths('= 4225 - 4 = 4221'),
        ),
        askAfter(
          'cm-near-hundred+choice',
          2,
          prose('With one number over and one under, the gaps have opposite signs, so their product is taken off. $104$ is $4$ over, $97$ is $3$ under:'),
          maths('104 - 3 = 101'),
          maths('101 \\times 100 - 4 \\times 3'),
          maths('= 10100 - 12 = 10088'),
        ),
        teach(
          prose('Split a number near a round one and multiply each part:'),
          maths('47 \\times 99 = 47 \\times 100 - 47'),
          maths('= 4700 - 47 = 4653'),
          prose('Read it backwards too. When two products share a factor, take it out first:'),
          maths('37 \\times 83 + 37 \\times 17 = 37 \\times (83 + 17)'),
          maths('= 37 \\times 100 = 3700'),
        ),
        ask('cm-distribute'),
        askAfter(
          'cm-five-square+choice',
          2,
          prose('The trick for $5$ works whenever the tens match and the units add to $10$. For $43 \\times 47$:'),
          maths('4 \\times 5 = 20'),
          maths('3 \\times 7 = 21'),
          maths('43 \\times 47 = 2021'),
          prose('The units part always fills two places: $41 \\times 49$ is $20$ then $09$, so $2009$.'),
        ),
        ask('cm-distribute+choice', 2),
        ask('cm-mid-square-steps', 2),
      ],
      skillCheck: [ask('cm-near-hundred', 2), ask('cm-five-square', 2), ask('cm-distribute', 2)],
    },
    {
      id: 'cm-l9-exponents',
      title: 'Exponents',
      slides: [
        teach(
          prose('Which is larger, $2^{30}$ or $3^{20}$? Both exponents are multiples of $10$, so give them the same exponent:'),
          maths('2^{30} = (2^3)^{10} = 8^{10}'),
          maths('3^{20} = (3^2)^{10} = 9^{10}'),
          prose('Now the exponents match and $9$ beats $8$, so $3^{20}$ is larger, even though its exponent is smaller.'),
        ),
        ask('cm-compare-powers'),
        askAfter(
          'cm-units-sum',
          1,
          prose('For the last digit of a sum, find each power’s last digit from its cycle, then add. Powers of $3$ end in $3, 9, 7, 1$ and powers of $7$ in $7, 9, 3, 1$.'),
          prose('$22$ leaves $2$ on dividing by $4$, so $3^{22}$ ends in $9$ and $7^{22}$ in $9$ too:'),
          maths('9 + 9 = 18'),
          prose('So $3^{22} + 7^{22}$ ends in $8$.'),
        ),
        askAfter(
          'cm-compare-powers',
          2,
          prose('Three at once works the same way: find one number that divides every exponent, and write each as a power with that exponent.'),
        ),
        teach(
          prose('A $2$ and a $5$ make a $10$. So pair them off, and count what is left:'),
          maths('2^{12} \\times 5^{10} = 2^2 \\times 2^{10} \\times 5^{10}'),
          maths('= 4 \\times 10^{10}'),
          prose('That is $4$ followed by ten zeros, which has $11$ digits.'),
        ),
        ask('cm-power-digits'),
        ask('cm-power-digits-table'),
        askAfter(
          'cm-power-digits+choice',
          2,
          prose('Other bases are powers of $2$ or $5$ in disguise. Rewrite them first:'),
          maths('8^4 = (2^3)^4 = 2^{12}'),
          maths('25^3 = (5^2)^3 = 5^6'),
        ),
        askAfter(
          'cm-units-sum+choice',
          2,
          prose('For a difference, take the last digits away. If the first is smaller, borrow $10$, just as in a column subtraction. A number ending in $3$ minus one ending in $7$:'),
          maths('13 - 7 = 6'),
          prose('So the result ends in $6$.'),
        ),
        ask('cm-power-digits-table', 2),
      ],
      skillCheck: [ask('cm-compare-powers', 2), ask('cm-power-digits', 2), ask('cm-units-sum', 2)],
    },
    {
      id: 'cm-l9-roots',
      title: 'Roots',
      slides: [
        teach(
          prose('To place a root between whole numbers, find the squares either side. $180$ is between $169$ and $196$:'),
          maths('13^2 = 169'),
          maths('14^2 = 196'),
          prose('So $\\sqrt{180}$ is between $13$ and $14$.'),
          prose('Roots multiply under one root, which can turn two awkward roots into a whole number:'),
          maths('\\sqrt{18} \\times \\sqrt{32} = \\sqrt{576}'),
          maths('= 24'),
        ),
        ask('cm-root-between'),
        askAfter(
          'cm-root-product',
          1,
          prose('Spot the square without multiplying out: $18$ is $2 \\times 9$ and $32$ is $2 \\times 16$, so the product is $2^2 \\times 9 \\times 16$:'),
          maths('\\sqrt{2^2 \\times 9 \\times 16} = 2 \\times 3 \\times 4'),
          maths('= 24'),
        ),
        askAfter(
          'cm-surd-sum-tiles',
          1,
          prose('Pull square factors out of a root, and roots of the same number collect like $x$ does:'),
          maths('\\sqrt{50} = \\sqrt{25} \\times \\sqrt{2} = 5\\sqrt{2}'),
          maths('\\sqrt{18} = 3\\sqrt{2}'),
          maths('\\sqrt{50} + \\sqrt{18} = 8\\sqrt{2}'),
        ),
        askAfter(
          'cm-root-between+choice',
          2,
          prose('To count the whole numbers between two roots, count the squares between the two numbers. Between $\\sqrt{30}$ and $\\sqrt{90}$ lie $6$, $7$, $8$ and $9$:'),
          maths('6^2 = 36'),
          maths('9^2 = 81'),
          prose('That is $4$ whole numbers.'),
        ),
        teach(
          prose('A root inside a root can sometimes be undone. Square a sum of two roots:'),
          maths('(\\sqrt{5} + \\sqrt{2})^2 = 5 + 2 + 2\\sqrt{10}'),
          maths('= 7 + 2\\sqrt{10}'),
          prose('So $\\sqrt{7 + 2\\sqrt{10}}$ is $\\sqrt{5} + \\sqrt{2}$. To undo one, look for two numbers that add to the whole number, $7$, and multiply to the number under the inner root, $10$.'),
          prose('Splitting $\\sqrt{7 + 2\\sqrt{10}}$ into $\\sqrt{7}$ plus the root of the rest is the trap: a root of a sum is not a sum of roots.'),
        ),
        ask('cm-nested-root'),
        ask('cm-surd-sum-tiles', 2),
        askAfter(
          'cm-root-product',
          2,
          prose('Four numbers in a row: pair the outside two and the inside two. For $4 \\times 5 \\times 6 \\times 7 + 1$:'),
          maths('4 \\times 7 = 28'),
          maths('5 \\times 6 = 30'),
          prose('Two numbers $2$ apart, plus $1$, make the square of the number between them:'),
          maths('28 \\times 30 + 1 = 29^2'),
        ),
        askAfter(
          'cm-nested-root',
          2,
          prose('With a minus sign it is a difference, larger root first, since a square root is never negative:'),
          maths('(\\sqrt{5} - \\sqrt{2})^2 = 7 - 2\\sqrt{10}'),
          maths('\\sqrt{7 - 2\\sqrt{10}} = \\sqrt{5} - \\sqrt{2}'),
        ),
      ],
      skillCheck: [ask('cm-root-between', 2), ask('cm-root-product+choice', 2), ask('cm-nested-root', 2)],
    },
    {
      id: 'cm-l9-whats-the-number',
      title: 'What’s the Number?',
      slides: [
        teach(
          prose('I think of a number, multiply it by $3$, add $7$ and then halve the result. The answer is $20$.'),
          prose('Work backwards, undoing each step from the last. Halving is undone by doubling:'),
          maths('20 \\times 2 = 40'),
          maths('40 - 7 = 33'),
          maths('33 \\div 3 = 11'),
          prose('The number was $11$.'),
        ),
        ask('cm-undo-number'),
        ask('cm-undo-table'),
        askAfter(
          'cm-always-same',
          1,
          prose('Some chains give the same answer whatever you start with. Call the number $n$: add $5$, double, take away $4$, halve.'),
          maths('n + 5'),
          maths('2n + 10'),
          maths('2n + 6'),
          maths('n + 3'),
          prose('Taking away $n$ leaves $3$ every time.'),
        ),
        ask('cm-undo-number+choice', 2),
        teach(
          prose('A two-digit number with digits $a$ and $b$ is worth $10a + b$. Swapping the digits changes it by a multiple of $9$:'),
          maths('(10b + a) - (10a + b) = 9(b - a)'),
          prose('So if the digits add to $11$ and swapping makes the number $27$ bigger, the digits differ by $3$:'),
          maths('b - a = 3'),
          maths('a + b = 11'),
          prose('The digits are $4$ and $7$, and the number is $47$.'),
        ),
        ask('cm-place-value'),
        askAfter('cm-always-same', 2, prose('Longer chains work the same way: follow $n$ through every step, and see whether it cancels at the end.')),
        askAfter(
          'cm-place-value+choice',
          2,
          prose('Writing a digit on the end of a number $N$ shifts every digit up a place: writing $7$ on the end makes $10N + 7$. So the increase is'),
          maths('10N + 7 - N = 9N + 7'),
          prose('If that is $412$, then $N$ is $45$.'),
        ),
        ask('cm-undo-table', 2),
      ],
      skillCheck: [ask('cm-undo-number', 2), ask('cm-place-value', 2), ask('cm-always-same', 2)],
    },
  ],
  levelCheck: [
    ask('cm-friendly-product', 2),
    ask('cm-regroup-sum+choice', 2),
    ask('cm-divide-quick', 2),
    ask('cm-near-hundred', 2),
    ask('cm-five-square+choice', 2),
    ask('cm-distribute', 2),
    ask('cm-compare-powers', 2),
    ask('cm-power-digits', 2),
    ask('cm-units-sum', 2),
    ask('cm-root-between', 2),
    ask('cm-root-product', 2),
    ask('cm-nested-root', 1),
    ask('cm-undo-number', 2),
    ask('cm-place-value+choice', 2),
  ],
};
