/**
 * Contest Math, Level 20: Trigonometry. One ratio gives the rest and the
 * quadrant gives the sign; whole turns change nothing and sin² pairs with
 * cos²; the law of cosines at 60° and 120°, and a parallelogram whose
 * cosines cancel; a/sin A as the circle's diameter and the height that
 * decides how many triangles fit; squaring sin θ + cos θ, dividing by cos θ
 * and the reach of a sin x + b cos x; and z^n − 1 factorised over the roots
 * of unity. Generators in `generators/contestTrigonometry.ts`.
 */
import type { Level } from '../../types';
import { teach, ask, prose, maths, askAfter } from './blocks';

export const contestTrig: Level = {
  id: 'cm-l20',
  title: 'Trigonometry',
  lessons: [
    {
      id: 'cm-l20-functions',
      title: 'Trigonometric Functions',
      slides: [
        teach(
          prose('On the unit circle, the point at angle $\\theta$ round from the positive $x$-axis is $(\\cos\\theta, \\sin\\theta)$, and $\\tan\\theta$ is $\\sin\\theta \\div \\cos\\theta$. For an acute angle that is a right triangle: opposite over hypotenuse, adjacent over hypotenuse, opposite over adjacent.'),
          prose('One ratio gives the others. If $\\theta$ is acute and $\\tan\\theta = \\frac{5}{12}$, draw a right triangle with opposite side $5$ and adjacent side $12$. The hypotenuse is'),
          maths('\\sqrt{5^{2} + 12^{2}} = 13'),
          maths('\\sin\\theta = \\frac{5}{13}, \\qquad \\cos\\theta = \\frac{12}{13}'),
          prose('Type a fraction with the / key.'),
        ),
        ask('cm-tr-other-ratio'),
        askAfter(
          'cm-tr-other-ratio+choice',
          2,
          prose('Past $90^\\circ$ the point is to the left of the vertical axis, so the cosine is negative, and so is the tangent. The sine stays positive until $180^\\circ$.'),
          prose('If $\\theta$ is between $90^\\circ$ and $180^\\circ$ and $\\sin\\theta = \\frac{5}{13}$, the triangle is the same, but'),
          maths('\\cos\\theta = -\\frac{12}{13}, \\qquad \\tan\\theta = -\\frac{5}{12}'),
        ),
        askAfter(
          'cm-tr-exact-table',
          1,
          prose('Measure any angle from the nearer side of the horizontal axis. $150^\\circ$ is $30^\\circ$ short of $180^\\circ$, in the second quadrant, where the sine is positive and the cosine negative:'),
          maths('\\sin 150^\\circ = \\sin 30^\\circ = \\frac{1}{2}'),
          maths('\\cos 150^\\circ = -\\cos 30^\\circ = -\\frac{\\sqrt{3}}{2}'),
          prose('The sines of $30^\\circ$, $45^\\circ$ and $60^\\circ$ are $\\frac{1}{2}$, $\\frac{\\sqrt{2}}{2}$ and $\\frac{\\sqrt{3}}{2}$, and their cosines are the same three the other way round.'),
        ),
        teach(
          prose('Whole turns change nothing: $360^\\circ$ brings the point back where it started. For $\\sin 1110^\\circ$, take off whole turns:'),
          maths('1110 - 3 \\times 360 = 30'),
          maths('\\sin 1110^\\circ = \\sin 30^\\circ = \\frac{1}{2}'),
          prose('Sine and cosine swap at the complement:'),
          maths('\\sin(90^\\circ - x) = \\cos x'),
          prose('So squares pair up to make $1$:'),
          maths('\\sin^{2} 20^\\circ + \\sin^{2} 70^\\circ = \\sin^{2} 20^\\circ + \\cos^{2} 20^\\circ = 1'),
          prose('In this sum the $8$ terms make $4$ pairs, so it comes to $4$:'),
          maths('\\sin^{2} 10^\\circ + \\sin^{2} 20^\\circ + \\cdots + \\sin^{2} 80^\\circ'),
          prose('With an odd number of terms the middle one is $\\sin^{2} 45^\\circ$, which is $\\frac{1}{2}$.'),
        ),
        ask('cm-tr-big-angle'),
        ask('cm-tr-square-sum'),
        askAfter(
          'cm-tr-big-angle+choice',
          2,
          prose('A negative angle turns the other way. Add whole turns until it lands between $0^\\circ$ and $360^\\circ$:'),
          maths('-750 + 3 \\times 360 = 330'),
          maths('\\cos(-750^\\circ) = \\cos 330^\\circ = \\frac{\\sqrt{3}}{2}'),
        ),
        askAfter(
          'cm-tr-square-sum+choice',
          2,
          prose('When the sum runs from one step up to $90^\\circ$, the last term has no partner. Pair the rest and add it on its own:'),
          maths('\\sin^{2} 90^\\circ = 1, \\qquad \\cos^{2} 90^\\circ = 0'),
          prose('A sum from $0^\\circ$ to $90^\\circ$ pairs $0^\\circ$ with $90^\\circ$, so there every term has a partner.'),
        ),
        ask('cm-tr-exact-table', 2),
      ],
      skillCheck: [ask('cm-tr-other-ratio', 2), ask('cm-tr-big-angle', 2), ask('cm-tr-square-sum', 2)],
    },
    {
      id: 'cm-l20-cosines',
      title: 'Law of Cosines',
      slides: [
        teach(
          prose('The law of cosines is Pythagoras with a correction for the angle. In any triangle, with $C$ the angle between sides $a$ and $b$:'),
          maths('c^{2} = a^{2} + b^{2} - 2ab\\cos C'),
          prose('At $60^\\circ$ the cosine is $\\frac{1}{2}$, so the correction is just $ab$. Sides $3$ and $8$ with $60^\\circ$ between them:'),
          maths('c^{2} = 9 + 64 - 24 = 49'),
          maths('c = 7'),
          prose('The trap is Pythagoras, which gives $\\sqrt{73}$: that is only right at $90^\\circ$.'),
        ),
        ask('cm-tr-cos-side'),
        askAfter(
          'cm-tr-cos-angle',
          1,
          prose('Turned round, the law gives an angle from three sides. In the triangle with sides $5$, $7$ and $8$, the angle opposite the $7$:'),
          maths('\\cos\\theta = \\frac{5^{2} + 8^{2} - 7^{2}}{2 \\times 5 \\times 8}'),
          maths('\\cos\\theta = \\frac{40}{80} = \\frac{1}{2}'),
          prose('So $\\theta = 60^\\circ$. A cosine of $-\\frac{1}{2}$ would mean $120^\\circ$.'),
        ),
        ask('cm-tr-cos-table'),
        askAfter(
          'cm-tr-cos-side+choice',
          2,
          prose('At $120^\\circ$ the cosine is $-\\frac{1}{2}$, so the correction is added. Sides $3$ and $5$ with $120^\\circ$ between them:'),
          maths('c^{2} = 9 + 25 + 15 = 49'),
          maths('c = 7'),
        ),
        teach(
          prose('A parallelogram with sides $a$ and $b$: neighbouring angles add to $180^\\circ$, so their cosines are opposite. Each diagonal is the third side of a triangle with sides $a$ and $b$:'),
          maths('p^{2} = a^{2} + b^{2} - 2ab\\cos A'),
          maths('q^{2} = a^{2} + b^{2} + 2ab\\cos A'),
          prose('Add them and the cosines cancel:'),
          maths('p^{2} + q^{2} = 2(a^{2} + b^{2})'),
          prose('Sides $7$ and $9$ with one diagonal $8$:'),
          maths('q^{2} = 2(49 + 81) - 64 = 196'),
          maths('q = 14'),
        ),
        ask('cm-tr-parallelogram'),
        askAfter(
          'cm-tr-cos-angle+choice',
          2,
          prose('Sometimes the sides come as an equation:'),
          maths('(a + b + c)(a + b - c) = 3ab'),
          prose('The brackets are a sum and a difference:'),
          maths('(a + b)^{2} - c^{2} = 3ab'),
          maths('a^{2} + b^{2} - c^{2} = ab'),
          prose('That is the top of the law of cosines, so'),
          maths('\\cos C = \\frac{ab}{2ab} = \\frac{1}{2}'),
          prose('and $C = 60^\\circ$.'),
        ),
        askAfter(
          'cm-tr-parallelogram+choice',
          2,
          prose('A median is half a diagonal. With $M$ the midpoint of $BC$, carry $AM$ on its own length past $M$: the four points make a parallelogram with sides $AB$ and $AC$ and diagonals $BC$ and $2AM$. With $AB = 13$, $AC = 9$ and $BC = 10$:'),
          maths('(2AM)^{2} + 10^{2} = 2(13^{2} + 9^{2})'),
          maths('4AM^{2} = 500 - 100 = 400'),
          maths('AM = 10'),
        ),
        askAfter(
          'cm-tr-cos-table',
          2,
          prose('When $c^{2}$ is more than $a^{2} + b^{2}$ the top is negative, so the cosine is negative and $C$ is obtuse.'),
        ),
      ],
      skillCheck: [ask('cm-tr-cos-side', 2), ask('cm-tr-cos-angle', 2), ask('cm-tr-parallelogram', 2)],
    },
    {
      id: 'cm-l20-sines',
      title: 'Law of Sines',
      slides: [
        teach(
          prose('The law of sines: each side over the sine of the angle opposite it gives the same number, and that number is the diameter of the circle through the three corners:'),
          maths('\\frac{a}{\\sin A} = \\frac{b}{\\sin B} = \\frac{c}{\\sin C} = 2R'),
          prose('With $BC = 7$ and $\\angle A = 30^\\circ$:'),
          maths('2R = 7 \\div \\frac{1}{2} = 14'),
          prose('so $R = 7$. And $\\sin 150^\\circ = \\sin 30^\\circ$, so an angle of $150^\\circ$ gives the same circle. Turned round, each side is the diameter times a sine:'),
          maths('a = 2R\\sin A'),
        ),
        ask('cm-tr-circumradius'),
        ask('cm-tr-sine-table'),
        askAfter(
          'cm-tr-sine-side',
          1,
          prose('Two angles and a side give the other sides. With $\\angle A = 45^\\circ$, $\\angle B = 30^\\circ$ and $BC = 6\\sqrt{2}$, the side $AC$ is opposite $B$:'),
          maths('AC = BC \\times \\sin 30^\\circ \\div \\sin 45^\\circ'),
          maths('AC = 6\\sqrt{2} \\times \\frac{1}{2} \\div \\frac{\\sqrt{2}}{2} = 6'),
          prose('Type $2\\sqrt{3}$ as 2√(3), with the √( key.'),
        ),
        askAfter(
          'cm-tr-circumradius+choice',
          2,
          prose('With a root in the sine, clear it from the bottom. $BC = 9$ and $\\angle A = 60^\\circ$:'),
          maths('2R = 9 \\div \\frac{\\sqrt{3}}{2} = \\frac{18}{\\sqrt{3}} = 6\\sqrt{3}'),
          prose('so $R = 3\\sqrt{3}$. $120^\\circ$ has the same sine as $60^\\circ$, and $135^\\circ$ the same as $45^\\circ$.'),
        ),
        teach(
          prose('Two sides and an angle that is not between them can fit two triangles, one or none. Say $\\angle A = 30^\\circ$, $AC = 12$ and $BC = 8$. Draw the line from $A$ at $30^\\circ$; $B$ is on it, $8$ from $C$. The nearest the line comes to $C$ is the height'),
          maths('h = 12 \\sin 30^\\circ = 6'),
          prose('$BC = 8$ is more than $6$, so it reaches the line, and less than $AC = 12$, so it can swing to meet it in two places beyond $A$: two triangles.'),
          prose('Shorter than the height: none. Exactly the height, or at least as long as $AC$: one. With $\\angle A$ obtuse, $BC$ must be the longest side, so there is one triangle if $BC$ is longer than $AC$, and none otherwise.'),
        ),
        ask('cm-tr-ssa'),
        askAfter(
          'cm-tr-sine-side+choice',
          2,
          prose('If the angle opposite the side you want is not given, find it first: the three angles add to $180^\\circ$. With $\\angle A = 45^\\circ$ and $\\angle C = 105^\\circ$:'),
          maths('\\angle B = 180^\\circ - 45^\\circ - 105^\\circ = 30^\\circ'),
        ),
        askAfter(
          'cm-tr-ssa+choice',
          2,
          prose('When there are two triangles, the law of cosines at $A$ is a quadratic in $x = AB$, and its two roots are the two lengths. With $\\angle A = 30^\\circ$, $AC = 12$ and $BC = 8$:'),
          maths('8^{2} = 12^{2} + x^{2} - 2 \\times 12 \\times x \\cos 30^\\circ'),
          maths('x^{2} - 12\\sqrt{3}\\,x + 80 = 0'),
          prose('The product of the roots is the constant term:'),
          maths('12^{2} - 8^{2} = 80'),
        ),
        askAfter(
          'cm-tr-sine-table',
          2,
          prose('With a root in the radius, multiply the roots together. $R = 2\\sqrt{3}$ and $\\angle A = 60^\\circ$:'),
          maths('a = 4\\sqrt{3} \\times \\frac{\\sqrt{3}}{2} = 6'),
        ),
      ],
      skillCheck: [ask('cm-tr-circumradius', 2), ask('cm-tr-sine-side', 2), ask('cm-tr-ssa', 2)],
    },
    {
      id: 'cm-l20-identities',
      title: 'Trigonometric Identities',
      slides: [
        teach(
          prose('Square a sum of sine and cosine: the squares add to $1$ and leave only the cross term. If'),
          maths('\\sin\\theta + \\cos\\theta = \\frac{7}{5}'),
          prose('then'),
          maths('(\\sin\\theta + \\cos\\theta)^{2} = \\frac{49}{25}'),
          maths('1 + 2\\sin\\theta\\cos\\theta = \\frac{49}{25}'),
          maths('\\sin\\theta\\cos\\theta = \\frac{12}{25}'),
          prose('With a minus sign it is $1 - 2\\sin\\theta\\cos\\theta$ instead. There is no need to find $\\theta$.'),
        ),
        ask('cm-tr-sum-product'),
        askAfter(
          'cm-tr-tan-ratio',
          1,
          prose('Given $\\tan\\theta$, divide the top and the bottom by $\\cos\\theta$ and everything becomes $\\tan\\theta$. With $\\tan\\theta = 3$:'),
          maths('\\frac{2\\sin\\theta + \\cos\\theta}{\\sin\\theta - \\cos\\theta} = \\frac{2\\tan\\theta + 1}{\\tan\\theta - 1}'),
          maths('\\frac{2 \\times 3 + 1}{3 - 1} = \\frac{7}{2}'),
        ),
        askAfter(
          'cm-tr-double-table',
          1,
          prose('The double angles come from the ratios themselves:'),
          maths('\\sin 2\\theta = 2\\sin\\theta\\cos\\theta'),
          maths('\\cos 2\\theta = \\cos^{2}\\theta - \\sin^{2}\\theta'),
          prose('With $\\sin\\theta = \\frac{3}{5}$ and $\\cos\\theta = \\frac{4}{5}$:'),
          maths('\\sin 2\\theta = \\frac{24}{25}, \\qquad \\cos 2\\theta = \\frac{7}{25}'),
        ),
        askAfter(
          'cm-tr-sum-product+choice',
          2,
          prose('Over a common denominator, $\\tan\\theta + \\frac{1}{\\tan\\theta}$ has $\\sin^{2}\\theta + \\cos^{2}\\theta$ on top, which is $1$:'),
          maths('\\tan\\theta + \\frac{1}{\\tan\\theta} = \\frac{1}{\\sin\\theta\\cos\\theta}'),
          prose('With $\\sin\\theta\\cos\\theta = \\frac{12}{25}$ it is $\\frac{25}{12}$.'),
        ),
        teach(
          prose('How big can $3\\sin x + 4\\cos x$ get? Not $7$: the two parts peak at different $x$. Take out'),
          maths('\\sqrt{3^{2} + 4^{2}} = 5'),
          maths('3\\sin x + 4\\cos x = 5\\left(\\frac{3}{5}\\sin x + \\frac{4}{5}\\cos x\\right)'),
          prose('$\\frac{3}{5}$ and $\\frac{4}{5}$ are the cosine and sine of one angle $\\alpha$, since their squares add to $1$. So the bracket is $\\sin(x + \\alpha)$, which runs from $-1$ to $1$:'),
          maths('-5 \\le 3\\sin x + 4\\cos x \\le 5'),
        ),
        ask('cm-tr-max-value'),
        askAfter(
          'cm-tr-tan-ratio+choice',
          2,
          prose('With squares, first write the expression over $\\sin^{2}\\theta + \\cos^{2}\\theta$, which is $1$, then divide the top and the bottom by $\\cos^{2}\\theta$. With $\\tan\\theta = 2$:'),
          maths('\\sin\\theta\\cos\\theta = \\frac{\\sin\\theta\\cos\\theta}{\\sin^{2}\\theta + \\cos^{2}\\theta}'),
          maths('\\frac{\\tan\\theta}{\\tan^{2}\\theta + 1} = \\frac{2}{4 + 1} = \\frac{2}{5}'),
        ),
        askAfter(
          'cm-tr-max-value+choice',
          2,
          prose('A constant added moves the whole range. $10 + 3\\sin x + 4\\cos x$ runs from'),
          maths('10 - 5 = 5'),
          prose('up to'),
          maths('10 + 5 = 15'),
        ),
        askAfter(
          'cm-tr-double-table',
          2,
          prose('Between $90^\\circ$ and $180^\\circ$ the cosine is negative, so $\\sin 2\\theta$ is too. $\\cos 2\\theta$ has only squares in it, so it keeps its sign.'),
        ),
      ],
      skillCheck: [ask('cm-tr-sum-product', 2), ask('cm-tr-tan-ratio', 2), ask('cm-tr-max-value', 2)],
    },
    {
      id: 'cm-l20-roots-of-unity',
      title: 'Roots of Unity',
      slides: [
        teach(
          prose('The solutions of $z^{n} = 1$ are the $n$th roots of unity. Each has size $1$, and their angles are the multiples of $\\frac{360^\\circ}{n}$, so they sit evenly round the unit circle, the corners of a regular polygon.'),
          prose('Common solutions: $z^{12} = 1$ has its angles at the multiples of $30^\\circ$, and $z^{18} = 1$ at the multiples of $20^\\circ$. The angles on both lists are the multiples of $60^\\circ$:'),
          maths('\\gcd(12, 18) = 6'),
          prose('so there are $6$ common solutions, the solutions of $z^{6} = 1$.'),
        ),
        ask('cm-tr-common-roots'),
        askAfter(
          'cm-tr-unity-count-table',
          1,
          prose('Count by where the angles land. The solutions of $z^{10} = 1$ are $36^\\circ$ apart. The real ones are at $0^\\circ$ and $180^\\circ$: $2$. Real part above $0$ means the angle is strictly between $-90^\\circ$ and $90^\\circ$:'),
          maths('0^\\circ, \\quad \\pm 36^\\circ, \\quad \\pm 72^\\circ'),
          prose('which is $5$. The other $8$ pair off above and below the axis, so $4$ have imaginary part above $0$.'),
        ),
        askAfter(
          'cm-tr-root-polygon',
          1,
          prose('The solutions of $z^{4} = 9$ all have the same size. Take sizes of both sides:'),
          maths('|z|^{4} = 9'),
          maths('|z|^{2} = 3'),
          prose('They make a square: $4$ triangles from the centre, each with two sides $|z|$ and $90^\\circ$ between them. In general there are $n$ triangles with $\\frac{360^\\circ}{n}$ at the centre.'),
          maths('\\text{area} = 4 \\times \\frac{1}{2} \\times 3 \\times \\sin 90^\\circ = 6'),
        ),
        askAfter(
          'cm-tr-common-roots+choice',
          2,
          prose('Three equations at once: the common solutions are the solutions of $z^{g} = 1$, with $g$ the highest common factor of all three exponents:'),
          maths('\\gcd(12, 18, 27) = 3'),
        ),
        teach(
          prose('Write $\\omega$ for the first root round from $1$:'),
          maths('\\omega = \\cos\\frac{360^\\circ}{n} + i\\sin\\frac{360^\\circ}{n}'),
          prose('The $n$ roots are $1, \\omega, \\omega^{2}, \\ldots, \\omega^{n-1}$, so'),
          maths('z^{n} - 1 = (z - 1)(z - \\omega)\\cdots(z - \\omega^{n-1})'),
          prose('Divide both sides by $z - 1$:'),
          maths('(z - \\omega)\\cdots(z - \\omega^{n-1}) = 1 + z + \\cdots + z^{n-1}'),
          prose('So with $n = 3$ and $z = 2$, where $\\omega$ is at $120^\\circ$:'),
          maths('(2 - \\omega)(2 - \\omega^{2}) = 1 + 2 + 4 = 7'),
        ),
        ask('cm-tr-unity-product'),
        askAfter(
          'cm-tr-root-polygon+choice',
          2,
          prose('A minus sign only turns the solutions round the origin. $z^{3} = -8$ has $|z| = 2$, and its three solutions make an equilateral triangle: $3$ triangles from the centre with $120^\\circ$ at each.'),
          maths('\\text{area} = 3 \\times \\frac{1}{2} \\times 4 \\times \\frac{\\sqrt{3}}{2} = 3\\sqrt{3}'),
        ),
        askAfter(
          'cm-tr-unity-product+choice',
          2,
          prose('At $z = 1$ each of the $n$ terms on the right is $1$, so'),
          maths('(1 - \\omega)(1 - \\omega^{2})\\cdots(1 - \\omega^{n-1}) = n'),
          prose('For any other $z$ the right side is a geometric series:'),
          maths('1 + z + \\cdots + z^{n-1} = \\frac{z^{n} - 1}{z - 1}'),
        ),
        askAfter(
          'cm-tr-unity-count-table',
          2,
          prose('The solutions of $z^{n} = -1$ sit half a step round from those of $z^{n} = 1$. For $z^{4} = -1$ they are at $45^\\circ$, $135^\\circ$, $225^\\circ$ and $315^\\circ$: none is real, $2$ have real part above $0$, and $2$ have imaginary part above $0$.'),
        ),
      ],
      skillCheck: [ask('cm-tr-common-roots', 2), ask('cm-tr-root-polygon', 2), ask('cm-tr-unity-product', 2)],
    },
  ],
  levelCheck: [
    ask('cm-tr-other-ratio', 2),
    ask('cm-tr-big-angle+choice', 2),
    ask('cm-tr-square-sum', 2),
    ask('cm-tr-cos-side+choice', 2),
    ask('cm-tr-parallelogram', 2),
    ask('cm-tr-cos-angle', 2),
    ask('cm-tr-circumradius+choice', 2),
    ask('cm-tr-sine-side', 2),
    ask('cm-tr-ssa', 2),
    ask('cm-tr-sum-product+choice', 2),
    ask('cm-tr-max-value', 2),
    ask('cm-tr-tan-ratio', 2),
    ask('cm-tr-unity-product+choice', 2),
    ask('cm-tr-root-polygon', 2),
  ],
};
