/**
 * Contest Math, Level 12: More Advanced Algebra. Systems solved by adding or
 * subtracting whole equations, rates timed rather than followed, quadratics
 * by completing the square, powers put over one base, functions with a
 * symmetry to use, and logarithms changed to one base. Generators in
 * `generators/contestAdvancedAlgebra.ts`.
 */
import type { Level } from '../../types';
import { teach, ask, prose, maths, askAfter } from './blocks';

export const advancedAlgebra: Level = {
  id: 'cm-l12',
  title: 'More Advanced Algebra',
  lessons: [
    {
      id: 'cm-l12-systems',
      title: 'Systems of Equations',
      slides: [
        teach(
          prose('A system often asks for a combination of the unknowns, and that combination can come straight out of the equations without finding $x$ and $y$.'),
          prose('Say $x + y = 12$ and $x^2 - y^2 = 48$. Factorise the difference of squares:'),
          maths('x^2 - y^2 = (x + y)(x - y)'),
          maths('48 = 12(x - y)'),
          maths('x - y = 4'),
          prose('For $x$ itself, add the equations for $x + y$ and $x - y$, and $y$ cancels:'),
          maths('2x = 12 + 4 = 16'),
          prose('So $x = 8$.'),
        ),
        ask('cm-aa-sum-diff'),
        askAfter(
          'cm-aa-sum-diff+choice',
          2,
          prose('First $x - y$ from the difference of squares, then add it to $x + y$ and halve.'),
        ),
        askAfter(
          'cm-aa-swap-tiles',
          1,
          prose('When the coefficients swap places, add and subtract the whole equations. $4$ apples and $1$ pear cost $90$p, and $1$ apple and $4$ pears cost $60$p. With prices $A$ and $P$:'),
          maths('4A + P = 90'),
          maths('A + 4P = 60'),
          prose('Adding gives each letter $5$ times, and subtracting leaves $3$ of each:'),
          maths('5(A + P) = 150, \\qquad 3(A - P) = 30'),
          maths('A + P = 30, \\qquad A - P = 10'),
          prose('Add those two and $P$ cancels:'),
          maths('2A = 40'),
          prose('So an apple costs $20$p.'),
        ),
        teach(
          prose('When every equation holds the same letters, **add them all**. Take'),
          maths('2x + y + z = 17'),
          maths('x + 2y + z = 19'),
          maths('x + y + 2z = 24'),
          prose('Each letter appears $4$ times across the left sides:'),
          maths('4(x + y + z) = 17 + 19 + 24 = 60'),
          maths('x + y + z = 15'),
          prose('The first equation is $x + y + z$ with one more $x$, so'),
          maths('x = 17 - 15 = 2'),
        ),
        ask('cm-aa-cyclic'),
        ask('cm-aa-swap'),
        ask('cm-aa-cyclic+choice', 2),
        ask('cm-aa-swap-tiles', 2),
        ask('cm-aa-swap+choice', 2),
      ],
      skillCheck: [ask('cm-aa-sum-diff', 2), ask('cm-aa-cyclic', 2), ask('cm-aa-swap', 2)],
    },
    {
      id: 'cm-l12-rates',
      title: 'Rates and Ratios',
      slides: [
        teach(
          prose('Average speed is total distance over total time, never the average of the speeds.'),
          prose('Out at $30$ km/h and back at $60$ km/h: the distance is not given, so pick one both speeds divide, say $60$ km each way. The times are $2$ hours and $1$ hour:'),
          maths('120 \\div 3 = 40'),
          prose('The average is $40$ km/h. The average of the speeds, $45$, is the trap: more of the time is spent going slowly.'),
        ),
        ask('cm-aa-avg-speed'),
        ask('cm-aa-avg-speed-tiles'),
        askAfter(
          'cm-aa-avg-speed+choice',
          2,
          prose('Backwards: out at $20$ km/h, how fast back for an average of $30$? Take $60$ km each way. The whole $120$ km at $30$ km/h takes $4$ hours, and the way out used $3$ of them:'),
          maths('60 \\div 1 = 60'),
          prose('So $60$ km/h. The tempting $40$ averages the speeds again.'),
        ),
        teach(
          prose('**Time it, don’t follow it.** Two friends $12$ km apart walk towards each other at $2$ and $4$ km/h. Their dog runs between them at $10$ km/h until they meet. Adding up the zigzags is hopeless; the gap closes at $6$ km/h, so they meet after'),
          maths('12 \\div 6 = 2 \\text{ hours}'),
          prose('and the dog runs for all of that time:'),
          maths('10 \\times 2 = 20 \\text{ km}'),
        ),
        ask('cm-aa-meet'),
        askAfter(
          'cm-aa-fill-drain',
          1,
          prose('Rates add, times do not. A tap fills a tank in $4$ minutes and a leak empties it in $12$. Each minute:'),
          maths('\\frac{1}{4} - \\frac{1}{12} = \\frac{1}{6}'),
          prose('of the tank fills, so it takes $6$ minutes.'),
        ),
        askAfter(
          'cm-aa-meet+choice',
          2,
          prose('A chase closes at the **difference** of the speeds. Ann walks at $4$ km/h; Ben follows $2$ hours later at $12$ km/h. She is $8$ km ahead, and he gains $8$ km/h, so he catches her after $1$ hour, $12$ km from the start.'),
        ),
        askAfter(
          'cm-aa-fill-drain+choice',
          2,
          prose('Two taps and a leak: add both taps, take the leak away. Taps of $3$ and $6$ minutes with a leak of $4$:'),
          maths('\\frac{1}{3} + \\frac{1}{6} - \\frac{1}{4} = \\frac{1}{4}'),
          prose('So the tank fills in $4$ minutes.'),
        ),
        ask('cm-aa-avg-speed-tiles', 2),
      ],
      skillCheck: [ask('cm-aa-avg-speed', 2), ask('cm-aa-meet', 2), ask('cm-aa-fill-drain', 2)],
    },
    {
      id: 'cm-l12-quadratics',
      title: 'Quadratics',
      slides: [
        teach(
          prose('To find the least value of a quadratic, **complete the square**. Half the $x$ coefficient of $x^2 - 8x + 21$ is $-4$, and $(x - 4)^2 = x^2 - 8x + 16$, so'),
          maths('x^2 - 8x + 21 = (x - 4)^2 + 5'),
          prose('A square is never negative, so the least value is $5$, when $x = 4$. The constant, $21$, is the trap.'),
        ),
        ask('cm-aa-square-tiles'),
        ask('cm-aa-complete-square'),
        askAfter(
          'cm-aa-complete-square+choice',
          2,
          prose('With a number in front of $x^2$, take it out of the $x$ terms first:'),
          maths('3x^2 + 12x + 20 = 3(x^2 + 4x) + 20'),
          maths('= 3(x + 2)^2 - 12 + 20'),
          maths('= 3(x + 2)^2 + 8'),
          prose('So the least value is $8$.'),
        ),
        ask('cm-aa-square-tiles', 2),
        teach(
          prose('Two quadratics with a **common root**: take one from the other, and the $x^2$ terms cancel. For'),
          maths('x^2 + x - 6 = 0'),
          maths('x^2 + 4x - 12 = 0'),
          prose('the first take away the second leaves'),
          maths('-3x + 6 = 0'),
          prose('so the common root is $2$. The roots of the second multiply to $-12$, so its other root is $-6$.'),
        ),
        ask('cm-aa-shared-root'),
        askAfter(
          'cm-aa-nested-root',
          1,
          prose('A pattern that goes on forever contains a copy of itself. With $x = \\sqrt{12 + \\sqrt{12 + \\cdots}}$, everything after the $12$ is $x$ again:'),
          maths('x^2 = 12 + x'),
          maths('(x - 4)(x + 3) = 0'),
          prose('A square root is not negative, so $x = 4$.'),
        ),
        askAfter(
          'cm-aa-shared-root+choice',
          2,
          prose('For the other root, use the product: the two roots of $x^2 + bx + c = 0$ multiply to $c$.'),
        ),
        askAfter(
          'cm-aa-nested-root+choice',
          2,
          prose('With minus signs, $x = \\sqrt{20 - \\sqrt{20 - \\cdots}}$ gives'),
          maths('x^2 = 20 - x'),
          maths('(x - 4)(x + 5) = 0'),
          prose('so $x = 4$.'),
        ),
      ],
      skillCheck: [ask('cm-aa-complete-square', 2), ask('cm-aa-shared-root', 2), ask('cm-aa-nested-root', 2)],
    },
    {
      id: 'cm-l12-exponents',
      title: 'Exponents',
      slides: [
        teach(
          prose('Powers of different numbers compare once they share a base. For $4^{x + 1} = 8^{x - 1}$, write $4 = 2^2$ and $8 = 2^3$:'),
          maths('2^{2(x + 1)} = 2^{3(x - 1)}'),
          prose('Equal powers of $2$ have equal exponents:'),
          maths('2x + 2 = 3x - 3'),
          maths('x = 5'),
        ),
        ask('cm-aa-power-equation-tiles'),
        ask('cm-aa-power-equation'),
        askAfter(
          'cm-aa-power-equation+choice',
          2,
          prose('A fraction is a negative power: $\\tfrac{1}{4} = 2^{-2}$. So $\\left(\\tfrac{1}{4}\\right)^{x + 1} = 8^{x - 4}$ becomes'),
          maths('-2(x + 1) = 3(x - 4)'),
          maths('-2x - 2 = 3x - 12'),
          maths('x = 2'),
        ),
        teach(
          prose('Adding copies of a power multiplies it. Four copies of $2^x$ make $4 \\times 2^x$, and $4 = 2^2$:'),
          maths('2^x + 2^x + 2^x + 2^x = 2^{x + 2}'),
          prose('So if the total is $2^{20}$, then $x = 18$. Dividing $20$ by $4$ is the trap.'),
          prose('A sum or difference of powers: take out the smallest power.'),
          maths('\\frac{2^{30} - 2^{28}}{2^{27}} = \\frac{2^{28}(2^2 - 1)}{2^{27}}'),
          maths('= 2 \\times 3 = 6'),
        ),
        ask('cm-aa-power-sum'),
        ask('cm-aa-factor-power'),
        askAfter(
          'cm-aa-power-sum+choice',
          2,
          prose('When the copies are powers of $4$ and the total a power of $2$, write $4^x = 2^{2x}$. Eight copies of $4^x$ total $2^{25}$:'),
          maths('2^3 \\times 2^{2x} = 2^{2x + 3}'),
          maths('2x + 3 = 25'),
          maths('x = 11'),
        ),
        askAfter(
          'cm-aa-factor-power+choice',
          2,
          prose('Take the smallest power out of the top **and** the bottom:'),
          maths('\\frac{3^{25} - 3^{22}}{3^{23} - 3^{22}} = \\frac{3^{22}(27 - 1)}{3^{22}(3 - 1)}'),
          maths('= 26 \\div 2 = 13'),
        ),
        ask('cm-aa-power-equation-tiles', 2),
      ],
      skillCheck: [ask('cm-aa-power-equation', 2), ask('cm-aa-power-sum', 2), ask('cm-aa-factor-power', 2)],
    },
    {
      id: 'cm-l12-special-functions',
      title: 'Special Functions',
      slides: [
        teach(
          prose('$\\lfloor y \\rfloor$, the **floor** of $y$, is its whole-number part: $\\lfloor \\sqrt{10} \\rfloor = 3$.'),
          prose('To add $\\lfloor \\sqrt{n} \\rfloor$ for $n = 1$ to $10$, group the terms by value. The value is $1$ for $n = 1$ to $3$, $2$ for $n = 4$ to $8$, and $3$ for $9$ and $10$. Each full group runs from one square up to just below the next, so value $k$ has $2k + 1$ terms.'),
          maths('1 \\times 3 + 2 \\times 5 + 3 \\times 2 = 19'),
        ),
        ask('cm-aa-floor-table'),
        ask('cm-aa-floor-sum'),
        askAfter(
          'cm-aa-abs-sum',
          1,
          prose('$|x - 1|$ is the distance from $x$ to $1$ on the number line. For $|x - 1| + |x - 5| = 10$: between $1$ and $5$ the two distances add to only $4$, so the solutions are outside. To the right of $5$ both bars open as they stand:'),
          maths('(x - 1) + (x - 5) = 10'),
          maths('2x - 6 = 10'),
          prose('So the larger solution is $x = 8$.'),
        ),
        askAfter(
          'cm-aa-abs-sum+choice',
          2,
          prose('When the total equals the gap, every point between works. $|x - 2| + |x - 7| = 5$ holds for all $x$ from $2$ to $7$: that is $6$ whole numbers, ends included, not $5$.'),
        ),
        teach(
          prose('A **functional equation** with $f(x)$ and $f(c - x)$: substitute twice to get two equations. For'),
          maths('f(x) + 2f(6 - x) = x + 3'),
          prose('put $x = 1$, then $x = 5$:'),
          maths('f(1) + 2f(5) = 4'),
          maths('f(5) + 2f(1) = 8'),
          prose('Twice the second take away the first cancels $f(5)$:'),
          maths('3f(1) = 16 - 4 = 12'),
          prose('So $f(1) = 4$.'),
        ),
        ask('cm-aa-functional'),
        askAfter(
          'cm-aa-pair-sum',
          1,
          prose('**Pair the ends.** For $f(x) = \\frac{4^x}{4^x + 2}$, $f(1 - x)$ works out to $\\frac{2}{2 + 4^x}$, so'),
          maths('f(x) + f(1 - x) = 1'),
          prose('Then $f(\\tfrac{1}{5}) + f(\\tfrac{2}{5}) + f(\\tfrac{3}{5}) + f(\\tfrac{4}{5})$ is two pairs, $2$. With an odd number of terms the middle one is $f(\\tfrac{1}{2}) = \\tfrac{1}{2}$, half a pair.'),
        ),
        askAfter(
          'cm-aa-functional+choice',
          2,
          prose('With $3$ in front instead of $2$, multiply the second equation by $3$ and take away the first: that leaves $8$ lots of the value you want.'),
        ),
        askAfter(
          'cm-aa-pair-sum+choice',
          2,
          prose('With $9$ in place of $4$ the partner is $3$, its square root: $f(x) = \\frac{9^x}{9^x + 3}$ pairs to $1$ the same way.'),
        ),
        ask('cm-aa-floor-sum+choice', 2),
      ],
      skillCheck: [ask('cm-aa-floor-sum', 2), ask('cm-aa-abs-sum', 2), ask('cm-aa-functional', 2)],
    },
    {
      id: 'cm-l12-logarithms',
      title: 'Logarithms',
      slides: [
        teach(
          prose('Logs to the same base add by multiplying inside:'),
          maths('\\log_{6} 4 + \\log_{6} 9 = \\log_{6} 36 = 2'),
          prose('And any log can be changed to one base: $\\log_b c = \\log c \\div \\log b$. In a chain, each top then cancels the bottom after it:'),
          maths('\\log_{2} 3 \\times \\log_{3} 4 \\times \\cdots \\times \\log_{7} 8 = \\frac{\\log 8}{\\log 2}'),
          maths('= \\log_{2} 8 = 3'),
          prose('Counting the $6$ factors is the trap.'),
        ),
        ask('cm-aa-log-tiles'),
        ask('cm-aa-log-chain'),
        askAfter(
          'cm-aa-log-chain+choice',
          2,
          prose('Turned upside down, the chain cancels the other way:'),
          maths('\\log_{3} 2 \\times \\log_{4} 3 \\times \\cdots \\times \\log_{8} 7 = \\log_{8} 2'),
          prose('Since $8 = 2^3$, that is $\\tfrac{1}{3}$.'),
        ),
        askAfter(
          'cm-aa-log-tiles',
          2,
          prose('Logs subtract by dividing inside:'),
          maths('\\log_{3} 162 - \\log_{3} 2 = \\log_{3} 81 = 4'),
        ),
        teach(
          prose('A log to a power base is a fraction of a log to the base itself: $\\log_{4} x$ is half of $\\log_{2} x$. So'),
          maths('\\log_{2} x + \\log_{4} x = 6'),
          maths('\\tfrac{3}{2}\\log_{2} x = 6'),
          maths('\\log_{2} x = 4'),
          prose('and $x = 16$.'),
          prose('By what a log means, $3^{\\log_{3} 5} = 5$. Write $9$ as $3^2$ and swap the two powers:'),
          maths('9^{\\log_{3} 5} = \\left(3^{\\log_{3} 5}\\right)^2 = 25'),
        ),
        ask('cm-aa-log-equation'),
        ask('cm-aa-log-power'),
        askAfter(
          'cm-aa-log-equation+choice',
          2,
          prose('A log to base $8 = 2^3$ is a third of a log to base $2$:'),
          maths('\\log_{2} x + \\log_{8} x = 8'),
          maths('\\tfrac{4}{3}\\log_{2} x = 8'),
          prose('So $\\log_{2} x = 6$ and $x = 64$.'),
        ),
        askAfter(
          'cm-aa-log-power+choice',
          2,
          prose('When the log’s base is a power too, put everything over the smallest base. $8 = 2^3$, and $\\log_{4} 9$ is half of $\\log_{2} 9$:'),
          maths('8^{\\log_{4} 9} = 2^{\\frac{3}{2}\\log_{2} 9} = 9^{\\frac{3}{2}}'),
          maths('= 3^3 = 27'),
        ),
      ],
      skillCheck: [ask('cm-aa-log-chain', 2), ask('cm-aa-log-equation', 2), ask('cm-aa-log-power', 2)],
    },
  ],
  levelCheck: [
    ask('cm-aa-sum-diff', 2),
    ask('cm-aa-swap', 2),
    ask('cm-aa-avg-speed+choice', 2),
    ask('cm-aa-meet', 2),
    ask('cm-aa-fill-drain', 1),
    ask('cm-aa-complete-square', 2),
    ask('cm-aa-nested-root', 2),
    ask('cm-aa-power-equation', 2),
    ask('cm-aa-factor-power', 2),
    ask('cm-aa-floor-sum', 2),
    ask('cm-aa-functional', 2),
    ask('cm-aa-log-chain', 2),
    ask('cm-aa-log-equation+choice', 2),
  ],
};
