/**
 * Contest Math, Level 17: Modular Arithmetic. Every lesson replaces a number
 * by its remainder as early as it can: to meet two or three remainder
 * conditions at once, to divide (add the modulus until the division comes
 * out), to read the last digits of towers and long sums, and to cut a huge
 * exponent down by p - 1 or φ(n). Generators in
 * `generators/contestModular.ts`.
 */
import type { Level } from '../../types';
import { teach, ask, prose, maths, askAfter } from './blocks';

export const modularArithmetic: Level = {
  id: 'cm-l17',
  title: 'Modular Arithmetic',
  lessons: [
    {
      id: 'cm-l17-congruences',
      title: 'System of Congruences',
      slides: [
        teach(
          prose('Contest problems about remainders use a shorthand. This line says $N$ leaves remainder $4$ when divided by $7$:'),
          maths('N \\equiv 4 \\pmod{7}'),
          prose('It is read "$N$ is congruent to 4 mod 7". The multiple of 7 inside $N$ leaves nothing behind, even once it is multiplied or squared, so a sum or product can use the remainder in place of $N$:'),
          maths('3N + 5 \\equiv 3 \\times 4 + 5 \\pmod{7}'),
          maths('3 \\times 4 + 5 = 17 = 7 \\times 2 + 3'),
          prose('So $3N + 5$ leaves $3$. Answering $17$ is the trap: a remainder is always less than the divisor.'),
        ),
        ask('cm-md-remainder-shift'),
        askAfter(
          'cm-md-crt-sieve',
          1,
          prose('Two conditions at once: the smallest positive $N$ with'),
          maths('N \\equiv 2 \\pmod{5}, \\qquad N \\equiv 3 \\pmod{7}'),
          prose('List the numbers that pass the larger divisor, 7, and test each on 5:'),
          maths('3, 10, 17, \\ldots'),
          maths('17 = 5 \\times 3 + 2'),
          prose('So $N = 17$. The next answer is $35$ further on, since $35$ is the first number that both 5 and 7 divide.'),
        ),
        ask('cm-md-crt-table'),
        askAfter(
          'cm-md-remainder-shift+choice',
          2,
          prose('Squares work the same way. With $N \\equiv 5 \\pmod{9}$:'),
          maths('N^{2} + 3N + 2 \\equiv 5^{2} + 3 \\times 5 + 2 \\pmod{9}'),
          maths('25 + 15 + 2 = 42 = 9 \\times 4 + 6'),
          prose('so it leaves $6$.'),
        ),
        teach(
          prose('Sometimes every remainder is the same distance short of its divisor:'),
          maths('N \\equiv 1 \\pmod{2}, \\qquad N \\equiv 2 \\pmod{3}, \\qquad N \\equiv 3 \\pmod{4}'),
          prose('Each remainder is 1 short, so $N + 1$ divides exactly by 2, 3 and 4. The smallest such $N + 1$ is their LCM:'),
          maths('\\text{LCM}(2, 3, 4) = 12'),
          maths('N = 12 - 1 = 11'),
          prose('Multiplying the divisors gives $24$, and $23$ works too, but it is not the smallest: that is the trap.'),
          prose('When every remainder is the same number, say 1 each time, $N - 1$ is the common multiple instead.'),
        ),
        ask('cm-md-same-gap'),
        askAfter(
          'cm-md-crt-sieve+choice',
          2,
          prose('Three conditions: solve the two with the largest divisors, then step through the third.'),
          maths('N \\equiv 1 \\pmod{3}, \\qquad N \\equiv 2 \\pmod{5}, \\qquad N \\equiv 3 \\pmod{7}'),
          prose('From the last two, $N = 17$ works as before, and so does every $35$ more. Test those on 3:'),
          maths('17, 52, \\ldots'),
          maths('52 = 3 \\times 17 + 1'),
          prose('So $N = 52$.'),
        ),
        askAfter(
          'cm-md-same-gap+choice',
          2,
          prose('To count them, write every answer in one list. In the example above $N + 1$ is a multiple of 12:'),
          maths('N = 11, 23, 35, \\ldots'),
          prose('From 1 to 100 the last one is'),
          maths('12 \\times 8 - 1 = 95'),
          prose('so there are $8$. When every remainder is the same, say $r$, the list is $r$, then $r$ plus 12, and so on: it starts at $r$ itself, 0 twelves plus $r$, so count the twelves from 0.'),
        ),
        ask('cm-md-crt-table', 2),
      ],
      skillCheck: [ask('cm-md-remainder-shift', 2), ask('cm-md-crt-sieve', 2), ask('cm-md-same-gap', 2)],
    },
    {
      id: 'cm-l17-fractions',
      title: 'Fractions',
      slides: [
        teach(
          prose('Dividing is the hard operation with remainders. When dividing by 7, $\\frac{1}{3}$ should mean the whole number $x$ with'),
          maths('3x \\equiv 1 \\pmod{7}'),
          prose('So $3x$ is 1 plus some 7s. Add 7s to 1 until the total divides exactly by 3:'),
          maths('1, 8, 15'),
          maths('15 \\div 3 = 5'),
          prose('Check:'),
          maths('3 \\times 5 = 15 = 7 \\times 2 + 1'),
          prose('So $x = 5$ plays the part of $\\frac{1}{3}$. Adding the modulus first is what makes the division come out whole.'),
        ),
        ask('cm-md-inverse'),
        askAfter(
          'cm-md-inverse-table',
          1,
          prose('Set the search out in a table. For'),
          maths('4x \\equiv 1 \\pmod{11}'),
          prose('the totals are'),
          maths('1, 12'),
          maths('12 \\div 4 = 3'),
          prose('so $x = 3$.'),
        ),
        askAfter(
          'cm-md-linear',
          1,
          prose('Any other fraction works the same way. To solve'),
          maths('4x \\equiv 3 \\pmod{7}'),
          prose('add 7s to 3 until the total divides exactly by 4:'),
          maths('3, 10, 17, 24'),
          maths('24 \\div 4 = 6'),
          prose('So $x = 6$.'),
        ),
        ask('cm-md-inverse+choice', 2),
        teach(
          prose('Fractions also turn up as repeating decimals, and a far-off digit comes from a remainder.'),
          maths('\\frac{3}{7} = 0.428571428571\\ldots'),
          prose('The block $428571$ repeats every 6 digits. For the 50th digit, divide 50 by 6:'),
          maths('50 = 6 \\times 8 + 2'),
          prose('After 8 whole blocks, the 50th digit is place 2 of the next block: $2$.'),
          prose('A remainder of 0 means the digit ends a block, so it is the last digit of the block, not the first.'),
        ),
        ask('cm-md-decimal-digit'),
        askAfter(
          'cm-md-linear+choice',
          2,
          prose('If the number in front of $x$ shares a factor with the modulus, it has no partner that makes 1. In'),
          maths('4x \\equiv 2 \\pmod{6}'),
          prose('4, 2 and 6 all share the factor 2. Divide all three by it, the modulus too:'),
          maths('2x \\equiv 1 \\pmod{3}'),
          prose('Add 3s to 1:'),
          maths('1, 4'),
          maths('4 \\div 2 = 2'),
          prose('So $x$ leaves 2 on dividing by 3, and from 0 to 5 that is two answers, 2 and 5:'),
          maths('2 + 5 = 7'),
          prose('Stopping at one answer is the trap.'),
        ),
        askAfter(
          'cm-md-decimal-digit+choice',
          2,
          prose('Some decimals start repeating one place late:'),
          maths('\\frac{1}{14} = 0.0714285714285\\ldots'),
          prose('The first digit, 0, comes before the block $714285$ starts. For the 50th digit, take that one digit off first:'),
          maths('50 - 1 = 49'),
          maths('49 = 6 \\times 8 + 1'),
          prose('Place 1 of the block: $7$. Skipping the shift lands on place 2, a $1$: the trap.'),
        ),
        ask('cm-md-inverse-table', 2),
      ],
      skillCheck: [ask('cm-md-inverse', 2), ask('cm-md-linear', 2), ask('cm-md-decimal-digit', 2)],
    },
    {
      id: 'cm-l17-units-digit',
      title: 'Units Digit',
      slides: [
        teach(
          prose('The last digit of a power runs in a cycle. Powers of 3 end in'),
          maths('3, 9, 7, 1, 3, 9, 7, 1, \\ldots'),
          prose('so only the remainder of the power on dividing by 4 matters. In a tower the power is itself a power:'),
          maths('3^{5^{10}}'),
          prose('5 leaves 1 on dividing by 4, so every power of 5 does too:'),
          maths('5^{10} \\equiv 1 \\pmod{4}'),
          prose('Remainder 1 is place 1 in the cycle, so $3^{5^{10}}$ ends in $3$.'),
          prose('An even base is quicker. $6^{2}$ already divides exactly by 4, so every higher power of 6 does too:'),
          maths('6^{10} \\equiv 0 \\pmod{4}'),
          prose('A remainder of 0 lands on place 4, so $3^{6^{10}}$ ends in $1$.'),
        ),
        ask('cm-md-tower'),
        askAfter(
          'cm-md-tower-table',
          1,
          prose('Set it out as a table: the cycle first, then the tower. For $7^{4^{3}}$, powers of 7 end in'),
          maths('7, 9, 3, 1'),
          prose('and $4^{3}$ divides exactly by 4, so it is place 4: $7^{4^{3}}$ ends in $1$.'),
        ),
        askAfter(
          'cm-md-tower+choice',
          2,
          prose('A base that leaves 3 on dividing by 4 is 1 short of 4, so treat it as $-1$. Its powers alternate:'),
          maths('7^{3} \\equiv (-1)^{3} = -1 \\pmod{4}'),
          maths('7^{4} \\equiv (-1)^{4} = 1 \\pmod{4}'),
          prose('and $-1$, 1 short of 4, is a remainder of 3. So $2^{7^{3}}$ is at place 3 of the cycle 2, 4, 8, 6 and ends in $8$, while $2^{7^{4}}$ is at place 1 and ends in $2$.'),
          prose('With a two-digit base only its last digit counts, so $13$ runs through the same cycle as $3$.'),
        ),
        teach(
          prose('A long sum of powers: the last digit of a power depends only on the last digit of the base, so 1 to 10, 11 to 20, and so on all give the same block of last digits.'),
          maths('1^{22} + 2^{22} + 3^{22} + \\cdots + 30^{22}'),
          prose('Last digits of powers repeat every 4 (or sooner), and 22 leaves 2 on dividing by 4, so each ends like a square:'),
          maths('1 + 4 + 9 + 6 + 5 + 6 + 9 + 4 + 1 + 0 = 45'),
          prose('Three blocks of ten:'),
          maths('3 \\times 45 = 135'),
          prose('so the sum ends in $5$. A power that leaves 0 on dividing by 4 ends like a 4th power, and then a block adds to 33, not 45.'),
        ),
        ask('cm-md-power-sum'),
        askAfter(
          'cm-md-last-two',
          1,
          prose('The last two digits of a power of a number ending in 1 come from multiplying out. Write 31 as 30 + 1:'),
          maths('(30 + 1)^{12} = 1 + 12 \\times 30 + (\\text{multiples of } 30^{2})'),
          prose('Every multiple of $30^{2}$ is a multiple of 100, so only the first two terms reach the last two digits:'),
          maths('1 + 12 \\times 30 = 361'),
          prose('So $31^{12}$ ends in $61$.'),
        ),
        askAfter(
          'cm-md-power-sum+choice',
          2,
          prose('When the sum stops partway through a block, add the full blocks, then the numbers left over.'),
          maths('1^{22} + 2^{22} + \\cdots + 23^{22}'),
          prose('Two full blocks reach 20, and the last three numbers end like $1^{2}$, $2^{2}$ and $3^{2}$:'),
          maths('2 \\times 45 + 1 + 4 + 9 = 104'),
          prose('so it ends in $4$.'),
        ),
        askAfter(
          'cm-md-last-two+choice',
          2,
          prose('For other bases, look for a power that ends in 01. Keep only the last two digits each time:'),
          maths('7^{2} = 49'),
          maths('49 \\times 7 = 343 \\to 43'),
          maths('43 \\times 7 = 301 \\to 01'),
          prose('So the last two digits of powers of 7 repeat every 4. For $7^{50}$:'),
          maths('50 = 4 \\times 12 + 2'),
          prose('so $7^{50}$ ends like $7^{2}$, in $49$.'),
        ),
        ask('cm-md-tower-table', 2),
      ],
      skillCheck: [ask('cm-md-tower', 2), ask('cm-md-power-sum', 2), ask('cm-md-last-two', 2)],
    },
    {
      id: 'cm-l17-euler',
      title: "Euler's Theorem",
      slides: [
        teach(
          prose("**Fermat's little theorem**: if $p$ is prime and does not divide $a$, then"),
          maths('a^{p - 1} \\equiv 1 \\pmod{p}'),
          prose('So the remainders of powers of $a$ repeat every $p - 1$ powers, and a huge power shrinks to a small one. For $3^{100}$ divided by 7 the cycle is 6:'),
          maths('100 = 6 \\times 16 + 4'),
          maths('3^{100} \\equiv 3^{4} = 81 \\pmod{7}'),
          maths('81 = 7 \\times 11 + 4'),
          prose('So the remainder is $4$. Cutting the power down by 7 rather than 6 is the trap. A base bigger than $p$ is replaced by its remainder first, as always.'),
        ),
        ask('cm-md-fermat'),
        askAfter(
          'cm-md-cycle-table',
          1,
          prose('The cycle can be shorter than $p - 1$, though its length always divides $p - 1$. Powers of 2 on dividing by 7 leave'),
          maths('2, 4, 1, 2, 4, 1, \\ldots'),
          prose('which repeats every 3. Multiply each remainder by 2 and divide by 7 again to get the next.'),
        ),
        askAfter(
          'cm-md-euler-tower',
          1,
          prose('For a tower, cut the top down first. $3^{5^{4}}$ divided by 7 needs the remainder of $5^{4}$ on dividing by 6. The powers of 5 leave'),
          maths('5, 1, 5, 1'),
          prose('so $5^{4}$ leaves 1, and'),
          maths('3^{5^{4}} \\equiv 3 \\pmod{7}'),
        ),
        ask('cm-md-cycle-table', 2),
        teach(
          prose('For a modulus that is not prime, count the numbers from 1 to $n$ that share no factor greater than 1 with $n$. The count is written $\\varphi(n)$.'),
          maths('36 = 2^{2} \\times 3^{2}'),
          prose('Half of the numbers 1 to 36 are not even, and two thirds of those are not multiples of 3:'),
          maths('\\varphi(36) = 36 \\times \\frac{1}{2} \\times \\frac{2}{3} = 12'),
          prose('Taking away the 18 multiples of 2 and the 12 multiples of 3 separately takes the multiples of 6 away twice: the trap.'),
          prose("**Euler's theorem**: if $a$ shares no factor with $n$, then"),
          maths('a^{\\varphi(n)} \\equiv 1 \\pmod{n}'),
          prose("For a prime $n$ every smaller number counts, $n - 1$ of them, and this is Fermat's theorem again."),
        ),
        ask('cm-md-phi'),
        askAfter(
          'cm-md-fermat+choice',
          2,
          prose("With Euler's theorem: $7^{50}$ divided by 20. 7 shares no factor with 20, and"),
          maths('\\varphi(20) = 20 \\times \\frac{1}{2} \\times \\frac{4}{5} = 8'),
          maths('50 = 8 \\times 6 + 2'),
          maths('7^{50} \\equiv 7^{2} = 49 \\pmod{20}'),
          maths('49 = 20 \\times 2 + 9'),
          prose('The remainder is $9$. Treating 20 as if it were prime, and cutting the power down by 19, is the trap.'),
        ),
        askAfter(
          'cm-md-phi+choice',
          2,
          prose('With three primes, keep the same share for each:'),
          maths('60 = 2^{2} \\times 3 \\times 5'),
          maths('\\varphi(60) = 60 \\times \\frac{1}{2} \\times \\frac{2}{3} \\times \\frac{4}{5} = 16'),
        ),
        askAfter(
          'cm-md-euler-tower',
          2,
          prose('Modulo 11 the top of a tower is cut down by 10, so only its last digit matters. For $2^{3^{6}}$ divided by 11:'),
          maths('3^{6} = 729'),
          maths('2^{3^{6}} \\equiv 2^{9} = 512 \\pmod{11}'),
          maths('512 = 11 \\times 46 + 6'),
          prose('The remainder is $6$. Modulo 13 the top is cut down by 12 in the same way.'),
        ),
      ],
      skillCheck: [ask('cm-md-phi', 2), ask('cm-md-fermat', 2), ask('cm-md-euler-tower', 2)],
    },
  ],
  levelCheck: [
    ask('cm-md-remainder-shift+choice', 2),
    ask('cm-md-crt-sieve', 2),
    ask('cm-md-same-gap', 2),
    ask('cm-md-crt-table', 2),
    ask('cm-md-inverse', 2),
    ask('cm-md-linear+choice', 2),
    ask('cm-md-decimal-digit', 2),
    ask('cm-md-tower+choice', 2),
    ask('cm-md-power-sum', 2),
    ask('cm-md-last-two', 2),
    ask('cm-md-phi', 2),
    ask('cm-md-fermat+choice', 2),
    ask('cm-md-euler-tower', 2),
  ],
};
