/**
 * Contest Math, Level 15: Sequences and Series. A step past Level 2's
 * sequences: places that add to the same number, three terms named round the
 * middle, terms from sums, the geometric mean, a sum that shifts into itself,
 * and series that telescope. Generators in
 * `generators/contestSequencesSeries.ts`.
 */
import type { Level } from '../../types';
import { teach, ask, prose, maths, askAfter } from './blocks';

export const sequencesSeriesLevel: Level = {
  id: 'cm-l15',
  title: 'Sequences and Series',
  lessons: [
    {
      id: 'cm-l15-arithmetic',
      title: 'Arithmetic Sequences',
      slides: [
        teach(
          prose('In an arithmetic sequence, two terms whose places add to the same number add to the same total. Going from term $4$ back to term $1$ takes off $3d$, and going from term $10$ on to term $13$ puts $3d$ back. So from'),
          maths('u_{4} + u_{10} = 50'),
          prose('it follows that'),
          maths('u_{1} + u_{13} = 50'),
          prose('Write the first $13$ terms forwards and backwards and add the two rows: $13$ columns of $50$, which is twice the sum.'),
          maths('S_{13} = \\frac{13 \\times 50}{2} = 325'),
        ),
        ask('cm-ss-index-pairs'),
        askAfter(
          'cm-ss-insert-tiles',
          1,
          prose('Putting $4$ numbers between $3$ and $28$ makes $6$ numbers with $5$ gaps, not $4$:'),
          maths('d = (28 - 3) \\div 5 = 5'),
          prose('The numbers put in are $8$, $13$, $18$ and $23$. They pair from the outside in, and each pair adds to $3 + 28$, which is $31$:'),
          maths('\\text{sum} = \\frac{4 \\times 31}{2} = 62'),
        ),
        askAfter(
          'cm-ss-index-pairs+choice',
          2,
          prose('Three terms spaced evenly round a middle one: terms $3$ and $11$ are $4$ steps either side of term $7$, so they add to twice it. If'),
          maths('u_{3} + u_{7} + u_{11} = 60'),
          prose('then'),
          maths('3u_{7} = 60'),
          maths('u_{7} = 20'),
          prose('Term $7$ is the middle of the first $13$ terms, so it is their mean:'),
          maths('S_{13} = 13 \\times 20 = 260'),
        ),
        askAfter(
          'cm-ss-symmetric-three',
          1,
          prose('Three numbers in an arithmetic sequence: name them round the middle, $a - d$, $a$ and $a + d$, so the $d$s cancel in the sum. If they add to $30$ and multiply to $910$:'),
          maths('3a = 30'),
          maths('a = 10'),
          maths('10(100 - d^{2}) = 910'),
          maths('d^{2} = 9'),
          prose('So $d = 3$ and the numbers are $7$, $10$ and $13$.'),
        ),
        teach(
          prose('A sequence can be given by its sums. $S_n$ is the sum of the first $n$ terms, so each term is what its sum adds to the one before:'),
          maths('u_{n} = S_{n} - S_{n-1}'),
          prose('and the first term is $S_{1}$ itself. With'),
          maths('S_{n} = 2n^{2} + 3n'),
          prose('the 10th term is'),
          maths('u_{10} = S_{10} - S_{9}'),
          maths('= 230 - 189 = 41'),
          prose('Dividing $S_{10}$ by $10$ gives $23$, the mean of the first ten terms, not the 10th term.'),
        ),
        ask('cm-ss-sum-rule-table'),
        ask('cm-ss-sum-rule+choice'),
        askAfter(
          'cm-ss-block-sums',
          1,
          prose('Cut the first $30$ terms into blocks of $10$. Each term of a block is $10$ steps past the term above it, so each block adds $100d$ more than the last: the block sums are arithmetic too.'),
          prose('If the first $10$ terms add to $100$ and the first $20$ to $300$, the blocks are'),
          maths('B_{1} = 100'),
          maths('B_{2} = 300 - 100 = 200'),
          maths('B_{3} = 200 + (200 - 100) = 300'),
          maths('S_{30} = 100 + 200 + 300 = 600'),
          prose('Adding the two sums given, $400$, is the trap.'),
        ),
        askAfter(
          'cm-ss-symmetric-three+choice',
          2,
          prose('Given the sum of the squares instead of the product, the cross terms cancel:'),
          maths('(a - d)^{2} + a^{2} + (a + d)^{2}'),
          maths('= 3a^{2} + 2d^{2}'),
          prose('Three numbers adding to $30$ whose squares add to $318$ have $a = 10$:'),
          maths('300 + 2d^{2} = 318'),
          maths('d^{2} = 9'),
          prose('So again they are $7$, $10$ and $13$.'),
        ),
        ask('cm-ss-block-sums+choice', 2),
      ],
      skillCheck: [ask('cm-ss-index-pairs', 2), ask('cm-ss-sum-rule', 2), ask('cm-ss-block-sums', 2)],
    },
    {
      id: 'cm-l15-geometric',
      title: 'Geometric Sequences',
      slides: [
        teach(
          prose('In a geometric sequence the same factor takes each term to the next. A term midway between two others is their **geometric mean**.'),
          prose('With $u_{3} = 12$ and $u_{7} = 192$, the factor that takes $u_{3}$ to $u_{5}$ also takes $u_{5}$ to $u_{7}$, so for positive terms'),
          maths('u_{5}^{2} = 12 \\times 192 = 2304'),
          maths('u_{5} = \\sqrt{2304} = 48'),
          prose('The average of $12$ and $192$, $102$, is the arithmetic mean, and the trap.'),
        ),
        ask('cm-ss-geo-middle'),
        askAfter(
          'cm-ss-geo-table',
          1,
          prose('Two terms give the ratio. From $u_{2} = 6$ to $u_{5} = 162$ is three steps, each multiplying by $r$:'),
          maths('r^{3} = 162 \\div 6 = 27'),
          prose('So $r = 3$, and the sequence is $2, 6, 18, 54, 162$. Filling the gap evenly, as if it were arithmetic, is the trap.'),
        ),
        askAfter(
          'cm-ss-geo-middle+choice',
          2,
          prose('It works past the given terms too. Places $3$ and $11$ are $4$ either side of place $7$, so $u_{7}$ is the geometric mean of $u_{3}$ and $u_{11}$. With $u_{3} = 12$ and $u_{7} = 192$:'),
          maths('192^{2} = 12 \\times u_{11}'),
          maths('u_{11} = 36864 \\div 12 = 3072'),
        ),
        teach(
          prose('To add a geometric series, multiply it by the ratio. The list moves one place along, and subtracting cancels everything but the two ends:'),
          maths('S = 3 + 6 + 12 + \\cdots + 768'),
          maths('2S = 6 + 12 + \\cdots + 768 + 1536'),
          maths('2S - S = 1536 - 3'),
          maths('S = 1533'),
          prose('A series that goes on for ever holds a copy of itself. In $24 + 12 + 6 + \\cdots$ everything after the $24$ is half the whole series again:'),
          maths('S = 24 + \\frac{1}{2}S'),
          maths('\\frac{1}{2}S = 24'),
          maths('S = 48'),
        ),
        ask('cm-ss-geo-shift-tiles'),
        ask('cm-ss-geo-shift-sum+choice'),
        ask('cm-ss-geo-infinite'),
        askAfter(
          'cm-ss-bounce+choice',
          1,
          prose('A ball dropped from $16$ m rises to $\\frac{3}{4}$ of its fall each time. The first fall happens once, and every bounce after it is travelled twice, up and down. The bounces start at $12$ and go on for ever:'),
          maths('12 + 9 + \\cdots = 12 \\div \\left(1 - \\frac{3}{4}\\right) = 48'),
          maths('16 + 2 \\times 48 = 112'),
        ),
        askAfter(
          'cm-ss-geo-infinite+choice',
          2,
          prose('When the signs alternate, the rest is minus the ratio times the whole series. For $24 - 12 + 6 - \\cdots$:'),
          maths('S = 24 - \\frac{1}{2}S'),
          maths('\\frac{3}{2}S = 24'),
          maths('S = 16'),
        ),
        askAfter(
          'cm-ss-geo-shift-sum',
          2,
          prose('With ratio $3$, multiply by $3$. Subtracting then leaves $2S$, so there is one more division:'),
          maths('S = 2 + 6 + 18 + \\cdots + 486'),
          maths('3S - S = 1458 - 2'),
          maths('2S = 1456'),
          maths('S = 728'),
        ),
      ],
      skillCheck: [ask('cm-ss-geo-middle', 2), ask('cm-ss-geo-infinite', 2), ask('cm-ss-bounce', 2)],
    },
    {
      id: 'cm-l15-telescoping',
      title: 'Telescoping Series',
      slides: [
        teach(
          prose('A **telescoping** series is one whose terms split into differences, so that almost everything cancels.'),
          maths('\\frac{1}{k(k + 1)} = \\frac{1}{k} - \\frac{1}{k + 1}'),
          maths('\\frac{1}{1 \\times 2} + \\frac{1}{2 \\times 3} + \\cdots + \\frac{1}{9 \\times 10}'),
          maths('= \\left(1 - \\frac{1}{2}\\right) + \\left(\\frac{1}{2} - \\frac{1}{3}\\right) + \\cdots + \\left(\\frac{1}{9} - \\frac{1}{10}\\right)'),
          maths('= 1 - \\frac{1}{10} = \\frac{9}{10}'),
          prose('When the bottom numbers differ by more than $1$, the difference needs a fraction in front. With a gap of $3$:'),
          maths('\\frac{1}{1 \\times 4} = \\frac{1}{3}\\left(1 - \\frac{1}{4}\\right)'),
          maths('\\frac{1}{1 \\times 4} + \\frac{1}{4 \\times 7} + \\cdots + \\frac{1}{13 \\times 16}'),
          maths('= \\frac{1}{3}\\left(1 - \\frac{1}{16}\\right) = \\frac{5}{16}'),
        ),
        ask('cm-ss-tele-unit'),
        ask('cm-ss-tele-table'),
        askAfter(
          'cm-ss-tele-unit+choice',
          2,
          prose('The same series can hide. In'),
          maths('\\frac{1}{20} + \\frac{1}{30} + \\frac{1}{42} + \\cdots + \\frac{1}{380}'),
          prose('the bottoms are $4 \\times 5$, $5 \\times 6$, and so on up to $19 \\times 20$, so the sum starts at $k = 4$:'),
          maths('\\frac{1}{4} - \\frac{1}{20} = \\frac{1}{5}'),
        ),
        ask('cm-ss-tele-gap'),
        teach(
          prose('Roots telescope too. Multiply the top and bottom by $\\sqrt{k + 1} - \\sqrt{k}$: the bottom becomes a difference of squares, which is $1$.'),
          maths('\\frac{1}{\\sqrt{k} + \\sqrt{k + 1}} = \\sqrt{k + 1} - \\sqrt{k}'),
          maths('\\frac{1}{1 + \\sqrt{2}} + \\cdots + \\frac{1}{\\sqrt{99} + \\sqrt{100}}'),
          maths('= \\sqrt{100} - 1 = 9'),
          prose('So do factorials. Write $k$ as $(k + 1) - 1$:'),
          maths('k \\times k! = (k + 1)! - k!'),
          maths('1 \\times 1! + 2 \\times 2! + \\cdots + 5 \\times 5!'),
          maths('= 6! - 1! = 719'),
        ),
        ask('cm-ss-tele-roots'),
        ask('cm-ss-tele-factorial+choice'),
        askAfter(
          'cm-ss-tele-gap+choice',
          2,
          prose('When the bottoms are $k$ and $k + 2$, each fraction cancels with the one two terms later, so two survive at each end:'),
          maths('\\frac{1}{k(k + 2)} = \\frac{1}{2}\\left(\\frac{1}{k} - \\frac{1}{k + 2}\\right)'),
          maths('\\frac{1}{1 \\times 3} + \\frac{1}{2 \\times 4} + \\cdots + \\frac{1}{8 \\times 10}'),
          maths('= \\frac{1}{2}\\left(1 + \\frac{1}{2} - \\frac{1}{9} - \\frac{1}{10}\\right) = \\frac{29}{45}'),
        ),
        askAfter(
          'cm-ss-tele-roots+choice',
          2,
          prose('In steps of $2$, the difference of squares is $2$, so a half goes in front:'),
          maths('\\frac{1}{\\sqrt{k} + \\sqrt{k + 2}} = \\frac{1}{2}\\left(\\sqrt{k + 2} - \\sqrt{k}\\right)'),
          maths('\\frac{1}{1 + \\sqrt{3}} + \\frac{1}{\\sqrt{3} + \\sqrt{5}} + \\cdots + \\frac{1}{\\sqrt{47} + \\sqrt{49}}'),
          maths('= \\frac{1}{2}(7 - 1) = 3'),
        ),
        askAfter(
          'cm-ss-tele-factorial',
          2,
          prose('With the factorial underneath, write the top as $(k + 1) - 1$:'),
          maths('\\frac{k}{(k + 1)!} = \\frac{1}{k!} - \\frac{1}{(k + 1)!}'),
          maths('\\frac{1}{2!} + \\frac{2}{3!} + \\frac{3}{4!} + \\frac{4}{5!}'),
          maths('= 1 - \\frac{1}{5!} = \\frac{119}{120}'),
          prose('Starting later only moves the first survivor. From $k = 3$ the first is $\\frac{1}{3!}$, and $k \\times k!$ from $k = 2$ adds to $(n + 1)!$ minus $2!$.'),
        ),
      ],
      skillCheck: [ask('cm-ss-tele-gap', 2), ask('cm-ss-tele-roots', 2), ask('cm-ss-tele-factorial', 2)],
    },
  ],
  levelCheck: [
    ask('cm-ss-index-pairs', 2),
    ask('cm-ss-symmetric-three', 2),
    ask('cm-ss-sum-rule', 2),
    ask('cm-ss-block-sums+choice', 2),
    ask('cm-ss-geo-middle', 2),
    ask('cm-ss-geo-shift-sum', 2),
    ask('cm-ss-geo-infinite', 2),
    ask('cm-ss-bounce', 2),
    ask('cm-ss-tele-unit', 2),
    ask('cm-ss-tele-gap', 2),
    ask('cm-ss-tele-roots+choice', 2),
    ask('cm-ss-tele-factorial', 2),
  ],
};
