/**
 * Contest Math, Level 6: Composite Figures. Areas built from simpler shapes
 * or cut out of them, leaves and lunes, circles and squares inscribed in one
 * another, area ratios inside a figure, and solids built from cubes.
 * Generators in `generators/contestComposite.ts`.
 */
import type { Level } from '../../types';
import { teach, ask, prose, maths, askAfter } from './blocks';

export const compositeFigures: Level = {
  id: 'cm-l6',
  title: 'Composite Figures',
  lessons: [
    {
      id: 'cm-l6-composites',
      title: 'Composites',
      slides: [
        teach(
          prose('A **composite** area is built from simpler shapes, or is a simple shape with pieces taken out. Find the pieces whose areas you know, then add or subtract.'),
          prose('A lawn is $10$ m by $6$ m, with a path $2$ m wide all the way round the outside. Lawn and path together make a rectangle $4$ m longer each way:'),
          maths('14 \\times 10 = 140'),
          prose('Take the lawn away and the path is left:'),
          maths('140 - 60 = 80'),
          prose('Four strips along the sides give $64$, the trap: they miss the four $2 \\times 2$ squares at the corners.'),
        ),
        ask('cm-garden-path'),
        askAfter(
          'cm-garden-path+choice',
          2,
          prose('Two paths crossing a lawn at right angles: add the paths, then take off the square where they cross, which was counted twice. A $10$ by $6$ lawn with two paths $2$ m wide:'),
          maths('2 \\times 10 + 2 \\times 6 = 32'),
          maths('32 - 2 \\times 2 = 28'),
        ),
        askAfter(
          'cm-overlap-squares',
          1,
          prose('A square of side $8$, and a bigger square with one corner at its centre, turned at any angle. The overlap is always a quarter of the first square: turning the second square gains a triangle on one side of the overlap and loses an identical one on the other.'),
          maths('8^2 \\div 4 = 16'),
        ),
        teach(
          prose('Curved pieces are parts of circles. A circle of radius $r$ has area $\\pi r^2$, a semicircle half that and a quarter circle a quarter. Leave $\\pi$ in the answer: that keeps it exact.'),
          prose('A window is a rectangle $8$ wide and $5$ tall, with a semicircle on its top side. The semicircle’s radius is half the width, $4$:'),
          maths('\\tfrac{1}{2} \\times \\pi \\times 4^2 = 8\\pi'),
          maths('8 \\times 5 = 40'),
          maths('\\text{area} = 40 + 8\\pi'),
          prose('Taking the width $8$ as the radius is the trap: the radius is half the diameter.'),
        ),
        ask('cm-arch-area'),
        ask('cm-arch-tiles'),
        askAfter(
          'cm-arch-area+choice',
          2,
          prose('Cut-outs are subtracted. A $10$ by $4$ plate has a semicircle cut from each short end, each with the short side as its diameter. The two halves make one whole circle of radius $2$:'),
          maths('\\pi \\times 2^2 = 4\\pi'),
          maths('\\text{area} = 40 - 4\\pi'),
        ),
        askAfter(
          'cm-overlap-squares+choice',
          2,
          prose('The area two overlapping shapes cover together is both areas added, less the overlap, which was counted twice. Squares of side $8$ and $10$, the second with a corner at the centre of the first:'),
          maths('64 + 100 - 16 = 148'),
        ),
        ask('cm-arch-tiles', 2),
      ],
      skillCheck: [ask('cm-garden-path', 2), ask('cm-overlap-squares', 2), ask('cm-arch-area', 2)],
    },
    {
      id: 'cm-l6-lunes',
      title: 'Lunes and Leaves',
      slides: [
        teach(
          prose('A **leaf**: in a square of side $4$, draw a quarter circle of radius $4$ from each of two opposite corners. The two quarter circles overlap in a leaf along the other diagonal.'),
          prose('Each quarter circle covers the leaf and one of the two corner pieces. Added together they cover the whole square with the leaf counted twice, so take the square off once:'),
          maths('2 \\times \\tfrac{1}{4} \\times \\pi \\times 4^2 = 8\\pi'),
          maths('\\text{leaf} = 8\\pi - 16'),
        ),
        ask('cm-leaf'),
        askAfter(
          'cm-leaf+choice',
          2,
          prose('The part of the square outside the leaf is the square less the leaf. For the square of side $4$:'),
          maths('16 - (8\\pi - 16) = 32 - 8\\pi'),
        ),
        askAfter(
          'cm-arbelos',
          1,
          prose('$C$ is on $AB$, and semicircles stand on $AB$, $AC$ and $CB$. The big one less the two small ones leaves a curved shape. A semicircle on a diameter $d$ has area $\\tfrac{\\pi d^2}{8}$, so with $AC = 6$ and $CB = 2$:'),
          maths('\\tfrac{\\pi}{8}\\left(8^2 - 6^2 - 2^2\\right) = \\tfrac{\\pi}{8} \\times 24 = 3\\pi'),
          prose('The squares always leave twice $AC \\times CB$, so the area is $\\tfrac{\\pi}{4} \\times AC \\times CB$.'),
        ),
        teach(
          prose('**Hippocrates’ lunes.** Triangle $ABC$ has a right angle at $C$, with $AC = 6$, $BC = 8$ and $AB = 10$. Semicircles stand outwards on $AC$ and $BC$, and the semicircle on $AB$ passes through $C$. The two crescents left outside it are **lunes**.'),
          prose('By Pythagoras the semicircles on the legs add up to the one on the hypotenuse:'),
          maths('\\frac{36\\pi}{8} + \\frac{64\\pi}{8} = \\frac{100\\pi}{8}'),
          prose('The lunes are the two small semicircles and the triangle, less the big semicircle. The $\\pi$ parts cancel, and the lunes are exactly the triangle:'),
          maths('\\tfrac{1}{2} \\times 6 \\times 8 = 24'),
          prose('An answer with $\\pi$ in it is the trap.'),
        ),
        ask('cm-lune'),
        ask('cm-lune-table'),
        askAfter(
          'cm-arbelos+choice',
          2,
          prose('Given only a height: the line from $C$ at right angles to $AB$ meets the big semicircle at $D$. The angle $ADB$ is in a semicircle, so it is a right angle, and $CD$ is the altitude of triangle $ADB$:'),
          maths('AC \\times CB = CD^2'),
          prose('So with $CD = 6$ the area is'),
          maths('\\tfrac{\\pi}{4} \\times 36 = 9\\pi'),
        ),
        askAfter(
          'cm-lune+choice',
          2,
          prose('When $AC = BC$ the figure is symmetric, so the two lunes are equal and each is half the triangle. With $AC = BC = 6$ the triangle is $18$, and one lune is'),
          maths('18 \\div 2 = 9'),
        ),
        askAfter(
          'cm-lune-table',
          2,
          prose('Given $AC$ and $AB$ only: the semicircle on $BC$ is the one on $AB$ less the one on $AC$, and the triangle needs $BC$ itself, from Pythagoras:'),
          maths('BC^2 = AB^2 - AC^2'),
        ),
      ],
      skillCheck: [ask('cm-leaf', 2), ask('cm-lune', 2), ask('cm-arbelos', 2)],
    },
    {
      id: 'cm-l6-inscribed',
      title: 'Inscribed Figures',
      slides: [
        teach(
          prose('A circle **inscribed** in a shape touches every side. Two facts do the work: the two tangents from a point to a circle are equal, and the radius to a touching point meets the side at right angles.'),
          prose('In a right triangle with sides $6$, $8$ and $10$, the centre and the two touching points on the legs make a square of side $r$ at the right angle. So each leg is $r$ plus a tangent from the far corner, and those two tangents make up the hypotenuse:'),
          maths('(6 - r) + (8 - r) = 10'),
          maths('2r = 6 + 8 - 10 = 4'),
          maths('r = 2'),
          prose('Half the hypotenuse, $5$, is the radius of the circle through the corners, not the one inside: the trap.'),
        ),
        ask('cm-incircle-right'),
        askAfter(
          'cm-incircle-right+choice',
          2,
          prose('The part of the triangle outside the circle is the triangle less the circle. For the $6$, $8$, $10$ triangle:'),
          maths('\\tfrac{1}{2} \\times 6 \\times 8 - \\pi \\times 2^2 = 24 - 4\\pi'),
        ),
        askAfter(
          'cm-semicircle-square',
          1,
          prose('A square standing on the diameter of a semicircle, with its top corners on the arc, sits in the middle, so the centre is the middle of its base. With side $s$, a top corner is $\\tfrac{s}{2}$ across and $s$ up from the centre, and that is a radius. With radius $5$:'),
          maths('s^2 + \\tfrac{1}{4}s^2 = 5^2'),
          maths('s^2 = 25 \\times \\tfrac{4}{5} = 20'),
        ),
        teach(
          prose('In an **equilateral triangle** the heights are also the medians, and the medians cross a third of the way up each one. That point is the centre of both the circle inside and the circle through the corners.'),
          prose('So the small radius $r$ is a third of the height, and the big radius $R$ two thirds. With $r = 4$:'),
          maths('R = 2 \\times 4 = 8'),
          maths('\\text{height} = 4 + 8 = 12'),
          prose('The ring between the two circles is'),
          maths('\\pi \\times 8^2 - \\pi \\times 4^2 = 48\\pi'),
        ),
        ask('cm-equilateral-circles'),
        askAfter(
          'cm-ring-chord',
          1,
          prose('Two circles share a centre, and a chord of the big one just touches the small one. The radius to the touching point cuts the chord in half at right angles, so with radii $R$ and $r$'),
          maths('R^2 - r^2 = (\\tfrac{1}{2}\\text{chord})^2'),
          prose('The ring is $\\pi R^2 - \\pi r^2$, so it needs only the chord. A chord of $10$ gives'),
          maths('\\pi \\times 5^2 = 25\\pi'),
        ),
        askAfter(
          'cm-semicircle-square+choice',
          2,
          prose('Going the other way, from a square of side $4$: a top corner is $2$ across and $4$ up from the centre, so'),
          maths('r^2 = 4^2 + 2^2 = 20'),
          maths('\\tfrac{1}{2}\\pi r^2 = 10\\pi'),
        ),
        askAfter(
          'cm-ring-chord+choice',
          2,
          prose('Backwards, from a ring of area $36\\pi$:'),
          maths('(\\tfrac{1}{2}\\text{chord})^2 = 36'),
          maths('\\text{chord} = 2 \\times 6 = 12'),
        ),
        askAfter('cm-equilateral-circles', 2, prose('Given the big radius instead, halve it for the small one: $R = 10$ gives $r = 5$ and a height of $15$.')),
      ],
      skillCheck: [ask('cm-incircle-right', 2), ask('cm-semicircle-square', 2), ask('cm-ring-chord', 2)],
    },
    {
      id: 'cm-l6-ratios',
      title: 'Ratios Meet Geometry',
      slides: [
        teach(
          prose('Areas inside a figure are often fixed fractions of the whole, however it is drawn. Write $[PAB]$ for the area of triangle $PAB$.'),
          prose('Join a point $P$ inside rectangle $ABCD$ to the four corners. Triangles $PAB$ and $PCD$ stand on the equal sides $AB$ and $CD$, and their heights add up to the height of the rectangle. So together they make half the rectangle, and so do the other two:'),
          maths('[PAB] + [PCD] = [PBC] + [PDA]'),
          prose('With $[PAB] = 10$, $[PBC] = 12$ and $[PDA] = 8$:'),
          maths('[PCD] = 12 + 8 - 10 = 10'),
        ),
        ask('cm-point-in-rectangle'),
        askAfter(
          'cm-triangle-bands',
          1,
          prose('Cut a triangle into $4$ strips of equal height by lines parallel to its base. The lines cut off triangles similar to the whole, with sides $\\tfrac{1}{4}$, $\\tfrac{2}{4}$ and $\\tfrac{3}{4}$ of it, so areas $1$, $4$ and $9$ times the top one, and the whole is $16$. Each strip is a difference of squares, so from the top the strips are'),
          maths('1 : 3 : 5 : 7'),
          prose('For a triangle of area $48$:'),
          maths('\\text{top} = 48 \\div 16 = 3'),
          maths('\\text{second strip} = 3 \\times 3 = 9'),
        ),
        askAfter(
          'cm-point-in-rectangle+choice',
          2,
          prose('The same works in a **parallelogram**: opposite sides are still equal and parallel, and the heights of the two triangles standing on them still add up to the distance between those sides.'),
        ),
        teach(
          prose('A regular hexagon $ABCDEF$ splits from its centre $O$ into six equilateral triangles, so count sixths:'),
          prose('Triangle $ABC$ is half the rhombus $ABCO$, which is two of the six: one sixth.'),
          prose('Triangle $ABD$ stands on the diameter $AD$, and is twice triangle $ABO$: two sixths.'),
          prose('Triangle $ACE$ is the hexagon less three triangles like $ABC$: three sixths.'),
          prose('Rectangle $ACDF$ is the hexagon less $ABC$ and $DEF$: four sixths. For a hexagon of area $60$ it is'),
          maths('\\tfrac{4}{6} \\times 60 = 40'),
        ),
        ask('cm-hexagon-table'),
        askAfter(
          'cm-square-cevian',
          1,
          prose('In square $ABCD$, $M$ is the midpoint of $BC$, and $AM$ crosses the diagonal $BD$ at $P$. $AD$ is parallel to $BM$ and twice as long, so triangles $PAD$ and $PMB$ make an hourglass, and $P$ is two thirds of the way from $A$ to $M$. So $P$ is a third of the way up from $AB$. For a square of side $6$:'),
          maths('[ABP] = \\tfrac{1}{2} \\times 6 \\times 2 = 6'),
          prose('a sixth of the square. In the same way $[BMP]$ is a third of triangle $ABM$, a twelfth of the square, and $[APD]$ is two thirds of triangle $ABD$, a third of it.'),
        ),
        askAfter(
          'cm-triangle-bands+choice',
          2,
          prose('Every other strip shaded, starting at the top, in $4$ strips: the shaded parts are $1$ and $5$ of the $16$. For the triangle of area $48$, with the top triangle $3$:'),
          maths('(1 + 5) \\times 3 = 18'),
          prose('Half the triangle, $24$, is the trap: the shaded strips are the smaller ones.'),
        ),
        askAfter(
          'cm-square-cevian+choice',
          2,
          prose('For the quadrilateral $PMCD$: triangle $BCD$ is half the square, and taking off triangle $BMP$, a twelfth, leaves it. In the square of area $36$:'),
          maths('18 - 3 = 15'),
        ),
        askAfter('cm-hexagon-table', 2, prose('Going the other way, from a piece: triangle $ABC$ is one sixth, so with $[ABC] = 7$ the hexagon is $42$ and every piece is a whole number of $7$s.')),
      ],
      skillCheck: [ask('cm-point-in-rectangle', 2), ask('cm-triangle-bands', 2), ask('cm-square-cevian', 2)],
    },
    {
      id: 'cm-l6-3d',
      title: 'Working in 3D',
      slides: [
        teach(
          prose('A cube of edge $4$ is painted on the outside and cut into $64$ unit cubes. Sort them by where they were:'),
          prose('**Corners**, three faces painted: always $8$.'),
          prose('**Edges** without their corners, two faces: each of the $12$ edges has $4 - 2$ of them.'),
          maths('12 \\times 2 = 24'),
          prose('**Face middles**, one face: a $2 \\times 2$ square on each of the $6$ faces.'),
          maths('6 \\times 2^2 = 24'),
          prose('**The core**, none painted: a $2 \\times 2 \\times 2$ cube.'),
          maths('2^3 = 8'),
          prose('They add up to the whole:'),
          maths('8 + 24 + 24 + 8 = 64'),
        ),
        ask('cm-painted-cube'),
        ask('cm-painted-table'),
        askAfter(
          'cm-painted-cube+choice',
          2,
          prose('A block that is not a cube works the same way, with each length $2$ shorter. A $3 \\times 4 \\times 5$ block has a core of'),
          maths('1 \\times 2 \\times 3 = 6'),
          prose('Its $12$ edges come in fours of each length, so the two-face cubes are'),
          maths('4 \\times (1 + 2 + 3) = 24'),
          prose('and its faces come in pairs, so the one-face cubes are'),
          maths('2 \\times (1 \\times 2 + 2 \\times 3 + 1 \\times 3) = 22'),
        ),
        teach(
          prose('A cube of edge $3$ is glued centred on top of a cube of edge $5$. The tower’s surface area is not the two cubes’ areas added, because the glued faces are hidden.'),
          prose('Look down from above: the tops you see fit together into exactly the big cube’s top face. So the top and the bottom are two big faces, and the sides are four faces of each cube:'),
          maths('2 \\times 5^2 + 4 \\times (5^2 + 3^2)'),
          maths('= 50 + 136 = 186'),
          prose('Adding all twelve faces, $204$, is the trap.'),
        ),
        ask('cm-stacked-cubes'),
        askAfter(
          'cm-drilled-cube',
          1,
          prose('A square hole of side $2$ is cut straight through a cube of edge $6$. The hole is a square prism as long as the cube:'),
          maths('2^2 \\times 6 = 24'),
          maths('6^3 - 24 = 192'),
        ),
        askAfter(
          'cm-stacked-cubes+choice',
          2,
          prose('With three cubes the view from above still shows exactly the bottom cube’s top. Edges $5$, $3$ and $2$:'),
          maths('2 \\times 25 + 4 \\times (25 + 9 + 4) = 202'),
        ),
        askAfter(
          'cm-drilled-cube+choice',
          2,
          prose('For the surface area of the drilled cube: two faces each lose a $2 \\times 2$ opening, and the tunnel adds four inside walls, each $2$ by $6$:'),
          maths('6 \\times 36 - 2 \\times 4 + 4 \\times 12 = 256'),
        ),
        ask('cm-painted-table', 2),
      ],
      skillCheck: [ask('cm-painted-cube', 2), ask('cm-stacked-cubes', 2), ask('cm-drilled-cube', 2)],
    },
  ],
  levelCheck: [
    ask('cm-garden-path', 2),
    ask('cm-overlap-squares+choice', 2),
    ask('cm-arch-area', 2),
    ask('cm-leaf+choice', 2),
    ask('cm-lune', 2),
    ask('cm-lune-table', 2),
    ask('cm-arbelos', 2),
    ask('cm-incircle-right+choice', 2),
    ask('cm-ring-chord', 2),
    ask('cm-triangle-bands+choice', 2),
    ask('cm-square-cevian', 2),
    ask('cm-painted-table', 2),
    ask('cm-drilled-cube', 2),
  ],
};
