/**
 * Contest Math, Level 2: Equations and Ratios. Percentages, ratios, simple
 * equations and sequences, each turned by one idea. Generators in
 * `generators/contestEquationsRatios.ts`.
 */
import type { Level } from '../../types';
import { teach, ask, prose, maths, askAfter } from './blocks';

export const equationsRatios: Level = {
  id: 'cm-l2',
  title: 'Equations and Ratios',
  lessons: [
    {
      id: 'cm-l2-ratios-percents',
      title: 'Ratios and Percentages',
      slides: [
        teach(
          prose('A percentage change is a multiplication. A rise of $20\\%$ multiplies by $1.2$, and a cut of $20\\%$ multiplies by $0.8$.'),
          prose('So a rise of $20\\%$ followed by a cut of $20\\%$ does not get back to the start:'),
          maths('1.2 \\times 0.8 = 0.96'),
          prose('The price ends at $96\\%$ of where it began, a change of'),
          maths('96 - 100 = -4'),
          prose('percent. Multiplying works in either order, so the order of the two changes makes no difference.'),
        ),
        ask('cm-percent-chain'),
        askAfter(
          'cm-percent-swap+choice',
          1,
          prose('$x\\%$ of $y$ is $x \\times y \\div 100$, and so is $y\\%$ of $x$. Swap them when that makes it easy:'),
          maths('16\\% \\text{ of } 25 = 25\\% \\text{ of } 16 = 4'),
        ),
        askAfter(
          'cm-reverse-percent',
          1,
          prose('Going back: after a rise of $25\\%$ a coat costs £$150$. The new price is $1.25$ times the old one, so divide:'),
          maths('150 \\div 1.25 = 120'),
          prose('Taking $25\\%$ off $150$ gives $112.50$, which is wrong: the $25\\%$ was of the old price.'),
        ),
        teach(
          prose('Ratios count **parts**. Sam and Tia share sweets $5 : 3$, and Sam gets $10$ more. The difference is $2$ parts:'),
          maths('2 \\text{ parts} = 10'),
          maths('1 \\text{ part} = 5'),
          prose('So Sam has $25$, Tia $15$, and there are $40$ in all.'),
          prose('Two ratios that share a quantity join by making the shared one match. With $a : b = 2 : 3$ and $b : c = 4 : 5$, make $b$ the LCM, $12$:'),
          maths('2 : 3 = 8 : 12'),
          maths('4 : 5 = 12 : 15'),
          maths('a : b : c = 8 : 12 : 15'),
        ),
        ask('cm-ratio-share'),
        ask('cm-ratio-combine'),
        askAfter(
          'cm-reverse-percent+choice',
          2,
          prose('A sale works the same way. In a $30\\%$ off sale the price is $70\\%$ of the old one, so divide by $0.7$.'),
        ),
        ask('cm-percent-chain+choice', 2),
        askAfter('cm-ratio-share', 2, prose('Once one part is known, any share is that many parts.')),
      ],
      skillCheck: [ask('cm-percent-swap', 2), ask('cm-ratio-combine', 2), ask('cm-reverse-percent', 2)],
    },
    {
      id: 'cm-l2-equations',
      title: 'Simple Equations',
      slides: [
        teach(
          prose('Brackets on both sides: multiply out, then collect $x$ on one side and numbers on the other.'),
          maths('4(x - 3) = 2(x + 5) + x'),
          maths('4x - 12 = 2x + 10 + x'),
          maths('4x - 3x = 10 + 12'),
          maths('x = 22'),
        ),
        ask('cm-brackets-equation'),
        askAfter(
          'cm-three-scores',
          1,
          prose('Word problems: name the smallest amount and write the others from it. The second has twice the third, and the first has $10$ more than the second, $100$ in all. With the third as $t$:'),
          maths('t + 2t + (2t + 10) = 100'),
          maths('5t = 90'),
          maths('t = 18'),
          prose('So the second has $36$ and the first $46$.'),
        ),
        ask('cm-three-scores-tiles'),
        askAfter(
          'cm-brackets-equation+choice',
          2,
          prose('When the right has more $x$, the $x$ left over is negative:'),
          maths('3(x - 1) = 2(x + 4) + 2x'),
          maths('3x - 3 = 4x + 8'),
          maths('-x = 11'),
          maths('x = -11'),
        ),
        teach(
          prose('Half a journey at $30$ mph and half at $60$ mph: the halves are the same distance, so the time goes the other way to the speed.'),
          maths('\\text{time}_1 : \\text{time}_2 = 60 : 30 = 2 : 1'),
          prose('A $45$-minute trip splits $30$ and $15$ minutes.'),
          prose('Mixtures: count the one thing that is mixed. Mix $x$ kg of a $10\\%$ nut mix with $20 - x$ kg of a $40\\%$ one to get $20$ kg at $25\\%$:'),
          maths('0.1x + 0.4(20 - x) = 5'),
          maths('10x + 800 - 40x = 500'),
          maths('30x = 300'),
          maths('x = 10'),
        ),
        ask('cm-halfway-speeds'),
        ask('cm-mixture'),
        ask('cm-halfway-speeds+choice', 2),
        ask('cm-mixture+choice', 2),
      ],
      skillCheck: [ask('cm-three-scores', 2), ask('cm-brackets-equation', 2), ask('cm-mixture', 2)],
    },
    {
      id: 'cm-l2-sequences',
      title: 'Sequences and Series',
      slides: [
        teach(
          prose('An arithmetic sequence adds the same step $d$ each time. Two terms give the step: the 3rd term is $7$ and the 8th is $22$, which is $5$ steps on.'),
          maths('22 - 7 = 15'),
          maths('d = 15 \\div 5 = 3'),
          prose('The 20th term is $12$ steps past the 8th:'),
          maths('22 + 12 \\times 3 = 58'),
        ),
        ask('cm-arith-term'),
        ask('cm-sequence-table'),
        askAfter(
          'cm-arith-sum',
          1,
          prose('To add an arithmetic series, count the terms, then pair the first with the last. For $5 + 7 + \\cdots + 25$:'),
          maths('(25 - 5) \\div 2 + 1 = 11'),
          maths('5 + 25 = 30'),
          maths('\\tfrac{1}{2} \\times 11 \\times 30 = 165'),
        ),
        ask('cm-arith-term+choice', 2),
        teach(
          prose('The first $n$ odd numbers add to $n^2$: there are $n$ terms and each pair makes $2n$.'),
          maths('1 + 3 + 5 + 7 = 16 = 4^2'),
          prose('The first $n$ even numbers are each one more, so they add to $n^2 + n$:'),
          maths('2 + 4 + 6 + 8 = 20 = 4^2 + 4'),
          prose('A geometric sequence multiplies instead, so it grows fast and it is quickest to write the terms out. Starting at $3$ and doubling: $3, 6, 12, 24, 48, 96, 192$. The first term past $100$ is the 7th.'),
        ),
        ask('cm-odd-sums'),
        ask('cm-geo-past'),
        askAfter('cm-odd-sums+choice', 2, prose('Evens take away odds: pair $2 - 1$, $4 - 3$ and so on, and each pair is $1$.')),
        ask('cm-arith-sum+choice', 2),
      ],
      skillCheck: [ask('cm-geo-past+choice', 2), ask('cm-sequence-table', 2), ask('cm-odd-sums', 2)],
    },
    {
      id: 'cm-l2-equations-ratios',
      title: 'Equations with Ratios',
      slides: [
        teach(
          prose('When a ratio changes, write the amounts as parts of an unknown $k$. Red to blue is $3 : 1$, and after $10$ more of each it is $2 : 1$:'),
          maths('3k + 10 = 2(k + 10)'),
          maths('3k + 10 = 2k + 20'),
          maths('k = 10'),
          prose('So there were $30$ red at first.'),
        ),
        ask('cm-ratio-change'),
        askAfter(
          'cm-age-ratio',
          1,
          prose('Ages work the same way, and both ages go up by the same number of years. Ana is $4$ times as old as Ben, and in $6$ years she will be $3$ times as old:'),
          maths('4s + 6 = 3(s + 6)'),
          maths('4s + 6 = 3s + 18'),
          maths('s = 12'),
          prose('So Ben is $12$ and Ana is $48$.'),
        ),
        ask('cm-ratio-change+choice', 2),
        teach(
          prose('When only a ratio is given, only the ratio matters, so pick numbers in it. With $x : y = 2 : 5$, take $x = 2$ and $y = 5$:'),
          maths('\\frac{3x + y}{x + y} = \\frac{6 + 5}{2 + 5} = \\frac{11}{7}'),
          prose('Working together, add the **rates**, not the times. Taps that fill a bath in $4$ and $6$ minutes fill, each minute,'),
          maths('\\frac{1}{4} + \\frac{1}{6} = \\frac{5}{12}'),
          prose('of it, so together they take $\\frac{12}{5}$ minutes.'),
        ),
        ask('cm-ratio-expression'),
        ask('cm-work-together'),
        ask('cm-age-ratio+choice', 2),
        askAfter(
          'cm-ratio-combine',
          2,
          prose('Two ratios with a shared quantity: make the shared one match. With $a : b = 3 : 4$ and $b : c = 6 : 5$, make $b = 12$:'),
          maths('a : b : c = 9 : 12 : 10'),
        ),
        ask('cm-work-together+choice', 2),
        ask('cm-ratio-expression+choice', 2),
      ],
      skillCheck: [ask('cm-age-ratio', 2), ask('cm-ratio-expression', 2), ask('cm-work-together', 2)],
    },
    {
      id: 'cm-l2-geometric-ratios',
      title: 'Non-numeric Geometric Ratios',
      slides: [
        teach(
          prose('Scale a shape so every length is $k$ times as long. Areas are two lengths multiplied, so they scale by $k^2$. Volumes are three, so by $k^3$.'),
          prose('Similar triangles with lengths $2 : 3$ have areas $4 : 9$. If the smaller has area $8$, the larger has'),
          maths('8 \\times \\tfrac{9}{4} = 18'),
          prose('Going back, areas $9 : 16$ mean lengths $3 : 4$ and so volumes $27 : 64$.'),
        ),
        ask('cm-scale-factor'),
        ask('cm-scale-tiles'),
        askAfter(
          'cm-scale-factor+choice',
          2,
          prose('Volumes cube the length ratio. Similar cones with lengths $1 : 2$ have volumes $1 : 8$, so a volume of $5$ becomes $40$.'),
        ),
        teach(
          prose('Some areas need no lengths at all.'),
          prose('Join any point on the top of a rectangle to the bottom corners. The triangle has the same base and height, so it is **half** the rectangle. A parallelogram works the same way.'),
          prose('Join the midpoints of a triangle’s sides. The middle triangle has sides half as long, so its area is a **quarter**. Do it twice and it is a sixteenth.'),
          prose('Draw a circle inside a square and a square inside that circle. The inner square’s diagonal is the outer square’s side, so its area is **half**.'),
        ),
        ask('cm-half-rectangle'),
        ask('cm-midpoint-triangles'),
        ask('cm-nested-squares+choice'),
        ask('cm-half-rectangle+choice', 2),
        ask('cm-nested-squares', 2),
      ],
      skillCheck: [ask('cm-midpoint-triangles', 2), ask('cm-scale-tiles', 2), ask('cm-half-rectangle', 2)],
    },
  ],
  levelCheck: [
    ask('cm-percent-chain', 2),
    ask('cm-reverse-percent', 2),
    ask('cm-ratio-combine', 2),
    ask('cm-brackets-equation', 2),
    ask('cm-three-scores', 2),
    ask('cm-halfway-speeds+choice', 2),
    ask('cm-arith-sum', 2),
    ask('cm-odd-sums', 2),
    ask('cm-age-ratio', 2),
    ask('cm-work-together', 2),
    ask('cm-scale-factor', 2),
    ask('cm-nested-squares', 2),
  ],
};
