/**
 * Contest Math, Level 8: Probability. Counting equally likely outcomes (and
 * noticing when a list of outcomes is not equally likely), inclusion and
 * exclusion and the complement, counting with binomial coefficients, and
 * symmetry and conditioning, which answer without counting everything.
 * Generators in `generators/contestProbability.ts`.
 */
import type { Level } from '../../types';
import { teach, ask, prose, maths, askAfter } from './blocks';

export const probability: Level = {
  id: 'cm-l8',
  title: 'Probability',
  lessons: [
    {
      id: 'cm-l8-outcomes',
      title: 'Probability by Outcomes',
      slides: [
        teach(
          prose('When every outcome is equally likely, a probability is a count: the outcomes that work, out of all of them.'),
          prose('Roll two dice and tell them apart, first and second. Each of $6$ numbers on the first goes with each of $6$ on the second:'),
          maths('6 \\times 6 = 36'),
          prose('A total of $7$ runs from $(1, 6)$ to $(6, 1)$, which is $6$ outcomes:'),
          maths('P(7) = \\frac{6}{36} = \\frac{1}{6}'),
          prose('The trap is to say there are $11$ totals, $2$ to $12$, so each has probability $\\tfrac{1}{11}$. The totals are not equally likely: $2$ is only $(1, 1)$. Count outcomes, never totals. Two $8$-sided dice work the same way, with $64$ outcomes.'),
        ),
        ask('cm-pr-dice-sum'),
        askAfter(
          'cm-pr-dice-table',
          1,
          prose('Up to the middle total, a total of $t$ has $t - 1$ outcomes. A total of $5$:'),
          maths('(1, 4), \\; (2, 3), \\; (3, 2), \\; (4, 1)'),
          prose('Past the middle the counts fall away again: $10$ has as many as $4$, which is $3$.'),
        ),
        askAfter(
          'cm-pr-order',
          1,
          prose('One die shows a $2$ and the other a $5$: that is two outcomes, not one, because either die can hold the $2$.'),
          maths('(2, 5), \\; (5, 2)'),
          maths('P = \\frac{2}{36} = \\frac{1}{18}'),
          prose('Forgetting the order gives $\\tfrac{1}{36}$, the trap.'),
        ),
        askAfter(
          'cm-pr-dice-sum+choice',
          2,
          prose('When several totals work, add their outcomes. A total that is a multiple of $5$ is $5$ or $10$:'),
          maths('4 + 3 = 7'),
          maths('P = \\frac{7}{36}'),
          prose('A total of at least $10$ is $10$, $11$ or $12$:'),
          maths('3 + 2 + 1 = 6'),
        ),
        teach(
          prose('Toss three coins. The $2^3 = 8$ sequences, like HTH, are equally likely. Exactly two heads is'),
          maths('\\text{HHT}, \\; \\text{HTH}, \\; \\text{THH}'),
          maths('P = \\frac{3}{8}'),
          prose('The numbers of heads, $0$ to $3$, are not equally likely, so $\\tfrac{1}{4}$ is the trap. The counts for each number of heads are a row of Pascal’s triangle, each entry the sum of the two above it:'),
          maths('1, \\; 3, \\; 3, \\; 1'),
          maths('1, \\; 4, \\; 6, \\; 4, \\; 1'),
          prose('So four coins give exactly two heads in $6$ of their $16$ sequences, $\\tfrac{3}{8}$.'),
        ),
        ask('cm-pr-coins'),
        askAfter(
          'cm-pr-coins',
          2,
          prose('For at least or at most, add entries of the row. At least $3$ heads from $5$ coins uses the row $1, 5, 10, 10, 5, 1$:'),
          maths('10 + 5 + 1 = 16'),
          maths('P = \\frac{16}{32} = \\frac{1}{2}'),
        ),
        askAfter(
          'cm-pr-order+choice',
          2,
          prose('Three dice showing $1$, $2$ and $3$ in some order: any of the three numbers on the first die, either of the other two on the second, the last on the third.'),
          maths('3 \\times 2 \\times 1 = 6'),
          maths('P = \\frac{6}{216} = \\frac{1}{36}'),
          prose('With a repeat, like $2$, $2$ and $5$, only the place of the $5$ matters, so there are $3$ orders:'),
          maths('P = \\frac{3}{216} = \\frac{1}{72}'),
        ),
        ask('cm-pr-dice-table', 2),
      ],
      skillCheck: [ask('cm-pr-dice-sum', 2), ask('cm-pr-order', 2), ask('cm-pr-coins+choice', 2)],
    },
    {
      id: 'cm-l8-pie',
      title: 'PIE and Complements',
      slides: [
        teach(
          prose('**Inclusion and exclusion** (PIE): to count what is in $A$ or $B$, add the two and take off the overlap, which was counted twice.'),
          maths('P(A \\cup B) = P(A) + P(B) - P(A \\cap B)'),
          prose('One card from a pack of $52$. A heart or a king: $13$ hearts and $4$ kings, but the king of hearts is in both.'),
          maths('13 + 4 - 1 = 16'),
          maths('P = \\frac{16}{52} = \\frac{4}{13}'),
          prose('Adding without the overlap gives $\\tfrac{17}{52}$, the trap. A red card or a king overlaps in the $2$ red kings; the face cards are the jacks, queens and kings, $12$ of them.'),
        ),
        ask('cm-pr-cards'),
        askAfter(
          'cm-pr-pie-count',
          1,
          prose('Pick a whole number from $1$ to $30$. Multiples of $2$ or of $3$: the overlap is the multiples of $6$.'),
          maths('15 + 10 - 5 = 20'),
          maths('P = \\frac{20}{30} = \\frac{2}{3}'),
        ),
        askAfter(
          'cm-pr-venn',
          1,
          prose('With probabilities: $P(A) = 0.5$, $P(B) = 0.4$ and neither $0.3$. Everything else is in a circle:'),
          maths('P(A \\cup B) = 1 - 0.3 = 0.7'),
          maths('P(A \\cap B) = 0.5 + 0.4 - 0.7 = 0.2'),
          prose('Then take the overlap off each circle:'),
          maths('0.5 - 0.2 = 0.3, \\quad 0.4 - 0.2 = 0.2'),
        ),
        askAfter(
          'cm-pr-cards+choice',
          2,
          prose('**Neither** is the complement of either. Neither a heart nor a king:'),
          maths('52 - 16 = 36'),
          maths('P = \\frac{36}{52} = \\frac{9}{13}'),
        ),
        teach(
          prose('**At least one** has many cases. Its complement, **none**, has just one, so work that out and take it from $1$.'),
          prose('Roll a die three times. Each roll misses a six with probability $\\tfrac{5}{6}$, and the rolls are independent:'),
          maths('P(\\text{no six}) = \\left(\\frac{5}{6}\\right)^3 = \\frac{125}{216}'),
          maths('P(\\text{at least one six}) = 1 - \\frac{125}{216} = \\frac{91}{216}'),
          prose('Adding $\\tfrac{1}{6}$ three times gives $\\tfrac{1}{2}$, the trap: it counts two sixes twice, and seven rolls would give more than $1$. And $\\tfrac{125}{216}$ itself is the answer to the wrong question.'),
        ),
        ask('cm-pr-at-least-one'),
        askAfter(
          'cm-pr-pie-count+choice',
          2,
          prose('Multiples of $4$ or of $6$ from $1$ to $50$: a number is a multiple of both when it is a multiple of their LCM, $12$, not of $24$.'),
          maths('12 + 8 - 4 = 16'),
          prose('Neither is the rest:'),
          maths('P = \\frac{50 - 16}{50} = \\frac{17}{25}'),
        ),
        ask('cm-pr-at-least-one+choice', 2),
        askAfter(
          'cm-pr-venn',
          2,
          prose('Given exactly one in place of neither: $P(A) = 0.5$, $P(B) = 0.4$, exactly one $0.5$. Adding $P(A)$ and $P(B)$ counts exactly one once and the overlap twice:'),
          maths('0.5 + 0.4 - 0.5 = 0.4'),
          maths('P(A \\cap B) = 0.4 \\div 2 = 0.2'),
        ),
      ],
      skillCheck: [ask('cm-pr-cards', 2), ask('cm-pr-at-least-one', 2), ask('cm-pr-pie-count', 2)],
    },
    {
      id: 'cm-l8-choosing',
      title: 'Choosing',
      slides: [
        teach(
          prose('Choosing $k$ things from $n$ at random makes every set of $k$ equally likely, and $\\binom{n}{k}$ counts them.'),
          prose('Two are chosen from $4$ girls and $3$ boys:'),
          maths('\\binom{7}{2} = \\frac{7 \\times 6}{2} = 21'),
          prose('Both girls: $\\binom{4}{2} = 6$ of them, so'),
          maths('P = \\frac{6}{21} = \\frac{2}{7}'),
          prose('One of each: choose the girl and the boy separately and multiply:'),
          maths('4 \\times 3 = 12'),
          maths('P = \\frac{12}{21} = \\frac{4}{7}'),
          prose('The trap is $\\left(\\tfrac{4}{7}\\right)^2$ for both girls: that puts the first girl back before choosing the second.'),
        ),
        ask('cm-pr-committee'),
        askAfter(
          'cm-pr-committee-table',
          1,
          prose('Set the count out in pieces: the ways to choose from each group, their product, and the ways to choose from everyone. The probability is the product over the last.'),
        ),
        askAfter(
          'cm-pr-both-chosen',
          1,
          prose('$3$ of $8$ people are chosen. Both Ana and Ben are in when the third place goes to one of the other $6$:'),
          maths('\\binom{6}{1} = 6, \\quad \\binom{8}{3} = 56'),
          maths('P = \\frac{6}{56} = \\frac{3}{28}'),
          prose('$\\left(\\tfrac{3}{8}\\right)^2$ is the trap: once Ana is in, fewer places are left for Ben.'),
        ),
        askAfter(
          'cm-pr-committee+choice',
          2,
          prose('Three from $5$ girls and $4$ boys, exactly $2$ girls:'),
          maths('\\binom{5}{2} \\times \\binom{4}{1} = 10 \\times 4 = 40'),
          maths('\\binom{9}{3} = 84'),
          maths('P = \\frac{40}{84} = \\frac{10}{21}'),
        ),
        teach(
          prose('Taking things out one at a time without putting them back is a tree whose second branches change. A bag holds $3$ red and $5$ blue counters:'),
          maths('P(\\text{R first}) = \\frac{3}{8}'),
          prose('After a red one, $7$ are left and $2$ of them are red, so the next branches are $\\tfrac{2}{7}$ red and $\\tfrac{5}{7}$ blue.'),
          prose('Two the same colour, by choosing, is a pair of reds or a pair of blues:'),
          maths('\\binom{3}{2} + \\binom{5}{2} = 3 + 10 = 13'),
          maths('\\binom{8}{2} = 28'),
          maths('P = \\frac{13}{28}'),
          prose('The tree agrees, adding the red-red and blue-blue paths:'),
          maths('\\frac{3}{8} \\times \\frac{2}{7} + \\frac{5}{8} \\times \\frac{4}{7} = \\frac{26}{56}'),
        ),
        ask('cm-pr-bag-tree'),
        ask('cm-pr-same-colour'),
        askAfter(
          'cm-pr-both-chosen+choice',
          2,
          prose('$3$ of $8$ again. Exactly one of Ana and Ben: pick which one ($2$ ways), then two places from the $6$ others:'),
          maths('2 \\times \\binom{6}{2} = 30'),
          maths('P = \\frac{30}{56} = \\frac{15}{28}'),
          prose('Neither: all three places from the $6$ others.'),
          maths('P = \\frac{\\binom{6}{3}}{56} = \\frac{20}{56} = \\frac{5}{14}'),
        ),
        askAfter(
          'cm-pr-same-colour+choice',
          2,
          prose('With three colours, add a pair for each colour. Different colours is every other pair, so take the same-colour pairs from the total. With $2$ red, $3$ blue and $4$ green there are $\\binom{9}{2} = 36$ pairs, and'),
          maths('\\binom{2}{2} + \\binom{3}{2} + \\binom{4}{2} = 1 + 3 + 6 = 10'),
          maths('P(\\text{different}) = \\frac{36 - 10}{36} = \\frac{13}{18}'),
        ),
        ask('cm-pr-bag-tree', 2),
      ],
      skillCheck: [ask('cm-pr-committee', 2), ask('cm-pr-same-colour', 2), ask('cm-pr-both-chosen', 2)],
    },
    {
      id: 'cm-l8-symmetry',
      title: 'Symmetry and Conditional',
      slides: [
        teach(
          prose('**Symmetry** answers without counting. $6$ people stand in a line in a random order. Nothing favours one place over another, so Ana is in each of the $6$ places with probability $\\tfrac{1}{6}$, and at one of the two ends with'),
          maths('P = \\frac{2}{6} = \\frac{1}{3}'),
          prose('Is Ana in front of Ben? Swap the two of them in any order and the answer flips, so the orders pair off:'),
          maths('P(\\text{Ana in front}) = \\frac{1}{2}'),
          prose('however many other people there are.'),
        ),
        ask('cm-pr-line-up'),
        askAfter(
          'cm-pr-beats',
          1,
          prose('Two dice, red and blue. A tie is $6$ of the $36$ outcomes. Swapping the colours turns red higher into blue higher, so the rest splits evenly:'),
          maths('P(\\text{red higher}) = \\frac{1}{2}\\left(1 - \\frac{1}{6}\\right) = \\frac{5}{12}'),
          prose('Red at least as big as blue takes in the tie as well:'),
          maths('\\frac{5}{12} + \\frac{1}{6} = \\frac{7}{12}'),
          prose('Forgetting ties gives $\\tfrac{1}{2}$, the trap.'),
        ),
        askAfter(
          'cm-pr-line-up+choice',
          2,
          prose('Next to each other: Ana and Ben take two of the $6$ places, every pair of places equally likely, and $5$ of the pairs are side by side.'),
          maths('P = \\frac{5}{\\binom{6}{2}} = \\frac{5}{15} = \\frac{1}{3}'),
          prose('Three people in a given order, not necessarily together: all $3! = 6$ orders of the three are equally likely, so $\\tfrac{1}{6}$. One of three standing between the other two: each is as likely as the others to be the middle one, so $\\tfrac{1}{3}$.'),
        ),
        askAfter(
          'cm-pr-beats+choice',
          2,
          prose('Turn a die over and a face $a$ becomes $7 - a$, just as likely. That sends a total $s$ of two dice to $14 - s$, so totals above $7$ are as likely as totals below it:'),
          maths('P(\\text{total} > 7) = \\frac{1}{2}\\left(1 - \\frac{1}{6}\\right) = \\frac{5}{12}'),
          prose('With three dice a total $s$ goes to $21 - s$. No total is $10.5$, so the totals up to $10$ and those from $11$ split exactly in half: each has probability $\\tfrac{1}{2}$.'),
        ),
        teach(
          prose('**Given** that something happened, throw away every outcome where it did not. What is left is still equally likely.'),
          prose('Two dice are rolled, and at least one shows a six. The six on red is $6$ outcomes, on blue $6$, with $(6, 6)$ in both:'),
          maths('6 + 6 - 1 = 11'),
          prose('Only $(6, 6)$ has two sixes, so'),
          maths('P(\\text{two sixes} \\mid \\text{at least one six}) = \\frac{1}{11}'),
          prose('Not $\\tfrac{1}{36}$, which ignores what you were told, and not $\\tfrac{1}{6}$, which pretends you know which die it was.'),
        ),
        ask('cm-pr-cond-dice'),
        askAfter(
          'cm-pr-bags-tree',
          1,
          prose('A die roll of $1$ or $2$ sends you to bag A, anything else to bag B:'),
          maths('P(A) = \\frac{2}{6} = \\frac{1}{3}, \\quad P(B) = \\frac{2}{3}'),
          prose('Bag A holds $2$ red and $3$ green counters, so under A the branches are $\\tfrac{2}{5}$ red and $\\tfrac{3}{5}$ green. Each bag gives its own branches.'),
        ),
        askAfter(
          'cm-pr-bags-bayes',
          1,
          prose('Turned round: a coin picks bag A ($3$ red, $1$ green) or bag B ($1$ red, $3$ green), and the counter is red. Multiply along both red paths:'),
          maths('P(A \\cap R) = \\frac{1}{2} \\times \\frac{3}{4} = \\frac{3}{8}'),
          maths('P(B \\cap R) = \\frac{1}{2} \\times \\frac{1}{4} = \\frac{1}{8}'),
          prose('Given red, keep only those two paths. Bag A is its share of them:'),
          maths('P(A \\mid R) = \\frac{3}{8} \\div \\left(\\frac{3}{8} + \\frac{1}{8}\\right) = \\frac{3}{4}'),
        ),
        askAfter(
          'cm-pr-cond-dice+choice',
          2,
          prose('Given the total, the kept outcomes are the ones with that total. Given a total of $8$:'),
          maths('(2, 6), \\; (3, 5), \\; (4, 4), \\; (5, 3), \\; (6, 2)'),
          prose('One of the five is a double, so a double has probability $\\tfrac{1}{5}$, not $\\tfrac{1}{6}$.'),
        ),
        ask('cm-pr-bags-bayes+choice', 2),
      ],
      skillCheck: [ask('cm-pr-line-up', 2), ask('cm-pr-cond-dice', 2), ask('cm-pr-bags-bayes', 2)],
    },
  ],
  levelCheck: [
    ask('cm-pr-dice-sum', 2),
    ask('cm-pr-order', 2),
    ask('cm-pr-coins', 2),
    ask('cm-pr-cards', 2),
    ask('cm-pr-pie-count', 2),
    ask('cm-pr-at-least-one+choice', 2),
    ask('cm-pr-committee', 2),
    ask('cm-pr-same-colour+choice', 2),
    ask('cm-pr-both-chosen', 2),
    ask('cm-pr-line-up', 2),
    ask('cm-pr-beats+choice', 2),
    ask('cm-pr-cond-dice', 2),
    ask('cm-pr-bags-bayes', 2),
  ],
};
