/**
 * Contest Math, Level 21: More Advanced Combinatorics. Building the object
 * so the rule looks after itself, counting the opposite, reading Pascal's
 * triangle, inclusion–exclusion with three sets and more, and sharing
 * identical things with minimums, odd parts and upper limits. Generators in
 * `generators/contestAdvancedCounting.ts`.
 */
import type { Level } from '../../types';
import { teach, ask, prose, maths, askAfter } from './blocks';

export const advancedCombinatorics: Level = {
  id: 'cm-l21',
  title: 'More Advanced Combinatorics',
  lessons: [
    {
      id: 'cm-l21-constructive',
      title: 'Constructive Counting',
      slides: [
        teach(
          prose('**Constructive counting** builds each object step by step, in an order that makes the rule look after itself.'),
          prose('Choose $3$ of $8$ chairs in a row so that no two chosen chairs are next to each other. Line up the $5$ chairs that are not chosen first. The chosen ones must go into the gaps between them, or at the two ends, at most one to a gap:'),
          maths('5 + 1 = 6'),
          prose('Any $3$ of those $6$ gaps keep the chosen chairs apart, and every good choice is one of them:'),
          maths('\\binom{6}{3} = 20'),
          prose('Choosing $3$ of all $8$ chairs, $56$ ways, is the trap: it counts chairs side by side.'),
        ),
        ask('cm-ac-no-adjacent'),
        ask('cm-ac-gaps-table'),
        askAfter(
          'cm-ac-no-adjacent+choice',
          2,
          prose('When the ones kept apart are different people, both groups are put in order. $3$ boys and $2$ girls in a line, no two girls together: the boys go first, in $3!$ orders, and leave $4$ gaps.'),
          maths('3! = 6'),
          prose('The two girls take two different gaps, and which girl takes which matters:'),
          maths('4 \\times 3 = 12'),
          maths('6 \\times 12 = 72'),
        ),
        ask('cm-ac-gaps-table', 2),
        teach(
          prose('Sometimes the order is **forced**, so only the choice counts. A $3$-digit number whose digits get larger from left to right, using only $1$ to $6$: choose any $3$ different digits, and there is exactly one way to write them in increasing order.'),
          maths('\\binom{6}{3} = 20'),
          prose('Counting $6 \\times 5 \\times 4 = 120$ is the trap: of the $3! = 6$ orders of each set of digits, only one increases.'),
          prose('The same idea counts crossings. Draw every diagonal of a convex hexagon, with no three through one point. Any $4$ corners have two diagonals that cross exactly once, and every crossing comes from the $4$ corners at the ends of its two diagonals:'),
          maths('\\binom{6}{4} = 15'),
        ),
        ask('cm-ac-increasing-digits'),
        ask('cm-ac-diagonal-crossings'),
        askAfter(
          'cm-ac-increasing-digits+choice',
          2,
          prose('When $0$ is allowed, look at where it would have to go. In decreasing order a $0$ can only come last, which is fine, so it joins the digits to choose from. $2$-digit numbers with falling digits from $0$ to $4$:'),
          maths('\\binom{5}{2} = 10'),
          prose('In increasing order a $0$ would have to come first, which is not allowed, so it never appears. Rising digits from $0$ to $4$ give only'),
          maths('\\binom{4}{2} = 6'),
        ),
        askAfter(
          'cm-ac-diagonal-crossings+choice',
          2,
          prose('To count **regions**, draw the chords one at a time. A chord crossing $c$ chords already drawn is cut into $c + 1$ pieces, and each piece splits a region in two. So each chord adds one region, plus one for each crossing on it:'),
          maths('\\text{regions} = 1 + \\text{chords} + \\text{crossings}'),
          prose('With $6$ points on a circle, all joined:'),
          maths('1 + \\binom{6}{2} + \\binom{6}{4} = 1 + 15 + 15 = 31'),
          prose('Not $32$: guessing that the regions double each time is the trap.'),
        ),
      ],
      skillCheck: [ask('cm-ac-no-adjacent', 2), ask('cm-ac-increasing-digits', 2), ask('cm-ac-diagonal-crossings', 2)],
    },
    {
      id: 'cm-l21-complementary',
      title: 'Complementary Counting',
      slides: [
        teach(
          prose('**Complementary counting**: when "at least one" is hard to count, count the opposite and take it away from everything.'),
          prose('$3$-digit numbers with at least one $7$. There are $900$ numbers with $3$ digits. With no $7$, the first digit avoids $0$ and $7$, so $8$ choices, and the other two avoid $7$, so $9$ each:'),
          maths('8 \\times 9 \\times 9 = 648'),
          maths('900 - 648 = 252'),
          prose('Adding up a $7$ in each place, $100 + 90 + 90 = 280$, is the trap: $777$ and $707$ are counted more than once.'),
          prose('At least one **odd** digit works the same way. With no odd digit every digit is $0$, $2$, $4$, $6$ or $8$, but the first cannot be $0$:'),
          maths('4 \\times 5 \\times 5 = 100'),
          maths('900 - 100 = 800'),
        ),
        ask('cm-ac-contains-digit'),
        askAfter(
          'cm-ac-committee',
          1,
          prose('A team of $4$ from $6$ boys and $4$ girls, with at least one girl: all the teams, less the teams with no girls.'),
          maths('\\binom{10}{4} - \\binom{6}{4} = 210 - 15 = 195'),
          prose('Choosing a girl first and then any $3$ others, $4 \\times 84 = 336$, is the trap: a team with two girls is counted once for each of them.'),
        ),
        ask('cm-ac-committee-tiles'),
        askAfter(
          'cm-ac-contains-digit+choice',
          2,
          prose('**At least two the same** is the opposite of **all different**. For $4$-digit numbers, all different has $9$ choices for the first digit, then $9$, $8$ and $7$, since $0$ is now allowed:'),
          maths('9 \\times 9 \\times 8 \\times 7 = 4536'),
          maths('9000 - 4536 = 4464'),
          prose('A code of $3$ presses on $5$ buttons: $5^{3} = 125$ codes in all and $5 \\times 4 \\times 3 = 60$ with no button twice, so $65$ press some button more than once.'),
        ),
        teach(
          prose('Routes on a grid that must **avoid** a closed corner: count every route, then take off the ones through the corner.'),
          prose('On a grid $4$ blocks across and $3$ up, going only right or up, every route is $4$ moves right and $3$ up in some order:'),
          maths('\\binom{7}{3} = 35'),
          prose('Close the corner $2$ across and $1$ up. A route through it goes $2$ right and $1$ up to reach it, then $2$ right and $2$ up to finish:'),
          maths('\\binom{3}{1} \\times \\binom{4}{2} = 3 \\times 6 = 18'),
          maths('35 - 18 = 17'),
          prose('Close the corner $3$ across and $2$ up as well: $20$ routes pass through it. A route through **both** corners was taken off twice, so add those back once. There are $3 \\times 2 \\times 2 = 12$ of them:'),
          maths('35 - 18 - 20 + 12 = 9'),
        ),
        ask('cm-ac-grid-avoid'),
        askAfter(
          'cm-ac-committee-tiles',
          2,
          prose('**At least one of each** rules out two kinds of team: all boys and all girls. A team of $3$ from $5$ boys and $4$ girls:'),
          maths('\\binom{9}{3} - \\binom{5}{3} - \\binom{4}{3} = 84 - 10 - 4 = 70'),
        ),
        ask('cm-ac-grid-avoid+choice', 2),
        ask('cm-ac-committee+choice', 2),
      ],
      skillCheck: [ask('cm-ac-contains-digit', 2), ask('cm-ac-grid-avoid', 2), ask('cm-ac-committee', 2)],
    },
    {
      id: 'cm-l21-binomial',
      title: 'Binomial Coefficients',
      slides: [
        teach(
          prose('Expanding $(x + 2)^{5}$ means picking one part from each of the $5$ brackets and multiplying. A term in $x^{3}$ picks $x$ from $3$ brackets and $2$ from the other $2$, and there are $\\binom{5}{3}$ ways to choose which brackets give the $x$:'),
          maths('\\binom{5}{3} \\times 2^{2} = 10 \\times 4 = 40'),
          prose('Stopping at $\\binom{5}{3} = 10$ is the trap: every one of those terms carries $2 \\times 2$ as well.'),
          prose('A minus sign travels with its number. In $(1 - 3x)^{4}$ the term in $x^{2}$ takes $-3x$ from two brackets:'),
          maths('\\binom{4}{2} \\times (-3)^{2} = 6 \\times 9 = 54'),
        ),
        ask('cm-ac-binom-coeff'),
        ask('cm-ac-expansion-table'),
        askAfter(
          'cm-ac-expansion-table',
          2,
          prose('An odd power of a negative number is negative, so with a minus sign the coefficients alternate in sign. For $(1 - 2x)^{4}$:'),
          maths('1,\\ -8,\\ 24,\\ -32,\\ 16'),
        ),
        askAfter(
          'cm-ac-binom-coeff+choice',
          2,
          prose('For the **constant term** of this expansion, take $\\frac{2}{x}$ from $r$ brackets and $x^{2}$ from the other $6 - r$:'),
          maths('\\left(x^{2} + \\frac{2}{x}\\right)^{6}'),
          prose('The power of $x$ in that term is'),
          maths('2(6 - r) - r = 12 - 3r'),
          prose('which is zero when $r = 4$. So the constant term is'),
          maths('\\binom{6}{4} \\times 2^{4} = 15 \\times 16 = 240'),
        ),
        teach(
          prose('$\\binom{n}{k}$ counts the groups of $k$ chosen from $n$ things, so a whole row of Pascal’s triangle counts every group of every size, and each thing is either in or out:'),
          maths('\\binom{5}{0} + \\binom{5}{1} + \\cdots + \\binom{5}{5} = 2^{5} = 32'),
          prose('Leaving out the $1$ at each end gives $32 - 2 = 30$. The even terms make exactly half the row, because $(1 - 1)^{5} = 0$ is the even terms minus the odd ones:'),
          maths('\\binom{5}{0} + \\binom{5}{2} + \\binom{5}{4} = 16'),
          prose('A **diagonal** adds up to the entry just below its last term, on the side away from the edge: the hockey stick. Each step is Pascal’s rule, two neighbours making the entry below them.'),
          maths('\\binom{2}{2} + \\binom{3}{2} + \\binom{4}{2} + \\binom{5}{2} = \\binom{6}{3}'),
          maths('1 + 3 + 6 + 10 = 20'),
        ),
        ask('cm-ac-row-sum'),
        ask('cm-ac-hockey-stick'),
        askAfter(
          'cm-ac-row-sum+choice',
          2,
          prose('$k\\binom{n}{k}$ counts the committees of $k$ with one member as chair. Count them the other way round: choose the chair first, then any group of the others to join. From $4$ people:'),
          maths('\\binom{4}{1} + 2\\binom{4}{2} + 3\\binom{4}{3} + 4\\binom{4}{4} = 4 \\times 2^{3} = 32'),
        ),
        askAfter(
          'cm-ac-hockey-stick+choice',
          2,
          prose('A diagonal that starts partway down: add from the edge as before, then take off the part that is missing, which is a hockey stick of its own.'),
          maths('\\binom{4}{2} + \\binom{5}{2} + \\binom{6}{2} = \\binom{7}{3} - \\binom{4}{3}'),
          maths('35 - 4 = 31'),
        ),
      ],
      skillCheck: [ask('cm-ac-binom-coeff', 2), ask('cm-ac-row-sum', 2), ask('cm-ac-hockey-stick', 2)],
    },
    {
      id: 'cm-l21-pie',
      title: 'Principle of Inclusion-Exclusion',
      slides: [
        teach(
          prose('**Inclusion–exclusion** with three sets: add the three, take off the three overlaps of two, then add back the overlap of all three, which was added three times and taken off three times.'),
          prose('From $1$ to $100$, divisible by $2$, $3$ or $5$:'),
          maths('50 + 33 + 20 = 103'),
          prose('Divisible by two of them means divisible by $6$, $10$ or $15$:'),
          maths('16 + 10 + 6 = 32'),
          prose('Divisible by all three means divisible by $30$, and there are $3$:'),
          maths('103 - 32 + 3 = 74'),
          prose('So $100 - 74 = 26$ are divisible by none of them.'),
        ),
        ask('cm-ac-pie-multiples'),
        ask('cm-ac-pie-table'),
        askAfter(
          'cm-ac-pie-table',
          2,
          prose('When the numbers share a factor, divisible by both means divisible by their **LCM**, not their product. Divisible by $4$ and $6$ means divisible by $12$, not $24$: up to $100$ that is $8$ numbers, not $4$.'),
        ),
        ask('cm-ac-pie-multiples+choice', 2),
        teach(
          prose('A **derangement** leaves nothing in its own place. $4$ letters go into their $4$ addressed envelopes at random, $4! = 24$ ways in all.'),
          prose('Fixing $k$ chosen letters in their own envelopes leaves $(4 - k)!$ ways for the rest, and there are $\\binom{4}{k}$ ways to choose them: $\\frac{4!}{k!}$ in all. Inclusion–exclusion takes these off and adds them back in turn:'),
          maths('24 - 24 + 12 - 4 + 1 = 9'),
          prose('Write $D_{n}$ for this count with $n$ things: $D_{2} = 1$, $D_{3} = 2$, $D_{4} = 9$, $D_{5} = 44$.'),
        ),
        ask('cm-ac-derangements'),
        askAfter(
          'cm-ac-onto',
          1,
          prose('Sharing **different** things so that nobody is left out is inclusion–exclusion too. $5$ different prizes to $3$ children, each at least one: $3^{5}$ ways with no rule. Take off the ways missing a given child, $3 \\times 2^{5}$, then add back the ways missing two, $3 \\times 1$:'),
          maths('243 - 96 + 3 = 150'),
        ),
        askAfter(
          'cm-ac-derangements+choice',
          2,
          prose('**Exactly** some right: choose which ones are right, then all the rest must be wrong. $5$ letters, exactly $2$ in the right envelopes:'),
          maths('\\binom{5}{2} \\times D_{3} = 10 \\times 2 = 20'),
        ),
        askAfter(
          'cm-ac-onto+choice',
          2,
          prose('With $4$ children the pattern runs one step further: take off, add back, take off. $5$ different prizes, each of $4$ children at least one:'),
          maths('4^{5} - 4 \\times 3^{5} + 6 \\times 2^{5} - 4 \\times 1^{5}'),
          maths('1024 - 972 + 192 - 4 = 240'),
        ),
      ],
      skillCheck: [ask('cm-ac-pie-multiples', 2), ask('cm-ac-derangements', 2), ask('cm-ac-onto', 2)],
    },
    {
      id: 'cm-l21-urns',
      title: 'Balls and Urns',
      slides: [
        teach(
          prose('Identical things shared between people are **balls in urns**. Hand out any minimums first, then share the rest freely as a row of balls and dividers.'),
          prose('$12$ identical sweets between Ann, Ben and Cal, with Ann getting at least $2$ and Ben at least $3$: hand out those $5$ first.'),
          maths('12 - 5 = 7'),
          prose('A row of the $7$ left and $2$ dividers has $9$ places, and choosing the $2$ places for the dividers settles the share:'),
          maths('\\binom{9}{2} = 36'),
          prose('Sharing all $12$ freely, $\\binom{14}{2} = 91$, is the trap.'),
        ),
        ask('cm-ac-urns-minimum'),
        ask('cm-ac-urns-tiles'),
        askAfter(
          'cm-ac-terms',
          1,
          prose('Counting the terms of $(a + b + c)^{4}$ is the same thing. Every term is $a^{i} b^{j} c^{l}$ with the powers adding up to $4$: a share of $4$ between three letters, where a letter may get none.'),
          maths('\\binom{6}{2} = 15'),
          prose('With four letters there are $3$ dividers, so $(a + b + c + d)^{4}$ has $\\binom{7}{3} = 35$ terms.'),
        ),
        askAfter(
          'cm-ac-urns-minimum+choice',
          2,
          prose('**Odd** parts: an odd positive number is one more than an even number, so write it as $2a + 1$ with $a$ from $0$ up. Odd positive solutions of'),
          maths('x + y + z = 11'),
          prose('become'),
          maths('2(a + b + c) + 3 = 11'),
          maths('a + b + c = 4'),
          maths('\\binom{6}{2} = 15'),
        ),
        teach(
          prose('An **upper limit** is taken off with inclusion–exclusion. Three dice, red, blue and green, totalling $10$: take $1$ off each, so each shows $0$ to $5$ and the three add up to $7$. With no limit:'),
          maths('\\binom{9}{2} = 36'),
          prose('A die over $5$ is at least $6$: give it $6$ first and share the $1$ left, for each of the $3$ dice:'),
          maths('3 \\times \\binom{3}{2} = 9'),
          maths('36 - 9 = 27'),
          prose('For a total of $16$ the three add up to $13$, and two dice can be over $5$ at once. Those were taken off twice, so add them back:'),
          maths('\\binom{15}{2} - 3\\binom{9}{2} + 3\\binom{3}{2} = 105 - 108 + 9 = 6'),
        ),
        ask('cm-ac-dice-cap'),
        askAfter(
          'cm-ac-urns-tiles',
          2,
          prose('Four people need $3$ dividers. $10$ sweets between four, with minimums $1$, $2$, $0$ and $2$: $5$ are handed out, and the $5$ left with $3$ dividers make $8$ places.'),
          maths('\\binom{8}{3} = 56'),
        ),
        askAfter(
          'cm-ac-terms+choice',
          2,
          prose('"At most" becomes "equal" with one more unknown, $w$, for what is left over. Each solution of'),
          maths('x + y + z \\le 5'),
          prose('in whole numbers from $0$ up is exactly one solution of'),
          maths('x + y + z + w = 5'),
          maths('\\binom{8}{3} = 56'),
          prose('The terms of $(1 + x + y + z)^{5}$ count the same way: the $1$ is a fourth letter.'),
        ),
        ask('cm-ac-dice-cap+choice', 2),
      ],
      skillCheck: [ask('cm-ac-urns-minimum', 2), ask('cm-ac-dice-cap', 2), ask('cm-ac-terms', 2)],
    },
  ],
  levelCheck: [
    ask('cm-ac-no-adjacent', 2),
    ask('cm-ac-increasing-digits+choice', 2),
    ask('cm-ac-diagonal-crossings', 2),
    ask('cm-ac-contains-digit', 2),
    ask('cm-ac-grid-avoid+choice', 2),
    ask('cm-ac-committee', 2),
    ask('cm-ac-binom-coeff', 2),
    ask('cm-ac-hockey-stick+choice', 2),
    ask('cm-ac-row-sum', 2),
    ask('cm-ac-pie-multiples', 2),
    ask('cm-ac-derangements+choice', 2),
    ask('cm-ac-onto', 2),
    ask('cm-ac-urns-minimum', 2),
    ask('cm-ac-dice-cap+choice', 2),
  ],
};
