/**
 * Contest Math, Level 3: Basic Statistics. Mean, median, mode and range,
 * turned by two ideas: a mean is a total in disguise, and the median is a
 * place in the sorted list. Generators in `generators/contestStatistics.ts`.
 */
import type { Level } from '../../types';
import { teach, ask, prose, maths, askAfter } from './blocks';

export const basicStatistics: Level = {
  id: 'cm-l3',
  title: 'Basic Statistics',
  lessons: [
    {
      id: 'cm-l3-measures',
      title: 'Data Measures',
      slides: [
        teach(
          prose('Four measures describe a data set. The **mean** shares the total out equally, the **median** is the middle value once the data is sorted, the **mode** is the value that appears most often, and the **range** is the largest take away the smallest.'),
          prose('Take $7, 3, 9, 3, 8$. Sorted, it reads'),
          maths('3,\\ 3,\\ 7,\\ 8,\\ 9'),
          prose('The total is $30$ and there are $5$ values:'),
          maths('\\text{mean} = 30 \\div 5 = 6'),
          prose('The median is the 3rd value, $7$, and the mode is $3$. The range is'),
          maths('9 - 3 = 6'),
          prose('With an even count there is no single middle, so the median is halfway between the middle two. For $2, 4, 5, 9$ it is'),
          maths('(4 + 5) \\div 2 = 4.5'),
        ),
        ask('cm-stat-measures'),
        askAfter(
          'cm-freq-median',
          1,
          prose('A frequency table lists each value once, but the median counts every match. $15$ matches are split $4, 6, 3, 2$ among $0, 1, 2$ and $3$ goals, so the median is the 8th match in order:'),
          maths('0\\text{s: places } 1 \\text{ to } 4'),
          maths('1\\text{s: places } 5 \\text{ to } 10'),
          prose('The 8th is a $1$, so the median is $1$ goal, not the middle column of the table.'),
        ),
        askAfter(
          'cm-freq-median+choice',
          2,
          prose('With an even number of matches, find the two middle places. For $20$ matches they are the 10th and 11th; if those are $2$ and $3$ goals, the median is'),
          maths('(2 + 3) \\div 2 = 2.5'),
        ),
        teach(
          prose('A mean hides a total: the total is the mean times the count. Most mean questions are one subtraction of totals.'),
          prose('Four tests average $80$, and the first three are $72$, $85$ and $90$. All four add to'),
          maths('4 \\times 80 = 320'),
          prose('so the last is'),
          maths('320 - 72 - 85 - 90 = 73'),
          prose('Numbers in a row are evenly spread, so their mean is the middle one. Five consecutive whole numbers add up to $115$:'),
          maths('115 \\div 5 = 23'),
          prose('So they are $21$ to $25$, and the largest is $25$.'),
        ),
        ask('cm-missing-score'),
        ask('cm-consecutive-mean'),
        askAfter(
          'cm-missing-score+choice',
          2,
          prose('Dropping a score works the same way. Five scores average $70$, and without the lowest the other four average $75$:'),
          maths('5 \\times 70 = 350'),
          maths('4 \\times 75 = 300'),
          prose('So the lowest was $50$.'),
        ),
        askAfter(
          'cm-consecutive-mean+choice',
          2,
          prose('Consecutive even or odd numbers step by $2$. Six consecutive odd numbers add up to $72$, so their mean is $12$, halfway between the middle two, $11$ and $13$. The largest is two steps of $2$ above $13$:'),
          maths('13 + 2 \\times 2 = 17'),
        ),
        ask('cm-stat-measures', 2),
      ],
      skillCheck: [ask('cm-stat-measures', 2), ask('cm-missing-score', 2), ask('cm-consecutive-mean+choice', 2)],
    },
    {
      id: 'cm-l3-changing',
      title: 'Changing Data Sets',
      slides: [
        teach(
          prose('When a number joins a set, compare totals. Six numbers have mean $15$, and one more number lifts the mean to $17$:'),
          maths('\\text{before: } 6 \\times 15 = 90'),
          maths('\\text{after: } 7 \\times 17 = 119'),
          prose('The new number is the difference, $29$.'),
          prose('Quicker: the new number sits at the new mean, $17$, and brings $2$ more for each of the $6$ already there:'),
          maths('17 + 6 \\times 2 = 29'),
        ),
        ask('cm-new-mean'),
        askAfter(
          'cm-count-from-shift',
          1,
          prose('Run it backwards to find the count. A mean of $80$ rises to $82$ when a score of $92$ is added. With $n$ scores before:'),
          maths('80n + 92 = 82(n + 1)'),
          maths('80n + 92 = 82n + 82'),
          maths('10 = 2n'),
          prose('So there were $5$ scores before.'),
        ),
        askAfter(
          'cm-new-mean+choice',
          2,
          prose('When a number leaves, the same subtraction runs the other way. Five people have a mean age of $30$; one leaves, and the mean of the rest is $28$:'),
          maths('5 \\times 30 = 150'),
          maths('4 \\times 28 = 112'),
          prose('So the person who left is $38$.'),
        ),
        teach(
          prose('Means of two groups do not average: add the **totals**. A class of $10$ averages $60$ and a class of $30$ averages $80$:'),
          maths('10 \\times 60 + 30 \\times 80 = 3000'),
          maths('3000 \\div 40 = 75'),
          prose('The larger class pulls the mean towards its own, so the answer is not $70$.'),
        ),
        ask('cm-combined-mean-tiles'),
        ask('cm-combined-mean+choice'),
        askAfter(
          'cm-change-table',
          1,
          prose('A change to the data moves each measure its own way. Adding $k$ to every number moves the mean and the median up $k$ and leaves the range alone.'),
          prose('Raising only the largest by $k$ leaves the median, adds $k$ to the range, and adds $k$ shared among the count to the mean. For $2, 5, 6, 9, 13$, with mean $7$ and range $11$, raise the $13$ by $5$:'),
          maths('\\text{mean: } 7 + 5 \\div 5 = 8'),
          maths('\\text{range: } 11 + 5 = 16'),
        ),
        askAfter(
          'cm-combined-mean',
          2,
          prose('Going backwards, measure from the combined mean: the gaps above and below it cancel. Boys average $70$, girls $80$, the whole class $76$, and there are $12$ girls. Each boy is $6$ below and each girl $4$ above:'),
          maths('6 \\times \\text{boys} = 4 \\times 12'),
          prose('So there are $8$ boys.'),
        ),
        askAfter(
          'cm-change-table',
          2,
          prose('Multiplying every number by $k$ multiplies the mean, the median and the range by $k$.'),
          prose('Lowering only the smallest by $k$ mirrors raising the largest: the median stays, the range grows by $k$, and the mean falls by $k$ shared among the count. For $12, 15, 16, 19, 23$, with mean $17$ and range $11$, lower the $12$ by $10$:'),
          maths('\\text{mean: } 17 - 10 \\div 5 = 15'),
          maths('\\text{range: } 11 + 10 = 21'),
        ),
        ask('cm-count-from-shift+choice', 2),
      ],
      skillCheck: [ask('cm-new-mean', 2), ask('cm-combined-mean', 2), ask('cm-change-table', 2)],
    },
    {
      id: 'cm-l3-determine',
      title: 'Determine the Set',
      slides: [
        teach(
          prose('A few measures can pin a set down completely. Five whole numbers have mean $7$, median $8$ and range $6$. Their mode is $9$, and no other number repeats.'),
          prose('Write them in order, the median in the middle. The mode appears at least twice and is above the median, so it fills both top places:'),
          maths('\\square,\\ \\square,\\ 8,\\ 9,\\ 9'),
          prose('The range fixes the smallest:'),
          maths('9 - 6 = 3'),
          prose('The five add to 5 times the mean, and the second is what is left:'),
          maths('5 \\times 7 = 35'),
          maths('35 - 3 - 8 - 9 - 9 = 6'),
          prose('The set is $3, 6, 8, 9, 9$.'),
        ),
        ask('cm-set-from-measures'),
        ask('cm-set-tiles'),
        askAfter(
          'cm-three-numbers',
          1,
          prose('Three numbers need only three facts. With mean $10$, median $9$ and range $13$, the other two add to'),
          maths('3 \\times 10 - 9 = 21'),
          prose('and are $13$ apart, so the largest and smallest are'),
          maths('(21 + 13) \\div 2 = 17'),
          maths('(21 - 13) \\div 2 = 4'),
        ),
        askAfter(
          'cm-set-from-measures+choice',
          2,
          prose('If the mode is **below** the median, it fills both bottom places, and the range fixes the largest. Mean $10$, median $9$, range $16$, mode $4$:'),
          maths('4,\\ 4,\\ 9,\\ \\square,\\ \\square'),
          maths('4 + 16 = 20'),
          maths('5 \\times 10 - 4 - 4 - 9 - 20 = 13'),
        ),
        teach(
          prose('With four numbers the median is halfway between the middle two. Four whole numbers have mean $9$ and median $7$; the mode is $5$, and nothing else repeats.'),
          prose('The mode is below the median, so it takes both bottom places. Then the median gives the third number:'),
          maths('5,\\ 5,\\ \\square,\\ \\square'),
          maths('2 \\times 7 - 5 = 9'),
          prose('The four add to 4 times the mean, and the largest is what is left:'),
          maths('4 \\times 9 = 36'),
          maths('36 - 5 - 5 - 9 = 17'),
          prose('The set is $5, 5, 9, 17$.'),
        ),
        ask('cm-four-set'),
        ask('cm-three-numbers+choice', 2),
        askAfter(
          'cm-four-set+choice',
          2,
          prose('When the mode is above the median, it takes the two top places and the median gives the second number. Mean $10$, median $11$, mode $14$:'),
          maths('\\square,\\ \\square,\\ 14,\\ 14'),
          maths('2 \\times 11 - 14 = 8'),
          maths('40 - 14 - 14 - 8 = 4'),
        ),
        ask('cm-set-tiles', 2),
      ],
      skillCheck: [ask('cm-set-from-measures', 2), ask('cm-three-numbers', 2), ask('cm-four-set', 2)],
    },
    {
      id: 'cm-l3-possibilities',
      title: 'Multiple Possibilities',
      slides: [
        teach(
          prose('When one number is unknown, the median can move with it. The numbers $2, 6, 9, 11$ and $x$ have a mean equal to their median. They add to $28 + x$, and where $x$ lands decides the median.'),
          prose('If $x$ is $6$ or less, the median is $6$:'),
          maths('28 + x = 5 \\times 6'),
          maths('x = 2'),
          prose('If $x$ is between $6$ and $9$, the median is $x$ itself:'),
          maths('28 + x = 5x'),
          maths('x = 7'),
          prose('If $x$ is $9$ or more, the median is $9$:'),
          maths('28 + x = 5 \\times 9'),
          maths('x = 17'),
          prose('Each answer sits inside its own case, so all three work, and they add to $26$.'),
        ),
        ask('cm-mean-median-cases'),
        ask('cm-mean-median-x'),
        askAfter(
          'cm-count-sets',
          1,
          prose('Counting the possibilities: three positive whole numbers $a \\le b \\le c$ have mean $6$ and median $5$. Then $b$ is $5$ and'),
          maths('a + c = 18 - 5 = 13'),
          prose('$a$ is at most $5$, and $c$ must be at least $5$, so $a$ is at most $8$. So $a$ runs from $1$ to $5$: five lists.'),
        ),
        ask('cm-mean-median-x+choice', 2),
        teach(
          prose('To make one number as large as possible, make every other number as small as the facts allow. Five positive whole numbers have mean $10$ and median $8$, so they add to $50$.'),
          prose('The two below the median can both be $1$, and the one above it can be no less than $8$:'),
          maths('1,\\ 1,\\ 8,\\ 8,\\ \\square'),
          maths('50 - 1 - 1 - 8 - 8 = 32'),
          prose('If the five must be **different**, the smallest choices are $1$ and $2$ below the median and $9$ above it:'),
          maths('50 - 1 - 2 - 8 - 9 = 30'),
        ),
        ask('cm-extreme-value'),
        askAfter(
          'cm-count-sets+choice',
          2,
          prose('If the numbers must be different, $a < b < c$, then $a$ is below $b$ and $c$ above it. With mean $6$ and median $5$, $a$ is at most $4$, and $c$ must be at least $6$, so $a$ is at most $7$. So $a$ runs from $1$ to $4$: four lists.'),
        ),
        ask('cm-extreme-value+choice', 2),
        ask('cm-mean-median-cases', 2),
      ],
      skillCheck: [ask('cm-mean-median-x', 2), ask('cm-count-sets', 2), ask('cm-extreme-value', 2)],
    },
  ],
  levelCheck: [
    ask('cm-stat-measures', 2),
    ask('cm-freq-median', 2),
    ask('cm-missing-score', 2),
    ask('cm-consecutive-mean+choice', 2),
    ask('cm-new-mean', 2),
    ask('cm-combined-mean', 2),
    ask('cm-change-table', 2),
    ask('cm-count-from-shift', 2),
    ask('cm-set-from-measures', 2),
    ask('cm-four-set', 2),
    ask('cm-three-numbers+choice', 2),
    ask('cm-mean-median-x', 2),
    ask('cm-count-sets', 2),
    ask('cm-extreme-value+choice', 2),
  ],
};
