/**
 * Contest Math, Level 1: Mathematical Problem-Solving. Samples the four
 * strands a contest draws on (algebra, geometry, counting and number theory)
 * and closes with a lesson of tricks that need a new idea rather than more
 * working. Generators in `generators/contestProblemSolving.ts`.
 */
import type { Level } from '../../types';
import { teach, ask, prose, maths, askAfter } from './blocks';

export const problemSolving: Level = {
  id: 'cm-l1',
  title: 'Mathematical Problem-Solving',
  lessons: [
    {
      id: 'cm-l1-algebra',
      title: 'Algebra',
      slides: [
        teach(
          prose('Contest questions look long and turn on one idea. Find what stays the same, and the working is short.'),
          prose('A full jar of jam weighs $500$ g. With half the jam gone it weighs $300$ g. The jar is in both weighings, so the difference is the jam that went:'),
          maths('500 - 300 = 200'),
          prose('That was half the jam, so all of it weighs $400$ g, and the jar weighs'),
          maths('500 - 400 = 100'),
        ),
        ask('cm-jar'),
        askAfter(
          'cm-work-rate',
          1,
          prose('Rates: count the work in worker-hours. If $3$ cooks make $6$ pies in $4$ hours, that is $12$ cook-hours for $6$ pies, so $2$ cook-hours a pie.'),
          prose('$10$ pies then take $20$ cook-hours: $5$ cooks need $4$ hours.'),
        ),
        askAfter('cm-jar+choice', 2, prose('With a third left, the part that went is two thirds of the whole: halve it, then treble it.')),
        teach(
          prose('When every unknown appears the same number of times, add all the equations at once.'),
          maths('\\begin{aligned} a + b &= 7 \\\\ a + c &= 9 \\\\ b + c &= 12 \\end{aligned}'),
          prose('Each letter appears twice:'),
          maths('2(a + b + c) = 28'),
          maths('a + b + c = 14'),
          prose('Then $c$ is the total without $a + b$: $14 - 7 = 7$.'),
        ),
        ask('cm-pair-sums'),
        ask('cm-pair-sums-tiles'),
        askAfter(
          'cm-close-fractions',
          1,
          prose('Fractions just under $1$: compare what each is short of $1$.'),
          maths('\\frac{99}{100} = 1 - \\frac{1}{100}'),
          maths('\\frac{199}{201} = 1 - \\frac{2}{201}'),
          prose('Turn the pieces over: $100$ against $100.5$. The bigger number means the smaller piece, so $\\frac{199}{201}$ is larger.'),
        ),
        ask('cm-work-rate+choice', 2),
        ask('cm-pair-sums', 2),
        ask('cm-close-fractions', 2),
      ],
      skillCheck: [ask('cm-jar', 2), ask('cm-pair-sums+choice', 2), ask('cm-work-rate', 2)],
    },
    {
      id: 'cm-l1-geometry',
      title: 'Geometry',
      slides: [
        teach(
          prose('Walk once round any polygon and you turn through a full circle, so its **exterior angles add to** $360^\\circ$.'),
          prose('Each interior angle of a regular polygon is $150^\\circ$. Each exterior angle is'),
          maths('180 - 150 = 30'),
          prose('and there are'),
          maths('360 \\div 30 = 12'),
          prose('sides.'),
        ),
        ask('cm-polygon-sides'),
        askAfter(
          'cm-angle-ratio',
          1,
          prose('Angles in a ratio: count the parts. A triangle in the ratio $2 : 3 : 4$ has $9$ parts sharing $180^\\circ$, so one part is $20^\\circ$ and the largest angle is $4 \\times 20 = 80^\\circ$.'),
        ),
        askAfter('cm-angle-ratio-tiles', 1, prose('A quadrilateral’s angles add to $360^\\circ$ instead, and the parts are counted the same way.')),
        askAfter(
          'cm-clock-angle',
          1,
          prose('Clock hands: the minute hand turns $6^\\circ$ a minute. The hour hand turns $30^\\circ$ an hour and keeps creeping, $\\tfrac{1}{2}^\\circ$ a minute.'),
          prose('At 3:30 the minute hand is at $180^\\circ$ and the hour hand at $90 + 15 = 105^\\circ$, so they are $75^\\circ$ apart.'),
        ),
        teach(
          prose('Slide the pieces of a shape about when that keeps what you are measuring.'),
          prose('Every step of a right-angled staircase slides out to the edge of its bounding rectangle, so the perimeter of a staircase $8$ wide and $5$ tall is'),
          maths('2 \\times (8 + 5) = 26'),
          prose('A rectangular notch cut into one edge slides back the same way, but its two sides are extra.'),
          prose('A square tilted inside a square, its corners cutting each side into $3$ and $4$, leaves four right triangles. The big square is $7^2 = 49$ and the triangles are $4 \\times 6 = 24$, so the tilted square is'),
          maths('49 - 24 = 25 = 3^2 + 4^2'),
        ),
        ask('cm-staircase-perimeter'),
        ask('cm-tilted-square'),
        askAfter('cm-polygon-sides+choice', 2, prose('When an interior angle is $k$ exterior angles, the two together are $k + 1$ exterior angles on a straight line, so that many exterior angles make $180^\\circ$ between them.')),
        ask('cm-clock-angle+choice', 2),
        askAfter('cm-tilted-square+choice', 2, prose('Given the big side and one piece, the other piece is what is left of the side.')),
      ],
      skillCheck: [ask('cm-staircase-perimeter', 2), ask('cm-angle-ratio+choice', 2), ask('cm-clock-angle', 2)],
    },
    {
      id: 'cm-l1-combinatorics',
      title: 'Combinatorics',
      slides: [
        teach(
          prose('Counting is about not counting anything twice, and not missing anything.'),
          prose('$6$ people each shake hands with everyone else once. Each shakes $5$ hands, but that counts every handshake from both sides:'),
          maths('6 \\times 5 \\div 2 = 15'),
          prose('A straight fence $20$ m long with a post every $5$ m has $4$ gaps, and one more post than gaps: $5$ posts.'),
        ),
        ask('cm-handshakes'),
        ask('cm-fence-posts'),
        askAfter(
          'cm-outfits',
          1,
          prose('Choices made one after another multiply: $3$ shirts and $2$ pairs of trousers give $3 \\times 2 = 6$ outfits, since each shirt goes with each pair.'),
        ),
        askAfter('cm-handshakes+choice', 2, prose('Going backwards, $n(n - 1)$ is twice the count, so look for two numbers one apart with that product.')),
        teach(
          prose('To count the multiples of $7$ from $30$ to $100$, count up to $100$ and take away those below $30$:'),
          maths('100 \\div 7 \\to 14, \\quad 29 \\div 7 \\to 4'),
          maths('14 - 4 = 10'),
          prose('To count the digits in page numbers $1$ to $150$, split by length:'),
          maths('9 \\times 1 + 90 \\times 2 + 51 \\times 3 = 342'),
        ),
        ask('cm-count-multiples'),
        ask('cm-page-digits-table'),
        askAfter(
          'cm-fence-posts+choice',
          2,
          prose('Round a closed loop the last gap ends at the first post, so posts equal gaps. Sawing a log into $n$ pieces takes $n - 1$ cuts.'),
        ),
        ask('cm-count-multiples+choice', 2),
        ask('cm-page-digits', 2),
      ],
      skillCheck: [ask('cm-outfits', 2), ask('cm-count-multiples', 2), ask('cm-fence-posts', 2)],
    },
    {
      id: 'cm-l1-number-theory',
      title: 'Number Theory',
      slides: [
        teach(
          prose('Swapping $+n$ for $-n$ changes a total by $2n$, which is even. So the signs never change whether the result is odd or even:'),
          maths('\\pm 1 \\pm 2 \\pm 3 \\text{ has the parity of } 1 + 2 + 3 = 6'),
          prose('Last digits of powers repeat. Powers of $7$ end in $7, 9, 3, 1$ and then start again, so $7^{10}$, with $10 = 4 \\times 2 + 2$, ends in the second, $9$.'),
        ),
        ask('cm-parity-signs'),
        ask('cm-last-digit'),
        askAfter(
          'cm-missing-digit',
          1,
          prose('A number is a multiple of $9$ when its digits add to a multiple of $9$. In $4\\square 71$ the others add to $12$, so the box holds $6$ to make $18$.'),
        ),
        ask('cm-parity-signs', 2),
        teach(
          prose('A highest common factor comes from prime factors. $1 + 2 + \\cdots + 10$ pairs up from the ends into $5$ pairs of $11$:'),
          maths('5 \\times 11 = 55'),
          prose('$1 \\times 2 \\times \\cdots \\times 10$ holds the $5$ but not the $11$, which is prime and bigger than $10$, so their HCF is $5$.'),
          prose('Sorting $1$ to $30$ by multiples of $2$ and of $3$: $15$ and $10$ of them, with the $5$ multiples of $6$ in both.'),
        ),
        ask('cm-gcd-sum-factorial'),
        ask('cm-venn-multiples'),
        ask('cm-last-digit+choice', 2),
        askAfter(
          'cm-missing-digit',
          2,
          prose('For $11$, give the digits signs $+, -, +, \\ldots$ from the left. $2728$ gives $2 - 7 + 2 - 8 = -11$, a multiple of $11$, so $2728$ is one.'),
        ),
        ask('cm-venn-multiples', 2),
      ],
      skillCheck: [ask('cm-last-digit', 2), ask('cm-gcd-sum-factorial+choice', 2), ask('cm-missing-digit+choice', 2)],
    },
    {
      id: 'cm-l1-creativity',
      title: 'Math Requires Creativity',
      slides: [
        teach(
          prose('Some sums are long only until you regroup them. Pair the terms of an alternating sum:'),
          maths('1 - 2 + 3 - 4 + \\cdots - 10'),
          maths('(1 - 2) + (3 - 4) + \\cdots + (9 - 10)'),
          prose('That is five pairs of $-1$, so $-5$.'),
        ),
        ask('cm-alternating-sum'),
        askAfter(
          'cm-diff-squares',
          1,
          prose('A difference of two squares factorises:'),
          maths('A^2 - B^2 = (A + B)(A - B)'),
          maths('103^2 - 97^2 = 200 \\times 6'),
          maths('= 1200'),
        ),
        askAfter(
          'cm-diff-squares-tiles',
          1,
          prose('Read it backwards. $48$ and $52$ sit $2$ either side of $50$:'),
          maths('48 \\times 52 = 50^2 - 2^2'),
          maths('= 2500 - 4 = 2496'),
        ),
        askAfter('cm-alternating-sum+choice', 2, prose('Counting down, or over odd numbers, the pairs work the same way. Check what each pair is worth, and whether one term is left over.')),
        teach(
          prose('Products can cancel down a whole row at once:'),
          maths('\\left(1 + \\tfrac{1}{2}\\right)\\left(1 + \\tfrac{1}{3}\\right)\\left(1 + \\tfrac{1}{4}\\right)'),
          maths('\\frac{3}{2} \\times \\frac{4}{3} \\times \\frac{5}{4} = \\frac{5}{2}'),
          prose('And when only differences matter, slide every number by the same amount to make one of them $0$. If the mean of $a$ and $b$ is $c$, taking $a = 0$ gives $c = \\tfrac{1}{2} b$.'),
        ),
        ask('cm-telescoping-product'),
        ask('cm-average-chain'),
        ask('cm-diff-squares+choice', 2),
        askAfter(
          'cm-telescoping-product+choice',
          2,
          prose('With minus signs each bottom cancels the next top instead. And $1 - \\tfrac{1}{k^2} = \\tfrac{k - 1}{k} \\times \\tfrac{k + 1}{k}$ splits a row of squares into two rows that each cancel.'),
        ),
        ask('cm-average-chain', 2),
      ],
      skillCheck: [ask('cm-average-chain+choice', 2), ask('cm-diff-squares', 2), ask('cm-telescoping-product', 2)],
    },
  ],
  levelCheck: [
    ask('cm-jar', 2),
    ask('cm-pair-sums', 2),
    ask('cm-close-fractions', 2),
    ask('cm-polygon-sides', 2),
    ask('cm-tilted-square', 2),
    ask('cm-clock-angle+choice', 2),
    ask('cm-handshakes', 2),
    ask('cm-page-digits', 2),
    ask('cm-missing-digit', 2),
    ask('cm-gcd-sum-factorial', 2),
    ask('cm-average-chain', 2),
    ask('cm-alternating-sum', 2),
  ],
};
