/**
 * Contest Math, Level 13: Inequalities. Turning the sign round, a square
 * that is never negative, AM-GM for a fixed product or a fixed sum, and
 * Cauchy-Schwarz on a circle, on a line and in its fractions form.
 * Generators in `generators/contestInequalities.ts`.
 */
import type { Level } from '../../types';
import { teach, ask, prose, maths, askAfter } from './blocks';

export const inequalities: Level = {
  id: 'cm-l13',
  title: 'Inequalities',
  lessons: [
    {
      id: 'cm-l13-basic',
      title: 'Basic Inequalities',
      slides: [
        teach(
          prose('Solve an inequality like an equation, with one exception: multiplying or dividing both sides by a negative number turns the sign round. $3$ is bigger than $2$, but $-3$ is smaller than $-2$.'),
          prose('Solve'),
          maths('7 - 2x \\le x + 1'),
          prose('Take $x$ and $7$ from both sides:'),
          maths('-3x \\le -6'),
          prose('Divide by $-3$, turning the sign round:'),
          maths('x \\ge 2'),
          prose('On a number line the dot at $2$ is filled, since $2$ is included, and the shading runs right. Leaving the sign alone gives the trap, $x \\le 2$.'),
        ),
        ask('cm-in-flip'),
        askAfter(
          'cm-in-count-integers',
          1,
          prose('To count the integers in a range, solve for $x$ first, then count from the first whole number inside to the last. How many integers satisfy this?'),
          maths('5 < 3x - 1 < 30'),
          prose('Add $1$ all along, then divide by $3$:'),
          maths('6 < 3x < 31'),
          maths('2 < x < \\tfrac{31}{3}'),
          prose('So $x$ runs from $3$ to $10$:'),
          maths('10 - 3 + 1 = 8'),
        ),
        askAfter(
          'cm-in-count-integers+choice',
          2,
          prose('A square has two roots. How many integers $n$ satisfy this?'),
          maths('10 < n^2 < 50'),
          prose('The squares in range are $16$, $25$, $36$ and $49$, from $n = 4$ to $7$. But $n = -4$ to $-7$ work too:'),
          maths('2 \\times 4 = 8'),
          prose('Counting only the positive ones, $4$, is the trap.'),
        ),
        teach(
          prose('A square is never negative, so completing the square finds a least value. For $x^2 - 6x + 11$, the square $(x - 3)^2$ brings in an extra $9$, so take it off:'),
          maths('x^2 - 6x + 11 = (x - 3)^2 + 2'),
          prose('The square is $0$ at $x = 3$ and never less, so the least value is $2$. The constant $11$ is the trap: it is only the value at $x = 0$.'),
          prose('A range from two ranges: with $1 \\le x \\le 5$ and $2 \\le y \\le 3$, $x - y$ is least when $x$ is least and $y$ greatest:'),
          maths('1 - 3 = -2'),
          prose('and greatest the other way round:'),
          maths('5 - 2 = 3'),
        ),
        ask('cm-in-bounds'),
        ask('cm-in-square-min'),
        askAfter(
          'cm-in-square-min+choice',
          2,
          prose('With two letters, complete a square in each. For $x^2 + y^2 - 4x + 6y + 20$, the squares bring in $4$ and $9$:'),
          maths('(x - 2)^2 + (y + 3)^2 + 20 - 4 - 9'),
          maths('(x - 2)^2 + (y + 3)^2 + 7'),
          prose('Both squares can be $0$ at once, at $x = 2$ and $y = -3$, so the least value is $7$.'),
        ),
        askAfter(
          'cm-in-flip',
          2,
          prose('Three parts at once: whatever you do, do it to all three. Solve'),
          maths('-4 < 2 - 3x \\le 11'),
          prose('Take $2$ from each part:'),
          maths('-6 < -3x \\le 9'),
          prose('Divide by $-3$, turning both signs round, then read from the smaller end:'),
          maths('2 > x \\ge -3'),
          maths('-3 \\le x < 2'),
        ),
        askAfter(
          'cm-in-bounds',
          2,
          prose('For a product, negatives can swap which ends matter, so try all four corners. With $-3 \\le x \\le 2$ and $-1 \\le y \\le 4$:'),
          maths('(-3) \\times (-1) = 3, \\qquad (-3) \\times 4 = -12'),
          maths('2 \\times (-1) = -2, \\qquad 2 \\times 4 = 8'),
          maths('-12 \\le xy \\le 8'),
          prose('Multiplying low end by low end and high by high, $3$ and $8$, is the trap.'),
        ),
      ],
      skillCheck: [ask('cm-in-count-integers', 2), ask('cm-in-square-min', 2), ask('cm-in-flip', 2)],
    },
    {
      id: 'cm-l13-amgm',
      title: 'AM-GM',
      slides: [
        teach(
          prose('For positive $a$ and $b$, the arithmetic mean is at least the geometric mean:'),
          maths('\\frac{a + b}{2} \\ge \\sqrt{ab}'),
          prose('It holds because a square is never negative:'),
          maths('(\\sqrt{a} - \\sqrt{b})^2 \\ge 0'),
          maths('a + b \\ge 2\\sqrt{ab}'),
          prose('with equality only when $a = b$. So when two positive parts have a fixed **product**, their sum is least when they are equal. For $2x + \\frac{18}{x}$ with $x > 0$, the parts always multiply to $36$:'),
          maths('2x + \\frac{18}{x} \\ge 2\\sqrt{36} = 12'),
          prose('Equality needs the parts equal:'),
          maths('2x = \\frac{18}{x}'),
          prose('which is at $x = 3$. Trying $x = 1$ gives $20$, which is not the least.'),
        ),
        ask('cm-in-amgm-min'),
        askAfter(
          'cm-in-product-table',
          1,
          prose('The same idea with whole numbers. The pairs that multiply to $36$:'),
          maths('1 + 36 = 37, \\qquad 2 + 18 = 20'),
          maths('3 + 12 = 15, \\qquad 4 + 9 = 13, \\qquad 6 + 6 = 12'),
          prose('The closer the pair, the smaller the sum.'),
        ),
        askAfter(
          'cm-in-pen-tiles',
          1,
          prose('A rectangle of area $49$ has sides $x$ and $\\frac{49}{x}$, and its perimeter is twice their sum. The sum is least when the sides are equal:'),
          maths('x + \\frac{49}{x} \\ge 2\\sqrt{49} = 14'),
          prose('So the best rectangle is a square of side $7$, with perimeter $28$.'),
        ),
        askAfter(
          'cm-in-amgm-min+choice',
          2,
          prose('Sometimes the fixed product is hidden. Split the fraction first:'),
          maths('\\frac{(x + 2)(x + 8)}{x} = x + \\frac{16}{x} + 10'),
          maths('x + \\frac{16}{x} \\ge 2\\sqrt{16} = 8'),
          prose('with equality at $x = 4$. Add the $10$ back:'),
          maths('8 + 10 = 18'),
          prose('Forgetting the $10$ gives $8$, the trap.'),
        ),
        teach(
          prose('Turn it round: when two positive parts have a fixed **sum**, their product is greatest when they are equal.'),
          maths('xy \\le \\left(\\frac{x + y}{2}\\right)^2'),
          prose('A rectangle with perimeter $40$ has a length and a width adding to $20$, so its area is at most'),
          maths('10^2 = 100'),
          prose('Against a wall, $40$ m of fence makes three sides: two of length $x$ meeting the wall and one of length $y$ facing it.'),
          maths('2x + y = 40'),
          prose('The parts $2x$ and $y$ have a fixed sum, so'),
          maths('2x \\times y \\le 20^2 = 400'),
          maths('xy \\le 200'),
          prose('at $x = 10$ and $y = 20$. Treating the $40$ m as a full perimeter, a $10$ by $10$ square of area $100$, is the trap.'),
        ),
        ask('cm-in-fixed-sum'),
        ask('cm-in-fixed-sum+choice', 2),
        askAfter(
          'cm-in-pen-tiles',
          2,
          prose('A pen of fixed area against a wall: with area $50$ and the sides meeting the wall $x$, the fence is $2x + \\frac{50}{x}$. The parts multiply to $100$:'),
          maths('2x + \\frac{50}{x} \\ge 2\\sqrt{100} = 20'),
          prose('Equality when the parts are equal:'),
          maths('2x = \\frac{50}{x}'),
          maths('x = 5'),
        ),
        ask('cm-in-product-table', 2),
      ],
      skillCheck: [ask('cm-in-amgm-min', 2), ask('cm-in-fixed-sum', 2), ask('cm-in-pen-tiles', 2)],
    },
    {
      id: 'cm-l13-cauchy-schwarz',
      title: 'Cauchy-Schwarz',
      slides: [
        teach(
          prose('**Cauchy-Schwarz** for two pairs of real numbers:'),
          maths('(ax + by)^2 \\le (a^2 + b^2)(x^2 + y^2)'),
          prose('with equality when $x : y$ is $a : b$. It caps a straight-line expression on a circle. With $x^2 + y^2 = 25$:'),
          maths('(3x + 4y)^2 \\le (9 + 16) \\times 25 = 625'),
          maths('3x + 4y \\le 25'),
          prose('reached at $x = 3$, $y = 4$. Putting $x = y = 5$ to get $35$ is the trap: that point is not on the circle.'),
        ),
        ask('cm-in-cs-max'),
        askAfter(
          'cm-in-cs-table',
          1,
          prose('To find where the greatest is, write $x = 3\\lambda$ and $y = 4\\lambda$, in step with the coefficients. On the circle $x^2 + y^2 = 100$:'),
          maths('25\\lambda^2 = 100'),
          maths('\\lambda = 2'),
          prose('so $x = 6$ and $y = 8$, and the greatest value of $3x + 4y$ is'),
          maths('18 + 32 = 50'),
        ),
        askAfter(
          'cm-in-cs-max+choice',
          2,
          prose('Three variables work the same way, with three squares in each bracket. With $x^2 + y^2 + z^2 = 4$:'),
          maths('(x + 2y + 2z)^2 \\le (1 + 4 + 4) \\times 4 = 36'),
          maths('x + 2y + 2z \\le 6'),
        ),
        askAfter(
          'cm-in-cs-min',
          1,
          prose('Turned round, it gives the least sum of squares on a line. With $2x + y = 10$:'),
          maths('10^2 \\le (2^2 + 1^2)(x^2 + y^2)'),
          maths('x^2 + y^2 \\ge \\tfrac{100}{5} = 20'),
          prose('Setting $x = y$ gives $\\frac{200}{9}$, which is more, so that is the trap.'),
        ),
        teach(
          prose('Cauchy-Schwarz has a fractions form. For positive $x$ and $y$:'),
          maths('\\frac{a^2}{x} + \\frac{b^2}{y} \\ge \\frac{(a + b)^2}{x + y}'),
          prose('with equality when $x : y$ is $a : b$. It is the way in when the bottoms have a fixed sum. With $x + y = 5$:'),
          maths('\\frac{4}{x} + \\frac{9}{y} = \\frac{2^2}{x} + \\frac{3^2}{y}'),
          maths('\\frac{2^2}{x} + \\frac{3^2}{y} \\ge \\frac{(2 + 3)^2}{5} = 5'),
          prose('at $x = 2$, $y = 3$. Splitting evenly, $x = y = 2.5$, gives $5.2$: the trap.'),
        ),
        ask('cm-in-titu'),
        askAfter(
          'cm-in-cs-min+choice',
          2,
          prose('Three variables: with $x + 2y + 3z = 14$,'),
          maths('14^2 \\le (1 + 4 + 9)(x^2 + y^2 + z^2)'),
          maths('x^2 + y^2 + z^2 \\ge \\tfrac{196}{14} = 14'),
        ),
        askAfter(
          'cm-in-titu+choice',
          2,
          prose('Three fractions work the same way. With $x + y + z = 6$:'),
          maths('\\frac{1}{x} + \\frac{4}{y} + \\frac{9}{z} \\ge \\frac{(1 + 2 + 3)^2}{6} = 6'),
        ),
        askAfter(
          'cm-in-cs-table',
          2,
          prose('In three variables, write each as $\\lambda$ times its coefficient. For $x + 2y + 2z$ on $x^2 + y^2 + z^2 = 36$:'),
          maths('9\\lambda^2 = 36'),
          maths('\\lambda = 2'),
          prose('so $x = 2$, $y = 4$ and $z = 4$, and the greatest value is'),
          maths('2 + 8 + 8 = 18'),
        ),
      ],
      skillCheck: [ask('cm-in-cs-max', 2), ask('cm-in-cs-min', 1), ask('cm-in-titu', 2)],
    },
  ],
  levelCheck: [
    ask('cm-in-flip', 2),
    ask('cm-in-count-integers', 2),
    ask('cm-in-square-min', 2),
    ask('cm-in-bounds', 2),
    ask('cm-in-amgm-min', 2),
    ask('cm-in-fixed-sum+choice', 2),
    ask('cm-in-product-table', 2),
    ask('cm-in-pen-tiles', 2),
    ask('cm-in-cs-max', 2),
    ask('cm-in-cs-min', 2),
    ask('cm-in-titu+choice', 2),
    ask('cm-in-cs-table', 1),
  ],
};
