/**
 * Contest Math, Level 7: Combinatorics. Counting in stages with restrictions,
 * two overlapping groups on a Venn diagram, branching on the first move,
 * counting too much and dividing, and symmetry. Generators in
 * `generators/contestCounting.ts`.
 */
import type { Level } from '../../types';
import { teach, ask, prose, maths, askAfter } from './blocks';

export const combinatorics: Level = {
  id: 'cm-l7',
  title: 'Combinatorics',
  lessons: [
    {
      id: 'cm-l7-counting',
      title: 'Counting',
      slides: [
        teach(
          prose('When a choice is made in stages, the number of ways **multiplies**: each way of making the first choice goes with every way of making the next.'),
          prose('Three-digit numbers from the digits $2, 4, 6, 8$, no digit used twice: $4$ choices for the hundreds, then $3$ left for the tens, then $2$ for the units.'),
          maths('4 \\times 3 \\times 2 = 24'),
          prose('**Fill the most restricted place first.** With $0, 3, 5, 7$ instead, the first digit cannot be $0$, so it has $3$ choices. The tens may use $0$ but not the first digit: $3$ choices. The units get the $2$ left.'),
          maths('3 \\times 3 \\times 2 = 18'),
          prose('Ignoring the zero gives $24$, the trap: it counts $035$ and the like, which are not three-digit numbers.'),
        ),
        ask('cm-digit-choices'),
        askAfter(
          'cm-stripes',
          1,
          prose('A choice can depend on the one before without changing **how many** ways there are. A flag of $4$ stripes in $3$ colours, touching stripes different: the top has $3$ choices, and each stripe below has $2$, whatever the one above it was.'),
          maths('3 \\times 2 \\times 2 \\times 2 = 24'),
        ),
        ask('cm-stripes-table'),
        askAfter(
          'cm-digit-choices+choice',
          2,
          prose('Four-digit numbers carry on the same way: after the first two places, each place has one choice fewer than the one before.'),
        ),
        teach(
          prose('Odd or even is decided by the **units** digit, so fill that place first. Odd three-digit numbers from $1, 2, 3, 4, 5$, no repeats: the units digit is $1$, $3$ or $5$, then $4$ digits are left for the hundreds and $3$ for the tens.'),
          maths('3 \\times 4 \\times 3 = 36'),
          prose('When two restrictions clash, **split into cases**. Even numbers from $0, 1, 2, 3$, no repeats: a units digit of $0$ leaves the first digit free, but a units digit of $2$ does not.'),
          maths('\\text{units } 0: \\ 3 \\times 2 = 6'),
          prose('With $2$ in the units, the first digit is $1$ or $3$, and the middle is $0$ or whichever of those is left:'),
          maths('\\text{units } 2: \\ 2 \\times 2 = 4'),
          maths('6 + 4 = 10'),
        ),
        ask('cm-odd-even-digits'),
        askAfter(
          'cm-stripes+choice',
          2,
          prose('A colour banned from the first stripe only takes a choice away **there**. The stripes after it may use that colour again, so each still has one fewer than all the colours. With $4$ colours, $3$ stripes and the top not white:'),
          maths('3 \\times 3 \\times 3 = 27'),
        ),
        ask('cm-odd-even-digits', 2),
        ask('cm-stripes-table', 2),
      ],
      skillCheck: [ask('cm-digit-choices', 2), ask('cm-odd-even-digits+choice', 2), ask('cm-stripes', 2)],
    },
    {
      id: 'cm-l7-venn',
      title: 'Venn Diagrams',
      slides: [
        teach(
          prose('Two overlapping groups make four regions: only the first, both, only the second, and neither. Fill a Venn diagram **from the middle out**.'),
          prose('Of $30$ students, $18$ play football, $12$ play tennis and $5$ play both. The $18$ includes the $5$, so only football is'),
          maths('18 - 5 = 13'),
          prose('and only tennis is'),
          maths('12 - 5 = 7'),
          prose('The rest play neither:'),
          maths('30 - 13 - 5 - 7 = 5'),
          prose('Writing $18$ in the football-only region is the trap: it counts the $5$ who play both twice.'),
        ),
        ask('cm-venn-survey'),
        ask('cm-venn-count'),
        askAfter(
          'cm-two-way-table',
          1,
          prose('A two-way table holds the same four regions as a grid, with the totals at the end of each row and column. Every row and every column adds up to its total, so each blank is a subtraction.'),
        ),
        askAfter(
          'cm-venn-count+choice',
          2,
          prose('Given **neither** instead of both, start outside. If $4$ of the $30$ play neither, then $26$ play at least one. Adding the two groups counts those in both twice, so the excess is the overlap:'),
          maths('18 + 12 - 26 = 4'),
        ),
        teach(
          prose('Sometimes the overlap is not given, only how big or small it **could** be.'),
          prose('Of $25$ people, $17$ like tea and $14$ like coffee. That is $31$ places for $25$ people, so at least'),
          maths('17 + 14 - 25 = 6'),
          prose('like both: the overlap is smallest when nobody is in neither.'),
          prose('The overlap is **largest** when the smaller group sits inside the larger one: all $14$ coffee drinkers also like tea, so at most $14$ like both.'),
        ),
        ask('cm-venn-extremes'),
        ask('cm-venn-survey', 2),
        askAfter(
          'cm-venn-extremes+choice',
          2,
          prose('The same two pictures answer questions about **neither**. With the smaller circle inside the larger, only the larger group is in either, so neither is as big as it can be:'),
          maths('25 - 17 = 8'),
          prose('With $10$ and $8$ of the $25$ and the circles pulled apart, nobody is in both, so neither is as small as it can be:'),
          maths('25 - 10 - 8 = 7'),
        ),
        askAfter('cm-two-way-table', 2, prose('When no cell in a row is given, start from a total: a row or column with only one blank left.')),
      ],
      skillCheck: [ask('cm-venn-survey', 2), ask('cm-venn-count', 2), ask('cm-venn-extremes', 2)],
    },
    {
      id: 'cm-l7-branches',
      title: 'Branch Diagrams',
      slides: [
        teach(
          prose('A branch diagram splits on the **first move** and counts what is left on each branch. Climbing $5$ stairs $1$ or $2$ at a time: a first step of $1$ leaves $4$ stairs, a first step of $2$ leaves $3$. So the ways for $5$ are the ways for $4$ plus the ways for $3$.'),
          prose('Build up from the bottom: $1$ stair has $1$ way, $2$ stairs have $2$ (one and one, or a two). Each count after that is the sum of the two before it:'),
          maths('1,\\ 2,\\ 3,\\ 5,\\ 8'),
          prose('So $5$ stairs can be climbed in $8$ ways.'),
        ),
        ask('cm-stairs'),
        askAfter(
          'cm-dice-total',
          1,
          prose('Split on the first die. A red $6$-sided die and a blue $4$-sided die total $7$ when red shows $3$, $4$, $5$ or $6$, since blue then needs $4$, $3$, $2$ or $1$:'),
          maths('(3, 4),\\ (4, 3),\\ (5, 2),\\ (6, 1)'),
          prose('That is $4$ outcomes. $(3, 4)$ and $(4, 3)$ are different outcomes: the dice are different colours.'),
        ),
        askAfter(
          'cm-stairs+choice',
          2,
          prose('With moves of $1$, $2$ or $3$, the first move leaves one, two or three fewer to go, so each count is the sum of the **three** before it. $1$ stair: $1$ way; $2$ stairs: $2$; $3$ stairs: $4$ (three ones, one then two, two then one, or a three).'),
          maths('1,\\ 2,\\ 4,\\ 7,\\ 13'),
        ),
        teach(
          prose('When only **how many** of each piece matters, not the order, list the cases by the biggest piece.'),
          prose('Stamps worth $2$p and $5$p making $20$p: try $0$ to $4$ fives. What is left must be a whole number of twos:'),
          maths('20,\\ 15,\\ 10,\\ 5,\\ 0'),
          prose('$20$, $10$ and $0$ are even, so there are $3$ ways.'),
          prose('With $1$p stamps as well, every case works, in several ways: whatever is left takes any number of twos, and ones fill the gap. For $12$p, $0$, $1$ or $2$ fives leave $12$, $7$ and $2$, which take up to $6$, $3$ and $1$ twos:'),
          maths('7 + 4 + 2 = 13'),
        ),
        ask('cm-stamp-ways'),
        ask('cm-stamp-table'),
        askAfter(
          'cm-dice-total+choice',
          2,
          prose('Three dice: split on the red one, and each branch is a two-dice count. Three $4$-sided dice totalling $6$: red $1$ leaves $5$ for the other two, $4$ ways; red $2$ leaves $4$, $3$ ways; red $3$ leaves $3$, $2$ ways; red $4$ leaves $2$, $1$ way.'),
          maths('4 + 3 + 2 + 1 = 10'),
        ),
        ask('cm-stamp-ways', 2),
        ask('cm-stamp-table', 2),
      ],
      skillCheck: [ask('cm-stairs', 2), ask('cm-dice-total', 2), ask('cm-stamp-ways', 2)],
    },
    {
      id: 'cm-l7-over-counting',
      title: 'Over-Counting',
      slides: [
        teach(
          prose('Sometimes it is easier to count too much, on purpose, and then divide. Pick a team of $3$ from $7$ players one at a time, in order:'),
          maths('7 \\times 6 \\times 5 = 210'),
          prose('Each team turns up once for every order of its three players:'),
          maths('3! = 3 \\times 2 \\times 1 = 6'),
          maths('210 \\div 6 = 35'),
          prose('Stopping at $210$ is the trap: it counts the team of Ann, Ben and Cal six times over.'),
        ),
        ask('cm-teams'),
        ask('cm-teams-tiles'),
        askAfter(
          'cm-arrangements',
          1,
          prose('Repeated letters work the same way. Pretend the two Ps of APPLE are different, $P_1$ and $P_2$: then there are $5!$ orders.'),
          maths('5! = 120'),
          prose('Swapping $P_1$ and $P_2$ gives the same word, so every word was counted twice:'),
          maths('120 \\div 2 = 60'),
        ),
        askAfter(
          'cm-arrangements+choice',
          2,
          prose('With several repeated letters, divide by the orders of each group. BANANA has three As and two Ns:'),
          maths('\\frac{6!}{3! \\times 2!} = \\frac{720}{12} = 60'),
        ),
        teach(
          prose('Round a table, only the order round the table matters, not which chair. In a row, $5$ people can be ordered in'),
          maths('5! = 120'),
          prose('ways. Round a table each seating turns up $5$ times, once for each way of moving everyone round, so'),
          maths('120 \\div 5 = 24'),
          prose('To keep two people **together**, glue them into one block: $4$ units round the table, and the block either way round:'),
          maths('2 \\times 3! = 12'),
          prose('To keep them **apart**, take the together seatings away from all of them:'),
          maths('24 - 12 = 12'),
        ),
        ask('cm-round-table'),
        askAfter(
          'cm-teams+choice',
          2,
          prose('A group of $4$ is counted once for each of its $4!$ orders, which is $24$. From $8$ people:'),
          maths('8 \\times 7 \\times 6 \\times 5 = 1680'),
          maths('1680 \\div 24 = 70'),
        ),
        ask('cm-round-table+choice', 2),
        ask('cm-teams-tiles', 2),
      ],
      skillCheck: [ask('cm-arrangements', 2), ask('cm-round-table', 2), ask('cm-teams', 2)],
    },
    {
      id: 'cm-l7-symmetry',
      title: 'Symmetry',
      slides: [
        teach(
          prose('**Symmetry**: when the cases pair up as mirror images, count one side and you have counted the other.'),
          prose('$5$ people queue. In how many orders is Ann ahead of Ben? Swap the two of them in any order and you get an order with Ben ahead. The orders pair up exactly, so it is half of them:'),
          maths('5! \\div 2 = 60'),
          prose('Two $6$-sided dice, red and blue: in how many of the $36$ outcomes is red bigger? $6$ outcomes are ties, and the other $30$ pair up by swapping the two numbers:'),
          maths('(36 - 6) \\div 2 = 15'),
        ),
        ask('cm-ahead-of'),
        ask('cm-dice-compare'),
        askAfter(
          'cm-ahead-of+choice',
          2,
          prose('With three named people, the $6$ orders of those three among themselves are equally common. Ann, then Ben, then Cara is one of the six, and Ann first of the three is two of them (Ann, Ben, Cara or Ann, Cara, Ben). With $5$ people:'),
          maths('5! \\div 6 = 20'),
          maths('5! \\div 3 = 40'),
        ),
        askAfter(
          'cm-dice-compare+choice',
          2,
          prose('Totals are symmetric too. On two $6$-sided dice change each number $x$ to $7 - x$: a total of $T$ becomes $14 - T$, so totals above $7$ pair up with totals below $7$. The $6$ outcomes totalling exactly $7$ are left over:'),
          maths('(36 - 6) \\div 2 = 15'),
          prose('On $m$-sided dice use $m + 1 - x$: the middle total is $m + 1$, made in $m$ ways.'),
        ),
        teach(
          prose('Symmetry also adds things up. Write down every number using $1$, $2$ and $3$ once each: $123, 132, 213, 231, 312, 321$. Each digit is in the units place twice, so the units column adds up to'),
          maths('2 \\times (1 + 2 + 3) = 12'),
          prose('The tens and hundreds columns add up to $12$ too, and $1 + 10 + 100$ is $111$, so the sum is'),
          maths('12 \\times 111 = 1332'),
        ),
        ask('cm-perm-sum'),
        ask('cm-perm-sum-tiles'),
        askAfter(
          'cm-perm-sum+choice',
          2,
          prose('Choosing $3$ of the $4$ digits $1, 2, 3, 4$: a digit is in the units place whenever the front two places are filled from the other three digits, in $3 \\times 2$ ways. So each digit is there $6$ times:'),
          maths('6 \\times (1 + 2 + 3 + 4) = 60'),
          maths('60 \\times 111 = 6660'),
        ),
        ask('cm-perm-sum-tiles', 2),
      ],
      skillCheck: [ask('cm-ahead-of', 2), ask('cm-dice-compare', 2), ask('cm-perm-sum', 2)],
    },
  ],
  levelCheck: [
    ask('cm-digit-choices', 2),
    ask('cm-odd-even-digits+choice', 2),
    ask('cm-stripes', 2),
    ask('cm-venn-count', 2),
    ask('cm-venn-extremes+choice', 2),
    ask('cm-venn-survey', 2),
    ask('cm-stairs', 2),
    ask('cm-dice-total+choice', 2),
    ask('cm-stamp-ways', 2),
    ask('cm-arrangements', 2),
    ask('cm-round-table+choice', 2),
    ask('cm-teams', 2),
    ask('cm-ahead-of', 2),
    ask('cm-perm-sum', 2),
  ],
};
