/**
 * Contest Math, Level 11: Reframing Problems. Turning a question into an
 * easier one with the same answer: count what each step removes, match
 * routes with words, work back from the end, sort cubes by where they sit,
 * and read numbers that describe themselves. Generators in
 * `generators/contestReframing.ts`.
 */
import type { Level } from '../../types';
import { teach, ask, prose, maths, askAfter } from './blocks';

export const reframingProblems: Level = {
  id: 'cm-l11',
  title: 'Reframing Problems',
  lessons: [
    {
      id: 'cm-l11-reframing',
      title: 'Reframing Problems',
      slides: [
        teach(
          prose('Some questions get easy when you count something else that has to come out the same.'),
          prose('$37$ players enter a knockout: each match has a winner, the loser is out, and a player left without an opponent gets a bye into the next round. Drawing the rounds is slow. Count the losers instead: every match makes exactly one, and everyone but the champion loses once.'),
          maths('37 - 1 = 36'),
          prose('So $36$ matches, whatever the byes. Counting rounds, $6$, or halving the players, $18$, are the traps.'),
        ),
        ask('cm-knockout'),
        askAfter(
          'cm-chocolate',
          2,
          prose('A $4 \\times 6$ chocolate bar snapped into squares, one piece at a time: every snap turns one piece into two, so the pieces go up by exactly one. From $1$ piece to $24$ takes'),
          maths('24 - 1 = 23'),
          prose('A block of cheese cut into unit cubes, one piece per cut, is the same: a $2 \\times 3 \\times 4$ block ends in $24$ cubes, so $23$ cuts.'),
        ),
        askAfter(
          'cm-knockout+choice',
          2,
          prose('When every game is played by three and only its winner goes through, each game knocks out two. With $25$ players, $24$ must go:'),
          maths('24 \\div 2 = 12'),
        ),
        teach(
          prose('A **bijection** pairs every object you want to count with exactly one object that is easier to count.'),
          prose('On a grid of streets $4$ blocks across and $2$ up, a route from the bottom-left corner to the top-right going only right or up is $4$ R moves and $2$ U moves, such as RRURUR. Every such word is a route, and every route is a word. So choose which $2$ of the $6$ moves are U:'),
          maths('\\binom{6}{2} = \\frac{6 \\times 5}{2} = 15'),
          prose('Another way: a route into any corner comes from the left or from below, so the count at each corner is the one to its left plus the one below it.'),
        ),
        ask('cm-grid-paths'),
        ask('cm-grid-table'),
        askAfter(
          'cm-grid-paths+choice',
          2,
          prose('Through a checkpoint $P$: split each route at $P$. If $P$ is $2$ across and $1$ up, and $B$ is $2$ more across and $2$ more up, then'),
          maths('\\binom{3}{1} \\times \\binom{4}{2} = 3 \\times 6 = 18'),
          prose('Every first half goes with every second half, so multiply, never add.'),
        ),
        askAfter(
          'cm-share-sweets',
          1,
          prose('Share $5$ identical sweets between $3$ children, some maybe getting none. Put the sweets in a row with $2$ dividers: the first child takes what is before the first divider, the second what is between, the third the rest. Every row of $5$ sweets and $2$ dividers is one sharing, so choose $2$ of the $7$ places for the dividers:'),
          maths('\\binom{7}{2} = 21'),
        ),
        askAfter(
          'cm-share-sweets+choice',
          2,
          prose('When everyone must get at least one, hand one to each first, then share the rest freely. $9$ sweets between $3$ children, at least one each, leaves $6$ to share:'),
          maths('\\binom{8}{2} = 28'),
        ),
      ],
      skillCheck: [ask('cm-knockout', 2), ask('cm-grid-paths', 2), ask('cm-share-sweets', 2)],
    },
    {
      id: 'cm-l11-strategies',
      title: 'Key Strategies',
      slides: [
        teach(
          prose('**Work backwards** when you know how something ends. I think of a number, multiply it by $3$, take away $4$, then divide by $2$, and get $10$. Undo the steps from the last to the first, each with its opposite:'),
          maths('10 \\times 2 = 20'),
          maths('20 + 4 = 24'),
          maths('24 \\div 3 = 8'),
          prose('So the number was $8$. Undoing the steps in their first order is the trap.'),
        ),
        ask('cm-work-backwards'),
        askAfter(
          'cm-backwards-table',
          1,
          prose('Each day half the sweets in a jar are eaten, then $2$ more. After a day $5$ are left. Before the $2$ went there were $7$, and that was half of the morning’s sweets:'),
          maths('2 \\times (5 + 2) = 14'),
          prose('Doubling first and then adding the $2$, $12$, is the trap.'),
        ),
        ask('cm-work-backwards+choice', 2),
        teach(
          prose('**Draw it.** Ria is $7$th from the front of a queue and $5$th from the back. Draw the queue: both counts end on Ria, so she is counted twice.'),
          maths('7 + 5 - 1 = 11'),
          prose('A snail in a well $10$ m deep climbs $4$ m each day and slips $2$ m each night. Draw the last day: once it is within $4$ m of the top, it climbs out without slipping back. So it must first reach'),
          maths('10 - 4 = 6'),
          prose('metres, gaining $2$ m for each day and night, which takes $3$ of them. It climbs out on day $4$. Dividing the depth by the $2$ m it gains, day $5$, is the trap.'),
        ),
        ask('cm-queue'),
        askAfter(
          'cm-queue+choice',
          2,
          prose('Two people: Ann is $3$rd from the front and Ben $2$nd from the back, with $4$ people between them. Draw it: $3$ up to and including Ann, the $4$ between, then $2$ from Ben to the end. Nobody is counted twice:'),
          maths('3 + 4 + 2 = 9'),
        ),
        ask('cm-snail'),
        ask('cm-snail+choice', 2),
        askAfter(
          'cm-count-squares',
          1,
          prose('**Small cases first.** How many squares of any size in a $3 \\times 3$ grid? Count one size at a time. A $1 \\times 1$ fits in $3 \\times 3$ places, a $2 \\times 2$ in $2 \\times 2$, and a $3 \\times 3$ in one:'),
          maths('9 + 4 + 1 = 14'),
          prose('In a grid $2$ high and $4$ wide, the $1 \\times 1$ squares fit in $2 \\times 4$ places and the $2 \\times 2$ in $1 \\times 3$:'),
          maths('8 + 3 = 11'),
        ),
        askAfter(
          'cm-count-squares+choice',
          2,
          prose('**Choose good variables.** A rectangle in a grid is fixed by its two horizontal sides and its two vertical sides. A grid $2$ high and $3$ wide has $3$ lines across and $4$ up and down, so'),
          maths('\\binom{3}{2} \\times \\binom{4}{2} = 3 \\times 6 = 18'),
        ),
      ],
      skillCheck: [ask('cm-work-backwards', 2), ask('cm-queue', 2), ask('cm-count-squares', 2)],
    },
    {
      id: 'cm-l11-cubes',
      title: 'Color Cube Assembly',
      slides: [
        teach(
          prose('A $3 \\times 3 \\times 3$ cube built from $27$ unit cubes: sort them by where they sit and how many of their faces show.'),
          prose('**Corners**: $8$, three faces showing. **Edges**: one in the middle of each of the $12$ edges, two faces. **Face middles**: one on each of the $6$ faces, one face. **Hidden**: the $1$ in the centre.'),
          maths('8 + 12 + 6 + 1 = 27'),
          prose('To make the whole outside red, every cube but the hidden ones must be red. For a cube of edge $4$ the hidden core is $2 \\times 2 \\times 2$:'),
          maths('4^3 - 2^3 = 64 - 8 = 56'),
          prose('Six faces of $16$ squares, $96$, is the trap: that counts squares, not cubes, and a corner cube carries three of them.'),
        ),
        ask('cm-cube-shell'),
        ask('cm-shell-tiles'),
        askAfter(
          'cm-cube-shell+choice',
          2,
          prose('A block that is not a cube works the same way: its core is $2$ shorter each way. A $3 \\times 4 \\times 5$ block has a $1 \\times 2 \\times 3$ core:'),
          maths('60 - 6 = 54'),
        ),
        ask('cm-shell-tiles', 2),
        teach(
          prose('A cube of edge $3$ glued together from $27$ ordinary dice, opposite faces adding to $7$. What is the least total of pips on the outside?'),
          prose('A corner die shows three faces meeting at a corner, and no two of those are opposite, so at best $1$, $2$ and $3$. An edge die shows two neighbouring faces, at best $1$ and $2$. A face-middle die shows one face, at best $1$. Each die turns freely, so all of that happens at once:'),
          maths('8 \\times 6 + 12 \\times 3 + 6 \\times 1 = 90'),
          prose('$54$, a $1$ on every square, is the trap: three $1$s cannot show on one die.'),
        ),
        ask('cm-dice-cube'),
        askAfter(
          'cm-dice-cube+choice',
          2,
          prose('For the most pips: a corner shows at best $4$, $5$ and $6$, which make $15$; an edge $5$ and $6$, which make $11$; and a face middle $6$. For the edge-$3$ cube:'),
          maths('8 \\times 15 + 12 \\times 11 + 6 \\times 6 = 288'),
        ),
        askAfter(
          'cm-red-surface',
          1,
          prose('Only $10$ of the $27$ cubes are red. For as much red outside as possible, put them where the most shows: $8$ at the corners, three squares each, and the other $2$ on edges, two squares each:'),
          maths('8 \\times 3 + 2 \\times 2 = 28'),
        ),
        askAfter(
          'cm-red-surface+choice',
          2,
          prose('For as little red as possible, hide them: the centre first, showing nothing, then the $6$ face middles, one square each, then edges, then corners. $10$ red cubes in the $3 \\times 3 \\times 3$:'),
          maths('1 \\times 0 + 6 \\times 1 + 3 \\times 2 = 12'),
        ),
      ],
      skillCheck: [ask('cm-cube-shell', 2), ask('cm-dice-cube', 2), ask('cm-red-surface', 2)],
    },
    {
      id: 'cm-l11-autobiographical',
      title: 'Autobiographical Numbers',
      slides: [
        teach(
          prose('In a **look-and-say** sequence each term describes the one before. Read the digits aloud in runs of equal digits, and write down what you say.'),
          maths('1, \\; 11, \\; 21, \\; 1211, \\; 111221'),
          prose('$1211$ is one $1$, one $2$, two $1$s, so the next term is $111221$. And $3113$ is one $3$, two $1$s, one $3$:'),
          maths('132113'),
          prose('Counting all the $3$s together, $2321$, is the trap: each run is read on its own.'),
        ),
        ask('cm-look-say'),
        ask('cm-look-say-table'),
        askAfter(
          'cm-look-say+choice',
          2,
          prose('Going back a term: read the digits in pairs, each a count and then a digit. $312211$ is $31$, $22$, $11$: three $1$s, two $2$s, one $1$:'),
          maths('111221'),
        ),
        teach(
          prose('A number **describes itself** when its first digit is how many $0$s it has, its second how many $1$s, and so on. Check $21200$ place by place: two $0$s, one $1$, two $2$s, no $3$s, no $4$s. Every place is right.'),
          prose('Every digit is counted once, so the digits of such a number always add up to how many digits it has:'),
          maths('2 + 1 + 2 + 0 + 0 = 5'),
          prose('That rules numbers out quickly, but a number can pass it and still fail: $12200$ says it has one $0$, and it has two.'),
        ),
        ask('cm-self-describing'),
        ask('cm-self-describing', 2),
        askAfter(
          'cm-digital-root',
          1,
          prose('Add a number’s digits, then the digits of that, until one digit is left. A number and its digit sum leave the same remainder when divided by $9$, so the last digit is that remainder, or $9$ for a remainder of $0$. The digit $5$ written $22$ times has digit sum'),
          maths('5 \\times 22 = 110'),
          maths('110 = 9 \\times 12 + 2'),
          prose('so the last digit is $2$.'),
        ),
        askAfter(
          'cm-digital-root+choice',
          2,
          prose('The numbers $1$ to $12$ in a row, $123456789101112$: each piece keeps its own remainder, so the long number leaves the remainder of'),
          maths('1 + 2 + \\cdots + 12 = 78'),
          maths('78 = 9 \\times 8 + 6'),
          prose('and the last digit is $6$.'),
        ),
        askAfter(
          'cm-number-plus-digits',
          1,
          prose('A number plus the sum of its digits is $49$. Name the digits, $10a + b$:'),
          maths('11a + 2b = 49'),
          prose('$2b$ is even and at most $18$. $a = 4$ leaves $5$, which is odd, so $a = 3$:'),
          maths('2b = 49 - 33 = 16'),
          prose('So $b = 8$ and the number is $38$. Check:'),
          maths('38 + 3 + 8 = 49'),
        ),
        askAfter(
          'cm-number-plus-digits+choice',
          2,
          prose('Three digits, $100a + 10b + c$, plus their sum is $250$:'),
          maths('101a + 11b + 2c = 250'),
          prose('$11b + 2c$ is at most $117$, so only $a = 2$ leaves that little:'),
          maths('11b + 2c = 250 - 202 = 48'),
          prose('$2c$ is even and at most $18$, so only $b = 4$ works:'),
          maths('2c = 48 - 44 = 4'),
          prose('So $c = 2$ and the number is $242$.'),
        ),
      ],
      skillCheck: [ask('cm-look-say', 2), ask('cm-self-describing', 2), ask('cm-digital-root', 2)],
    },
  ],
  levelCheck: [
    ask('cm-knockout', 2),
    ask('cm-chocolate+choice', 2),
    ask('cm-grid-paths', 2),
    ask('cm-share-sweets', 2),
    ask('cm-work-backwards', 2),
    ask('cm-queue+choice', 2),
    ask('cm-snail', 2),
    ask('cm-count-squares', 2),
    ask('cm-cube-shell+choice', 2),
    ask('cm-dice-cube', 2),
    ask('cm-red-surface', 2),
    ask('cm-look-say', 2),
    ask('cm-self-describing', 2),
    ask('cm-digital-root', 2),
  ],
};
